### PR TITLE
chore: do not remove fixtures until project is closed

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes N/A

### User facing changelog

N/A

This one:

image

### Additional details

- the test was always flaky. it was a race condition.
- chokidar v3 gives a 17x perf improvements (according to the author). we upgraded to it recently from chokidar v2.
- the perf improvement makes the race condition more likely to occur
- the problem is we are cleaning up the fixture project before we do project.close().
- chokidar is still watching the fixture files that got deleted
- the files are deleted 
- our application code still tries to call the `_remove` on a file that no longer exists (since it was deleted)
- error

### How has the user experience changed?

Spend less time messing around with CI and flaky tests.

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by agg23 — APPROVED** [review]
Fantastic. Ship it

**Review by chrisbreiding — APPROVED** [review]
Nice work!

**Comment by lmiller1990** [comment]
I will run CI a few more times before merging to be sure.

**Review by flotwig — APPROVED** [review]
so good

**Pull request merged**
