### PR TITLE
feat: Add keystrokeDelay

### LINKED ISSUE #566: Add `keystrokeDelay` configuration option
Currently Cypress uses a `setTimeout` between keystrokes to mimic how a user would press each key.

## Concern 1:
We should enable this property to be globally configurable such as `keystrokeDelay`.

## Concern 2:
When set to `false` or `0`, instead of making each key press be async, we should make it synchronous. This would be helpful to not only type faster but could make things easier for 3rd party JS frameworks such as react.

Currently as it stands since keypresses as async - its indeterminate whether or not your JS framework has finished 'processing' all of the keystrokes. For instance it may fire its change events while typing vs after all characters have been typed. See issue #534 for more detail.

## Concern 3:
When typing very long sequences its often useful just to have it all "type at once" and not have to wait. Give developers the choice to decide.

## Recommendation
- set `keystrokeDelay` to `true` by default (which is the minimum `setImmediate` async between key presses)
- if `keystrokeDelay` is set to `false` or `0` typing all characters synchronously
- if `keystrokeDelay` is set to a number then use this as the `setTimeout` value

Passing the `delay` option to `cy.type()` will override anything globally set in config.

### PR DESCRIPTION
**Pull request by herecydev**
- Closes #566

### User facing changelog

- You can now override the default delay between characters for `cy.type()` with [`Cypress.Keyboard.defaults()`](https://on.cypress.io/keyboard-api) or via [test configuration](https://on.cypress.io/writing-and-organizing-tests#Allowed-config-values).

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/3977
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [x] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@herecydev Thanks! Can you add tests around this new behavior? 

We need tests that: 

- the default keystroke still works
- setting a new config value increases the keystroke delay
- setting a global config value overwrites a delay value set in the type command
- setting an invalid value to keystrokeDelay (like 'foo') will error
- setting keystroke to false or 0 disables keystroke delay
- the types are correctly tested
- etc

There is a Contributing Guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

To run the tests:

- within `cypress` root, run `yarn`
- run `yarn workspace @packages/driver cypress:open`
- click on the test you're writing to run it within Cypress

Instructions for running the `driver` tests can always be found here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/README.md

**Comment by herecydev** [comment]
@jennifer-shehane Some initial tests added which I believe covers this:

> * the default keystroke still works
> * setting a new config value increases the keystroke delay
> * setting a global config value overwrites a delay value set in the type command
> * setting keystroke to false or 0 disables keystroke delay

Can you link some existing tests that cover the following, would be really helpful to follow along how these are already covered;

> * setting an invalid value to keystrokeDelay (like 'foo') will error
> * the types are correctly tested

Also, I'm getting some issues with the CI failing around missing percy tokens, which seems totally unrelated to the changes. How do I approach CI failures, given I can't rerun them?

**Comment by jennifer-shehane** [comment]
Yah, I'm looking into the percy token. That shouldn't error like that, so ignore that for now.

Testing the error on an option that's of the wrong type would be similar to this structure: https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/integration/commands/actions/type_spec.js#L2535:L2535

Testing the types would be something like this: https://github.com/cypress-io/cypress/blob/develop/cli/types/tests/actions.ts#L85:L85

**Comment by jennifer-shehane** [comment]
Hey @herecydev, will you have time to add the extra tests?

**Comment by herecydev** [comment]
> 
> 
> Hey @herecydev, will you have time to add the extra tests?

I will and I haven't forgotten. Just on holiday at the moment, but will endeavour to finish those up next week. Sorry for the delay.

**Comment by herecydev** [comment]
@jennifer-shehane I think all the correct tests have now been written. I'm still a little hesistant about the extent of testing invalid types. You can see my efforts to validate an invalid delay, but I can't see other configuration going through similar testing. Take `waitForAnimations` as an example, should that also not throw a reasonable error if misconfigured?

In addition, after rereading this test criteria "setting a global config value overwrites a delay value set in the type command". I disagree with that behavior. I think it's meant to be flipped, and have written a test on that assumption.

**Comment by chrisbreiding** [comment]
Hey @herecydev, appreciate the work on this. 

The team discussed this and decided we'd like this to work through a method like `Cypress.Keyboard.defaults()`, similar to how [`Cypress.Screenshot.defaults()`](https://docs.cypress.io/api/cypress-api/screenshot-api#Syntax) works, instead of being a `cypress.json` setting. We also want the per-test configuration for this setting to work, but we don't currently have the infrastructure in place for it to work with the `Cypress.Keyboard.defaults()` method. We're planning to add that in the near future and then we can revisit this. 

There's nothing further you need to do. Just wanted to let you know, since this won't be getting merged immediately. We'll take it from here and get this in as soon as we can.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Needs some minor changes. I think this also needs to be included in the test config types: https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L2794:L2794 

I think we should discuss the final implementation in our team touchpoint to get some feedback from the whole team on the test config + Keyboard.defaults usage.

I know test config is not a 1to1 reflection of only configuration values, but currently the only exception is 'browser'. That's probably the only thing to go over.

**Review by jennifer-shehane — APPROVED** [review]
I manually tested this and looked over the code. Looks good. Everyone seems satisfied with the API for now. Thanks again @herecydev!

**Comment by jennifer-shehane** [comment]
These tests passed - looks like the Cypress checks are stuck running for some reason and are not up to date with latest reruns. Going to merge in.

**Pull request merged**
