### PR TITLE
Fix regression in 3.5.0 where a cy.visit that changes superdoma…

### LINKED ISSUE #5756: Since 3.5.0, a cy.visit that changes superdomain incorrectly clears cookies of other domains.
### Current behavior:

Given the following flow:

1. `http://foo.com` sets cookie `foo=bar` and redirects to `http://bar.com`
2. `http://bar.com` returns 200

`cy.visit("http://foo.com")` with a current superdomain of `foo.com` will result in no cookies being set, since the superdomain changes and causes the cookies to erroneously be cleared.

### Desired behavior:

Cookies are kept from all redirects during a cy.visit.

This can be accomplished by getting rid of the shortcut we take to make `cy.visit` only send 1 HTTP request, even if superdomain changes. This shortcut is the root of all evil: https://github.com/cypress-io/cypress/blob/0a24df272303556589cd991096f2aee7c68c896e/packages/server/lib/server.coffee#L364-L382

### Steps to reproduce: (app code and test code)

See #5702 for reproduction.

### Versions

Cypress >=3.5.0

### PR DESCRIPTION
**Pull request by flotwig**
- Fixes #5756

### User facing changelog

- Fixed a regression in 3.5.0 where a `cy.visit` that changes superdomain would incorrectly clear cookies of other domains.
- `cy.visit`s that cause a superdomain change will now result in 2 requests to your origin server. This should not affect tests, as tests will still re-run on a superdomain change.

### Additional details

- created a sandbox repo to test Chrome cookies scenarios using Puppeteer: https://github.com/flotwig/google-chrome-behavior-tests
	- we are handling simple single-Set-Cookie flows correctly
- [x] failure with `cookies without whitelist in a cy.visit when redirected to a HTTP URL can set cookies on lots of redirects, ending with different domain:` with `localhost` baseUrl
	- seems to be missing all cookies from non-localhost (quux.bar.net)
	- passes under cy.request, passes under same domain, passes under cy.request+same domain
	- issue occurs when superdomain changes - if you cy.visit the baseurl right before this test, it passes! otherwise the cookies from the alternate domain are wiped!
- having trouble reproducing the issues users are mentioning with cookies in cy.request
	- could be caused by obsolete multi-Set-Cookie syntax
	- most likely #5656 

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by flotwig** [comment]
@brian-mann there isn't an open issue for this AFAIK, think we should merge this in anyways? it definitely fixes some issue... people might not even know they have this issue

**Comment by brian-mann** [comment]
@flotwig definitely needs a corresponding issue opened. The regression fix is easily describable and should be noted in the issue.

**Comment by flotwig** [comment]
> @flotwig definitely needs a corresponding issue opened. The regression fix is easily describable and should be noted in the issue.

Created one: #5756

**Comment by brian-mann** [comment]
Removing the superdomain stitching may in fact fix other esoteric issues that are open - but they may be very hard to find...

The superdomain visit buffering is likely the cause of other difficult to understand/debug issues due to the state changes that happen. This could have manifested itself in situations where Cypress changes the superdomain - but then does not serve itself correctly (instead it would proxy to the real origin server). Another possible candidate would be seeing the "Cypress did not launch this browser" message about not being able to connect to the automation extension.

@flotwig and @jennifer-shehane might be worth peaking around / searching through issues to see if we can find others that fixing this will close.

**Pull request merged**
