### PR TITLE
feat: add the option to ignore chrome prefs

### LINKED ISSUE #29330: Add an option to ignore preferences files load on browser relaunch
### What would you like?

I'd like the option to be able to ignore chrome preferences load on relaunch

### Why is this needed?

We have a browser application that encrypts the user data dir, causing relaunches of the browser not to work.

### Other

_No response_

### PR DESCRIPTION
**Pull request by agentran**
- Closes [29330](https://github.com/cypress-io/cypress/issues/29330)

### Steps to test

1. Define the IGNORE_CHROME_PREFERENCES environment variable to your system
2. start the cypress server
3. start a cypress project
4. close the browser.
5. relaunch the browser
### How has the user experience changed?
There is no change unless you add the environment variable to ignore the chrome preferences

### PR Tasks

- [ ] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@agentran I'm going to try to run this branch so that it will build a binary that you'll be able to download and try out to see if this resolves the browser launching issue. If it does, we can look further into how to accommodate this.

**Comment by agentran** [comment]
> @agentran I'm going to try to run this branch so that it will build a binary that you'll be able to download and try out to see if this resolves the browser launching issue. If it does, we can look further into how to accommodate this.

Hey, No problem, LMK when the binary is available.

**Comment by jennifer-shehane** [comment]
@agentran I've remembered that the binaries won't build for contributor PRs so I'll have to pull this out into another PR.

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress/pull/29447

**Pull request closed without merging**
