### PR TITLE
Update cli to display version via console

### PR DESCRIPTION
**Pull request by mavimo**
Currently cypress use the logger to display CLI version.
Logger do not generate output if the current logging level is lower than the configured disabling possibility to display version (this happen by default).

### Current
```
root@24e921bbf865:/usr/local/lib/node_modules/cypress# cypress version
root@24e921bbf865:/usr/local/lib/node_modules/cypress# 
```
with debug:
```
root@24e921bbf865:/usr/local/lib/node_modules/cypress# DEBUG=cypress:cli cypress version
  cypress:cli cli starts with arguments ["/usr/local/bin/node","/usr/local/bin/cypress","version"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli printing Cypress version +6ms
  cypress:cli Reading binary package.json from: /root/.cache/Cypress/3.1.0/Cypress/resources/app/package.json +0ms
root@24e921bbf865:/usr/local/lib/node_modules/cypress#
```

### After fix
```
root@24e921bbf865:/usr/local/lib/node_modules/cypress# cypress version
Cypress package version: 3.1.0
Cypress binary version: 3.1.0
root@24e921bbf865:/usr/local/lib/node_modules/cypress# 
```
with debug:
```
root@24e921bbf865:/usr/local/lib/node_modules/cypress# DEBUG=cypress:cli cypress version
  cypress:cli cli starts with arguments ["/usr/local/bin/node","/usr/local/bin/cypress","version"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli printing Cypress version +6ms
  cypress:cli Reading binary package.json from: /root/.cache/Cypress/3.1.0/Cypress/resources/app/package.json +0ms
Cypress package version: 3.1.0
Cypress binary version: 3.1.0
root@24e921bbf865:/usr/local/lib/node_modules/cypress#
```

### CODE REVIEW

**Comment by mavimo** [comment]
@brian-mann @jennifer-shehane I think that the failure on testing are related to timeout that is not related to code in this PR, let me know if I can do something to fix it (or to improve code in this PR)

**Comment by brian-mann** [comment]
@Bkucera 	can you look at this ?

**Comment by Bkucera** [comment]
this seems to be introduced by https://github.com/cypress-io/cypress/issues/817 
I'm going to open a PR that allows the npm loglevel to only silence info logs, not calls to `logger.log(...)`, so this will be fixed by extension

**Comment by jennifer-shehane** [comment]
closing this in favor of PR here: #2706

**Pull request closed without merging**
