### PR TITLE
fix: Improve Big Sur browser detection performance

### LINKED ISSUE #17773: Detection of browsers take a long time on Mac OS Big Sur
### Current behavior

When running `cypress open` (not sure about `cypress run`), the detection of browsers takes a long time. 

Some knowns:

- The browser detection takes longer on Big Sur
- The browser detection takes longer on `cypress open-ct` than `cypress open` See https://github.com/cypress-io/cypress/issues/17808

### Desired behavior

Detect the browsers in a more performant manner for all OSes, but particularly Big Sur.

### Test code to reproduce

- `cypress open` or `cypress open-ct`

### Cypress Version

8.3.0

### Other

I ran some older versions of Cypress previously and it seemed to be bad in every version.

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #17773

### User facing changelog

- Projects will now open much faster on MacOS Big Sur with improved browser detection performance.

### Additional details

The root of the issue is [this bug in Electron](https://github.com/electron/electron/issues/26143), which causes spawning child processes to take 300-1000ms instead of the usual <30ms when using MacOS Big Sur and Electron 12+. We spawn a child process for each binary of each browser, plus potential fallback lookups if any of the standard ones fail. This causes the browser detection on Big Sur to take upwards of 10 seconds.

We considered using the Electron patch in that issue, but it's not a perfect solution (it was reverted in libuv due to failing tests), and would require us to build Electron ourselves, which is a large amount of work and responsibility.

As a workaround, we spawn a single child process (only incurring the performance penalty once instead of N+ times), and use it to call into our browser detection code from the user's Node.js. Since it's outside Electron, it doesn't suffer from the same bug and performs quickly. This reduces the time taken for browser detection from ~10s to ~1s.

### How has the user experience changed?

Users on Big Sur will see projects open much quicker.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by bahmutov** [comment]
👏 👏 👏

**Comment by JessicaSachs** [comment]
Nice. Thank you!

**Review by flotwig — APPROVED** [review]
We do what we can because we must. LGTM

**Comment by flotwig** [comment]
BTW, was not able to test this on an actual Big Sur install as part of my review, my VM is stuck on Catalina.

**Comment by flotwig** [comment]
An upstream fix is coming: https://github.com/electron/electron/issues/26143#issuecomment-1057583242

**Pull request merged**
