### PR TITLE
feat(vue2): Allow nested mounts preserving original vue instance

### PR DESCRIPTION
**Pull request by adambullmer**
Looking for feedback/approval before propagating to vue3 and completing tasks.

### Additional details
The intent here is to streamline the component mount process when it is necessary to have some wrapping components in the same vue app (e.g. when using vuetify). The current recommendations are to make a single test component that orchestrates a sub component along with the needed wrappers. However this leads to testing the component indirectly, through bindings on the test component, and can lead to bugs or tests that don't actually test the desired component.

The suggestion is to instead, utilize the `attachTo` and `localVue` options to avoid clearing/unmounting the previous state, thus allowing multiple mounts to occur, while sharing the same test instance of vue, or localVue.

`support/default-component-wrapper.ts`
```ts
import { defineComponent, h } from "vue";
import { VApp, VMain, VContainer } from "vuetify/lib";

// Create a dummy baseline app wrapper that centers the input component vertically and horizontally.
export const DefaultAppWrapper = defineComponent({
  components: { VApp, VMain, VContainer },
  setup(_props, _context) {
    return () =>
      h(VApp, [
        h(VMain, [
          h(
            VContainer,
            {
              staticClass: "fill-height justify-center",
            },
            [h("div", { attrs: { id: "vue_app" } })],
          ),
        ]),
      ]);
  },
});
```

`support/component.ts`
```ts
import { mount } from "cypress/vue2";
import { DefaultAppWrapper } from "./default-component-wrapper";

import { plugins } from "./setup";
import "./commands";

// get the last vueWrapper, which naively should be the component under test
export function vueWrapper() {
  return Cypress.vueWrapper[Cypress.vueWrapper.length - 1 || 0];
}

// expose test component wrapper as a cypress chainable
function vue() {
  return cy.wrap(vueWrapper());
}

/**
 * Mounts a component iwith proper plugin support enabled.
 */
function cyMount(Component: Parameters<typeof mount>[0], options?: Parameters<typeof mount>[1]) {
  return mount(Component, {
    ...plugins,
    ...options,
  });
}

/**
 * Mounts a component inside a wrapping component, such as one that contains a required <v-app>
 * wrapper when vuetify placement is involved. This will additionally share the same localVue instance
 * as the wrapping component and include index.html included globals, such as CSS sheets.
 *
 * - If the last parameter `Wrapper` is provided, it will customize the wrapping component. It should,
 * however, include a mounting point element `#app` unless `attachTo` is also provided in `options`.
 * - If `localVue` is passed as an option, it will be included in both the wrapper and inner components.
 * - If `attachTo` if provided, it will override the default mounting element `#app`. Useful for custom
 */
function cyMountWrapper(
  Component: Parameters<typeof mount>[0],
  options?: Parameters<typeof mount>[1],
  Wrapper = DefaultAppWrapper,
) {
  return cy
    .mount(Wrapper, {
      localVue: options?.localVue,
    })
    .window()
    .then((win) => {
      return cy.mount(Component, {
        attachTo: "#vue_app",
        localVue: win.Vue,
        // Spread will overwrite any above options as potential overrides
        ...options,
      });
    });
}

// Augment the Cypress namespace to include type definitions for
// your custom command.
// Alternatively, can be defined in cypress/support/component.d.ts
// with a <reference path="./component" /> at the top of your spec.
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    // When adding new commands, add them to the cypress interface here. e.g.:
    // interface Chainable {
    //   login(username: string, password: string): Chainable
    // }
    interface Chainable {
      mount: typeof cyMount;
      mountWrapper: typeof cyMountWrapper;
      vue: typeof vue;
    }
  }
}

Cypress.Commands.add("mount", cyMount);
Cypress.Commands.add("mountWrapper", cyMountWrapper);
Cypress.Commands.add("vue", vue);
```

### Steps to test
Using a setup as illustrated above, utilize the wrapped mounting method with a simple component test

`specs/MyBtn.spec.ts`
```ts
import MyBtn from "@/components/MyBtn.vue";

describe("MyBtn", () => {
  it("renders", () => {
    const wrapper = cy.mountWrapper(MyBtn);

    wrapper.get(".btn").should("exist");
  });
});
```

### How has the user experience changed?

This suggestion would also have docs/examples updated, but this would be a breaking change, unless a new `Cypress.vueWrapper` storage item were utilized.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by lmiller1990** [comment]
Hi, thanks for the PR. I don't fully understand what the benefit is here. I think it actually makes more sense to completely clean up between each test - this makes your tests more reliable. If you want to have the same state, couldn't we just do the setup all inside of `cyMountWrapper()`?

Another concern I have is consistency; all our implementations (React, Angular, etc) do the same thing - I'm not sure we want to deviate from this pattern, unless there is a compelling reason.

I normally just do Vuetify like this: https://cypress-testing-handbook.netlify.app/vuetify.html. I could be missing something here (this example doesn't have `VApp`, but you could easily see how it would work).

Can you provide some example tests that better support your use case? Your example test doesn't make use of this new feature. I think that might make the use case more clear.

**Comment by adambullmer** [comment]
>  I think it actually makes more sense to completely clean up between each test - this makes your tests more reliable.

this wasn't to avoid cleaning up between tests, but to allow calling `mount` multiple times in the same test without necessarily cleaning up. Today, the cypress/vue2  `mount` function cleans up the previous wrapper unconditionally, making it impossible to mount inside of another component, as the desired parent disappears on the second `mount` call.

> I could be missing something here (this example doesn't have `VApp`, but you could easily see how it would work).

The netlify example that omits `VApp` (and `VMain`), is actually really important for using any component that utilizes an overlay, such as a modal, tooltip, or snackbar (to name a few), to determine layout, positioning, and adding additional elements to the app.

> Another concern I have is consistency; all our implementations (React, Angular, etc) do the same thing 

That's totally fair, and I assume doable, but I'm no expert in non-vue frameworks, so some additional contributions may be necessary. In addition, I was waiting until I had buy in and agreement from you all before dedicating more time propagating the changes to other frameworks on every revision.

**Comment by lmiller1990** [comment]
Thanks for the reply!

> this wasn't to avoid cleaning up between tests, but to allow calling mount multiple times in the same test without necessarily cleaning up. Today, the cypress/vue2 mount function cleans up the previous wrapper unconditionally, making it impossible to mount inside of another component, as the desired parent disappears on the second mount call.

I think I am still missing something - why not just write two tests, with a fresh mount each time? I think the "mount in another component" part is confusing to me. Can you share an example component and test using your new API that cannot be written in a practical way with the current API? I think it will be useful to illustrate what kind of tests your improvements enable.

> The netlify example that omits VApp (and VMain), is actually really important for using any component that utilizes an overlay, such as a modal, tooltip, or snackbar (to name a few), to determine layout, positioning, and adding additional elements to the app.

Yep, we should add it - I'm still working on this book, early days.

**Comment by nagash77** [comment]
Hi @adambullmer this PR seems to have stalled out.  Can you provide a response to @lmiller1990 's question or if this is no longer relevant close this PR?

**Comment by adambullmer** [comment]
Sorry about that. Had been a bit busy the past few weeks. I'll try and re-explain the problem: Some components have an implicit requirement to be used within another component. Vuetify components are a good example of this for anything that will get placed out of the component of origin's scope (like the tooltip, modal, or snackbar), or for things using a portal. Currently in cypress component testing, the only way to set this up is to create an temporary abstraction component that consumes the previously described component.

This is a negative experience for the following reasons:
- in your temporary extraction component, you must be able to forward all the necessary props, attrs, and events to the child component
- you cannot access a test wrapper for the component you wish to test, but instead must access in some other way, and without any testing helpers
- you lose type inference on the component you wish to test as the wrapper is now the abstraction component
- your abstraction component adds a variable to testing as it adds the potential for integration issues to crop up, yielding false test failures/passes

The proposed changes I made try to alleviate these concerns by:
- utilizing the existing API of vue test utils and actually allow `attachTo` and `localVue` to do something (currently when passed they are ignored)
- Allowing sharing the same vue runtime (when provided), so app instances continue to be consistent
- Allow choosing the element to attach to (currently only an element with the `data-cy-root` attribute will work)
- Allowing you to first mount some simple scaffolding for the page that is an actual vue component, and not just vanilla html from the test template. Actual vue components like `v-app` are necessary given the vuetify example
- Allow in the same test case to call mount again for the component you want to test. The DOM/previous component won't get cleaned up so long as the intent to mount to an existing element is there

After that last point, when you are testing your component, you can have a wrapper that is for the actual vue component you wanted to test in the first place, and have other vue components on the page to fulfill the implicit usage requirements

> why not just write two tests, with a fresh mount each time?

As stating above, I'm not actually trying to test the page setup, but instead the relevant component that is required to be a descendent of the root `v-app`

If this still needs it, I can make a sample repo to help illustrate the problem further

**Comment by marktnoonan** [comment]
Thanks for this extra context @adambullmer. I think a sample repo could be very helpful. I'm not sure without exploring a little bit but there may be a workaround that meets your needs without changes to Cypress. But this is a good conversation to be having. I don't want to discourage this PR as much as make sure we understand the need, before you put extra work into it. A concrete example would be great.

It sounds like you are pointing out a general issue with testing components that use portals, for example, and Vuetify is just one example.

The Vuetify project itself uses Cypress component testing and handles some things that seem a bit related to this through a custom [mount command](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/cypress/support/mount.ts). I wonder if you have already taken a look at their codebase to see how component tests are implemented, and if they either haven't hit this problem around portals yet or are solving it in a different way.

I also don't really mind, in principle, exposing more VTU features in Cypress. Once we have the concrete example I think we'll have enough information to properly discuss with the team. We tend to be pretty conservative about API changes, so please forgive us if it takes some time to respond on our side from time to time.

**Comment by lmiller1990** [comment]
> Allow in the same test case to call mount again for the component you want to test. The DOM/previous component won't get cleaned up 

This seems like the main issue here, to me. I think `mount` should always clean up all the things and give you a fresh instance of whatever component you are testing. It works the same as `mount` in `createApp(app).mount(el)` - it blows away the entire previous app.

I think an example of what you currently do + what would be enabled by this feature would be very useful. Maybe there is a more fundamental issue we can address - ideally, in a fashion that other frameworks (like React) could benefit from too - I don't think the issue you are describing is unique to testing Vue.

**Pull request closed without merging**
