### PR TITLE
feat(component-testing): support passing a webpack config path

### PR DESCRIPTION
**Pull request by lmiller1990**
Support passing a path to a webpack config instead of using `find-webpack`.

closes CT-198

### CODE REVIEW

**Review by elevatebart — APPROVED** [review]
I think I like your API (the option bag for startServer) better than the original one (probably mine).
Can you update the merge so that we can see if tests are passing?

On another note, does this mean we definitely abandon automatically finding local webpack configurations if they exist? Or does it mean we will bring it back later in another architecture?

**Review by JessicaSachs — COMMENTED** [review]
Can we just take the object in? Why do we need to support the string?

**Review by JessicaSachs — CHANGES_REQUESTED** [review]
Spoke with Lachlan. I'd like to go with an object-based API instead of the webpack string path route. We can give editor hints with the Webpack Configuration types.

We _could_ support either a string or the object... but I'd rather just have one way of doing it.

**Comment by lmiller1990** [comment]
@JessicaSachs done: https://github.com/cypress-io/cypress/pull/14575/commits/9526eaf2f50bad98cb3b4e42c027410fcb123b06

**Review by JessicaSachs — APPROVED** [review]
I suppose I have one comment about the need for path.resolve... if you can drop it, drop it. Else, you can merge.

**Pull request merged**
