### PR TITLE
fix: "RangeError: Index out of range | The value of "offset" is out of range"

### LINKED ISSUE #2034: Error during screenshot capture: RangeError: Index out of range | The value of "offset" is out of range.
### Current behavior:
Executing `cy.screenshot()` on large pages causes error.  Stack trace:

```bash
     RangeError: Index out of range
      at checkInt (buffer.js:1180:11)
      at Buffer.writeUInt32BE (buffer.js:1271:5)
      at new Jimp (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/jimp/index.js:137:30)
      at stitchScreenshots (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:199:17)
      at /Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:295:21
      at tryCatcher (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
      at Async._drainQueue (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (/Users/rbayliss/Library/Caches/Cypress/3.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:781:20)
      at tryOnImmediate (timers.js:743:5)
      at processImmediate [as _immediateCallback] (timers.js:714:5)
```

### Desired behavior:
Screenshots are captured.

### Steps to reproduce:
Call `cy.screenshot()` on a page that exceeds 16,000,000 square pixels (in my case, the element is 1195px by 13518px).  Reproduction test case: https://github.com/rbayliss/cypress-test-tiny/tree/index_error

### Versions

```
Cypress package version: 3.0.1
Cypress binary version: 3.0.1
Chrome 67.0.3396.87 on OSX 10.13
```

### PR DESCRIPTION
**Pull request by santam85**
Closes #2034 

Some browsers return in certain situations a negative offset for element positions, and this is generally not an issue in Cypress, until it attempts to crop a screenshot.

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]
Thanks! This looks great. I've added a test to ensure this fixes the issue and we don't have a regression in the future. 

This is good to merge in if all the tests pass.

**Comment by santam85** [comment]
@jennifer-shehane good to hear. Any idea why the circleci checks were not coming in for me?

**Comment by jennifer-shehane** [comment]
@santam85 Sometimes they don't run for certain outside contributors and it's not obvious why. I haven't had time to investigate why ☹️

**Comment by jennifer-shehane** [comment]
### Before

Screen Shot 2020-11-30 at 3 06 54 PM


### After

No error

**Pull request merged**
