### PR TITLE
fix(proxy): omit CSP report only header

### PR DESCRIPTION
**Pull request by sdemjanenko**
Since Cypress omits the blocking CSP header, it should also omit the
report-only CSP header. This fixes a lot of `unsafe-inline` script-src
warnings that I have seen when running cypress.

A test has been added to checked that this header is removed.

### CODE REVIEW

**Comment by sdemjanenko** [comment]
Here is the console warning that shows up (and logged to our CSP reporting service):

image


As for the Linting warnings:
- Where do I go to see these warnings? The only error I found was the one I talk about below.
- Also, I copied the test block that checks `content-security-policy` is stripped out of the headers. If there are lint warnings in the test that I added, then there are lint warnings in the test that I copied. If that is the case, I recommend that the lint warnings get fixed independently to ensure the repo is in a passing state.

I also noticed that some tests failed because of a 1 character shift in the CLI output
```
   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
-  │ Cypress:    1.2.3                                                                              │
+  │ Cypress:    1.2.3                                                                             │
   │ Browser:    FooBrowser 88                                                                      │
   │ Specs:      1 found (images_spec.coffee)                                                       │
   │ Searched:   cypress/integration/images_spec.coffee                                             │
   └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Do we know why this happens? How can we make this more stable?

**Comment by jennifer-shehane** [comment]
@sdemjanenko Sorry, you can see linting warnings here or run `yarn lint`: https://circleci.com/gh/cypress-io/cypress/389664

Screen Shot 2020-07-13 at 1 07 28 PM

The other errors were unrelated to your PR and should be fixed after I merge in develop.

**Comment by sdemjanenko** [comment]
I've updated the commit to fix the lint issues.

**Comment by sdemjanenko** [comment]
The decision that gets made for `content-security-policy-report-only` should get mirrored for `content-security-policy`. Usually the `report-only` version is a jump-off step for moving to a CSP config that blocks violations instead of just reporting on them.

Personally, I don't find much value in watching CSP reports come in from Cypress, especially because Cypress' internals do a bunch of rewriting.

**Comment by flotwig** [comment]
> The decision that gets made for `content-security-policy-report-only` should get mirrored for `content-security-policy`.

That's a good point, if we decide to only strip certain CSP directives, it should apply to both headers equally.

> Personally, I don't find much value in watching CSP reports come in from Cypress, especially because Cypress' internals do a bunch of rewriting.

Yeah, it would be ideal if we could eliminate the warnings caused by rewriting, while keeping the rest.

Are the `unsafe-inline script-src` warnings the only ones you're seeing?

**Comment by sdemjanenko** [comment]
Yes, `unsafe-inline script-src` is the only warning that I observe.

**Comment by flotwig** [comment]
Ok, you are probably seeing `unsafe-inline` warnings because Cypress injects Javascript into the page header, not because of proxy's header changes: https://github.com/cypress-io/cypress/blob/cf1432e3ca75baa2b5a87def3872ece659bcc10c/packages/proxy/lib/http/util/inject.ts#L1-L25

In light of this, the best solution IMO is to always add a `script-src 'unsafe-inline'` directive whenever a Content-Security-Policy or Content-Security-Policy-Report-Only is encountered in the proxy, either by adding to the existing `script-src` directive, or by adding a new `script-src` directive. 

I think this will get rid of these Cypress-only warnings while letting us retain the behavior of CSP, which helps accomplish the goal of Cypress tests closer to matching the "real world".

What do you think?

**Comment by flotwig** [comment]
Slightly better idea: we could always add `'nonce-<base64-value>'` as documented [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src), with a nonce matching the injected HTML, so we don't need to universally apply `'unsafe-inline'`. The injected HTML contains variables, so you'd need to be passing the nonce around a bit, so this is a little more work.

**Comment by sdemjanenko** [comment]
I like the nonce idea best. Adding `unsafe-inline` feels too general.

**Comment by flotwig** [comment]
Converting this to a draft since it's not ready for review. @sdemjanenko if you pick this back up again, please feel free to tag me with any questions/when you are ready for review.

**Comment by sdemjanenko** [comment]
@flotwig I'm actually pretty annoyed by this. Given your responses indicating the desire for new functionality, I assumed you and your team would be taking that on.

I think this commit is independent of that work. This commit just brings the same behavior to the report only header as already exists for the normal header.

I would ask that you reconsider pulling in this change as is and then put that additional functionality on your roadmap for your team to do.

**Comment by flotwig** [comment]
> I assumed you and your team would be taking that on.

I assumed the opposite :smile: Apologies for not communicating more clearly on that point.

> I think this commit is independent of that work. This commit just brings the same behavior to the report only header as already exists for the normal header.

Thanks for the reminder, I see what you mean now. With that context, I think this is fine to merge as-is.

**Comment by sdemjanenko** [comment]
Thanks for the quick response. I should have followed up earlier as well. I am looking forward to seeing this hit a production release. It will fix a lot of CSP report only noise that I see.

**Comment by flotwig** [comment]
Oh wow, our very own @bahmutov opened an issue for this 3 years ago: https://github.com/cypress-io/cypress/issues/1030

**Pull request merged**
