### PR TITLE
chore: merge develop into 10.0-release

### PR DESCRIPTION
**Pull request by marktnoonan**
We had 14 files with merge conflicts this time around. Summary:

- Several dependency-version-related conflicts, mostly resolved in favor of the 10.0 versions, unless `develop` was a higher version.
- `circle.yml` conflict with branch names to test for in specific workflows, resolved by dropping old branches and adding this branch name
- Couple of tiny conflicts related to [unexpected ANSI color chars shown on Firefox warning message about chromeWebSecurity](https://github.com/cypress-io/cypress/pull/20512/) changes
- Some conflicts around new uses in `develop` of the global `root` variable from `spec_helper` that's been removed in `10.0-release`

The rest were straightforward conflicts where keeping both changes was fine, or it was obvious that, eg a deleted file in `10.0-release` that was edited in `develop` should stay deleted in `10.0-release`

### CODE REVIEW

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Easy one - changes seem fine, can you re-run CI to see if it's just flake?

**Comment by marktnoonan** [comment]
@lmiller1990 one of the CI failures was flake, the windows one was pre-existing on 10.0-release, but not usually run on PRs, so I'll make a bug ticket for what seems to be the cause of the flake.

**Review by flotwig — DISMISSED** [review]

**Comment by flotwig** [comment]
@marktnoonan it seems weird to me that your change didn't require changing any tests, isn't this covered by some spec somewhere?

**Comment by marktnoonan** [comment]
@flotwig `/packages/launchpad/cypress/e2e/migration.cy.ts` was failing in windows due to `path.normalize` converting forward slashes to backslashes, so when we use a different method to manage the `./` at the start of the paths we generate, we are not avoiding those (unwanted) backslashes, so the test is passing now. The test itself was correct all along.

**Review by flotwig — APPROVED** [review]

**Pull request merged**
