### PR TITLE
Add option to ignore special character sequences to cy.type

### LINKED ISSUE #4287: Allow to ignore special character sequences for cy.type
### Current behavior:

`cy.type` considers everything in `{}` as modifier sequence. In our app we have embedded code runner. For testing we put there code from fixtures with `cy.type`. And `cy.type` throws `CypressError: Special character sequence: '{...}' is not recognized` when code includes some braced expression.

### Desired behavior:

Add option to `cy.type` to not treat `{}` as modifier sequence.

### Versions

Cypress: 3.2.0

### PR DESCRIPTION
**Pull request by JArlinghaus**
closes #4287

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Hey @JArlinghaus, thanks for the contribution! We've recently implemented automatic linting on this project and are getting some linting failures if you could fix these. 🙏 	

```
/root/cypress/packages/driver/src/cypress/keyboard.js
  355:5   error  Expected space(s) after "if"               keyword-spacing
  355:32  error  Multiple spaces found before '{'           no-multi-spaces
  361:9   error  Expected blank line before this statement  padding-line-between-statements

/root/cypress/packages/driver/test/cypress/integration/commands/actions/type_spec.js
  1512:77  error  A space is required after '{'   object-curly-spacing
  1512:98  error  A space is required before '}'  object-curly-spacing
```

**Comment by JArlinghaus** [comment]
@jennifer-shehane linting failures should be fixed now.

**Comment by JArlinghaus** [comment]
@chrisbreiding I changed the name of the option to disableSpecialCharSequences, and made a PR for the documentation here https://github.com/cypress-io/cypress-documentation/pull/1885.

**Comment by jennifer-shehane** [comment]
The only failure is the one caused by cypress.io - which is known, so merging in with this failure.

**Comment by brian-mann** [comment]
We need to rename this option to be `parseSpecialCharSequences: false` to couple the option with the intended behavior in an affirmative way - as opposed to inverting it with `disable*: true`.

**Pull request merged**
