### PR TITLE
feat: updated scaffolding, new project & user banners, ability to remove scaffolding

### PR DESCRIPTION
**Pull request by panzarino**
- Closes GROW-175, GROW-204, GROW-211, GROW-212

Adds some of the functionality (or equivalent) mentioned in #3364, given this work + CT CLI might be time to close that issue?

Updated scaffolding changes implemented in https://github.com/cypress-io/cypress-example-kitchensink/pull/481

### User facing changelog

List of things in this PR that could be mentioned in changelog:

- Updates initial scaffolding to include example tests for TodoMVC
- Removes existing onboarding modal for new project
- Adds onboarding banners with helpful links for new users and new projects
- Adds ability to easily remove scaffolded integration tests when a new project is created
- Added ability to create a new file from the UI when no files are found

Not sure if we need to include specifics around the modal/banners - we could probably just consolidate to improved first time / new project onboarding experience

### Additional details

For removing files, we only remove files that came from our scaffolding and were not modified (compares by name, filesize) to ensure that users do not loose any of their work.

The new user banner will only appear the first time that someone uses Cypress if they're joining an existing project. The new project banner will appear on every new project.

Updated kitchen sink has been deployed

### How has the user experience changed?

Here's a gif showing the new project banner as well as deleting the example files and the updated "no files found" screen

Screen-Recording-2021-05-19-at-1

Here's what the new user banner looks like (joining an existing project)

Screen Shot 2021-05-19 at 19 34 02

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by chrisbreiding** [comment]
Looks good code-wise. Functionally, I found one case that might need some work:

- Open a new project in Cypress
- Choose to delete all example specs
- Close Cypress
- Manually delete the `cypress` folder and `cypress.json`
- Open the project in Cypress again

It scaffolds all the files, including the specs, but doesn't show the banner with the option to delete them. 

Maybe this is fine, it's a bit of an edge-case, but I feel like we should either:

- Show the option to delete the example specs again
- Or detect that the user had opted to delete them already and only scaffold the other folders/files that Cypress needs

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
1. A note I have around the experience. If you edit the example files, then select 'Delete example files', is prompts asking if you want to delete all examples files, but then it doesn't delete *all* of them like it said it would, since I edited some. This is unexpected. I would prefer either of the options below:

	- It says it will delete all, so it deletes all (since it prompted to confirm anyway).
	- It indicates that it won't delete edited files. Like in the prompt "Are you sure you want to delete all example files? *Note: this won't delete any files that were already edited*. 

	The second option seems unexpected to me though. I don't know why I would want to keep an example file that I edited and confirmed is ok to delete, I was likely just playing around with stuff. So it adds an extra step of me having to delete each file individually and the directory. 

2. If you're a new user to Cypress completely, there's no option to remove the example files from the UI? Is that intended?

	Screen Shot 2021-05-24 at 12 09 08 PM

3. I'm trying to test the deleting of files on Windows, just waiting for my VM to spin up Cypress.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
I have another edge case. If I have a different `integrationFolder` set which was empty, then I click to 'Create File' and create a file, the banner for the new project shows up with the prompt to delete the example files (which were never created). 

Screen Shot 2021-05-24 at 12 16 20 PM

**Comment by panzarino** [comment]
@jennifer-shehane I added an error message to handle your first point from above - we had some discussions about how the functionality works so I'd be hesitant to change that now, you do make a good point though and we can revisit in the future.

For the second, yes that is intentional. You will never get the new user banner and the new project banner - if you're a first time user for your first project you should see the new project banner (just updated a test for this). The new user banner only appears for new users that are joining existing projects (and therefore shouldn't have a reason to delete the files).

As for your second comment, that's a very valid issue and the fix for that could be a bit more involved (off the top of my head). The growth team has been trying to get these scaffolding changes in for a while now (we've been held up iterating on copy & design) so I'd be in favor of releasing as is and adding that as a fast follow, but if you feel like that's something strictly necessary to release this in the first place then I'd understand and we'll probably have to hold off until the next release.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Cypress crashes on Windows when you confirm to delete the example files on a new project with the following error:

```
(node:2576) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `Cypress --trace-warnings ...` to show where the warning was created)
Error: You attempted to scaffold a file, 'cypress\integration\1-getting-started', that's not in the scaffolded file tree. This is because you added, removed, or changed a scaffolded file. Make sure to update scaffold#fileTree to match your changes.
    at C:\Users\sheha\Documents\cypress\packages\server\lib\scaffold.js:377:15
    at processImmediate (internal/timers.js:461:21)
Error: You attempted to scaffold a file, 'cypress\integration\1-getting-started', that's not in the scaffolded file tree. This is because you added, removed, or changed a scaffolded file. Make sure to update scaffold#fileTree to match your changes.
    at C:\Users\sheha\Documents\cypress\packages\server\lib\scaffold.js:377:15
    at processImmediate (internal/timers.js:461:21)
Done in 1086.72s.
```

Tried again to get debug logs and it's printing this

```
2021-05-24T19:28:04.192Z cypress:server:scaffold scaffolded files ["cypress\\integration\\1-getting-started\\todo.spec.js","cypress\\integration\\2-advanced-examples\\actions.spec.js","cypress\\integration\\2-advanced-examples\\aliasing.spec.js","cypress\\integration\\2-advanced-examples\\assertions.spec.js","cypress\\integration\\2-advanced-examples\\connectors.spec.js","cypress\\integration\\2-advanced-examples\\cookies.spec.js","cypress\\integration\\2-advanced-examples\\cypress_api.spec.js","cypress\\integration\\2-advanced-examples\\files.spec.js","cypress\\integration\\2-advanced-examples\\local_storage.spec.js","cypress\\integration\\2-advanced-examples\\location.spec.js","cypress\\integration\\2-advanced-examples\\misc.spec.js","cypress\\integration\\2-advanced-examples\\navigation.spec.js","cypress\\integration\\2-advanced-examples\\network_requests.spec.js","cypress\\integration\\2-advanced-examples\\querying.spec.js","cypress\\integration\\2-advanced-examples\\spies_stubs_clocks.spec.js","cypress\\integration\\2-advanced-examples\\traversal.spec.js","cypress\\integration\\2-advanced-examples\\utilities.spec.js","cypress\\integration\\2-advanced-examples\\viewport.spec.js","cypress\\integration\\2-advanced-examples\\waiting.spec.js","cypress\\integration\\2-advanced-examples\\window.spec.js","cypress\\fixtures\\example.json","cypress\\support\\commands.js","cypress\\support\\index.js","cypress\\plugins\\index.js"]
Error: You attempted to scaffold a file, 'cypress\integration\1-getting-started', that's not in the scaffolded file tree. This is because you added, removed, or changed a scaffolded file. Make sure to update scaffold#fileTree to match your changes.
    at C:\Users\sheha\Documents\cypress\packages\server\lib\scaffold.js:377:15
    at processImmediate (internal/timers.js:461:21)
Error: You attempted to scaffold a file, 'cypress\integration\1-getting-started', that's not in the scaffolded file tree. This is because you added, removed, or changed a scaffolded file. Make sure to update scaffold#fileTree to match your changes.
    at C:\Users\sheha\Documents\cypress\packages\server\lib\scaffold.js:377:15
    at processImmediate (internal/timers.js:461:21)
2021-05-24T19:28:04.266Z cypress:server:browsers browsers.kill called with no active instance
2021-05-24T19:28:04.794Z cypress:electron electron closing { code: 0, signal: null }
2021-05-24T19:28:04.794Z cypress:electron calling callback with code 0
2021-05-24T19:28:04.794Z cypress:server:cypress electron finished with 0
2021-05-24T19:28:04.826Z cypress:cli child event fired { event: 'exit', code: 0, signal: null }
2021-05-24T19:28:04.828Z cypress:cli child event fired { event: 'close', code: 0, signal: null }
Done in 78.23s.
```

**Comment by jennifer-shehane** [comment]
@panzarino I have another note on the new scaffolding that I just found. For the new `todo` spec, if you run it via `cypress run` on a Mac in Electron (headless and headed) - it exhibits this issue https://github.com/cypress-io/cypress/issues/7245, where it prints `Cypress Helper (Renderer)[2978:18327] CoreText note:` messages to stdout. 

Example run here: https://github.com/cypress-io/cypress-example-kitchensink/pull/493/checks?check_run_id=2669349890

I think this is a less than ideal experience for Mac users to provide a person's first run with all these logs. I don't have a lot of understanding why this prints for some site and not others. 

So if you have time to investigate and fix - great, otherwise you could probably hide the logs when they're printed. I believe we've used this utility to suppress warnings in the past: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/suppress_warnings.js 

Screen Shot 2021-05-26 at 7 53 41 AM

```
  example to-do app
2021-05-25 20:57:28.041 Cypress Helper (Renderer)[2978:18327] CoreText note: Client requested name ".AppleSymbolsFB", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2021-05-25 20:57:28.041 Cypress Helper (Renderer)[2978:18327] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2021-05-25 20:57:28.379 Cypress Helper (Renderer)[2978:18327] CoreText note: Client requested name ".AppleSymbolsFB", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
    ✓ displays two todo items by default (4670ms)
2021-05-25 20:57:29.136 Cypress Helper (Renderer)[2978:18327] CoreText note: Client requested name ".AppleSymbolsFB", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
    ✓ can add new todo items (1709ms)
2021-05-25 20:57:30.447 Cypress Helper (Renderer)[2978:18327] CoreText note: Client requested name ".AppleSymbolsFB", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
    ✓ can check off an item as completed (708ms)
    with a checked task
2021-05-25 20:57:30.997 Cypress Helper (Renderer)[2978:18327] CoreText note: Client requested name ".AppleSymbolsFB", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
      ✓ can filter for uncompleted tasks (679ms)
2021-05-25 20:57:31.772 Cypress Helper (Renderer)[2978:18327] CoreText note: Client requested name ".AppleSymbolsFB", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
      ✓ can filter for completed tasks (875ms)
2021-05-25 20:57:32.730 Cypress Helper (Renderer)[2978:18327] CoreText note: Client requested name ".AppleSymbolsFB", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
      ✓ can delete all completed tasks (829ms)
```

**Comment by panzarino** [comment]
Ok so I've fixed some of the issues that have been mentioned here. A majority of the things that I've said [above](#issuecomment-847210049) still hold true, but I have also made some improvements.

> I have another edge case. If I have a different `integrationFolder` set which was empty, then I click to 'Create File' and create a file, the banner for the new project shows up with the prompt to delete the example files (which were never created).

I've fixed this issue reported above so that we no longer display the message at all if files were not scaffolded. Ideally we would just hide the delete files link but that's a bit more complicated and we can be reasonably sure that users changing their `integrationFolder` are familiar with the basics of writing tests. 

I've fixed the issue with font error messages when `run`ning the tests in https://github.com/cypress-io/cypress-example-kitchensink/pull/497. I've already deployed this to the live kitchensink.

I also believe that I've fixed the issue with deleting files on Windows. I still don't have a Windows dev env so this will have to be manually tested before we merge but I'm reasonably confident that it should work just fine. If it doesn't, I would guess that perhaps this line may not work properly since it uses `/` hardcoded (but it has worked in the past) - https://github.com/cypress-io/cypress/blob/GROW-175/packages/server/lib/scaffold.js#L16. I made a change that uses function now in the function that creates the scaffolding files so testing that the actual scaffolding works along with the deleting would be useful. In the case that something is wrong, changing the `/` to `path.sep` should fix it (I didn't want to change it preemptively because it might be working as is and a change would break it).

All in all, with these updates I think that we should be good to get this finally merged and released 🎉

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@panzarino Just wanted to give immediate feedback for the Windows fix. So, it doesn't crash when I confirm to delete the example files, but it also doesn't delete the example files at all. 😢 I confirmed looking in the directory - all the files are still there. So it's not just a visual bug. 

I plan to look over the other changes still.

**Comment by jennifer-shehane** [comment]
So, I don't think this is deleting the example files on my Mac either. I don't think I'm doing anything weird. I'm creating a brand new project - removing the `firstOpenedCypress` field from the saved state then opening it in global mode (`yarn start`). I don't think the delete button is working. 

I updated the 'note' in the delete modal to be a bit more subtle. 

#### Before

Screen Shot 2021-06-17 at 1 36 38 PM


#### After

Screen Shot 2021-06-17 at 1 35 43 PM

**Comment by panzarino** [comment]
@jennifer-shehane I've made the change I mentioned in my previous comment along with using a different remove function to delete the files with the goal of fixing this issue on Windows. I'm unable to repro the issue on Mac but perhaps these changes will fix it. I've tried testing multiple times both before and after these changes and it's been working perfectly for me (+ tests are passing).

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@panzarino So, this seems to have really broken the initial scaffolding of files on Windows.  

I attached a photo of what is scaffolded. This seems really weird. Where is this `eha` directory even coming from?? 

We've had reports of like, weird scaffolding before on Windows (I'd have to find them). So I thought maybe I did something unusual. But I made sure to switch to `develop` to confirm that it doesn't happen on develop.

Screen Shot 2021-06-21 at 8 36 08 AM

I would suggest setting up a VM at this point - if only to have 2 people verify the behavior and isolate whether it's a local issue or not. It will also close the loop on work + review so this can get done quicker. Sorry. :(

**Comment by panzarino** [comment]
@jennifer-shehane Yeah I had a feeling that the initial scaffolding would break with some of the changes that I just introduced - I've reverted those and kept some of the removal changes so hopefully everything works properly now.

I'm working on setting up a VM so that I can test on my own - thanks for being so patient and testing this on Windows so many times already.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@panzarino The scaffolding is fixed now, but after confirming to delete the files - the files are not deleting on Windows.

**Comment by panzarino** [comment]
@jennifer-shehane Thought that might happen - I have slow internet so I'm unable to download Windows for a VM in a realistic timeframe. I'm currently testing through appveyor and looking at the test results there to hopefully get it to work - once the unit tests pass on windows I imagine it would work properly in practice

**Comment by jennifer-shehane** [comment]
@panzarino K, let me know when you want me to run again. Setting up a VM will take a long time.

**Comment by panzarino** [comment]
@jennifer-shehane So I believe that I've finally actually fixed the problem - I've gotten all remove scaffolding unit tests to pass  on appveyor so I'm confident that it'll actually work in manual testing.

**Review by jennifer-shehane — APPROVED** [review]
@panzarino Seems to be working now on Windows + Mac. Looks like it will make it in this release. 👍

**Pull request merged**
