### PR TITLE
fix: head content reset, fix #19721

### LINKED ISSUE #19721: @cypress/vue - Global component does only include CSS in first test
### Current behavior

I use a global component for my FontAwesomeIcon (@fortawesome/vue-fontawesome).

When I import component and configure it in my mount statement then the CSS of this Component is only available in my first Test. All other test will miss the CSS.

Only when I import the CSS file directly, then it's available in all tests.

### Desired behavior

The CSS should be loaded in all tests.

### Test code to reproduce

```
import Sidebar from '@/components/ui/Sidebar.vue'
import { mount } from '@cypress/vue'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import router from '@/router/index'
import i18n from '@/lib/i18n'
import { createPinia } from 'pinia'

import '@/styles/index.css'
// import '@fortawesome/fontawesome-svg-core/styles.css'

function wrapperFactory() {
  const pinia = createPinia()

  return mount(Sidebar, {
    extensions: {
      components: {
        FontAwesomeIcon: FontAwesomeIcon,
      },
      plugins: [i18n, pinia, router]
    }
  })
}

it('Sidebar is visible', () => {
  wrapperFactory()
    .get('#sidebar .sidebar')
    .should('be.visible')
})

it('Toggle Sidebar', () => {
  const wrapper = wrapperFactory()

  // open sidebar
  wrapper
    .get('#sidebar .toggle-button')
    .click()

  wrapper
    .get('#sidebar .sidebar')
    .invoke('outerWidth')
    .should('be.gt', 100)

  // close sidebar
  wrapper
    .get('#sidebar .toggle-button')
    .click()

  wrapper
    .get('#sidebar .sidebar')
    .invoke('outerWidth')
    .should('be.lt', 100)
})

```

### Cypress Version

9.2.1

### Other

"@cypress/vite-dev-server": "^2.2.2",
"@cypress/vue": "^3.1.0",
"cypress": "^9.2.1",
"vite": "^2.7.10",
"vue": "^3.2.26",

### PR DESCRIPTION
**Pull request by Akryum**
- Closes #19721

### User facing changelog

Fixed Vue component style missing after the first test.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by ZachJW34** [comment]
@Akryum Thanks for the contribution! Can you rebase your branch so as to only include the vue change? Might be easier to checkout latest master and copy your changes over.

**Review by ZachJW34 — APPROVED** [review]
Looks good!

**Review by JessicaSachs — APPROVED** [review]
LGTM, thank you. This was missed when we changed how we clean up the document.

**Comment by ZachJW34** [comment]
CI is not working correctly for external contributors. I believe it is fixed on develop so I've created [a PR](https://github.com/cypress-io/cypress/pull/21298) getting master up to date. Once we get that merged we can get a new build for this PR

**Comment by Akryum** [comment]
@ZachJW34 I see there are some (probably flacky) errors for this run: https://circleci.com/gh/cypress-io/cypress/1499006?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ZachJW34** [comment]
@Akryum going to merge, the flake you are seeing is due to a bug with how we run our tests and you being an external contributor.

**Pull request merged**
