### PR TITLE
feat: take Firefox support out of beta

### LINKED ISSUE #8241: Take Firefox support out of beta; put `firefoxGcInterval` behind version switch
### Current behavior:
Cypress FF support is in beta and we always force `firefoxGcInterval`.

### Desired behavior:
Remove beta label from FF support and only require `firefoxGcInterval` if running Firefox < 80 (check exact version here: https://bugzilla.mozilla.org/show_bug.cgi?id=1608501#c65 )

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #8241

### User facing changelog

- Firefox support is now out of beta!
- Updated `firefoxGcInterval` workaround to only apply to versions of Firefox older than 80. A warning will be presented if an older version is used.

### Additional details

New warning:

image

(note, the BrowserIcon for Custom Firefox is wrong (?)... not related to these changes)

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?  https://github.com/cypress-io/cypress-documentation/pull/3168
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by Bkucera — CHANGES_REQUESTED** [review]
we also claim firefox is in beta when we list supported browsers:
other than that looks good
image

**Comment by flotwig** [comment]
oo, nice catch, thanks

**Comment by flotwig** [comment]
wow, our tests really do not like FF 81...

**Comment by flotwig** [comment]
@Bkucera the e2e test failures seem to be related to an issue with video recording and Firefox 80, not specifically related to this PR. I am able to reproduce failures in `develop` by running `4_domain_spec` with Firefox 79 (passes) and Firefox 80 (fails with video recording error from no frames). 

`4_domain_spec` passing on `develop` by Firefox version:

|| headed | headless
|--- | --- | ---
|Firefox 79.0 | :heavy_check_mark: | :heavy_check_mark: 
|Firefox 80.0 | :x: | :x:

So for this PR let's not bump the docker image. I'll create a new issue for this.

**Comment by flotwig** [comment]
@Bkucera i've completed testing this PR against the memory leak repro we have in 1_firefox spec. Here are the results + videos running in a Fedora VM with 3GB of RAM:

* [Firefox 79 with forced GC disabled](https://drive.google.com/file/d/1Wa51TWns23DZzl02gukB7fhGnFBjcKFW/view?usp=sharing) - invokes Fedora's OOM killer when system runs out of RAM, as expected
- [Firefox 79](https://drive.google.com/file/d/1Ayb3Ouzs3_ny5Wz8ynmkqD_fpVC22x5Z/view?usp=sharing) - completes in 288 seconds with forced GC happening
- [Firefox 80](https://drive.google.com/file/d/1lgN7CN24OdMMZtR71AiMWbOet3vXGnOk/view?usp=sharing) - completes in 208 seconds with NO forced GC
	* from the debug output (and the fact that it's ~40% faster) you can see that no forced GC is happening

I believe that this confirms that Mozilla fixed the memory leak as of FF 80, and also confirms that this PR still appropriately handles forced GC for older versions of Firefox.

**Review by Bkucera — APPROVED** [review]
Looks good

**Pull request merged**
