### PR TITLE
Issue 5656 Fix validation of cookie domain

### LINKED ISSUE #5656: Cypress incorrectly validates domain of cookies in 3.5.0
### Current behavior:

Cookies are failing to set for subdomains during `cy.request`.
E.g. we call `/auth` of `auth.test.server` and it returns `token` cookie with `.test.server`. In this case cookie is not set.

### Desired behavior:

Cookie is set in above example.

### Steps to reproduce: (app code and test code)

Look at [packages/server/lib/request.coffee#setCookiesOnBrowser](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/request.coffee#L449):

```
return if not tough.domainMatch(cookie.domain, parsedUrl.hostname)
```

And at [`tough-cookie` documentation](https://www.npmjs.com/package/tough-cookie#domainmatchstrdomstrcanonicalizetrue):

```
domainMatch(str,domStr[,canonicalize=true])
Answers "does this real domain match the domain in a cookie?". The str is the "current" domain-name and the domStr is the "cookie" domain-name. Matches according to RFC6265 Section 5.1.3, but it helps to think of it as a "suffix match".
```

So it should be:

```
return if not tough.domainMatch(parsedUrl.hostname, cookie.domain)
```

### Versions

`>=3.5.0`

### PR DESCRIPTION
**Pull request by donotello**
- Closes #5656

### User facing changelog

- Fixed a regression in 3.5.0 where cookies set in a redirect on a `cy.visit` or in a `cy.request` with a custom `Domain` that is not a subdomain of the current domain would fail to set. 

### Additional details

Defect introduced in `3.5.0` was fixed by correct usage of 3rd party library (`tough-cookie`) method.

### How has the user experience changed?

N/A

### PR Tasks

Not sure what is the right place for the tests. I suggest cypress team itself to decide if tests for these are needed and add them if required.

- [ ] Have tests been added/updated?

*NOTE:* looks like 2 lines change didn't work (though it doesn't seems to me that failures are related to my change). Feel free to close this PR and work on #5656 in a separate one or update this pull request.

### CODE REVIEW

**Comment by flotwig** [comment]
Thanks for the PR. `tough-cookie`'s documentation is kinda confusing when it comes to the order of parameters here.

The tests that are failing in `server-e2e-tests-2` are relevant to cookies, it seems like these changes break sending the correct cookies when a FQDN is requested. You can check 2_cookies_spec locally to see what's going on:

```
cd packages/server
npm run test-e2e -- --spec 2_cookies_spec --browser electron
```

**Comment by jennifer-shehane** [comment]
Hey @donotello, any updates on the requests made by @flotwig? These changes broke some of our other tests. Will you have time to look at this?

**Comment by flotwig** [comment]
I think the failures in the tests are just because we don't clear all cookies of all domains after each test (see #408 ), a `cy.clearCookies({ domain: null })` should fix these up... I will look at this some more tomorrow.

**Comment by donotello** [comment]
> Hey @donotello, any updates on the requests made by @flotwig? These changes broke some of our other tests. Will you have time to look at this?

Hi, sorry I was away.

I see that tests are passing now. Are we ready to merge?

**Pull request merged**
