### PR TITLE
chore: fixed typos docs line 386 & 387

### PR DESCRIPTION
**Pull request by anicodes404**
- Closes 

### User facing changelog
Fixed typos of 'component(s)' on line 386 & 387

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by AtofStryker** [comment]
@adnerdable are you able to make the single commit here semantic to pass the PR checks? You might need to rebase and amend the message to something like `chore: fixed typos in docs line 386 & 387`? If it's too confusing let me know and we can figure something out!

**Review by warrensplayer — APPROVED** [review]
Thanks for fixing the typos!

**Review by emilyrohrbough — APPROVED** [review]

**Comment by AtofStryker** [comment]
@adnerdable I went ahead and amended the commit message to make it semantic in the forked branch. I hope that was alright. We should be able to get this into develop shortly and thank you again for fixing this!

**Comment by anicodes404** [comment]
@AtofStryker Perfectly fine, thank you! Apologies for the delay, I was researching how to do it as I am unfamiliar with semantic commit. This is my first PR and I really appreciate being able to contribute. 🙂

**Pull request merged**
