### PR TITLE
Catch & ignore ENOTCONN errors when piping Cypress subprocess

### LINKED ISSUE #5241: ENOTCONN error on Windows runs
### Current behavior:
cypress throws error on Windows when launching more than one run as a separate process with execSync

```
C:\Users\fetest\Desktop\runners\loki\builds\bkDJzsb2\0\games\bridge\node_modules\cypress\lib\exec\spawn.js:175
          throw err;
          ^

Error: shutdown ENOTCONN
    at Socket._final (net.js:409:25)
    at callFinal (_stream_writable.js:627:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOTCONN',
  code: 'ENOTCONN',
  syscall: 'shutdown'
}
child_process.js:660
    throw err;
    ^

Error: Command failed: "./node_modules/.bin/cypress" run --env layout="portrait-hd",lang="en",suite="dev",url="https://cdn.dopamine-gaming.com/review/games/bridge/dev" --spec cypress/integration/base_spec.js --headed
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at execScript (C:\Users\fetest\Desktop\runners\loki\builds\bkDJzsb2\0\games\bridge\node_modules\automation\bin\test.js:81:5)
    at run (C:\Users\fetest\Desktop\runners\loki\builds\bkDJzsb2\0\games\bridge\node_modules\automation\bin\test.js:74:9)
    at C:\Users\fetest\Desktop\runners\loki\builds\bkDJzsb2\0\games\bridge\node_modules\automation\bin\test.js:50:42
    at Array.forEach (<anonymous>)
    at test (C:\Users\fetest\Desktop\runners\loki\builds\bkDJzsb2\0\games\bridge\node_modules\automation\bin\test.js:50:24)
    at Object.<anonymous> (C:\Users\fetest\Desktop\runners\loki\builds\bkDJzsb2\0\games\bridge\node_modules\automation\bin\test.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 996,
  stdout: null,
  stderr: null
}
```

### Steps to reproduce:

Launch more than one time cypress run command with execSync
```
execSync('"./node_modules/.bin/cypress" run --spec cypress/integration/base_spec.js');
execSync('"./node_modules/.bin/cypress" run --spec cypress/integration/components_spec.js');
```

### Versions
Cypress v3.4.1
Windows Version 10.0.18362
Node 12.11.0
npm 6.11.3

This issue is related to https://github.com/cypress-io/cypress/issues/1841

and is fixable by adding the erro code into already existing condition (line 169)

image

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #5241

### User facing changelog

Fixed a bug where Cypress would exit with an `ENOTCONN` error at the end of a test run if using Node 12.11.0 or greater on Windows.

### Additional details

~~Still trying to reproduce in my Windows VM, but a user in #5241 did say that this patch resolves the issue for them.~~

Was able to reproduce (only in `cypress run`) and confirmed that this patch does fix the issue for Node 12.11.0 and Windows 10.

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

**Comment by Bkucera** [comment]
why dep change to `https-proxy-agent` ?

**Comment by flotwig** [comment]
> why dep change to `https-proxy-agent` ?

To fix the build - this PR hadn't been merged at the time: https://github.com/cypress-io/cypress/pull/5294

**Comment by michalko** [comment]
when's the new version coming ?

**Comment by TaukSnarkyAgrud** [comment]
I just want to know if there's a temp fix I can perform.
I am running async calls from a node script and this fails even when I make them await. 

`await executeCypressRun('path-to-spec-redacted', "⚕️app👩‍⚕️", "💻subdomain💻", webTestDescription, "Production Environment", 35000);

        executeCypressRun('path-to-spec-redacted', "⚕️app👩‍⚕️", "📟subdomain📟", emrTestDescription, "Production Environment", 35000);

function executeCypressRun(spec, domain, subdomain, environment, usualTime){
    console.log("------------------>Checkpoint1<_-----------------")
    return cypress.run({ 
        spec: spec,
        config: {
            defaultCommandTimeout: 10000,
            integrationFolder: 'path-to-integration-redacted',
            trashAssetsBeforeRuns: true
        }
    }).then((results) => {
        console.log("------------------>Chekpoint2<_-----------------");
        analyseThenPostToTeams(results, domain, subdomain, environment, usualTime);
    });
}`

**Comment by flotwig** [comment]
@TaukSnarkyAgrud There's a 1-line patch in the original issue comment that you can use: https://github.com/cypress-io/cypress/issues/5241

**Comment by TaukSnarkyAgrud** [comment]
@flotwig Thanks. I saw 5241 but my understanding didn't coalesce till just now. Working now.

**Pull request merged**
