### PR TITLE
fix: elements with opacity: 0 are not visible

### LINKED ISSUE #4474: Opacity is not considered for visibility checks
### Current behavior:
image

### Desired behavior:
When opacity === 0, the element should be considered as not visible to avoid evaluating the next command sooner than expected and causing flakiness.

### Steps to reproduce: (app code and test code)
I think the issue is pretty clear from the image, but I can provide reproduction later if you consider it necessary.

### Versions
cypress@3.3.1
Electron 61
Windows 10 x64

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-78) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #4474

### User facing changelog

BREAKING CHANGE: Elements with `opacity: 0` are no longer considered to be visible. This includes elements with an ancestor that has `opacity: 0` since a child element can never have a computed opacity greater than that of an ancestor.

### Additional details

This is a **breaking change** since it has the potential to change the behavior of existing tests that rely on elements with `opacity: 0` to be visible.

Docs PR: https://github.com/cypress-io/cypress-documentation/pull/3071

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by jennifer-shehane — DISMISSED** [review]
I'd love to have a test case for testing something changing opacity. I feel like the most common use case is someone having an element with `opacity: 100`, click something which triggers the element to have `opacity: 0`. So we'd want to make sure that when they assert 'el is not visible' that it waits for opacity to reach 0 and passes. I think this will work from the code that's written, but a test would be nice to confirm.

Is the `ignoreOpacity` option meant to be user facing? It seems it's just hard coded to be `false`. Why is it there at all?

Looks good to me otherwise. I think Brian had some notes about the mocha assertions and opacity that he wanted to make sure was covered. Not sure if y'all touched base on that.

**Review by Nishant-Ranjan-vineti — DISMISSED** [review]

**Comment by panzarino** [comment]
@jennifer-shehane Just added a test for that.

Regarding `ignoreOpacity`, it is not intended to be user facing and it can be considered hard-coded when the user is making an assertion. From now on, we will always consider `opacity: 0` to not be visible when asserting on visibility. However, we still need to consider these elements actionable. Therefore, we have to check all of the other components of visibility, excluding opacity. That's why [I changed](https://github.com/cypress-io/cypress/pull/8244/files#diff-c74b4e0ff6c718de2fb860b3bbe4c7afL161-R161) `ensureVisibility` to call `isHidden` directly (with `ignoreOpacity: true`) rather than using the jquery selector.

Adding this additional parameter seemed to be the easiest and cleanest way of achieving this. Outside of `isHidden` there is no easy way to detect if an element is hidden only because of opacity (doing something like `isVisible() || opacity == 0` logically doesn't work). We could do something like moving the opacity check in `getReasonIsHidden` to the end and checking if the reason is opacity, but I didn't feel like that was a good solution. I've [added tests](https://github.com/cypress-io/cypress/pull/8244/files#diff-8ab80eff8639f9e77e217a5024c4bc51R2057-R2067) that complement my (somewhat convoluted) explanation here.

[Selenium has this option, too](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/atoms/dom.js#L453).

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@panzarino It seems that the sizzle selector calls into the `isHidden` method, calling it with the element, context (document), and xml. This xml is evaluating to `false`, which was always setting the `ignoreOpacity` option to `false` on these calls. 

Screen Shot 2020-08-24 at 3 37 43 PM

Since updating the logic to try and accept an object, it's always set to `false` when using the `:hidden` selectors, so I don't think this option is being read in correctly.

Put a `debugger` in `isHidden` method - see that 3rd arg is always called with `false` from sizzle: https://github.com/cypress-io/cypress/blob/issue-4474/packages/driver/src/dom/visibility.js#L23:L23

Maybe I'm misunderstanding something about the implementation.

**Comment by panzarino** [comment]
@jennifer-shehane Looks like jQuery always calls the selector with 3 parameters, the element, a context (which is always the document), a a third `xml` which is always false. I'm surprised that the second parameter hasn't caused any issues with our implementation yet. I've updated `jquery.js` to only accept the first element parameter for our overwrite, and this seems to fix the issue.

**Review by jennifer-shehane — APPROVED** [review]

**Comment by thienthu1410** [comment]
I just checked on the page https://demoqa.com/automation-practice-form, and I see that: one element has opacity: 0, but it is still visible to my eyes
image
But Cypress treat it as invisible 
image


Version Cypress: 13.0.0

**Comment by NityaQA** [comment]
I think its not fixed properly. As same issue I am facing. I tried to assert a checkbox, which is clearly visible to my eye. But cypress is throwing element is not visible as opacity:0

**Comment by jennifer-shehane** [comment]
@NityaQA Please open a new issue filling out the issue template

**Pull request merged**
