### PR TITLE
driver: use fromViewport vs fromWindow coords in actionability check (fixes #1475)

### LINKED ISSUE #1475: position sticky and flex, cypress scrolls to the end of page to access element
- Operating System: macOS High Sierra 10.13.3
- Cypress Version: 2.1.0
- Browser Version: Chrome 59

### Is this a Feature or Bug?

Bug

### Current behavior:
When using `position: sticky` and `display: flex` combination cypress gets mad when trying to access element inside sticky element:

cy-bug

It scrolls to the end of the page before performing any operations on the element while it is not required as the element is visible and accessible.

### Desired behavior:
Should access elements without scrolling

### How to reproduce:

https://github.com/RomanGotsiy/cypress-test-tiny

Just run `npm run cypress:open` and select the only available suite.
There are three tests there:
- `type` into the input
- `click` on the link
- both but with `{force: true}` which works as expected

### PR DESCRIPTION
**Pull request by RomanGotsiy**
When there is fixed/sticky element on the page like in #1475 actionability check caused triggered scrolling page to the end while it was not needed (check details in the #1475).

Why did this happen:
1) `scrollIntoView` on the element inside sticky causes an initial scroll of the page [[line 231]](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee#L231) (caused by [chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=664246))
2) `coordsHistory` gets filled with `.fromWindow` coords which are not correct to use for sticky/fixed elements [[line 250]](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee#L250)
3) `ensuereNotAnimating` [[line 253]](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee#L253)
4) `cy.ensureElementIsNotAnimating` scrolls page to the end because `.fromWindow` coords of element are always updated while page is scrolling [[line 204]](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee#L204)

I have no idea how to add tests for this. Feel free to commit them on top of this PR or give me some advice.

close #1475

### CODE REVIEW

**Comment by Bkucera** [comment]
Thank you! We are busy these days, we will look into it asap.

**Comment by brian-mann** [comment]
I'll add a test for this

**Comment by RomanGotsiy** [comment]
@brian-mann any progress with this?

**Comment by jennifer-shehane** [comment]
@RomanGotsiy We will be reviewing open PRs today.

**Comment by RomanGotsiy** [comment]
Any update on this? The broken test seems to be unrelated to the fix

**Comment by jennifer-shehane** [comment]
While reviewing the code, I realized this is checking that the element is sticky *or* fixed, but this behavior has only been observed when the element is sticky. 

We'll need to add a function to `$dom.getFirstStickyPositionParent` to only target sticky els and then update https://github.com/cypress-io/cypress/blob/issue-1475/packages/driver/src/cy/actionability.coffee#L251 to just check against that.

**Comment by RomanGotsiy** [comment]
@jennifer-shehane while this concrete behavior is observed only when the element is sticky caused by [this chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=664246) the changes are correct for fixed elements too.

`coordsHistory` for both fixed and sticky elements must be relative to the viewport. Otherwise, page scrolling will make all the fixed elements `animating`, i.e. it makes statements 'page is scrolling' and 'fixed element is animating' equal.

This issue can be caused by some other page scroll not related to sticky bug.

Does it makes sense?

**Comment by RomanGotsiy** [comment]
I just checked it again and understood that it can't be caused by other page scrolls as the code is synchronous between `scrollIntoView` and `ensuereNotAnimating` and the only reason why the page scrolls in between is a `sticky` bug.

While I still think that changes I submitted are more valid in theory I am OK with only targeting target sticky els.

@jennifer-shehane what are your thoughs?  Should update PR to target only sticky?

**Comment by jennifer-shehane** [comment]
Well, I think the key is, if we are going to add a feature or target this element, we want a 'failing' situation, a failing test that we are then fixing with that improvement. 

If there can be a failing test written for a situation of 'fixed' elements that this code fixes, I would be ok with leaving it.

**Comment by RomanGotsiy** [comment]
@jennifer-shehane I can't come up with a failing test so I just updated the PR

**Pull request merged**
