### PR TITLE
Break up e2e Error UI tests and fix flakiness

### LINKED ISSUE #7671: Flaky internal test: Timeout of 180000ms exceeded in 8_error_ui_spec
### Current behavior:

**CircleCI Run** https://github.com/cypress-io/cypress-test-node-versions
**Failing test** https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/8_error_ui_spec.ts#L34:L34

Screen Shot 2020-06-11 at 11 23 53 AM

```
  1) e2e error ui displays correct UI for errors [chrome]:
     Error: Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/cypress/packages/server/test/e2e/8_error_ui_spec.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
  

  2) e2e error ui displays correct UI for errors in custom commands [chrome]:
     Error: Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/cypress/packages/server/test/e2e/8_error_ui_spec.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
```

### Versions

4.8.0

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #7671

### User facing changelog

N/A - Internal only

### Additional details

- Breaks up the e2e tests into multiple files so they don't take too long and time out. 
- Fixes an issue where one of the tests plus firefox garbage collection caused a failure.
- Adds better error output, so if a test do fail, it's easier to find which one it is.

### CODE REVIEW

**Comment by chrisbreiding** [comment]
Looks like the timeouts were hiding some legitimate failures/flakiness. If I have time, I'll look into fixing them. Or if the isolated runner PR gets in first, will just move these tests to that.

**Comment by brian-mann** [comment]
The isolated runner PR has been in for about a week now - get with @Bkucera on transferring these over.

**Comment by chrisbreiding** [comment]
I experimented with moving them to the isolated runner. Unfortunately, it doesn't look like it will work for these tests as it currently stands. Since it evals the test function, the errors don't end up with a stack trace. It might be possible to get it to work with some updates to the isolated runner.

In any case, it would be valuable to merge the changes in this PR now as they are, since the flakiness of these tests are slowing down other PRs. I can take another look at moving them to the isolated runner next week.

**Comment by chrisbreiding** [comment]
Closing in favor of #7831

**Pull request closed without merging**
