### PR TITLE
Decaff driver part 4

### PR DESCRIPTION
**Pull request by sainthkh**
Part of #2690

Now no CoffeeScript file in `driver/src`! :confetti_ball: 

# NEVER SQUASH THIS PR

### CODE REVIEW

**Comment by sainthkh** [comment]
Flaky failure.

**Comment by chrisbreiding** [comment]
In regards to `error_messages.js`, I think it's less than ideal that  has to be left-aligned in order to get the proper whitespace. That’s an area where CoffeeScript is superior because it allows you to indent to align with the code, but strips out unnecessary whitespace in an intuitive way.

I wonder if we can pass these strings to a function or use a tagged template for them that can do something similar. Since tagged templates don’t have CoffeeScript’s benefit of being executed at compile-time, they can’t know the correct level of indentation to strip. I think we might need to just use a function and pass in the level of indentation, which isn’t the best, but it’s better than left-aligning everything in my opinion.

So it might look something like:

```{
  command: {
    some_error: s(3, `
      You made a grievous error.

      I can't believe you've done this.
    `)
  }
}```

We pass `3` because it’s 3 levels of indentation (6 spaces) in. It can also strip the opening and closing newline and extra whitespace, so we don’t need the backslashes, and the string ends up like this:

```You made a grievous error.

I can't believe you've done this.```

**Comment by flotwig** [comment]
We use `common-tags` `stripIndent` elsewhere: https://github.com/cypress-io/cypress/blob/ca6ceebeebf246a6b9ef1248b46e018df50da39a/cli/lib/errors.js#L19-L25

**Comment by chrisbreiding** [comment]
Nice! That's probably what we should use here. This seems like a big caveat for our use-case here though:

> Important note: this tag will not indent multiline strings coming from the substitutions. If you want that behavior, use the html tag (aliases: source, codeBlock).

Some error message substitute in other error messages, which could be multiline. I wonder if there's any reason not to just always use the `html` tag (and alias it as `stripIndent` or something).

**Comment by jennifer-shehane** [comment]
@sainthkh Feel free to move out the error_messages.coffee conversion from this PR if it's easier, since we want more changes and review on that specific file. I can approve everything else otherwise. 

There are some conflicts now since we merged in a big feature.

**Comment by sainthkh** [comment]
* Flaky failure.
* Removed error_message.coffee from the decaff list.
* Fixed conflicts.

**Comment by jennifer-shehane** [comment]
oh no, more conflicts 🤦‍♀️

**Comment by sainthkh** [comment]
* Merge conflicts.
* Flaky failures.

**Pull request merged**
