### PR TITLE
Allow passing a list of space-separated specs to --spec

### LINKED ISSUE #2298: Cypress run: --spec argument cannot be single quoted
### Current behavior:

An error occurs when a filepath for `--spec` is surrounded by quotes.

### Desired behavior:

I should be able to use quoted filepaths as per the docs.

### Steps to reproduce:

1) Use `cypress run --spec '(some spec)'` to start a test run, making sure to wrap `(some spec)` in quotes.

### Versions

Cypress 3.0.3
Windows 10

----

The following example is in the docs for using the `--spec` flag:

`cypress run --spec 'cypress/integration/examples/actions.spec.js'`

I have tried something similar, and it doesn't work. Here's the command and the resulting output:

`node_modules\.bin\cypress run --spec 'C:\(...)\SomeTest.js'`

This produces the following error:

> Can't run because no spec files were found.
>
> We searched for any files matching this glob pattern:
>
> `'C:\(...)\SomeTest.js'`

However, when I remove the quotes, it works:

`node_modules\.bin\cypress run --spec C:\(...)\SomeTest.js`

```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.0.3                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      1 found (SomeTest.js)                                                              │
  │ Searched:   ..\(...)\SomeTest.js                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### LINKED ISSUE #3318: Fix unexpected behavior when passing glob pattern for specs
### Current behavior:

It's unclear to new users how they should pass glob patterns to `cypress run`, mostly because

* their shell will expand globs - `--spec *` gets passed as `--spec fileA fileB fileC`
* then, Cypress thinks that `spec === 'fileA'`
    * \- unless they use double quotes, in which case Cypress receives `"*"` and we glob it ourselves (unintuitive)
    * \- or if they use `--spec=*`, which the shell also won't expand, and we glob it ourselves

Passing `--spec=` will interfere with tab-completion of spec names. Double-quoting the spec names also supposedly interferes with tab-completion of spec names in the shell, though I haven't been able to reproduce this yet

### Desired behavior:

* Accept a space-delimited series of filenames as the spec filenames, so that users can use their shell's built-in globbing when passing a set of spec filenames
    * Currently we accept comma-delimited spec filenames, but shells expand using spaces
* Potentially warn the user that they are passing a list of filenames to Cypress and not a glob pattern, because passing a long list of filenames will make various GUI elements in dashboard, desktop-gui look funny

### Related issues

- #3220 
- #1225
- #1845
- #1834
- #1810

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #3318 

Also fixes #2298

image

### CODE REVIEW

**Comment by Bkucera** [comment]
@flotwig could you post screenshot(s) of the terminal error message?

**Comment by flotwig** [comment]
@Bkucera Done. Now that i'm taking another look at this, maybe we don't need to print the entire list to the user, maybe just the first few lines of it, or maybe not at all. If they have a ton of spec files in their glob pattern it will totally overwhelm the terminal:

image

Any thoughts on the warning?

**Comment by jennifer-shehane** [comment]
@flotwig 

1. I think it's necessary to print the entire `--spec` arg, especially if there may be cases where we are reading the arg different from what they typed. For printing the args, however, I would like to add a descriptor above it of what you're printing, similar to how we format our driver errors. So, "The spec argument you passed was:"
	screen shot 2019-02-27 at 1 08 10 pm
2. The long error however is confusing if they happen to not scroll up beyond the arg, maybe we could make the reason for the error a bit clearer again after pasting the args.
3. I'm also just....generally confused by this error. It says "this will work, but it's not recommended"...uh, why is this not recommended exactly, if you're telling me it works...?

**Comment by flotwig** [comment]
@brian-mann do you remember what the reasoning was for why we need to warn the user as opposed to just silently allowing them to use a long list of spec names? I seem to recall it being something to do with the way the Dashboard displays test runs, but I could be wrong.

**Pull request merged**
