### PR TITLE
feat: adding i18n infrastructure for different languages

### PR DESCRIPTION
**Pull request by JessicaSachs**
Added a fun little feature during the team touchpoint to add language support for new languages. I had no idea that ~40% of our users were from the EU and that we saw a significant conversion rate increase when localizing our signup pages :-)

Seems like a nice gesture.

**It only applies if your native machine language is in another lang.**

image

The i18n Ally VSCode extension helps you audit what language keys need translations :-)

スクリーンショット 2022-02-24 午後2 21 55

### CODE REVIEW

**Comment by marktnoonan** [comment]
Before we merge it, can we add a test that checks that nav item - using `en-US`, `ja`, and some other value that should default to `en-US`?

**Review by emilyrohrbough — CHANGES_REQUESTED** [review]
I don't want to be grumpy, but this is out of scope for the 10.0 release. It doesn't seem like a good experience to provide a partially localized application.

**Comment by JessicaSachs** [comment]
I added i18n support **for** 10.0, so I don't see why this is out of scope. It's a JSON file using the existing infra we have.

> It doesn't seem like a good experience to provide a partially localized application.

Most of my OSS community is non-US (Asia + EU). Translations are always a **progressive enhancement**. Non-english speakers are very accustomed to the incomplete translation strings and will (very!) happily submit PRs so long as we've given them a JSON file to put it in.

40% of our userbase is in the EU so the non-US centrism will be really appreciated and all it takes is a JSON file 🤷🏻.

**Comment by JessicaSachs** [comment]
Post 10.x

**Pull request closed without merging**
