### PR TITLE
fix: issue-22732-add-check-CI-browser-value

### LINKED ISSUE #22732: Cypress encountered an error while parsing the argument: --spec
### Current behavior

I made a mistake to pass an empty string to the `--browser` option of `cypress run`, but the error message says that I pass a wrong `--spec` option, this is very confusing.

```console
$ npx cypress run --browser  --spec "cypress/integration/1-getting-started/todo.spec.js" 

[95081:0711/163933.485060:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[95081:0711/163933.485081:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[95081:0711/163933.485088:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
Cypress encountered an error while parsing the argument: --spec

You passed: true

The error was: spec must be a string or comma-separated list
```

### Desired behavior

In this situation, cypress should say that the value of `--browser` options is not valid.say

### Test code to reproduce

```console
$ npx cypress run --browser  --spec "cypress/integration/1-getting-started/todo.spec.js" 
```

### Cypress Version

10.3.0

### Other

```console
$ npx cypress -v                                                                         
Cypress package version: 10.3.0
Cypress binary version: 10.3.0
Electron version: 18.3.0
Bundled Node version: 16.13.2
```

### PR DESCRIPTION
**Pull request by lunaautomation**
- Closes https://github.com/cypress-io/cypress/issues/22732

### Additional details
Resolves the issue where a user doesn't specify a browser and the check ignores the null value passed.

### Steps to test
Run the steps to reproduce on the issue, providing a CI run command with the browser tag and a null value.

### PR Tasks
- [ x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@lunaautomation Thanks for the contribution! Could you please sign our CLA?

**Comment by lunaautomation** [comment]
@jennifer-shehane 
I've tried writing a test for the fix but I get the following error when it runs 
`     Error: 
      The context has already been set. If this is occurring in a testing context,
      make sure you are clearing the context. Otherwise`
      
I am not sure what the issue is here?

**Comment by jennifer-shehane** [comment]
@lunaautomation Have you allowed access for maintainers to edit? 
Screenshot 2024-04-16 at 2 31 59 PM

**Comment by jennifer-shehane** [comment]
@lunaautomation Are you able to look at this? We'll have to close this PR if the previous comments aren't addressed.

**Comment by lunaautomation** [comment]
Hi @jennifer-shehane
I think because this originated from my orgs fork it's not showing that option when I go to edit the PR. I can attempt to open a new one but I don't know if I'll see the option

**Pull request closed without merging**
