### PR TITLE
feat(chore): Include new info command

### LINKED ISSUE #4540: Having a dedicated command to show up local environment information 'cypress info'
## Feature Request

Most CLI tools these days are shipped with a dedicated `info` command which shows up local environment information. Also, the present issue template includes a section which expects to have information regarding the local environment.

With this all the user has to do is just copy and paste the information as shown by `cypress info` within the respective section.

### PR DESCRIPTION
**Pull request by jamesgeorge007**
## Proposed API

`cypress info`

Screenshot from 2019-06-24 13-22-14

Fixes #4540

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @jennifer-shehane

**Comment by jennifer-shehane** [comment]
Hey @jamesgeorge007, this looks like a great start. Could you write a test for this `cypress info` command also? The current tests are here: https://github.com/cypress-io/cypress/blob/develop/cli/__snapshots__/cli_spec.js#L46

This may be a bit tricky because I suspect it will print different env info depending on the machine we run it in. So, feel free to ask us any questions or let us know if you want us to take over from here. cc @bahmutov

**Comment by jamesgeorge007** [comment]
@jennifer-shehane Yeah, it seems to be tricky :sweat_smile:

**Comment by jamesgeorge007** [comment]
@jennifer-shehane I would love to work on further if you could give me a better picture of having the unit test done :clap:

**Comment by jennifer-shehane** [comment]
@jamesgeorge007 I actually recently learned how to exclude the env info from our tests, so I will try to take a look at this again.

**Comment by jamesgeorge007** [comment]
@jennifer-shehane Any updates here?

**Comment by jennifer-shehane** [comment]
Closing due to inactivity.

**Pull request closed without merging**
