### PR TITLE
fix(route2): Fix content-length for route2 intercepts

### PR DESCRIPTION
**Pull request by jeremydorne**
- Closes https://github.com/cypress-io/cypress/issues/9166

### User facing changelog

Fixes `content-length` for requests intercepted by `cy.route2()` by calculating the request body's length in bytes instead of its length in characters.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by flotwig — CHANGES_REQUESTED** [review]
Hey @jeremydorne, thanks for opening a PR! Could you add test(s) in `packages/driver/cypress/integration/commands/net_stubbing_spec.ts` for this bugfix? You can run those tests by doing `yarn cypress:open` inside of `packages/driver`.

**Comment by jennifer-shehane** [comment]
@jeremydorne Could you also please sign our CLA here: https://cla-assistant.io/cypress-io/cypress?pullRequest=9224 ?

**Comment by jeremydorne** [comment]
@flotwig Good call. I added a couple tests and caught a falsy check that didn't account for an empty body.

@jennifer-shehane CLA should be signed now.

**Review by flotwig — COMMENTED** [review]
Thanks!

**Pull request merged**
