### PR TITLE
chore: fix flaky test

### LINKED ISSUE #24575: Flaky test: "App: should re-query for executing runs" (windows mainly)
### Link to dashboard or CircleCI failure

https://app.circleci.com/pipelines/github/cypress-io/cypress/45562/workflows/8510305c-0f92-41d6-b8fb-2abaa50db11a/jobs/1914521/tests#failed-test-2

### Link to failing test in GitHub

https://github.com/cypress-io/cypress/blob/963e184446dffe627c7c412c72c428be0da388b0/packages/app/cypress/e2e/runs.cy.ts#L888-L955

These two are flaky on windows.

Edit: First one is fixed  https://github.com/cypress-io/cypress/pull/24833

### Analysis

Not sure if it's race condition, I've seen it flake on linux too, but much less.

These tests override `window.setTimeout` and stub out multiple GraphQL requests - it's quite confusing since there's so much stubbing going on, it's not entirely clear if the flake is in the app code or the test code.

I think we should consider an alternative way to orchestrate these tests that relies less on stubbing, and is more deterministic.

### Cypress Version

10.11

### Other

It's particularly bad on windows, I can reproduce it locally about 90% of the time.

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes #24575

### User facing changelog

N/A

### Additional details

Reduced flake by:

- increasing timeout.
- only requiring test to re-fetch data twice (not three times). This was only required for windows. I am not sure why, but I don't think we can spend too much more time on it. 

Windows was the most flaky, but linux exhibited some, too. Hopefully this will alleviate it. You will notice that `App: Runs refetching should re-query for executing runs` isn't in the failing list.

A lot of windows tests are now failing. You can see this develop, too. The test I fixed in this PR isn't failing, though, which was the goal. I don't expect windows to be fully green prior to merging this PR.

### Steps to test

N/A, observe CI is working - this was only ever a problem there.

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by marktnoonan** [comment]
@lmiller1990 for some reason in the dashboard this was still showing as skipped, I've updated the branch to re-run CI, will check back when windows is complete.

**Comment by marktnoonan** [comment]
I can see that it's the new code running (based on test definition in the dashboard) but the [video](https://cloud.cypress.io/projects/ypt4pf/runs/41739/test-results/e5dfd1f7-edd4-4476-b6e6-f14327b90d1e/video) still makes it looked skipped. Haven't taken a more detailed look yet 🤔 

Screen Shot 2022-11-29 at 12 26 14 PM
Screen Shot 2022-11-29 at 12 26 06 PM

**Review by BlueWinds — APPROVED** [review]

**Comment by lmiller1990** [comment]
@marktnoonan I was just fixing the first one. I misread the original issue :cry: and was focusing on the first of the two skipped tests.

image

The other one is still conditionally skipped on windows. I will see if it's fixed by this, too.

**Comment by lmiller1990** [comment]
I gave up on this. I wrote my findings https://github.com/cypress-io/cypress/issues/24575#issuecomment-1333108450. I cannot figure out why this is only a bug windows. May get motivated and try again in the future.

**Pull request closed without merging**
