### PR TITLE
fix(Proxy): Fixes `Can't set headers after they are sent.` error thrown

### PR DESCRIPTION
**Pull request by zakhenry**
when the request has already been sent and a redirect is attempted

### CODE REVIEW

**Comment by brian-mann** [comment]
The issue in this case is that we have to understand the underlying reason *why* this is happening - and we naturally need tests to cover it.

I understand that this may fix the issue you're having but why are **you** having it and not everyone else? And what is the behavior? Is Cypress crashing?

I can statically look at the code and I *think* I see how it could be happening but I'd like to better understand the environment causing this. Making a single change to the proxy code can have dire and drastic implications and must be taken with extreme care.

**Comment by zakhenry** [comment]
@brian-mann yep that's fair, to give you more background

* This is a consistent failure, which occurs when an API response with status code 307 is proxied
* The effect is a hard crash
```
OPTIONS /my-api/v0/parts/b64ebf27-2f42-4036-9111-85168c92b700 200 7.154 ms - -
PUT /my-api/v0/parts/b64ebf27-2f42-4036-9111-85168c92b700 200 35.217 ms - -
OPTIONS /my-api/v0/parts/b64ebf27-2f42-4036-9111-85168c92b700/cad-geometry 200 6.858 ms - -
PUT /my-api/v0/parts/b64ebf27-2f42-4036-9111-85168c92b700/cad-geometry 307 114.792 ms - 90
OPTIONS /uploaded-geometry/b64ebf27-2f42-4036-9111-85168c92b700 200 8.270 ms - -
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:700:10)
    at ServerResponse.res.location (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:814:8)
    at ServerResponse.redirect (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:853:8)
    at /Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/proxy.js:200:24
    at Request.endWithResponseErr (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/proxy.js:160:9)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:845:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:700:10)
    at ServerResponse.res.location (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:814:8)
    at ServerResponse.redirect (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/node_modules/express/lib/response.js:853:8)
    at /Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/proxy.js:200:24
    at Request.endWithResponseErr (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/lib/controllers/proxy.js:160:9)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/zak/repos/frontend/node_modules/cypress/dist/Cypress.app/Contents/Resources/app/packages/server/node_modules/request/request.js:845:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by brian-mann** [comment]
Can you provide me with the tiniest reproducible test code (hopefully its only a single cy.visit)?

And then provide me with the tiniest express code needed to reproduce this.

We have tests around 307 redirects in the server code, so there has to be something different about your setup - likely in your server code.

Creating a new repo would be desirable too - so we can remove all the variables involving a full blown application and reduce it down to the simplest case.

**Comment by zakhenry** [comment]
@brian-mann sure, I'll give it a shot, my app is a fairly large Angular 2 application, but the error appears to be in my little express mock server so I have hope ;)

**Comment by brian-mann** [comment]
Yah per looking at the console logs it appears that you're making a simple fetch or XHR which is causing the OPTIONS preflight check. **This is likely important**. 

It's likely a combination of several factors.

To reproduce what you're app is doing is likely something like this.....

1. Spin up mock server at http://localhost:9999

```js
it('waits for xhr to be redirected', () => {
  return new Promise((resolve) => {
    const xhr = new XMLHttpRequest
    xhr.open('PUT', 'http://localhost:9999/foo')
    xhr.send()
    xhr.onload = resolve
  })
})
```

That may be all you need. Additionally if that doesn't work you may need to also spin up a static file server something and then just involve a `cy.visit` to that first. That may have something to do with it too.

**Comment by zakhenry** [comment]
@brian-mann I've managed to reproduce the error fairly minimally at https://github.com/zakhenry/cypress-bug

**Comment by zakhenry** [comment]
It appears that the issue occurs when doing a PUT with a fairly large file

**Comment by brian-mann** [comment]
Okay thanks - I'll look at this later today, this is exactly what we are looking for. Perhaps the underlying issue is not with headers but something else involving the request / response bodies. 

Now we'll be able to really fix the issue.

**Comment by brian-mann** [comment]
I spent a few hours on this. I got it to break just like in your repo - but when trying to write isolated tests for the server + proxy layer I'm having difficulty reproducing. Really would prefer understanding the root cause of it before merging this in. I'm worried there is a more underlying problem that needs to be addressed.

**Comment by zakhenry** [comment]
@brian-mann Yep understood, I agree that the fix applied here might just be masking the underlying culprit.

**Comment by zakhenry** [comment]
@brian-mann has there been any further progress on this issue / anything I can help with?

**Comment by brian-mann** [comment]
There has not. I spent hours on it and have trouble reproducing with an actual test due to trying to reproduce the way browsers send large file bodies. It's unfortunately gotten sidetracked now.

**Comment by bertoltmeier** [comment]
We noticed the same error, but in a slightly different setting: In our case we received a 302 from the server and body that could not be parsed:

`cypress:server:proxy Parsing ERROR. :( { Error: Parse Error at Socket.socketOnData (_http_client.js:454:20) at emitOne (events.js:115:13) at Socket.emit (events.js:210:7) at addChunk (_stream_readable.js:252:12) at readableAddChunk (_stream_readable.js:239:11) at Socket.Readable.push (_stream_readable.js:197:10) at TCP.onread (net.js:589:20) bytesParsed: 215, code: 'HPE_INVALID_CONSTANT' } +3ms`

Parsing errors like this seem to be quite common, e.g. when working with legacy servers which are out of reach for influencing (like in our particular case). See e.g. https://github.com/nodejs/node-v0.x-archive/issues/4863

Above code snippet fixed our issue, but I would suggest a different solution, because I noticed that on parsing errors endWithResponseErr is called and this function resets the response with same redirect status code (30x), but without location. This is then causing the uncatched exception, because the redirect cannot be executed without location.

e.g. like this:

`endWithResponseErr = function(err) {
        debug("What is this ERROR? %o", err);
        var checkResStatus, ref, ref1, status, str;
        checkResStatus = function() {
          if (res.headersSent) {
            return res.statusCode;
          }
        };
        status = (ref = (ref1 = err.status) != null ? ref1 : checkResStatus()) != null ? ref : 500;
        if (!res.headersSent) {
          res.removeHeader("Content-Encoding");
        }
        str = through(function(d) {
          return this.queue(d);
        });
        debug("This is what I am doing");
        // In case of faulty responses on redirects, we want to change the status code, because we cannot trust the redirect.
        if (redirectRe.test(status)) {
            onResponse(str, {
            statusCode: no_redirect_status_code,
            headers: {
              "content-type": "text/html"
            }
          });
        } else {
          onResponse(str, {
            statusCode: status,
            headers: {
              "content-type": "text/html"
            }
          });
        };
        debug("END: This is what I am doing");
        return str.end(getErrorHtml(err));
      };`

Can you reproduce the error at your end and respond, if my suggestion makes sense?

**Comment by Saibamen** [comment]
Please merge latest develop branch into this PR branch to run new tests

**Pull request closed without merging**
