### PR TITLE
build: allow unified to run cypress on Apple Silicon (arm64)

### PR DESCRIPTION
**Pull request by elevatebart**
connected to #14923

This PR updates electron-packager for arm64 compatibility.
Defaults have cnaged a little so a rename was necessary.

### CODE REVIEW

**Comment by mapsandapps** [comment]
Working for me! It'd be nice if we could merge this.

**Comment by elevatebart** [comment]
@flotwig @chrisbreiding you guys are the experts in all things electron. 
Do you think this change can break the binary?

**Comment by emilyrohrbough** [comment]
@elevatebart What is your plan to test this to ensure binary behaves as expected? Were you able to verify the linux, mac & windows binaries with this change?

**Comment by elevatebart** [comment]
@emilyrohrbough I ran this on Mac M1 & Intel and it works.
I cannot sign a binary myself. I don't know that I can test anything prod like without signing the final binary.
I would hope that we merge this, test it and revert the commit if things are broken.
The change is simple enough that it will not impact much.

Additionally, the windows build for 10.0-release has not compiled for at least a few weeks.
I don't have a linux machine, but I expect tests in CI to be run. with a linux machine

**Comment by flotwig** [comment]
I'm not totally sure what advantage this brings. I see in  15.1.0 `electron-packager` added `darwin-arm64` as an arch/platform combo. But this change doesn't modify any of the build artifacts, right? So is there any advantage to making this change? 

@elevatebart are you planning on making the rest of the changes needed for `darwin-arm64` support (updating the download server, CLI, build process, CI setup?) afaik we are still blocked on https://circleci.canny.io/cloud-feature-requests/p/support-new-m1-arm-based-macs

**Comment by elevatebart** [comment]
@flotwig this change only impact development. 
For the rest of the work, I plan to wait for [your PR](https://github.com/cypress-io/cypress/pull/14923) to be delivered. Then I can iterate to make this branch work with the changes.

For information, until recently we could run `yarn dev` on a arm64 machine without trouble using Rosetta. 
Now it has become impossible, even using Rosetta because yarn dev packages for the current environment. 
This small change fixes the dev process.

**Review by flotwig — DISMISSED** [review]
Seems fine to upgrade. @elevatebart do you happen to have a link to the issue that changed `app.js` -> `index.js`? I'm not seeing anything in `electron-packager`'s changelog.

> For the rest of the work, I plan to wait for your PR to be delivered. Then I can iterate to make this branch work with the changes.

Gotcha, currently waiting on CircleCI for that one.

**Comment by elevatebart** [comment]
@flotwig I did not find this issue, I read the error message and fixed the error as I saw it.
I can try and dig it up if you really care but it will take me a while.

**Comment by flotwig** [comment]
> I can try and dig it up if you really care but it will take me a while.

All good. I did push a commit just to verify that the packaged app still works on all platforms, but as long as that passes, LGTM. 9308af8

**Review by flotwig — APPROVED** [review]

**Pull request merged**
