### PR TITLE
Fallback to env variables for git info and include PR id and default branch

### LINKED ISSUE #1844: Collect pull request information for each run
Collect and send PR to api when specs are run, so that a link to the PR can be shown in the Dashboard.

### LINKED ISSUE #2073: Collect CI environment variables if git returns no results
When recording to the dashboard we've noticed many situations in which things like the current `branch`, `commit sha`, etc is not collected due to git configuration issues - even on popular CI services.

Instead we should opt to fallback to environment variables that CI providers expose to accurate collect the information for use in the Dashboard.

### LINKED ISSUE #2129: No information regarding git branch in cypress dashboard - Jenkins CI
### Current behavior:

`Branch` on test run not showing current branch name

image

### Desired behavior:

Show info regarding branch test when running from Jenkins
### Steps to reproduce:

Run Cypress e2e test from Jenkins
(Running same test from Mac OS for example is showing current branch)

### Versions
Cypress: 3.0.1
Browser: Electron 59.0.3071.115
Operating System: CentOS 7.3.1611
CI Service: Jenkins

### PR DESCRIPTION
**Pull request by chrisbreiding**
- fixes #2073
- fixes #1844 
- fixes #2129

### CODE REVIEW

**Comment by chrisbreiding** [comment]
I think we need json schema updates to get the e2e specs passing.

**Comment by brian-mann** [comment]
Yes schema changes are necessary. That is good we want to see those failures happen.

**Comment by bahmutov** [comment]
- schema changes with pull request id and default branch in https://github.com/cypress-io/json-schemas/releases/tag/v5.9.0 and schema changes in https://github.com/cypress-io/json-schemas/commit/8e3bba81bb7de2aef092db85c2a71c1de5ecaaa1

Getting pull request number on Circle is a little trickier because it is part of the pull request url, see https://github.com/cypress-io/cypress/issues/1844

**Comment by bahmutov** [comment]
Let's land this bad boy

**Pull request merged**
