### PR TITLE
Fix selector playground tooltip

### LINKED ISSUE #1351: Open Selector Playground - Select element (Tooltips)
# Open Selector Playground - Select element (Tooltips)

Operating System: Windows 10
Cypress Version: 2.0.2
Browser Version: Chrome 64 (64 bits)

### Is this a Feature or Bug?

Bug (ish)

### Current behavior:

The tooltips are showing correctly above the fold of the viewport. Result that the tooltips are floating somewhere above the fold when you are selecting/inspecting something under the fold.

### Expected behavior:

The tooltips showing correctly also under the fold.

### See attachments:

qa - cypress

### PR DESCRIPTION
**Pull request by desfero**
Fixes #1351.
Now there is `cursor: pointer` on the highlighted element.
Some refactoring to selector playground was made.

To reproduce on `Kitchen Sink` example run tests and then add to `html` and `body` `height: 100%`. After that popover will not calculate boundaries properly.

### CODE REVIEW

**Comment by desfero** [comment]
@jennifer-shehane can you please add more details about how can I do it? To test this case I need to enable selector playground which is not possible through the test and from the code I see it's not possible too.

**Comment by jennifer-shehane** [comment]
@desfero ooo, yeah, you may be right. I haven't tested the selector playground specifically. cc @chrisbreiding ?

**Comment by desfero** [comment]
@jennifer-shehane @chrisbreiding I see basically two ways: 
1. Route test to `/__cypress/runner/*` and render runner inside runner.
2. Add an ability to turn on selector playground from cypress API

**Comment by chrisbreiding** [comment]
I wasn't able to reproduce the issue using 100% height on html and body in the kitchen sink, so I can't verify whether or not this fixes it. In any case, these changes seem good from a refactoring standpoint. (I could swear the `$cover` element and the boundary were necessary when this was originally implemented, but perhaps a React upgrade along the way has changed things so they aren't anymore.)

As for writing tests for this, it would be very difficult and perhaps impossible with Cypress due to our [lack of shadow dom support](https://github.com/cypress-io/cypress/issues/144). It would also require some upfront time investment to set up testing the `runner` with itself. When this was first implemented, we made a conscious decision not to spend the time and effort since this is a "nice-to-have" feature that only operates in open mode.

**Comment by desfero** [comment]
@chrisbreiding this seems strange that you are not able to reproduce this on the kitchen sink app. Please have a look at the screenshot below that was taken a minute ago on latest `develop`.
image

**Comment by chrisbreiding** [comment]
The original issue was reported on Windows. Which operating system are you using? Just curious if it's OS-specific and that's why I can't reproduce (on macOS at least).

**Comment by desfero** [comment]
I'm on macOS too `10.14.3`

**Comment by desfero** [comment]
@jennifer-shehane can you restart build? Seems there are some flaky tests

**Pull request merged**
