### PR TITLE
misc: Update styling of Runs Page

### LINKED ISSUE #26180: ACI - Runs page UI Updates
Update Runs page UI with updated icon, responsive fix, and UTM parameters

### Icons for `RunCard`
* Update the icons for the following statuses to match designs
  * RUNNING  Screenshot 2023-03-28 at 12 14 37 PM
  * CANCELLED  Screenshot 2023-03-28 at 12 15 30 PM
  * NOTESTS  Screenshot 2023-03-28 at 12 14 47 PM

Figma - https://www.figma.com/file/RJFI3Gv2hsdhQt1x4K5rvr/Runs-Page?node-id=419%3A76421&t=orOYl5ooKYcCixaT-1
Figma Design System Icons - https://www.figma.com/file/1WJ3GVQyMV5e7xVxPg3yID/Design-System%2C-v1.x?node-id=6814%3A10841&t=0Jt8aHid7WrnLR4k-1

### Responsive Updates
* Update component to allow the `RunResults` component to wrap down under the other content when needed.  It may need to get pulled out of the `#right` slot for this to work, or redo the component without using the `ListRowHeader` at all.  The `RunCard` is designed similar to that component, but it is not really used the same way as the other uses of the `ListRowHeader`.  

**NOTE** The Figma design is currently showing a third small breakpoint which cannot occur.  Ignore this one at the bottom.

Figma - https://www.figma.com/file/RJFI3Gv2hsdhQt1x4K5rvr/Runs-Page?node-id=419%3A85793&t=MxXXCo0NDJpsmMdH-1

### UTM parameters
* The links when clicking on the card should supply UTM parameters
  * Source: `Binary: App`
  * Medium: `Runs Tab`
  * Campaign: `Cloud Run`

[UTM Spreadsheet](https://docs.google.com/spreadsheets/d/1Cs933TLXcS63PmMlXA4wKLJtQSFH90dProvzI9oyEB4/edit#gid=0)

Clickup - https://app.clickup.com/t/18033298/PM-2889

### PR DESCRIPTION
**Pull request by mike-plummer**
- Closes #26180 

### Additional details
* Updating status icons to match other areas of the app (specs list, debug page)
  * Use shared component to reduce complexity and use icon assets from design system
* Wrap run status as viewport shrinks to improve responsive layout
* Add link params

### Steps to test
Review `RunCard.cy.tsx` component test. Changes can be viewed in the following tests:

- "renders expected icon for each run status"
- "renders with all run information on small viewport"

### How has the user experience changed?

Screenshot 2023-04-03 at 10 09 41 AM

Screenshot 2023-04-03 at 10 29 56 AM

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by mike-plummer** [comment]
Hmm, Percy seems to be doing some odd things with wrapping the Run Results section over and not spacing properly that I can't reproduce locally. Works fine for me locally in Chrome, Edge, FF, and Safari. Any ideas why this could be happening @marktnoonan ?

**Review by warrensplayer — CHANGES_REQUESTED** [review]
All looks good except if there is a long commit message:
Screenshot 2023-04-04 at 11 09 02 AM

I played around with the code, but the only solution I can see is to not use the `ListRowHeader` component so that you can better control how the commit message is rendered.

**Comment by warrensplayer** [comment]
> Hmm, Percy seems to be doing some odd things with wrapping the Run Results section over and not spacing properly that I can't reproduce locally. Works fine for me locally in Chrome, Edge, FF, and Safari.

@mike-plummer I am not able to reproduce locally either.  One thing to try might be to replace the `span` you added (`<span class="flex flex-wrap gap-30px justify-between">`) with `div`.  Percy seems to be wrapping early and then not honoring your `gap` of 30px that is there to offset the negative top margin.  

My hope also is that rewriting the component to not use `ListRowHeader` will fix it as well.

**Review by warrensplayer — APPROVED** [review]
Everything looking good now.  

Extra credit would be some documentation or a test for the addition to the `ListRowHeader` component.

**Comment by warrensplayer** [comment]
@mike-plummer I like the test update.  Can I approve the PR twice?  ✅ ✅

**Review by lmiller1990 — APPROVED** [review]
Beautiful, looks great!

**Comment by lmiller1990** [comment]
Percy looks fine to me - the update (right hand) seems like it's correct now.

image

**Comment by lmiller1990** [comment]
Can definitely look into Percy if we think there's still issues - might go ahead and merge this up since the code and UI looks correct to me. Maybe the `<span>` as suggested by @warrensplayer solved the issue?

Either way no blocker, let's ship it 👍

**Pull request merged**
