### PR TITLE
fix: remove postinstall-postinstall

### LINKED ISSUE #6477: Unable to install dependencies via "npm install"
### Current behavior:

After updating my fork of the repo, I cannot (re)install the dependencies without any errors.  Here is the relevant snippet of the error message:
```
> fmerge@1.2.0 install /home/ubuntu/environment/cypress/node_modules/fmerge
> node install.js

`fmerge.min.js` created

> husky@2.4.1 install /home/ubuntu/environment/cypress/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done
husky > Like husky? You can support the project on Patreon:
husky > https://www.patreon.com/typicode 🐕

> core-js@2.6.11 postinstall /home/ubuntu/environment/cypress/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /home/ubuntu/environment/cypress/node_modules/ejs
> node ./postinstall.js


> postinstall-postinstall@2.0.0 postinstall /home/ubuntu/environment/cypress/node_modules/postinstall-postinstall
> node ./run.js

00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn run postinstall
ERROR: [Errno 2] No such file or directory: 'run'

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (/home/ubuntu/environment/cypress/node_modules/postinstall-postinstall/run.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

### Desired behavior:

`npm install` should output no errors.

### Test code to reproduce

* `cd` to the root directory of the Cypress repo.
* `npm install`

### Versions

OS: 
Mac OS Catalina 10.15.3
Ubuntu LTS 18.04

npm:
6.9.0
6.13.4

### PR DESCRIPTION
**Pull request by maddhruv**
Resolves #6477 

### User facing changelog
Not able to do a fresh `yarn install` as the `postinstall` script is breaking, throwing
> postinstall-postinstall@2.0.0 postinstall /home/ubuntu/environment/cypress/node_modules/postinstall-postinstall
> node ./run.js
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
child_process.js:669
    throw err;
    ^
Error: Command failed: yarn run postinstall
ERROR: [Errno 2] No such file or directory: 'run'

Ref - https://github.com/cypress-io/cypress/issues/6477#issuecomment-587462492

Just can't understand the use-case for `postinstall-postinstall` package here. As after removing the package everything (build and install) seems to be working fine

Screenshot from 2020-02-18 19-05-10

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

Feel free to close the PR, if there is a valid use-case, but we have to figure out a solution on why is it failing

### CODE REVIEW

**Comment by flotwig** [comment]
@andrew-codes did this come in with the Yarn PR? if so, can you shed some light on this?

**Comment by andrew-codes** [comment]
Here is from what I can recall with the yarn branch:

At some point, I ran across cypress already or additionally needing to run postinstall on a dependency package. This was not ideal of course. However, at the time, there was an effort to minimize the change set required to migrate to yarn.

From looking at the current codebase, I do not see that need as present anymore. I'm not sure if the package was patched instead or some other change effectively removed the need. Assuming everything works without the package, then this lends some credence to that assumption; in which case, it should be removed.

**Comment by bahmutov** [comment]
if we remove this, does it still execute `postinstall` hook in https://github.com/bahmutov/parse-domain/blob/master/package.json ? Because we use that hook to update the domains list

**Comment by maddhruv** [comment]
@bahmutov can we not directly add https://github.com/bahmutov/parse-domain/blob/master/scripts/build-tries.js as a `postinstall` script?

**Comment by andrew-codes** [comment]
I think this is also relevant to shed some additional light on its usage with patch-package and yarn: https://www.npmjs.com/package/patch-package#yarn
More specifically, a link from the above on why yarn needs `postinstall-postinstall`: https://www.npmjs.com/package/patch-package#why-use-postinstall-postinstall-with-yarn

I am starting to feel a bit hesitant in simply removing the package. I'll try to dig deeper into the root cause of why `postinstall-postinstall` is not working in the first place. Maybe we can address that issue instead, and avoid pitfalls of removing a package that it appears we may need.

Open to thoughts on this.

**Comment by maddhruv** [comment]
More Debugging ->
- `cypress$ yarn`
  install fails with these errors
  
> 



- `packages/ui-components$ yarn run build`
  rebuilds `node-sass` and exits with success

- `cypress$ yarn`
  now it works fine, don't know-how, maybe 'cause the `node-sass` build was successfull above

**Comment by andrew-codes** [comment]
@maddhruv are you saying it is resolved for you now?

If so, I'd still like to know a little more about your local repo and try to better understand why it was happening at all. If it has happened to you, then I imagine it will likely happen to others as well. I'll ask my questions on the issue itself, instead of this PR.

Thank you for raising the issue and helping us track down a resolution.

**Comment by maddhruv** [comment]
It is solved (the dependencies are installed), but when I do a fresh install, it fails again.

I also tried installing a common node-sass version, but even that didnt work out fine.

**Comment by andrew-codes** [comment]
I believe we do need `postinstall-postinstall` and, from what I can gather, the issue has resolved itself for the moment. The originating issue has been closed, but we can re-open if we find this crops up again. For the time being, I am going to close this PR.

Thanks again @maddhruv for your help in troubleshooting and submitting a fix to the issue. It has been invaluable. :+1:

**Pull request closed without merging**
