### PR TITLE
chore: switch fonts to use @fontsource rather than locally maintained version

### PR DESCRIPTION
**Pull request by panzarino**
Updates fonts to use [`@fontsource`](https://fontsource.org/docs/introduction) rather than our own locally managed versions - note: Mulish is the exact same font as Muli

In the past I'd been frustrated when working in the reporter that we had limited Muli font weights which really limited design options - this adds all the basic (non-italic) font weights. In addition, it makes it super easy to add additional italic fonts for any font weights needed.

This change also has the intention of making it easier to use the same fonts throughout both the desktop-gui and browser experience, plus makes it easier to add/change fonts in the future.

I've also manually tested some special characters (eg. Chinese) and it all seems to be working properly

In addition, I've noticed for a while now that Firefox was actually able to find the correct font weights (or create them somehow) for Muli even though they weren't in the style sheet (and I always noticed that it looked pretty poor). Now the  the UI should be actually be properly unified between Chromium and FF.

I've updated the font weights in quite a few places across the reporter - previously we didn't actually have many of the font weights that we tried to use (for Muli) so the old css was effectively doing nothing - now we do have the weights so that we can actually use them in the future (and maybe even update some parts of the current app to look a bit better)

The Percy snapshots are showing some tiny differences for the Fira font but the weights are the exact same - since the Fira we're using is from years ago I would guess that minor alterations have been made to improve the font over time (there's over a hundred new commits to the actual repo since then) and we don't actually have to do anything here (we're switching away from Fira soon anyways)

The Percy snapshots also seem to show some differences for the reporter fonts even after my updates. I actually manually went through and compared every usage of a font weight and can confirm that in Chromium there is no difference between the latest prod version and this branch. The Percy screenshots are both from Chrome so I really don't understand where the discrepancy is coming from. I would guess that it's because Chrome is somehow finding the correct font weights that were not actually listed in the old stylesheets (like FF above) and there isn't really any legitimate difference. If you look at the current `develop` version locally vs what shows up in Percy you'll see that the weights are different in the Percy screenshot that's allegedly testing the exact same thing. I think this is a non issue for this PR due to the manual verification - I definitely could have missed something but I've explicitly tested things that show a diff like the suite title and notice no difference. Now hopefully we'll get more consistent Percy screenshots as it's actually going to be using the correct fonts from the stylesheet.

### CODE REVIEW

**Comment by panzarino** [comment]
Converting back to draft since there's a couple of legitimate issues regarding mismatching font weights

**Review by jennifer-shehane — DISMISSED** [review]
Honestly the snapshots look fine, there are differences but it does not detract from the design. So even if percy's rendering of the fonts `were` correct, I would be fine with this change. 

For me I do see a slight change in the weight during `develop`. But as I said above, it's fine. I think it looks a bit cleaner actually.

**Comment by jennifer-shehane** [comment]
@panzarino This test seems to be reliably failing, but not failing in develop. I reran it a bunch - put I find this impossible to have been affected by your changes.

**Comment by jennifer-shehane** [comment]
@panzarino This test is actually failing from the changes. It looks like we take screenshots and then compare them byte for byte in the server tests. We probably want to rethink this since we're using Percy more extensively across the Test Runner. I haven't had time to look into it.

Screen Shot 2021-06-04 at 9 34 35 AM

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@panzarino This test is actually failing from the changes. It looks like we take screenshots and then compare them byte for byte in the server tests. We probably want to rethink this since we're using Percy more extensively across the Test Runner. I haven't had time to look into it.

Screen Shot 2021-06-04 at 9 34 35 AM

**Comment by panzarino** [comment]
@jennifer-shehane Yeah I realized that - I'll take a look at it this weekend and fix

**Comment by panzarino** [comment]
@jennifer-shehane so it turns out the fonts weren't being loaded properly on that screen. I think this was happening since we intercept all requests to the Cypress port from a regular browser. We were intercepting the routes to request the fonts and returning the html page so they weren't loading properly. This wasn't an issue in the past since the raw content of the Muli fonts was included in the CSS file and no extra request had to be made. Rather than create an exception to allow font requests through or update the webpack config to automatically inline font files, I figured it was best to just update the screenshot for the test since its an edge case to even see that screen and the fonts aren't important there anyways.

**Review by jennifer-shehane — APPROVED** [review]
Thanks!

**Pull request merged**
