### PR TITLE
chore: add batch execution to CloudDataSource

### PR DESCRIPTION
**Pull request by tgriesser**
### Additional details
Addresses @flotwig comment on #21250 re: network queries, batching multiple GraphQL requests into a single remote request with rewritten variables, using `@graphql-tools/batch-execute`. This makes it simpler to batch on the remote server.

The documentation here explains how the merging works: https://www.graphql-tools.com/docs/batch-execution

Additionally only does this in situations where we have multiple requests to batch, so we don't end up with rewritten queries on every request, but just the ones where we have multiple requests. Limits the batching to max 20 items per-query

### Steps to test
- Checkout the branch
- Observe fewer network requests

### How has the user experience changed?

Before:

https://user-images.githubusercontent.com/154748/175098776-fc16a10a-eb3b-4ebd-b126-7f9652f3c9fd.mp4

After:

https://user-images.githubusercontent.com/154748/175099329-66035f11-0b70-4d9a-adab-8bfe04991c55.mp4

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by tbiethman — APPROVED** [review]
Everything seems to work well. There are tests failing here that don't seem flaky and don't seem to be failing in the feature branch, are you going to address those before merging down?

**Review by mike-plummer — COMMENTED** [review]
🤯 Very cool! Works well on my local

**Review by mike-plummer — APPROVED** [review]
Thanks for the updates!

**Review by lmiller1990 — COMMENTED** [review]
I did not pull it down but I grok the general idea. I haven't written an ACI code yet, hoping to do so soon to get my hands dirty in this area of the code base and really internalize it + the dev workflow.

**Review by flotwig — APPROVED** [review]

**Comment by emilyrohrbough** [comment]
@tgriesser Looks like there may be some legit test failures that need to be fixed so this can merge.

**Comment by estrada9166** [comment]
I moved it to draft - waiting some changes on the cloud side so this can be properly handle

**Comment by emilyrohrbough** [comment]
@estrada9166 Can you link to the cloud side PR or issue we need to track to determine when this is ready?

**Comment by estrada9166** [comment]
Cloud PR: https://github.com/cypress-io/cypress-services/pull/5045

**Pull request merged**
