### PR TITLE
fix: add code signing certificate details for Windows build

### LINKED ISSUE #2543: Not signed binary files in package for Windows
### Is this a Feature or Bug?
Security improvement.

### Current behavior:
Windows binary files aren't signed by your certificate - easier for malware to "be Cypress".
In some organisations only signed exe files can be allowed to use.

### Desired behavior:
Signed binary files in package for Windows.

### Steps to reproduce:
None :)

### Versions
Cypress 3.1.0
Windows 10

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #2543

### User facing changelog

- On Windows, the Cypress executable is now code signed by "Cypress.io, Inc.".
	- This fixes `spawn UNKNOWN` errors when launching Cypress with code signing required by policy on Windows.

### How has the user experience changed?

This won't happen: https://github.com/cypress-io/cypress/issues/2543#issuecomment-848176458

exe will appear as signed: https://github.com/cypress-io/cypress/pull/16946#issuecomment-861741727

### PR Tasks

- [na] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by flotwig** [comment]
Seems to be working properly:

Capture

**Comment by minijus** [comment]
I have noticed that there are more executables in Cypress directory.

When launching Cypress with `--spec` option it tries to spawn `ffmpeg.exe`. Is it possible to sign all required executables?

**Comment by bahmutov** [comment]
Is the ffmpeg explicitly listed under binaries to sign on mac? I remember adding all such binaries to be signed

**Comment by flotwig** [comment]
`mac.binaries` looks like it's only for Mac: https://www.electron.build/configuration/mac

https://github.com/cypress-io/cypress/blob/41be55820acb7d4c2eeb610a95507f245a497ac3/electron-builder.json#L13-L22


I'm only assuming that electron-builder is supposed to sign all exes based off of conversations like this that imply that it does: https://github.com/electron-userland/electron-builder/issues/5256 Having trouble finding documentation on this point.

**Comment by bahmutov** [comment]
Welcome to the core signing jungle

**Comment by flotwig** [comment]
> When launching Cypress with `cypress run --spec` option it tries to spawn `ffmpeg.exe`. Is it possible to sign all required executables?

@minijus in the interest of getting some benefit out to users, we can go ahead and merge this as-is to get signed `Cypress.exe`s out. The way I see it, there's 2 groups here:

1. Folks who run `cypress open` locally with code signing required and test in CI (majority of users) - a signed `ffmpeg.exe` is not needed for this, only `Cypress.exe`
2. Folks who run `cypress run --video true` either locally or in CI with code signing required (fewer users) - a signed `ffmpeg.exe` is required for these users to record video.

Issue tracking the unsigned `ffmpeg.exe`: #17033

I'm curious, does your CI pipeline run in Windows with code signing required?

**Review by jennifer-shehane — APPROVED** [review]

**Comment by minijus** [comment]
Thank you @flotwig !

Having `Cypress.exe` signed is already nice step forward. As you've summed up it will allow to run `cypress open` which unlocks possibility to conveniently run and develop tests in restricted Windows environment.

We do not run CI on Windows, but it would be great to have possibility to launch headless run locally as well.

**Comment by flotwig** [comment]
Great to hear. In that case, we will likely not prioritize part (2) for now, until we know someone is affected by it.

**Pull request merged**
