### PR TITLE
fix(deps): update dependencies in @cypress/react

### PR DESCRIPTION
**Pull request by anark**
- Closes 

### User facing changelog

Updates dependencies used by @cypress/react to match latest version from cypress-react-unit-test instead of a regression

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@anark Thanks for the contribution! Could you please sign our CLA?

**Review by lmiller1990 — APPROVED** [review]
CI is green so a big ✅  for me

**Review by dmtrKovalenko — APPROVED** [review]

**Comment by dmtrKovalenko** [comment]
Did you run `yarn install`? wondering why lockfile did not updated – and as a result tests were not run on CI with new deps

**Review by dmtrKovalenko — CHANGES_REQUESTED** [review]
We need to update a lock file and pass CI with the new deps

**Review by lmiller1990 — APPROVED** [review]

**Review by dmtrKovalenko — APPROVED** [review]

**Comment by anark** [comment]
Thank you!

Would it be possible to get a version bump on @cypress/react

**Comment by dmtrKovalenko** [comment]
Will be auto released on monday

**Pull request merged**
