### PR TITLE
Open spec file from desktop gui and refactor ui-components to typescript

### LINKED ISSUE #7713: Open spec file from desktop gui [TR-3]
User Story: When viewing my specs in the desktop GUI, I want to be able to open a spec in my IDE, so that I can easily transition from Cypress to my codebase. 

**Acceptance Criteria**
- Hovering a spec file line item shows hover state
- Hover state reveals hidden `Open in IDE` button
- Button appears all the way to the right on the line item
- Hovering `Open in IDE` button has it’s own hover state
  - Background of button is: `rgba(186, 186, 186, 0.2)`
  - When button is hovered, the entire spec line item also retains hover state

Normal state:

Screen Shot 2020-06-16 at 1 13 07 PM

Hover over spec file name:

Screen Shot 2020-06-16 at 1 13 17 PM

Hover over "Open in IDE":

Screen Shot 2020-06-16 at 1 13 29 PM

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #7713

### User facing changelog

Adds the ability to open a spec file in your editor of choice directly from the desktop gui

### Additional details

Converted existing components in the `ui-components` package to typescript, since some other existing typescript modules were moved there so it was easy just to convert it all  

### How has the user experience changed?

Before:

ezgif-6-ca23d0c329e9

After:

ezgif-6-c63f252fde56

ezgif-6-99ab2f5107d8

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?

### CODE REVIEW

**Review by chrisbreiding — CHANGES_REQUESTED** [review]
This looks really good over all. 

My only issue is that the font size in the modal is kind of small. Looking at the computed font-size for the majority of the text (description and editors list), the value is 12.6px. In the file opener preference in the settings tab, it's 14px. In the modal in the browser, it's 14.4px. Let's bump up the size for the desktop-gui modal so it's at least 14px computed. (This should be done so all the text modal is bumped up proportionally, including the header. I'm just using the description/editors values for reference.)

Screen Shot 2020-06-22 at 9 52 25 AM

**Comment by panzarino** [comment]
@chrisbreiding I've updated the modal so that the font is a bit bigger (computed 14px) and the entire modal is a bit bigger because of that which also looks better.

I also got design approval from Sara (her only change was reverting the hover state background to the old, lighter version as the change in the design mockups was unintentional).

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Seems to be working for me! Testing manually and tested when no file opener preference is chosen.

Going to be picky about the css here. The image behind is the comp - the image in front is the app. The current CSS feels really heavy compared to the design. I think the font size and weight need to be reduced.

Screen Shot 2020-06-23 at 3 26 21 PM

**Comment by panzarino** [comment]
@jennifer-shehane I updated the font color and size to make it appear more like that in the mockup:

Screen Shot 2020-06-24 at 12 26 02 AM

The mock actually uses a font that isn't used anywhere in the desktop-gui, so the actual version is going to look a little different. In addition, decreasing the font weight looks way too skinny:

Screen Shot 2020-06-24 at 12 28 08 AM

**Review by jennifer-shehane — DISMISSED** [review]
Looks good. 👍

**Review by chrisbreiding — DISMISSED** [review]
Looks good to me 👍 Just need to iron out the merge conflict.

**Review by jennifer-shehane — APPROVED** [review]

**Review by chrisbreiding — APPROVED** [review]

**Pull request merged**
