### PR TITLE
misc: Add generic types to net-stubbing for use in intercept and wait

### LINKED ISSUE #29507: Enhance typings for cy.intercept and cy.wait
### What would you like?

In order to have request and response types for the `body` property in calls to `cy.intercept` and `cy.wait`, I'd like to be able to specify generics for these, so that I don't have to use `any` in the callbacks.

Specifically:
```typescript
cy.intercept<CustomRequest, CustomResponse>(url, (req) => {
  req.body // ← this should be a CustomRequest

  req.continue((res) => {
    res.body // ← this should be a CustomResponse
  })
})
```
and
```typescript
cy.wait<CustomRequest, CustomResponse>('@alias').then(({ request, response }) => {
  request.body // ← this should be a CustomRequest
  response.body // ← this should be a CustomResponse
})
```

### Why is this needed?

While looking at converting our project to TypeScript, I was surprised that we'd have to either:
* use `any` for the `body` parameter in all callbacks of `intercept` and `wait`
* manually specify the interception type to get types in those calls, such as:
```typescript
cy.intercept('/url', (req: CyHttpMessages.IncomingHttpRequest) => {
  (req.body as CustomRequest).payload = {};

  req.continue(res => {
    expect((res.body as CustomResponse).data).to.exist;
  })
}).as('alias')
```
which still requires `as` if we want to keep full type safety.

This feels especially awkward because we have wrapped some `wait` calls to their own methods:
```typescript
const whenComplete = (expectations: ((i: { request: CyHttpMessages.IncomingRequest, response?: CyHttpMessages.IncomingResponse }) => void)) => cy.wait('@alias').then(expectations);

whenComplete(({ request, response }) => {
  expect((request.body as CustomRequest).payload).to.exist
  expect((response?.body as CustomResponse).data).to.exist
})
```

Instead. with the proposal above, it is marginally easier and less error prone to write:
```typescript
const whenComplete = (expectations: ((i: Interception<CustomRequest, CustomResponse>) => void)) => cy.wait('@alias').then(expectations);

whenComplete(({ request, response }) => {
  expect(request.body.payload).to.exist // ← here the request type is known
  expect(response?.body.data).to.exist // ← here the response type is known
})
```

We do have these types (`CustomRequest` and `CustomResponse` as examples) already defined, so would be good if we can use them easily everywhere.

### Other

I have a fork that puts a type on the core `BaseMessage` interface, for `body`. This caused all the related types to have required updates to their types (i.e. made generic too).
I might have missed a better way to think about or do this.

### PR DESCRIPTION
**Pull request by scottmcginness**
- Closes #29507 
This adds a generic type to the `BaseMessage` interface in net-stubbing, for the `body` property. This then carries over to all of the related request/response types. And importantly into the `cy.intercept` and `cy.wait` methods, where it will be possible to write generic types for these and have them flow into the callbacks/chainables.

### Additional details
- Why was this change necessary?
See the related issue for examples.

- What is affected by this change?
The types that are exported from net-stubbing.d.ts were almost all affected. But their generic types still default to `any` in all cases, so the current behaviour should remain unless the user explicitly writes the generic types.
This may be a breaking change, depending on whether current users have specified types on these methods already. I don't think it was possible to write them in this way, but I can't quite figure out if it will be breaking for sure.

- Any implementation details to explain?
I'm not sure about the implementation of `cy.wait(['alias1'])` (i.e. the array of aliases). It seems to work, but is slightly tricky to use, because it needs to return an array of both the request and response types for each element in the alias array. As such the user has to specify `cy.wait<[[Req1, Res1], [Req2, Res2]]>(['alias1', 'alias2'])`, which is unlike the other overloads. (As an aside, I don't have a current use case for making types on this kind of call, but it made some sense to make it _possible_).

### Steps to test
I believe this only affects the experience inside an IDE (I used VSCode). Tested by running the `dtslint` script in the `cli` project.
I had a slightly hard time with this as I'm on Windows, and couldn't get the project to start. Nor do all the unit tests pass for me locally (but seems like just lots of line endings hopefully?)

### How has the user experience changed?
Before (without types) on `intercept`:
image
and after:
image

Before (without types) on `wait`:
image
and after:
image

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? **Not sure if this is required yet**
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)? **These are type definitions in themselves, for another area**

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@scottmcginness Thanks for the contribution! Can you add a changelog entry for this change? Instructions are [here](https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md#when-to-add-an-entry).

**Comment by scottmcginness** [comment]
> Can you add a changelog entry for this change? Instructions are [here](https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md#when-to-add-an-entry).

Thanks for the link! I've added this now, having missed that I should do it the first time around.

I noticed now that a few system tests have failed.
The related one seems to be that they are running Webpack with TypeScript 3.9, which did not support the type definitions as written for the `cy.wait(string[])` overload. I've reverted how that one works, in favour of just using `Interception<any, any>` in this case.

If someone wants to revive the fully-typed version in future, that's fine by me. It didn't seem easy enough or worth it to get it working in all cases with that extra constraint on the TypeScript version (unless I've missed something).

Hopefully those tests will pass now 🤞

**Comment by jennifer-shehane** [comment]
Rerunning the tests now

**Comment by cacieprins** [comment]
This looks fantastic! Thank you for the comprehensive tests. I've opened a [PR in our documentation repo](https://github.com/cypress-io/cypress-documentation/pull/5831) to provide examples based on this PR - can you take a look and verify that I'm understanding things correctly?

**Review by cacieprins — CHANGES_REQUESTED** [review]
This looks fantastic! Thank you for the comprehensive tests. I've opened a https://github.com/cypress-io/cypress-documentation/pull/5831 to provide examples based on this PR - can you take a look and verify that I'm understanding things correctly?

Unfortunately, we've since released a new version, so the changelog will need to be updated before we can merge it.

**Comment by scottmcginness** [comment]
> a https://github.com/cypress-io/cypress-documentation/pull/5831 to provide examples based on this PR

This looks just like my use cases, so thank you for this. I've left some comments (hope that's alright!) just on how exactly those work.

> the changelog will need to be updated

Moved the entry up to the pending section 👍

**Review by cacieprins — APPROVED** [review]

**Review by ryanthemanuel — APPROVED** [review]

**Pull request merged**
