### PR TITLE
docs: move contributing and code of conduct

### PR DESCRIPTION
**Pull request by santoshyadav198613**
- Closes 

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@santoshyadav198613 We just moved these files into the `.github` folder per this PR: https://github.com/cypress-io/cypress/pull/5701

Could you please detail why this change is necessary and fill out our Pull Request template? This PR will be closed otherwise.

**Comment by santoshyadav198613** [comment]
If you refer to big projects s like Angular even React they keep it in root so it's easy to find for the Developer's.

**Comment by santoshyadav198613** [comment]
Also they should not be part of .git as they can be changed by developers, the .git folder is more of template which is managed by core team, hope it makes sense.

**Comment by jennifer-shehane** [comment]
@santoshyadav198613 It is not part of the `.git` directory, it is part of the `.github` directory. 

I could see us pulling back out CONTRIBUTING and CODE_OF_CONDUCT because these are not reliant on GitHub itself, whereas the PR and Issue templates are only relevant on GitHub.

**Comment by jennifer-shehane** [comment]
Will need to update this link again: https://github.com/cypress-io/cypress-services/pull/1848

**Pull request merged**
