### PR TITLE
fix: Prevent crash when running on read-only FS.

### LINKED ISSUE #2064: Cypress should have a warning when in a Read Only FS not error
### Current behavior:
Cypress will throw when run in a read only FS.
In my case im running it under Bazel which only allows reading from it's processes unless specific files are stated to be written.

>The error was:
Error: EROFS: read-only file system, mkdir '/home/fabian/.config/Cypress/cy/production/projects'

### Desired behavior:
This error should be caught and handled as a warning that features like project seed, screenshots, video recording will be disabled when being unsed in a Read Only File system.

### Versions
```
Cypress:  3.0.1 
Browser:  Electron 59 (headless) 
Node: 8.11.2
OS: linux x64
```

related: https://github.com/cypress-io/cypress/issues/1281

### PR DESCRIPTION
**Pull request by magJ**
- Closes https://github.com/cypress-io/cypress/issues/2064

### User facing changelog

Support project directories mounted on read-only filesystems.

### Additional details

Cypress should be able to run when it's project directory is read-only, and only emit a warning about saving screenshots and videos.
The existing access checking logic only checks for permission issues, and does not handle the case of a read only filesystem.
Certain platforms like AWS-lambda use read-only filesystems.
With this change, it will now be possible to run cypress from those platforms.
 

### Steps to test

Mount a cypress project on a read-only filesystem, see if it runs.

### How has the user experience changed?

Can now run cypress from a read-only FS.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by AtofStryker — CHANGES_REQUESTED** [review]
Hi @magJ. Thank you for opening a contributor pull request. The proposed changes look OK to me, but in order to approve/merge this we will need a unit test. Can you add a unit test in `project_spec.js` after [this test](https://github.com/cypress-io/cypress/blob/develop/packages/server/test/unit/project_spec.js#L600)? The test can likely serve as a boilerplate. Not sure why the CircleCI job didn't run, but pulled in `develop` to prompt a re run.

**Comment by magJ** [comment]
@AtofStryker I've added a test, circleci was previously failing because I had revoked it's access to my account, it now appears to be failing because I'm not authorized by the cypress org.

**Comment by AtofStryker** [comment]
> @AtofStryker I've added a test, circleci was previously failing because I had revoked it's access to my account, it now appears to be failing because I'm not authorized by the cypress org.

well that is unfortunate. I am going to take a look into this and see what is going on!

**Review by AtofStryker — APPROVED** [review]

**Review by flotwig — APPROVED** [review]

**Comment by magJ** [comment]
The latest test run failures seem unrelated to the change 🤷, perhaps someone with permission could rerun the failed tests?

**Comment by flotwig** [comment]
Looks good now. Thanks @magJ!

**Pull request merged**
