### PR TITLE
feat: including version in CYPRESS_DOWNLOAD_PATH_TEMPLATE

### LINKED ISSUE #5141: Enable CYPRESS_DOWNLOAD_MIRROR to be used with a static file server
### Current behavior:

When `CYPRESS_DOWNLOAD_MIRROR` is specified Cypress will download the binaries from something like `https://whatever/desktop?platform=OS&arch=ARCH`.

This means we cannot serve these binaries from a static file server. Because of the query parameters.

### Desired behavior:

Change the API so that the file gets downloaded from something like `https://whatever/desktop/platform/:platform/arch/:arc/cypress.zip`.

Such an API can easily be implemented with a simple static file server. Something that is usually easy to setup in corporate environments.

### Steps to reproduce: (app code and test code)

1. Set `CYPRESS_DOWNLOAD_MIRROR` to point at a static file server.
2. Try to create files on this server that will implement the API so that Cypress will use linux binary when on Linux and Windows binary when on Windows.

### Versions

3.4.1

### PR DESCRIPTION
**Pull request by tomasbjerre**
- Closes #5141 #16976 #22864

### User facing changelog

Including `version` as a variable that can be used in `CYPRESS_DOWNLOAD_PATH_TEMPLATE`.

### Additional details

To allow users that are behind a firewall to point `CYPRESS_DOWNLOAD_PATH_TEMPLATE` at an internally hosted binary.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/4651
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by BlueWinds** [comment]
Looks good to me; I merged in develop to kick off a CI build.

**Review by BlueWinds — APPROVED** [review]

**Comment by tomasbjerre** [comment]
There was a linting issue, fixed that and force-pushed it.

**Comment by tomasbjerre** [comment]
Not sure if I need to do something more here? Seems to be some tests failing but I dont see how they are related to my patch.

**Comment by BlueWinds** [comment]
> Not sure if I need to do something more here? Seems to be some tests failing but I dont see how they are related to my patch.

Yeah, sorry about that - we have some flake in our tests that we're currently attempting to address. I'll see about getting this merged today, thank you for your patience!

**Review by mjhenkes — APPROVED** [review]

**Comment by fengmk2** [comment]
Install cypress binary from China Mirror

```bash
CYPRESS_DOWNLOAD_PATH_TEMPLATE='https://cdn.npmmirror.com/binaries/cypress/${version}/${platform}-${arch}/cypress.zip' npm install cypress
```

**Pull request merged**
