### PR TITLE
feat: Support Bearer token injection alongside Basic Auth

### LINKED ISSUE #4837: Optional values: bearer and sendImmediately are missing in Cypress.Auth interface (TypeScript)
### Current behavior:

The current interface for Auth:

```js
 interface Auth {
    username: string;
    password: string;
  }
```

### Desired behavior:

Both `bearer` and `sendImmediately` should be optional props:

```js
  interface Auth {
    username: string;
    password: string;
    bearer?: string;
    sendImmediately?: boolean;
  }
```

### Steps to reproduce: (app code and test code)

Try passing either `bearer` or `sendImmediately` as options

### Versions

Cypress 3.3.2

### PR DESCRIPTION
**Pull request by blakestoddard**
- Closes #4837

### User facing changelog
- Support `Bearer` tokens inside `auth` option blocks. 

### Additional details

Allows a user to use the Cypress proxy middleware to inject `Bearer` tokens via the `Authorization` header. Currently on basic auth is supported.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by flotwig** [comment]
@blakestoddard Thanks for opening a PR. The code looks solid (missing tests tho); however, I don't think that we can merge this feature.

[`cy.visit()`](https://on.cypress.io/visit)'s goal is to simulate a user visiting a web page in their browser, like via a bookmark or by clicking some hyperlink somewhere. That is why HTTP basic auth is supported by passing `auth` to `cy.visit` - real browsers support sending HTTP basic auth with a visit, so Cypress's API seeks to enable and match that behavior.

HTTP bearer token auth, on the other hand, is not (AFAIK) ever sent with a regular visit. The bearer token is always added later down the line by the JS code making the request.

With this in mind, it doesn't really make sense to add `bearer` to the `auth` property, since it's not something that makes sense to add to a visit.

Also, I am not totally sure, even after reading this PR and #4837, what a valid use case for this looks like. It seems like if the purpose is to send a request for a test with `bearer` auth, you should just use [`cy.request()`](https://on.cypress.io/request) or the `fetch` API.

----

That being said, there is a way to do this today with [`cy.intercept()`](https://on.cypress.io/intercept), if you decide that you really need to send `bearer` auth with a `cy.visit`:

```ts
cy.intercept('/url-to-visit', (req) => {
	// intercept the cy.visit and add auth header with bearer token
	req.headers['authorization'] = 'bearer <token...>'
})

// later...
cy.visit('/url-to-visit')
```

----

Closing this since it won't be merged. I'll post a link to this comment in the parent issue and close it too.

**Comment by blakestoddard** [comment]
Hey Zach! Happy to expand a bit more on this.

For the use-case I have, I can't simulate OAuth/SSO because of some CORS restrictions in Cypress and in our app. The workaround is fetching a `bearer` token from an authentication service (which I do as a `Cyress.Command`) and then injecting that into the initial request so that it is authenticated (HTTP basic auth, the bearer token, cookie -- they're all valid methods of authentication). The issue I run into is that that app makes other external calls to, say, GraphQL that won't be authenticated without `bearer` token injection by Cypress (in regular operation they would have the cookie store, but I can't simulate it for Reasons), and if they're unauthenticated, the app gets into a bad state because effectively you're authenticated for the initial page-load but it can't fetch data client-side.

Using `cy.visit()` emulates that flow -- "visit this page with this set of authentication info and then force that in all of the child network requests too".

**Comment by flotwig** [comment]
I see, it sounds like another way would be to set up your tests with the correct cookies, so your app can obtain the bearer token it needs. But `cy.intercept()` to add the desired header should work for your case as well.

**Comment by blakestoddard** [comment]
Yeah, I'm going to give the `cy.intercept()` method a go. The cookies are a can of worms to get into...

**Pull request closed without merging**
