### PR TITLE
Formats number string in quotes.

### LINKED ISSUE #25: Commands UI assert errors should clearly delineate integers from strings.
The ASSERT error (in red background) on the commands UI does not signify whether my value is a string or not. The AssertionError (in yellow background) more clearly defines my error (that the integer 25 does not equal "25").

**Example**
screen shot 2015-04-20 at 11 57 25 am

### To reproduce:

```js
it('test', () => {
  expect(25).to.eq('25')
})
```

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #25

### User facing changelog

Formats number strings in test results in quotes. In other words, 25 -> '25'.

#### Why was this change necessary:

> The ASSERT error (in red background) on the commands UI does not signify whether **my value is a string or not.**
>
> 

#### What is affected by this change?

Not much. I just decaffeinated some files to work easily and added a test to show this case clearly. 

#### Any implementation details to explain?

Not much. 

As codes have been decaffeinated, I guess it is not recommended to be squashed. It should be rebased or merged. 

### How has the user experience changed?

Before: above.

After: 
Screenshot from 2019-10-31 08-49-10

### PR Tasks

- [x] Have tests been added/updated?
- ~~Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? ~~
- ~~Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?~~
- ~~Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?~~

### CODE REVIEW

**Comment by sainthkh** [comment]
Which one do you prefer, decaffeinated PR or coffee(#5544) PR?

**Comment by jennifer-shehane** [comment]
@sainthkh We prefer to have decaffeinated PRs as separate PRs from actual code work. If you can make a separate PR for decaffeinating files, then open a new PR after that is merged with the code changes. Evaluating decaffeinations with changes to code is more difficult.

**Comment by jennifer-shehane** [comment]
Also, the final result of this PR does not look like the exact desired result either, with the multiple quotations. I think this has something to do with how we format markdown? I'm not sure.

**Comment by sainthkh** [comment]
Added #5556 as a decaffeination part for this PR. 

Trying to understand why we have those quotation marks.

**Pull request closed without merging**
