### PR TITLE
feat: allow bypassing OS validation

### PR DESCRIPTION
**Pull request by saschanaz**
- Allow workaround for #30252. Could be used when the platform has no official support but still has emulation layer to run the given binary (which may be given either via `CYPRESS_INSTALL_BINARY` or `CYPRESS_DOWNLOAD_PATH_TEMPLATE`)

### Steps to test

Set $CYPRESS_BYPASS_OS_VALIDATION when `npm install`

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

(I want to get some feedback before checking PR tasks)

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@saschanaz Could you add a test for this case?

**Comment by saschanaz** [comment]
I'm happy to, do you think the direction itself is acceptable?

**Comment by jennifer-shehane** [comment]
@saschanaz I'd have to discuss it with the team

**Comment by jennifer-shehane** [comment]
You could use patch-package to update your Cypress for now to bypass the OS validation for now. That's our recommendation.

**Comment by saschanaz** [comment]
> You could use patch-package to update your Cypress for now to bypass the OS validation for now. That's our recommendation.

That's for maintainers and not for users. And this is for users. Can you reconsider, as there's no clear schedule when the native binary can be supported?

**Pull request closed without merging**
