### PR TITLE
chore(deps): migrate to community @faker-js/faker

### LINKED ISSUE #30096: Migrate `faker` to supported version
### What would you like?

Migrate the use of the deprecated npm module [faker](https://www.npmjs.com/package/faker) to the replacement supported community version [@faker-js/faker](https://www.npmjs.com/package/@faker-js/faker)

https://github.com/cypress-io/cypress/blob/919f86426eb620d2d3048b954c47590395fbe597/packages/app/package.json#L54

https://github.com/cypress-io/cypress/blob/919f86426eb620d2d3048b954c47590395fbe597/packages/frontend-shared/package.json#L55

### Why is this needed?

The GitHub repo associated with the npm module [faker](https://www.npmjs.com/package/faker) was deleted by the owner in January 2022 and is de-facto unsupported. This is described in [I heard something happened. What's the TLDR?](https://fakerjs.dev/about/announcements/2022-01-14.html#i-heard-something-happened-what-s-the-tldr). Renovate declares [faker](https://www.npmjs.com/package/faker) as deprecated, although the npm registry does not show any related notice.

Website https://fakerjs.dev/ provides documentation for the replacement npm module [@faker-js/faker](https://www.npmjs.com/package/@faker-js/faker).

### Other

- The following modules are currently listed as deprecated on https://github.com/cypress-io/cypress/issues/3777:
    - [faker](https://www.npmjs.com/package/faker) - replacement available
    - [@types/faker](https://www.npmjs.com/package/@types/faker) - replacement not available
  
Removing the dependency on [@types/faker](https://www.npmjs.com/package/@types/faker) requires migrating to [@faker-js/faker](https://www.npmjs.com/package/@faker-js/faker) >= `6.x` which needs to be a separate issue / PR.

### PR DESCRIPTION
**Pull request by MikeMcC399**
- Closes https://github.com/cypress-io/cypress/issues/30096

### Additional details

- The npm module [faker](https://www.npmjs.com/package/faker) is currently listed as deprecated on https://github.com/cypress-io/cypress/issues/3777

The deprecated npm module [faker@5.5.3](https://www.npmjs.com/package/faker/v/5.5.3) is migrated to the identical (non-deprecated) community version [@faker-js/faker@5.5.3](https://github.com/faker-js/faker/releases/tag/v5.5.3). See note in https://v6.fakerjs.dev/migration-guide-v5/

> In addition to releasing all future versions under the @faker-js/faker package namespace, we have also provided all historical versions of Faker.

For background information read also [I heard something happened. What's the TLDR?](https://fakerjs.dev/about/announcements/2022-01-14.html#i-heard-something-happened-what-s-the-tldr).

### Steps to test

```shell
git clean -xfd
yarn
yarn workspace @packages/frontend-shared cypress:run:ct
yarn workspace @packages/frontend-shared check-ts
yarn workspace @packages/app check-ts
```

### How has the user experience changed?

No change.

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by MikeMcC399** [comment]
This needs more work.

**Comment by MikeMcC399** [comment]
Migrating 1:1 from 

- [faker@5.5.3](https://www.npmjs.com/package/faker/v/5.5.3) 
- to [@faker-js/faker@5.5.3](https://github.com/faker-js/faker/releases/tag/v5.5.3)

in a TypeScript environment seems not to be possible due to missing TypeScript definitions. The test `check-ts` fails (see https://app.circleci.com/pipelines/github/cypress-io/cypress/63677/workflows/525deb32-1364-4a28-b882-129fed469e23/jobs/2639926). [@faker-js/faker@6.0.0](https://github.com/faker-js/faker/releases/tag/v6.0.0) is the first migrated version which deals with TypeScript definitions cleanly.

Closing this PR. I will open a new PR to migrate directly to [@faker-js/faker@6.0.0](https://github.com/faker-js/faker/releases/tag/v6.0.0)

**Comment by MikeMcC399** [comment]
I made a mistake which led me to think this PR couldn't be made to work. In the meantime I realized what went wrong, so I've corrected the PR and all tests (so far) are passing. 🙂

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Great! I'll kick off the tests.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Some relevant failures here: https://app.circleci.com/pipelines/github/cypress-io/cypress/63678/workflows/0390e57b-20a3-4945-827b-8fc6d4c5bf44/jobs/2640546/tests

Screenshot 2024-08-26 at 11 16 33 AM

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Thanks for picking out the failures!

I reverted the [tree-shaking syntax for importing faker](https://v6.fakerjs.dev/migration-guide-v5/#tree-shaking) which it seems is only good for `@faker-js/faker@6` and not for the legacy `@faker-js/faker@5.5.3` version.

The following tests all pass when run locally:

```shell
yarn workspace @packages/frontend-shared cypress:run:ct
yarn workspace @packages/frontend-shared cypress:run:ct --browser chrome
yarn workspace @packages/frontend-shared check-ts
yarn workspace @packages/app check-ts
```

**Review by jennifer-shehane — APPROVED** [review]

**Review by cacieprins — APPROVED** [review]

**Pull request merged**
