### PR TITLE
fix: update border color values

### PR DESCRIPTION
**Pull request by marktnoonan**
This doesn't have an issue but came from design review with @ryanjwilke 

### User facing changelog

No functional changes.

### Additional details

There were some places we had borders set to be too dark compared to figma, and in the specs list while we did set the correct value, it wasn't set in the right place.

### Steps to test

- Open the launchpad for any project
- Pick a testing type, see the lighter border
- Pick a browser, see the lighter border
- Open specs list, see the lighter border

### How has the user experience changed?

Before:

before - browsers
before - cards
before - specs list

After:

after - browsers

after - cards

after - specs list

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by mike-plummer — APPROVED** [review]
Looks good from a code perspective - fyi, this also impacts the "Create a new spec" dialog since that uses `Card`

I personally find the lighter shades more difficult visually - the row dividers are almost non-existent on my non-retina monitor. I'm probably overthinking it, but the card borders feel more like a "grouping" divider than an actionable element; the darker gray may have felt more like a box shadow which isn't there anymore. In any event it's just personal preference, I'll defer to the more design-minded among us

**Comment by marktnoonan** [comment]
Good point on the other usage of card - it's intended for all cards 👍 

@mapsandapps maybe can weigh in on the design feedback itself before we merge.

**Comment by mapsandapps** [comment]
@abelb is going to look into the grays to see if there's something better to do. it sounds like any changes we make here will require rethinking other situations across the app, so imo it might be best to go ahead and merge this now and maybe make a design ticket to think about what to change them to and then change them across figma first and then in the code.

**Comment by marktnoonan** [comment]
@mapsandapps your call, if you can approve the PR I'll merge it in 👍

**Review by mapsandapps — APPROVED** [review]

**Pull request merged**
