### PR TITLE
more permissive check for json to include application/vnd.api+j…

### LINKED ISSUE #5165: response.body isn't converted to JSON if content-type is application/vnd.api+json
### Current behavior:

If a response comes back with a `content-type` header set to `application/vnd.api+json`, response.body does not contain JSON:

```
Object
body: Blob {size: 4370, type: "application/vnd.api+json"}
headers: {content-length: "1877", content-type: "application/vnd.api+json"}
__proto__: Object
```

I think this is because `request.coffee` only returns JSON if `content-type` exactly matches `application/json`, based on [these lines in the develop branch](https://github.com/cypress-io/cypress/blob/9f717fe7e8b73313ee23c5aa3c92e504fb899337/packages/server/lib/request.coffee#L484-L486):

```coffeescript
contentTypeIsJson: (response) ->
      ## TODO: use https://github.com/jshttp/type-is for this
      response?.headers?["content-type"]?.includes("application/json")
```

Those lines include a `TODO` which suggests using [type-is](https://github.com/jshttp/type-is) to improve on the potential JSON `content-type` pattern-matching.

### Desired behavior:

Cypress XHR responses with a content-type of `application/vnd.api+json` also have their bodies parsed as JSON. Happy to write a PR to use `type-is` to handle `application\/[\S]+?\+?json$` if no one objects.

### Steps to reproduce: (app code and test code)

This spec will write a fixture file without the bodies of the responses, they will all be `undefined`:

```javascript
describe('Cypress does not parse JSON API', () => {
  // We declare an empty array to gather XHR responses
  const xhrData = [];
  after(() => {
    // In record mode, save gathered XHR data to local JSON file
    if (Cypress.env('RECORD')) {
      const path = './cypress/fixtures/fixture.json';
      cy.writeFile(path, xhrData);
    }
  });
  it('Works', () => {
    cy.server({
      // Here we handle all requests passing through Cypress' server
      onResponse: (response) => {
        if (Cypress.env('RECORD')) {
          const url = response.url;
          const method = response.method;
          const data = response.body;
          // We push a new entry into the xhrData array
          xhrData.push({ url, method, data });
        }
      },
    });
    // This tells Cypress to hook into any GET request
    if (Cypress.env('RECORD')) {
      cy.route({
        method: 'GET',
        url: '*',
      });
    }
    if (!Cypress.env('RECORD')) {
      cy.fixture('fixture').then((data) => {
        for (let i = 0, length = data.length; i < length; i++) {
          cy.route(data[i].method, data[i].url, data[i].data);
        }
      });
    }


    cy.visit('/');
  });
});
```

### Versions

```bash
$ npx cypress --version
Cypress package version: 3.1.5
Cypress binary version: 3.1.5
```

### PR DESCRIPTION
**Pull request by jazwiecki**
Decided to go with the smallest possible change rather than introducing a new package (`type-is`) as suggested in the neighboring TODO.

Closes #5165.

### Pre-merge Tasks

- [x] Have tests been added/updated for the changes in this PR?

### CODE REVIEW

**Comment by flotwig** [comment]
There's a test for the existing `application/json` behavior here, you can add a test for the `application/vnd.api+json` behavior as well: https://github.com/cypress-io/cypress/blob/8a9ec9089335262330d8d9aacc4ecca1daaf6038/packages/server/test/unit/request_spec.coffee#L438-L450

**Comment by flotwig** [comment]
Also, I didn't know there was this much controversy about what the correct JSON MIME type is:

- https://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type
- https://stackoverflow.com/questions/28055526/header-value-application-vnd-apijson

**Comment by jjnypr** [comment]
@flotwig thank you! I can't tell why some of the tests on this are failing. Specifically, `server-e2e-tests` 2 through 6. At a glance, it doesn't look like the failures have anything to do with swapping `includes` for `endsWith`. Does anyone know why this is happening?

**Comment by flotwig** [comment]
Looking at 3_user_agent_spec, there's this failure: `CypressError: Timed out retrying: expected '{"userAgent":"foo bar baz agent"}' to deeply equal { userAgent: 'foo bar baz agent' }`

It seems like it's no longer converting JSON according to the same rules, although I'm not sure exactly how your changes caused this, since it looks correct to me.

**Comment by jazwiecki** [comment]
@flotwig Poking around more, I see some other "deeply equal" errors that seem to hinge on seemingly trivial formatting differences for specs that pass when _not_ run e2e. For example, 2_cookies_spec.coffee returns this error:

```
  1) cookies without whitelist sends cookies to localhost:2121:
     CypressError: Timed out retrying: expected '{"asdf":"jkl"}' to deeply equal { asdf: 'jkl' }
```

...but it's just running `test/unit/request_spec.coffee`, which otherwise works in tests? I'm stumped!

**Comment by jazwiecki** [comment]
@flotwig I'm a bit embarrassed by this solution but all the tests pass. I don't really know coffeescript so if there's a more elegant way to do this without causing all the tests to fail, I'd love to know more. As is, I've added a test for responses with a `content-type` of `vnd.api+json`. OK to merge?

**Comment by flotwig** [comment]
Got it figured out by setting `DEBUG=cypress:server:request` and checking the logs - tests were sending `content-type': 'application/json; charset=utf-8`, which would fail the `endsWith` check.

**Pull request merged**
