### PR TITLE
chore: use `import type` syntax

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes N/A

### Additional details

I added the `importsNotUsedAsValues` rule to our `ts/tsconfig.json`. This enforces than type-only imports be written using the new `import type` syntax. Read about that rule [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export). 

The reason this is useful is a lot of the newer ESM based build tools, like [Vite](https://vitejs.dev/), sometimes have problems trying to import types from TypeScript code designed to be used on the server. It will help future proof us.

For example in the unified feature branch ("launchpad"), which is developed using Vite, I may want to import an interface from `server/lib/project-base.ts`. That file also imports some Node.js only modules, like `fs`. If you do `import { ProjectBase } from '@packages/server/lib/project-base.ts`, it will error out, since Vite attempts to import the entire file to the browser, including the Node.js-only modules, like `fs`. 

`import type { ProjectBase } from '...' works correctly - Vite is able to extract the type, and ignore the actual implementation code. No side effects 😎 

Another potential benefit is the TS compiler can likely do some optimizations if it just importing a file for type definitions, not actual runtime code. 

There's no real downside to the new `import type` syntax, so I just went ahead and added it to the entire code base. VS Code can even automatically do the correct import for you, since we have the rule in `tsconfig.json`.

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — DISMISSED** [review]
Looks good.

**Comment by jennifer-shehane** [comment]
@lmiller1990 Seems to be quite a bit of failures in this branch. Could you look into those?

**Comment by lmiller1990** [comment]
@jennifer-shehane actually just reporter is failing, I think the rest is flake -- gimme an hour. Thanks for the quick response.

**Review by tgriesser — DISMISSED** [review]
This is great work, thanks for doing this @lmiller1990!

**Review by tgriesser — APPROVED** [review]
Great, let's merge as-is and revisit for any other packages it's missing on (reporter, ui-components, etc.)

**Review by flotwig — APPROVED** [review]
TIL about `import type`. Not sure what's up with semantic commit/percy checks...

**Pull request merged**
