### PR TITLE
WIP: add pac proxy script

### LINKED ISSUE #2539: Switch to using proxy pac files
Instead of configuring each individual browser's `proxy` settings we should switch to using a pac file, which is much more flexible and gives us the ability to consistently work the same way in all browser agents.

A pac file also makes it easy to bypass the proxy and forward directly to servers running on loopback for automation purposes.

### PR DESCRIPTION
**Pull request by brian-mann**
fixes #2539

### CODE REVIEW

**Comment by pvdyck** [comment]
@bahmutov ready for Sprint 5 or postpone ?

**Comment by jennifer-shehane** [comment]
Hey @brian-mann, what's the hold up on this PR. Last commits were from October.

**Comment by flotwig** [comment]
The reason we wanted to use a PAC file for the browser was so that we could forward all requests EXCEPT requests for Cypress itself through Cypress's proxy. However, we currently detect connections that are destined for Cypress when we proxy through Cypress's proxy and handle them accordingly, so this isn't necessary.

**Comment by brian-mann** [comment]
This PR is still necessary and handles a different situation for use in remote browser environments. Reopening.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this PR due to inactivity. Please open a new PR to address the original issue.

**Pull request closed without merging**
