### PR TITLE
fix: test runner reporter performance

### LINKED ISSUE #6783: Tests slow down over time when performing several XHR requests calls in single test
### Current behavior:

Typing into several inputs in a single test where there are XHR requests that goes out during each keypress event - like `keyup` or similar - causes the tests to slow down over time.

The network request responses do not seem to be responding any slower over time. 

This slowness does *not* occur if you split up the typing across several tests. 

### Desired behavior:

Performance of running tests should stay the same over time

#### ❗️ Looping through input in a single test

Causes slowdown - maybe because we are saving a lot of XHR request data for every command

`spec.js`

```js
it("test1", () => {
  cy.visit('index.html')
  for (var i = 0; i < 100; i++) {
    cy.get('input').type('test no animations long test case') 
    cy.get('input').clear()
  }
})
```

`index.html`

```html
<html>
<body>
<input />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
    $(() => {
    $('input').on('keyup', (e) => {
        $.ajax({
        url: 'https://jsonplaceholder.cypress.io/comments',
        method: 'POST',
        data: {
          name: 'Using POST in cy.route()',
          email: 'hello@cypress.io',
          body: 'You can change the method used for cy.route() to be GET, POST, PUT, PATCH, or DELETE',
        },
        })
    })
    });
</script>
</body>
</html>
```

Screen Shot 2020-03-19 at 12 33 04 PM

Starting to slow down

Now really slow towards the end

#### ❗️ Looping through clicking button in a single test

The slowness is not isolated to the `.type()` command

`spec.js`

```js
it("test1", () => {
  cy.visit('index.html')
  for (var i = 0; i < 1000; i++) {
    cy.get('button').click()
  }
})
```

`index.html`

```html
<html>
<body>
<button />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
    $(() => {
    $('button').on('click', (e) => {
        $.ajax({
        url: 'https://jsonplaceholder.cypress.io/comments',
        method: 'POST',
        data: {
          name: 'Using POST in cy.route()',
          email: 'hello@cypress.io',
          body: 'You can change the method used for cy.route() to be GET, POST, PUT, PATCH, or DELETE',
        },
        })
    })
    });
</script>
</body>
</html>
```

#### ✅ Looping through input over different tests

**No slowdown** - even with `numTestsMemory` kept at `50`.

```js
describe("Testing", () => {
  Array(100).fill(0).forEach((val, i) => {
    it(`test ${i}`, () => {
      cy.visit('index.html')
      cy.get('input').type('test no animations long test case')
      cy.get('input').clear()
    })
  })
})
```

Screen Shot 2020-03-19 at 1 06 01 PM

#### ✅ Looping through input without XHR requests

**No slowdown**

`spec.js`

```js
it("test1", () => {
  cy.visit('index.html')
  for (var i = 0; i < 100; i++) {
    cy.get('input').type('test no animations long test case') 
    cy.get('input').clear()
  }
})
```

`index.html`

```html
<html>
<body>
<input />
</body>
</html>
```
### Versions

4.2.0 - tried to track this down to some regression in earlier version, but couldn't find any correlation.

### PR DESCRIPTION
**Pull request by tgriesser**
- Closes #6783 

### User facing changelog

Improved performance with larger numbers of tests.

### Additional details

Did some digging into rendering bottlenecks in the reporter, found a number of things needing addressing, the lowest hanging fruit are the lazy initial rendering of runnables, and the custom styling of the reporter scrollbar. The PR removes the custom styling for the scrollbar & renders all runnables from the start.

Uses this test case, updating the `COUNT` as seen in the table screenshot below:

```ts
const COUNT = 100

describe('renders tests', () => {
  Cypress._.times(COUNT, (n) => {
    it(`${n} test`, () => {
      expect(true).to.be.true
    })
  })
})
```

Recorded benchmarks for removing the progressive rendering of the runnable list, as well as the style fixes - and then both combined. My hunch here is that the reason we needed to add the incremental node rendering has been addressed by more recent React versions.

Also manually confirmed that it fixes the experience in: https://github.com/cypress-io/cypress/issues/6783

### How has the user experience changed?

image

Screen Shot 2021-07-08 at 1 48 30 PM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@tgriesser 

1. I can see that this improves performance for https://github.com/cypress-io/cypress/issues/6783 but doesn't completely account for all slowdown. The test still runs progressively slower towards the end of the test than it did at the beginning, although the original example is a bit extreme. The type command is about ~400ms slower towards the end compared to the  first type command instead of ~3000ms slower (before this change)! So this is a big improvement.
2. I don't feel super great about not displaying a scrollbar for scrollable content. This is poor usability. Anything we can do about this?
3. The performance seems to be slightly worse in Firefox after this change? 😬 
4. It would be 💯 if we had a way to test this. I know this is the hardest part though. There's kind of nothing stopping someone in the future from adding some slight change and just blowing out the performance again. 

I'd like to explore points 2 and 3, but overall I still think this may be an improvement to merge in even with those downsides. Would love someone else on the team to review as well.

### Chromium browsers

#### Before

Finished in 223 seconds

Screen Shot 2021-07-08 at 2 10 29 PM

Using [cypress-timings](https://www.npmjs.com/package/cypress-timings) to show the `type` command duration of first type versus last type in test.

Screen Shot 2021-07-08 at 3 02 31 PM


#### After

Finished in 107 seconds

Screen Shot 2021-07-08 at 2 05 12 PM

Using [cypress-timings](https://www.npmjs.com/package/cypress-timings) to show the `type` command duration of first type versus last type in test.

Screen Shot 2021-07-08 at 3 08 00 PM

### Firefox browser

#### Before

Finished in 128 seconds

Screen Shot 2021-07-08 at 3 54 11 PM


Using [cypress-timings](https://www.npmjs.com/package/cypress-timings) to show the `type` command duration of first type versus last type in test.

Screen Shot 2021-07-08 at 3 54 42 PM

Screen Shot 2021-07-08 at 3 54 52 PM



#### After

Finished in 151 seconds

Screen Shot 2021-07-08 at 3 49 03 PM

Using [cypress-timings](https://www.npmjs.com/package/cypress-timings) to show the `type` command duration of first type versus last type in test.

Screen Shot 2021-07-08 at 3 50 28 PM

Screen Shot 2021-07-08 at 3 50 38 PM

**Comment by tgriesser** [comment]
@jennifer-shehane Thanks for the detailed review!

> I don't feel super great about not displaying a scrollbar for scrollable content. This is poor usability. Anything we can do about this?

We could display the normal scrollbar unstyled ([screenshot](https://user-images.githubusercontent.com/154748/124993385-4e24cd80-e012-11eb-8a52-057578223ad7.png)), or enable the scrollbar if you're not auto-scrolling?

I didn't know if we wanted to keep the current styling to keep it consistent with how it is now, so I opted to disable it entirely while the specs are running and show it when you're done and are more likely to find it useful. If we virtualize (see point below), we'll probably want to disable it entirely as well.

> The performance seems to be slightly worse in Firefox after this change? 😬

Interesting about Firefox, will need to take a look and see if it's the CSS or the runnable renderings that causes this regression

>  The test still runs progressively slower towards the end of the test than it did at the beginning, although the original example is a bit extreme.

Yes, didn't anticipate this would be the only solution - this was just the simplest first pass, also looking into another approach of virtualizing the runner content while it's executing, which I believe should have a pretty massive improvement - but the implementation remains to be seen.

> It would be 💯 if we had a way to test this. I know this is the hardest part though. There's kind of nothing stopping someone in the future from adding some slight change and just blowing out the performance again.

We could probably create a bounds of what we roughly expect to be correct timings and run this in its own isolated e2e spec. Might be flaky but I think should be doable 🤔

**Comment by jennifer-shehane** [comment]
@tgriesser I feel like the original intent for styling the scrollbar years ago was to make it slimmer than the native one and standardize across OS. I think it'd probably be ok to just remove the styling altogether. It doesn't even work in Firefox.

**Comment by jennifer-shehane** [comment]
@tgriesser Is this  ready for rereview? I'm a little unclear.

**Comment by tgriesser** [comment]
Ran in Firefox w/ your test cases & prod build of react `yarn build-prod` in `runner` package, seeing about equivalent performance:

| Before | After |
|-------|-------|
| Screen Shot 2021-07-27 at 10 56 47 AM | Screen Shot 2021-07-27 at 11 01 33 AM |

**Comment by jennifer-shehane** [comment]
I've run into this error trying to run `yarn build-prod` for the `runner`. I've seen this error before, not sure why it throws sometimes.

Screen Shot 2021-07-28 at 11 00 23 AM

**Review by jennifer-shehane — APPROVED** [review]
Um, yah this is a lot faster with the `build-prod` than I even realized. 💯 💯 💯 💯 Thanks @tgriesser

**Pull request merged**
