### PR TITLE
Ctrl+F to set focus on the search bar 

### PR DESCRIPTION
**Pull request by Manuel-Suarez-Abascal**
- Closes [6229](https://github.com/cypress-io/cypress/issues/6229)

### User facing changelog

There is a new keyboard shortcut (CTRL + F) to search spec files in the Test Runner.

### Additional details

This PR allows users to perform a search for test files with the CTRL + F command. The file where the implementation was added is `cypress\packages\desktop-gui\src\specs\specs-list.jsx`. I used a method that uses the  `ternary operator` & adds `focus` to the search `input` if CRTL + F is pressed. Then I called the `method` on `keydown` on the `window` object.

### How has the user experience changed?
You can check the new behaviour in the gif below:

execute-search-ctlr-f

### PR Tasks

- [X] Has a PR for user-facing changes been opened in [`issue-6269`](https://github.com/cypress-io/cypress/issues/6229)?

### CODE REVIEW

**Comment by Manuel-Suarez-Abascal** [comment]
> We will need some tests written to verify this new behavior.

@jennifer-shehane thanks for all the information. I have been trying to add the tests for the new behavior & I have tried this:

```
it.only('sets focus on search filters if user presses Ctrl + F', () => {
      // assertions passed here
      cy.get('body').click()
      cy.get('.filter').should('to.be.focus')

      // assertions don't passed here
      cy.get('.filter').type('{ctrl}f')
      cy.get('.filter').should('to.be.focus')     
})
```
But it won't pass, it seems it doesn't recognise as `Ctrl + f` command. Can you offer some guidance on how to solve this?

**Comment by Manuel-Suarez-Abascal** [comment]
> We will need some tests written to verify this new behavior.

@jennifer-shehane thanks for all the information. I have tried to add the following tests:

```
it('sets focus on search filters if user presses Ctrl + F', () => {
      cy.get('.filter').type('{ctrl}F')
      cy.get('.filter').should('to.be.focus')
})
```

It passes correctly, but when I tried to `commit` the changes, I get this error message:
```
Found .only in folder(s) 👎
305:        it('displays only matching spec', () => {
```

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane I have tried adding the test in different places within the `specs_list.spec.js` file, but I still the same error message when I tried to commit the changes. I have attached a screenshot below showing that all test passed properly:

localhost_54384____

**Comment by jennifer-shehane** [comment]
@Manuel-Suarez-Abascal The warning is indicating that you have a `.only` on this test file when you are trying to commit https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/integration/specs_list_spec.js#L299:L299

But, if this is not the case, I think that there is an issue where this `.only` warning displays unnecessarily when trying to commit on Windows as documented here: https://github.com/cypress-io/cypress/issues/5518

Pass the `--no-verify` flag during your commit to ignore this warning.

**Comment by Manuel-Suarez-Abascal** [comment]
> But, if this is not the case, I think that there is an issue where this `.only` warning displays unnecessarily when trying to commit on Windows as documented here: #5518
> 
> Pass the `--no-verify` flag during your commit to ignore this warning.

@jennifer-shehane thanks! It worked like a charm! I have pushed my latest changes.

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane I see I thought we wanted to use/focus on the filter search when pressing `Ctrl + F` command.

I assume the GUI is built on Electron, is that accurated? 

I'll have to find a way to get the **[`BrowserWindow` object](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentsfindinpagetext-options)** on Electron because I don't think it has access to the `browser's API`. What are your thoughts on this?

**Comment by jennifer-shehane** [comment]
@Manuel-Suarez-Abascal Let me check with the team on the implementation we want and get back to you.

**Comment by jennifer-shehane** [comment]
K, recommendations for this PR are as follows:

- Keep the `ctrl + f` shortcut to search within the spec files. If would be nice if the shortcut were displayed somewhere so that people know this exists (maybe in placeholder text? It would have to be a good design and also show OS specific shortcuts depending on launched OS)
- Look into adding the Electron menu for general Find within Electron. Would be added here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/gui/menu.js#L66:L66

**Comment by Manuel-Suarez-Abascal** [comment]
> K, recommendations for this PR are as follows:
> 
> * Keep the `ctrl + f` shortcut to search within the spec files. If would be nice if the shortcut were displayed somewhere so that people know this exists (maybe in placeholder text? It would have to be a good design and also show OS specific shortcuts depending on launched OS)
> * Look into adding the Electron menu for general Find within Electron. Would be added here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/gui/menu.js#L66:L66

Perfect, sounds good to me! I'll start working asap, but first I need to solve an issue that I currently have...I  made a `git pull` to get latest changes locally & now when I run `npm run watch` or `npm run cypress:open` it won't work. I also tried to remove the `node_modules` &  run `npm i`, but I can't make it to work. I might clone the `branch` to my local to see if it solves the issue. Any tips will be appreciated! 🙂

**Comment by jennifer-shehane** [comment]
@Manuel-Suarez-Abascal Sorry for the confusion. We've switched to using `yarn` in latest `develop`, so you'll need to use `yarn`. 

There are updated instructions in the CONTRIBUTING.md and each README.md in the project.

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane an update on this ticket.

After taking the time to think about the implementation, I decided to add an info icon & create click event to toggle the search `input`'s placeholder from `Search...`  to `Press CTRL + F (or CMD + F on Mac) to make a quick search...` & vice-versa.

 In the beginning, I was thinking about on a `mouseenter` or `mouseleave` event, but I thought it was too intrusive & distracting.

Now, I need to add the functionality to the Electron menu. However, I wanted to know your opinion before moving forward in order to know if I'm on the right track.

 I have attached a gif below. I think the info icon is...meh, so maybe you have another icon? :thinking:

search-tips

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane 
> * I would remove the info icon. I think that we should show the placeholder text containing the keyboard shortcuts on `focus` of the searchbar. This will make them aware of it in the future and not be distracting.

Great idea! :bulb:  I have implemented it!

> * We do not need to have text like 'if on Mac'. We _know_ the operating system Cypress is running within, so you should show the appropriate command shortcut based off of the OS they are using.

I have a created method called `isMac` to check for the current Operating System & returns the desired message in the placeholder in consequence. I cannot test in different Operating System, so please let me know if it's working properly on different OS.

> * Yeah, I'm seeing now that Electron actually does not support a built-in Find menu. I'm honestly not sure off the top of my head on how to get this shortcut to focus on the search bar. It may need some kind of similar mechanism as `onLogOutClicked` uses. Feel free to reduce the scope of this PR to remove this requirement if needed.

I'm not sure how to implement this behavior, so for now, I'll reduce the scope of this ticket.

**Comment by Manuel-Suarez-Abascal** [comment]
> You can check for this using `Cypress.platform`. https://on.cypress.io/platform

I have tried to find the Operating System with this code snippet: 

```
return (Cypress.platform === 'darwin')
      ? 'Press Cmd + F to make a quick search...'
      : 'Press Ctrl + F to make a quick search...'
```
But it states ```Cypress is not defined```. I have tried importing it like so: `import cypress from 'cypress'`, but it doesn't work. 

I'm stuck on how to get the Operating System. In the beginning, I tried with `os.platform()`, but no luck.

Can you provide me with some pointers on how to accomplish this

**Pull request closed without merging**
