### PR TITLE
fix: missing fallback generic browser icon in some places

### LINKED ISSUE #21766: Fallback browser icon missing from selected state in dropdown
This is a screenshot of a configuration set to use the installed Brave browser. The generic icon appears in most places, but is missing from the drop down within the AUT frame. It's in the expanded list but not when the element is selected in the menu.

Screen Shot 2022-03-15 at 11 18 16 AM

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/UNIFY-1356) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://cypress-io.atlassian.net/rest/api/2/attachment/content/11510">Screen Shot 2022-03-15 at 11.18.16 AM.png</a>
┆author: Paul Jaffre
┆epic: UI/UX Improvements
┆friendlyId: UNIFY-1356
┆priority: Low
┆sprint: Backlog
┆taskType: Bug

### PR DESCRIPTION
**Pull request by gitstart**
- Closes https://github.com/cypress-io/cypress/issues/21766

### User facing changelog

Fixed an issue where fallback browser icon missing from selected state in dropdown within the AUT frame. Fixes [#21766](https://github.com/cypress-io/cypress/issues/21766)

### Additional details

We are missing fallback value `allBrowsersIcons.generic` when getting selected browser icon in some places. 

### Steps to test

- Install Brave browser, start and complete all setup steps
- Prepare target project and follow [this instruction](https://docs.cypress.io/guides/guides/launching-browsers#Customize-available-browsers) to add Brave into launching browser list.
- Start cypress app, select the target project and then select Brave browser
- Start any specs (even example specs) you will see the generic browser icon missing from header

#### Before

image

#### After

image

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by gitstart** [comment]
@jennifer-shehane CircleCI pipeline is stuck at `Build` step with `Unauthorized` warning. Is there any action we should do to resolve that.

**Review by marktnoonan — CHANGES_REQUESTED** [review]
Thanks for this, and good catch! Before we review, please add a test. You could refer to [this block](https://github.com/cypress-io/cypress/blob/develop/packages/app/src/runner/SpecRunnerHeaderOpenMode.cy.tsx#L150) and do something similar that maybe overrides the name of the `activeBrowser` in `onResult` to be one that would cause `allBrowsersIcons[selectedBrowser.displayName]` to not be found.

**Comment by marktnoonan** [comment]
Thanks for the updates @gitstart, I will check what's going on with CI.

**Comment by marktnoonan** [comment]
Hi @gitstart sorry for the lack of communication - the errors do not result from your PR. There is currently some sort of permissions issue affecting the CI runs kicked off by github users outside of the organization. This PR looks good, my plan is to babysit CI and get it merged before the next release.

**Comment by gitstart** [comment]
Hi @marktnoonan Thank for checking. We can see all checks are passed. We are going to contribute more PRs to resolve current issues in Cypress Open Source in next times. Glad to contribute :)

**Review by marktnoonan — APPROVED** [review]
Installed Brave locally to do manual testing, all works great, thanks! Gonna find one more reviewer and then we can merge this.

**Review by ZachJW34 — APPROVED** [review]
Looks good!

**Comment by gitstart** [comment]
This PR was pushed through [Gitstart](https://www.gitstart.com/), with contributions from @phunguyenmurcul, @raph941.

**Pull request merged**
