### PR TITLE
fix(driver): fixed an issue with tests not failing for scripts with custom window.onerror

### PR DESCRIPTION
**Pull request by Andarist**
### User facing changelog 
Fixed an issue with tests not being failed on uncaught errors if the tested application has implemented its own `window.onerror` handler.

### Additional details
I'm not sure how to test this properly. Most stuff around failing tests in such situations are tested in suites like this:
https://github.com/cypress-io/cypress/blob/d2b8806d7c91e8386faaf6d89d5f32ab35e96dab/packages/server/test/e2e/1_caught_uncaught_hook_errors_spec.js
but those are using custom "runners" like this:
https://github.com/cypress-io/cypress/blob/d2b8806d7c91e8386faaf6d89d5f32ab35e96dab/packages/driver/cypress/fixtures/sync_error.html

I couldn't find any tests that would test this using what is actually used in the final product (the changed code line) but this repo is quite huge and maybe there is such a place. Happy to add the appropriate test if you point me in the right direction.

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@Andarist Can you provide a failing Cypress test showing this outside of our repo? Just an example `index.html` file with cypress tests? That would help us see the current error and help advice on an approach for fixing and testing it. 

This current change is breaking some of our existing tests, so may need some rethinking. You can see the failing status checks at the bottom of this PR.

**Comment by Andarist** [comment]
> @Andarist Can you provide a failing Cypress test showing this outside of our repo? Just an example index.html file with cypress tests? That would help us see the current error and help advice on an approach for fixing and testing it.

The problem is not about the spec files but the application code. The expectation is that uncaught errors should always (unless configured otherwise) fail the spec but with such (simplified) app code this doesn't happen:
```html
<!doctype html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <script type="text/javascript">
      // assume that this is the application under test
      window.onerror = err => sentry.report(err)
      throw new Error("Should fail the spec, but it doesn't.")
    </script>
  </head>
  <body>
  </body>
</html>
```
The problem is really simple - the app code overwrites the Cypress' error handler that is responsible for failing tests because it's attached using an overridable global property, rather than the `addEventListener` API.

> This current change is breaking some of our existing tests, so may need some rethinking. You can see the failing status checks at the bottom of this PR.

I'll try to take a look but if you would have any feedback regarding that before I manage to do so - please let me know. There are a lot of tests in the repo and I had problems running them from the root dir so far. I've managed to run some tests within the `packages/server`, need to learn how to filter them using the current setup as running so many at once just ain't practical.

**Comment by Andarist** [comment]
Ok, I believe that I've managed to fix tests (we'll see what CI has to say about that though 😉 ) and also added a test for the fixed issue 🎉

**Comment by Andarist** [comment]
Tests are mostly passing, based on other branches and testing locally some tests are just flaky and I fail to get a clean run when triggering CI. Those failures don't seem related to this PR.

**Review by jennifer-shehane — COMMENTED** [review]
Thanks for provided the situation. I figured there was already an open issue and wanted to track down what this was fixing. This will partially address this issue: https://github.com/cypress-io/cypress/issues/2487 (I'll have to check the other instances in the issue to see if we can just close this).

Glad to see you were able to add a test, the repo can definitely be confusing about where to test things because we have so many tests. 

We'll get a PR review in as soon as we're able.

**Comment by jennifer-shehane** [comment]
Actually, this doesn't address any of the error thrown from https://github.com/cypress-io/cypress/issues/2487 ☹️ oh well.

**Comment by Andarist** [comment]
> Actually, this doesn't address any of the error thrown from #2487 ☹️ oh well.

This is interesting. I wasn't aware of this issue - I've just fixed something I have noticed on my own, couldn't find an exact issue for this problem so instead of filing one I've jumped into fixing it.

Looking at this issue though I was expecting:
- that the rejected promise **won't** fail the test - or rather, the expectation should be that it should, but I know this is not handled right now and my PR has not touched unhandled rejections, so nothing has changed here
- that the thrown error from within `setTimeout` **would** fail the test, but it did not happen

So taking a closer look at this particular thing we can reduce the failing test to:
```html
<html lang="en">
  <head>
    <title>Hello World</title>
  </head>
  <body>
    <script>
      setTimeout(() => {
        throw new Error("original error");
      });
    </script>
    <div>
      <h1>This should fail...</h1>
    </div>
  </body>
</html>
```

So no funky stuff is going on in this test case and yet it doesn't fail as expected. After digging more into this I've noticed that a separate error handler catches this thrown error - or rather almost the same handler but attached to the top window, rather than the "AUT" window. `setTimeout`'s callback is wrapped by you and thus the invocation context changes - which has a small impact on how the application under test behaves (its own error handler won't be invoked). I don't yet know why the [`onTopError`](https://github.com/cypress-io/cypress/blob/052892d79f95f9792e00d426722a9d904b572df4/packages/driver/src/cypress/cy.js#L89-L91) doesn't fail this but at least we have an explanation on why this case is different from others.

As to unhandled rejections - I believe there are other issues about this as well and I might look into fixing this as it has affected me as well.

**Comment by Andarist** [comment]
Ok, I've investigated this even more - let me know if I should report my findings to some other, more appropriate, issue. 

In case of synchronous error (like in the test added by me here) the test is being correctly failed because of this line:
https://github.com/cypress-io/cypress/blob/052892d79f95f9792e00d426722a9d904b572df4/packages/driver/src/cypress/cy.js#L602
which is triggered by `reject` in `rejectOuterAndCancelInner ` here:
https://github.com/cypress-io/cypress/blob/052892d79f95f9792e00d426722a9d904b572df4/packages/driver/src/cypress/cy.js#L586-L590
which is called by that "top" error handler because `reject` is stored in the `state`:
https://github.com/cypress-io/cypress/blob/052892d79f95f9792e00d426722a9d904b572df4/packages/driver/src/cypress/cy.js#L593

However, this happens because that error is thrown when there is an **active** command (`visit`). When we try to execute the simplified test from my previous post - the one with an error thrown from within `setTimeout` - we **no longer** have an active command. This allows that crazy promise to settle (resolve) so even when the top error handler finally rejects the promise this has no effect, because that promise is already settled.

Why the promise gets resolved? Because the test is considered to be "stable" and this logic kicks in:
https://github.com/cypress-io/cypress/blob/052892d79f95f9792e00d426722a9d904b572df4/packages/driver/src/cypress/cy.js#L500-L513

What could/should be done? Well, you can't expect to handle random errors to happen at any time - many of them can happen completely out of your control, even after a test is considered to be completed. However, up until the test is considered to be running you probably should try to handle all uncaught errors. In this particular situation I would see 2 possible approaches:
- extend `whenStable` to also handle `done` - no idea if this is feasible, maybe "stable" has a more narrow meaning than that
- await `done` being called here, together with `whenStable` - this would just affect the logic locally which probably is less likely to break some scenarios

**Comment by jennifer-shehane** [comment]
There was some discussion that this may be considered a breaking change, so we may want to change the base branch to 6.0.

**Comment by Andarist** [comment]
I'm fine with waiting for v6. This is not blocking me in any way.

What about the findings from my last 2 comments? What should I do with them?

**Comment by jennifer-shehane** [comment]
Changed base branch to 7.0-release branch

**Review by chrisbreiding — APPROVED** [review]

**Comment by chrisbreiding** [comment]
Thanks for your work on this. We've had some discussions regarding how we want to handle uncaught errors and promise rejections and decided on a path forward to make it all more consistent and improve the experience. This is in line with that, so I'm going to merge it into https://github.com/cypress-io/cypress/pull/14826 and tie everything together there along with your [unhandled rejection PR](https://github.com/cypress-io/cypress/pull/9118). It should all go out with v7.0 in a couple weeks.

**Pull request merged**
