### PR TITLE
Add ignoreTestFiles to configKeys

### LINKED ISSUE #1696: ignoreTestFiles is ignored when passed from cli
### Current behavior:
When invoking cypress with `config ignoreTestFiles=*blob` from the command line, specs that match the blob aren't ignored. For instance, this `npm` command:
```
"cypress:run": "cypress run --config ignoreTestFiles=*.demo.js"
```
Will make a `spec.demo.js` to run, when it should be ignored.

### Desired behavior:
Files that match the `ignoreTestFiles` parameter should be ignored.

### Steps to reproduce:

I set up a test-tiny-repo clone with a demo of the issue. The branch is called `ignore-test-files-cli-issue`. [You can find the repo here](https://github.com/Sergeon/cypress-test-tiny/tree/ignore-test-files-cli-issue).

The readme has all the instructions.

### Versions:
Mac Os: 10.13.4
Cypress: 2.1

### PR DESCRIPTION
**Pull request by brianmcgue**
close #1696 

`ignoreTestFiles` is listed as a config option in the [guide](https://docs.cypress.io/guides/references/configuration.html#Global), 
but is not one of the `configKeys`.

This then causes Cypress to filter out `ignoreTestFiles` from the 
default config when filtering it to just the whitelisted values:
https://github.com/cypress-io/cypress/blob/36760b8abbbf72692810f2dab266a13dd6fdbce7/packages/server/lib/project.coffee#L132

As such, when Cypress attempts to update the config with the plugin 
values, `resolvedObj[key]` will return `undefined` here:
https://github.com/cypress-io/cypress/blob/36760b8abbbf72692810f2dab266a13dd6fdbce7/packages/server/lib/config.coffee#L291

which will result in attempting to set values on `undefined`.

Alternatively, and possibly a good addition to this pull request as it 
stands currently, `setResolvedOn` should only recurse on non-array 
objects.

https://github.com/cypress-io/cypress/blob/36760b8abbbf72692810f2dab266a13dd6fdbce7/packages/server/lib/config.coffee#L288

should become
```javascript
if _isObject(val) && !_.isArray(val)
```

EDIT: I added a commit for array change suggested above since they'll need to be supported as well.

### CODE REVIEW

**Comment by brianmcgue** [comment]
I'm happy to squash commits here if that will help. I can also open an issue and create a new branch to match the suggestions in the **[Pull Requests](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#pull-requests)** section of the **Contributing to Cypress** guide if that would help as well.

**Comment by jennifer-shehane** [comment]
Does this PR fix this issue? https://github.com/cypress-io/cypress/issues/1696

**Comment by brianmcgue** [comment]
Unfortunately, it doesn't seem to solve that issue.

**Comment by brianmcgue** [comment]
Re: #1696, it actually does seem to solve the issue for me, but just not with the setup described in #1696 itself. I'll post more details there.

**Comment by brianmcgue** [comment]
FWIW, I just needed to build my own binary

**Pull request merged**
