### PR TITLE
fix(grep): @cypress/grep types

### LINKED ISSUE #24512: @cypress/grep cannot find module cypress-grep or it's corresponding type declarations
### Current behavior

Support file, Config file, and the tsconfig file installation instructions are incorrect.

Module names and paths are incorrect.

Support file: I am getting a _could not find a declaration file for module @cypress/grep/src/support_ as that's what I have at the moment. Following the readme, the error is _Cannot find module 'cypress-grep'_. Additionally, the function appears to be cypressGrep and not registerCypressGrep. 

Config file registration: `require('@cypress/grep/src/plugin')(config)`

tsconfig.json: the types array addition should be `"@cypress/grep"`

I am probably missing something.

### Desired behavior

I am able to install the package, follow the configuration instructions, grepping specs works.

### Test code to reproduce

n/a

### Cypress Version

10.10.0

### Node version

16.17.1

### Operating System

Windows 10

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by samtsai**
- Closes #24512 

### User facing changelog

Fix `@cypress/grep` types. Fixes #24512 

### Additional details

When migrating `cypress-grep` to `@cypress/grep` some references were missed and with recent changes #24603 additional types were needed.

### Steps to test

Used `yarn link` to test against my local project.

### PR Tasks

- [n/a] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by samtsai** [comment]
cc @jordanpowell88 @emilyrohrbough

**Review by jordanpowell88 — APPROVED** [review]

**Comment by samtsai** [comment]
Whoops, let me clean up the history a bit.

**Comment by samtsai** [comment]
sorry I pushed but don't have permission to re-run checks cc @emilyrohrbough @jordanpowell88

**Comment by emilyrohrbough** [comment]
@jordanpowell88 are there typescript tests in npm/grep? 

@samtsai I think this would also fix #24814

**Comment by jordanpowell88** [comment]
> @jordanpowell88 are there typescript tests in npm/grep?
> 
> @samtsai I think this would also fix #24814

Not currently, My plan is to create a `grep-typescript` project to validate these typescript scenarios

**Review by emilyrohrbough — APPROVED** [review]

**Pull request merged**
