### PR TITLE
Pass projectRoot and configFile to plugins file through config

### LINKED ISSUE #5941: Cypress config object passed to the plugins file should have config filename
Cypress v3.7.0

The plugins file receives resolved config object with properties from `cypress.json` resolved. But the config object has plugins, fixtures, integration paths - yet it does not have the project root or configuration filename. Since we have added `--config-file` option, we should pass it in the config object (or `false` is the user has disabled it)

See https://docs.cypress.io/guides/guides/command-line.html#cypress-run-config-file-lt-config-file-gt

Expected behavior with the following plugins file

```js
module.exports = (on, config) => {
  console.log(config.configFile)
}
```
```
$ cypress run
cypress.json
$ cypress run --config-file false
false
$ cypress run --config-file my-config.json
/resolved/path/to/my-config.json
```

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #5941

### User facing changelog

* The plugins file function's `config` argument now includes `projectRoot` (absolute path to the root of the project) and `configFile` (absolute path to the configuration file)

### Additional details

Documentation PR: https://github.com/cypress-io/cypress-documentation/pull/2534

### How has the user experience changed?

The plugins file config argument now includes `projectRoot` and `configFile`:

```javascript
module.exports = (on, config) => {
  // {
  //  ... other properties ...
  //  configFile: '/Users/me/my-project/cypress.json',
  //  projectRoot: '/Users/me/my-project,
  // }
}
```

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
I opened an issue about throwing/warning when writing to 'readonly' `config` values. https://github.com/cypress-io/cypress/issues/6407 We can consider addressing this in this issue or not.

**Comment by chrisbreiding** [comment]
Working on that now 👍

**Comment by brian-mann** [comment]
Is this ready to merge? I approved.

**Comment by brian-mann** [comment]
conflicts with `README.md`

**Comment by bahmutov** [comment]
Another feature!

**Pull request merged**
