### PR TITLE
fix: also use agent on first preflight request

### LINKED ISSUE #28423: Performance issues to connect to Cypress Dashboard when behind a proxy
### Current behavior

When running Cypress behind a corporate proxy, there is always a 1 minute overhead for each Cypress run when connecting to the Cypress Dashboard.
The problem seems to be the "preflight" request, which first tries to connect to `api-proxy.cypress.io` without the system-wide defined proxy and then after 1 minute, it tries `api.cypress.io` with the correct proxy which then responds immediately.

### Desired behavior

_No response_

### Test code to reproduce

This is a bit harder to reproduce easily. You need a setup where internet access is blocked unless a specific proxy is used, then define this proxy as `http_proxy` and `https_proxy` environment variable and run Cypress.

### Cypress Version

13.5.0

### Node version

v18.17.1

### Operating System

Docker Container (Debian)

### Debug Logs

```shell
cypress:server:cloud:api request to url: POST https://api-proxy.cypress.io/preflight with params: {"body":{"apiUrl":"https://api.cypress.io/","dependencies":{},"errors":[],"projectId":"xxx","ciBuildId":"rbl-test-05","testingType":"e2e","parallel":true},"headers":{"x-route-version":"1","x-cypress-request-attempt":0,"x-os-name":"linux","x-cypress-version":"13.5.0"}} and token: undefined +0ms

--------- Lots of process_profiler entries

cypress:server:cloud:api request to url: POST https://api.cypress.io/preflight with params: {"body":{"apiUrl":"https://api.cypress.io/","dependencies":{},"errors":[],"projectId":"xxx","ciBuildId":"rbl-test-05","testingType":"e2e","parallel":true},"headers":{"x-route-version":"1","x-cypress-request-attempt":0,"x-os-name":"linux","x-cypress-version":"13.5.0"}} and token: undefined +1m
cypress:network:agent addRequest called { isHttps: true, href: 'https://api.cypress.io/preflight' } +0ms
cypress:network:agent got family { family: undefined, href: 'https://api.cypress.io/preflight' } +1ms
cypress:network:agent Creating proxied socket for https://api.cypress.io/preflight through http://myproxy:3128 +3ms
cypress:network:connect successfully connected { opts: { port: 3128, host: 'myproxy', useTls: false, getDelayMsForRetry: [Function (anonymous)] }, iteration: 0 } +0ms
cypress:network:agent Proxy socket for https://api.cypress.io/preflight established +9ms
cypress:server:cloud:api response { apiUrl: 'https://api.cypress.io/', encrypt: false } +415ms
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by Roemer**
Closes https://github.com/cypress-io/cypress/issues/28423

We use a proxy in order to communicate with the "outside world". Now the preflight first tries a request to `api-proxy.cypress.io` but with the `agent` explicitly set to `null`. When this request fails, it retries with `api.cypress.io` and this time with the `agent` set.
I suspect that the `agent` has the proxy info and therefore, the first request does not use the proxy and depending on the local setup, might wait up to 1 minute before aborting and retrying with the proxy. This leads to +1 minute to every cypress run.

### CODE REVIEW

**Comment by Roemer** [comment]
This is extremely limiting us, as we run Cypress for a lot of projects and all of them now have 1 minute additional time for each project and I did not find a way to decrease the `timeout` from `SIXTY_SECONDS` with config or environment variables.
As the only difference between the call that works (`makeReq({ baseUrl: apiUrl, agent })`) and the one that does not work (`makeReq({ baseUrl: preflightBaseProxy, agent: null })`) is the agent, I am fairly sure that this is the issue.
Is there anything else needed to have its PR checked?

**Review by mirobo — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
@Roemer Thanks for opening a PR. We'll need a test to confirm the behavior before merging and we'll take a look to review.

**Comment by Roemer** [comment]
This PR is still relevant.

**Comment by jennifer-shehane** [comment]
@Roemer Oh boy, this definitely got lost. Sorry. We'll need a test to verify this behavior in order to accept the PR. Could you write a test to verify and prevent regressions?

**Comment by Roemer** [comment]
Pity the PR is closed as the bug still persists. As mentioned already, it is pretty much impossible to create a test as this is dependent on a specific (corporate) network setup. Having a networking-aware developer look at it should make it fairly obvious that it is currently a bug.

**Pull request closed without merging**
