### PR TITLE
chore: stabilize Percy snapshots of the launchpad

### PR DESCRIPTION
**Pull request by astone123**
### Additional details

After [we got rid of the code that hid Cypress version number from Percy snapshots](https://github.com/cypress-io/cypress/pull/26105), some other snapshots became flakey because we're not asserting that the version number has loaded into the header before we take it.

This PR adds assertions to some of the problematic Percy snapshots to stop them from flaking.

Examples of flake:
https://percy.io/cypress-io/cypress/builds/26126218/changed/1456121409?browser=chrome&browser_ids=34&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=800&widths=450%2C800

https://percy.io/cypress-io/cypress/builds/26219319/changed/1460471097?browser=chrome&browser_ids=34&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=800&widths=616%2C650%2C800%2C900%2C1200%2C2000

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by warrensplayer — COMMENTED** [review]
@astone123 Two things... 

Will this fix just cause it to flake every time the version number changes?  It looks like builds on `develop` just auto-approve the Percy snapshots, so will that alleviate any issues? 

Second, will be just continue to have problems on any page where we take a Percy snapshot that displays the version in the header if we do not add an assertion for it?  I don't think the solution should be adding assertions to tests that do not care about that part of the page.  Can this check be embedded in the `cy.percySnapshot()` command in the `e2e.ts` file if we know we are on a page that should show it?

**Comment by astone123** [comment]
@warrensplayer

1. We mock the version that comes back in the tests to be the version from our root package.json file, so the only time that the version will change and cause the snapshot to change is on the PR where we bump the version, which is correct.
2. Yes, I think this will be an issue with any snapshot that is on the launchpad, but I haven't really seen any of those flake except for these ones 🤔 it would be ideal to embed the check in `cy.percySnapshot`, I'll have to look into how we'd do that

**Comment by warrensplayer** [comment]
> 2. Yes, I think this will be an issue with any snapshot that is on the launchpad, but I haven't really seen any of those flake except for these ones 🤔 it would be ideal to embed the check in `cy.percySnapshot`, I'll have to look into how we'd do that

@astone123 If the desire is just to get a quick fix out for this flake for now, then I think this would be fine with comments above each of these new assertions stating that they are there just to address Percy flake and then filing a separate issue to look at a more wholistic solution to this problem.

**Comment by lmiller1990** [comment]
@warrensplayer I pushed a comment to that meaning, assuming I interpreted your recommendation correctly. Can you take another look?
@astone123 I will help get this one over the line, since you are on firewatch.

**Review by lmiller1990 — APPROVED** [review]

**Comment by warrensplayer** [comment]
@lmiller1990 @astone123 I just noticed there is a `before` option to the `installCustomPercyCommand` option.  You an see its use here: https://github.com/cypress-io/cypress/blob/develop/packages/reporter/cypress/support/e2e.ts

Instead of having to put those assertions in the test themselves, perhaps adding a before case when installing the Percy command would fix all current and future launchpad issues surrounding these snapshots.

**Comment by astone123** [comment]
@warrensplayer this is helpful, the issue is knowing which tests to add that assertion to. If we add it to a page where the version is **not** supposed to be displayed in the header, then the test will time out 🤔

**Review by warrensplayer — APPROVED** [review]
@astone123 Not going to block this on any additional updates.

I do think we should look for a more robust fix to this scenario going forward.  Any additional `percySnapshot` calls in the launchpad would be susceptible to this type of flake.  I do think as assertion in the `before` option in the `installCustomPercySnapshot` would probably work, but it might have to be wrapped in a conditional check to see if the header was being shown, etc.

**Comment by warrensplayer** [comment]
@astone123 Another option to look at in the future would be a pattern like here:

https://github.com/cypress-io/cypress/blob/1d04a3dc505b8417988e7881cea222bb8acfa22e/packages/app/cypress/e2e/runner/support/snapshot-reporter.ts#L2-L26

There could be a custom command in the launchpad that takes snapshots and hides the version for the snapshots.

**Comment by marktnoonan** [comment]
I actually think it's really safe to assume we always expect a version number in the header. I can't think of a page in an end-to-end test where that doesn't apply - the only page would be the Spec Runner in the app, but we have no percy snapshots in e2e for the app anyway. There's no design for that header that doesn't show the version of Cypress.

I'd suggest we do this in the custom percy stuff & then only think about this again if there is a case where there's not supposed to be a version in the header.

**Comment by warrensplayer** [comment]
FYI, here is the same flake in another test: https://percy.io/cypress-io/cypress/builds/26486640/changed/1474488490?browser=chrome&browser_ids=38&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=800&widths=616%2C650%2C800%2C1200%2C2000

**Comment by lmiller1990** [comment]
I like @warrensplayer idea - just replace the version with `vXX.XX` or something deterministic.

Happy to merge this, happy to not - will leave this decision to @astone123.

**Comment by astone123** [comment]
Replacing the version number with x.x.x won't fix this issue though, the version number is already deterministic because we mock it, but it doesn't always appear on screen before the snapshot is taken. I'll take a look at this on Monday

**Pull request closed without merging**
