### PR TITLE
[WIP] updated the tests for #6431

### LINKED ISSUE #6431: .its command with compound properties failing TypeScript check
Cypress v3, v4

Our typescript definition for `cy.its` command "understands" the properties of the subject, thus it can do

```js
cy.wrap({ foo: 1 }).its('foo') // yup, subject has property "foo"
```

but it does not understand nested (compound) properties that Lodash `_.get` can do and we use under the hood

```js
cy.wrap({
  foo: {
    bar: 1
  }
}).its('foo.bar') // oops, TypeScript freaks out, "foo.bar" is invalid
```

Maybe someone can look at Lodash and its TypeScript definition for `_.get` to see if they have solved this problem and bring the solution?

### PR DESCRIPTION
**Pull request by arshmakker**
- Closes #6431

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by arshmakker** [comment]
hi @eventualbuddha 
while linting am getting an error: 
` error  [stdin]:119:7: error: unexpected + 
"{" + str.join(", ") + "}"`

in file /home/person/cypress/packages/driver/src/cypress/utils.coffee

is it expected, I did not change anything in the file. It was last modified 3 years ago.. so asking.

Regards
Arsh

**Comment by eventualbuddha** [comment]
I have no idea why you're getting that error. I do not work on this project. Good luck!

**Comment by arshmakker** [comment]
Thanks @eventualbuddha 
> I have no idea why you're getting that error. I do not work on this project. Good luck!
@lorennorman 
Could you help please?

**Comment by jennifer-shehane** [comment]
@arshmakker Do you still have time to address the changes requested in this PR? We will have to close this PR due to inactivity otherwise.

**Comment by arshmakker** [comment]
Hi @jennifer-shehane ,

I was not able work on it, since I was getting an linting error:
error [stdin]:119:7: error: unexpected + "{" + str.join(", ") + "}"
and no one was able to help out :(

I can still work but i need some help cause cypress is huge 👍 
Regards
Arsh

**Pull request closed without merging**
