### PR TITLE
Update https-proxy-agent to 3.0.0

### PR DESCRIPTION
**Pull request by flotwig**
### User facing changelog

Not user facing

### Additional details

The fixes we need for our tests to run have been merged:

https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/3.0.0

This dependency doesn't need to rely on a git hash now that the changes have been published to NPM.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
We actually have separate guidelines for dependency upgrades - but they're only triggered for renovatebot triggered PRs. 

Below are some guidelines Cypress uses when reviewing dependency updates. 

## Dependency Update Instructions

- Read through the entire changelog of the dependency's changes. If a changelog is not available, check every commit made to the dependency. **NOTE** - do not rely on semver to indicate breaking changes - every product does not follow this standard.
- Add a PR review comment noting any relevant changes in the dependency. 
- If any of the below checklist is not complete, select 'Request changes', otherwise 'Approve'.

## Dependency Updates Checklist

- [ ] If there are breaking changes, have the proper updates been made to accommodate those? 
- [ ] Does the dependency still support the version of Node that the package requires?
- [ ] The PR been tagged with a release in ZenHub
- [ ] If the PR itself will cause a breaking change for Cypress users, the PR has been labeled as `type: breaking change`

**Comment by flotwig** [comment]
@jennifer-shehane Okay, should be good to go now - should this be tagged with a release since it's not user-facing?

**Comment by jennifer-shehane** [comment]
@flotwig Yah I tag every dep update PR - devDeps and deps just to keep a better internal log for later if it does break something.

**Comment by Bkucera** [comment]
this electron driver test failure seems legitimate https://dashboard.cypress.io/#/projects/ypt4pf/runs/7254/failures/44af1fc6-ecb0-438b-ba31-096659ce7222

**Comment by flotwig** [comment]
> @flotwig this electron driver test failure seems legitimate [dashboard.cypress.io/#/projects/ypt4pf/runs/7254/failures/44af1fc6-ecb0-438b-ba31-096659ce7222](https://dashboard.cypress.io/#/projects/ypt4pf/runs/7254/failures/44af1fc6-ecb0-438b-ba31-096659ce7222)

Shouldn't be possible, this dependency is only used in the server integration tests, it couldn't leak over to the driver tests.

**Comment by Bkucera** [comment]
@flotwig agreed, I'll rerun ci

**Pull request merged**
