### PR TITLE
[WIP] Issue 1281 warning on no write

### LINKED ISSUE #1281: Cypress should not require write access of root folder
Why do we check if the root of the project is writeable? 👇 i.e. the ` fs.accessAsync(projectRoot, fs.W_OK) `

https://github.com/cypress-io/cypress/blob/2b2b6d99a9f1bf232d9c7396b25390913d5f2b18/packages/server/lib/util/settings.coffee#L76-L93

cc:/ @zacblazic

### PR DESCRIPTION
**Pull request by Toxicable**
- Closes #1281

### User facing changelog

Cypress no longer requires write access to the projectRoot, it instead will display a warning.

### Additional details

This allows for cypress inetegration with other tools such as Bazel

### How has the user experience changed?

It allows Cypress to be run in sandboxed or otherwise readonly fs environments

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by Toxicable** [comment]
@jennifer-shehane Hey, thanks for the reply, I've tried getting the tests running locally both on windows and ubuntu but both times im getting a whole bunch of unit testing failures from path mis-matches to different shaped objects.

As for writing the unit test for this specific case itself. All that needs to be done is a file system needs to be created in readonly mode, then `cypress` needs to execute with the projectRoot pointing to this readonly file system. Finally asserting that this warning is displayed and that it can continue executing.

Are there any existing tests similar to this that I could use an example for how to set this up?

**Comment by jennifer-shehane** [comment]
@Toxicable you may need to follow these instructions for contributing in Windows. https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started

Although I'm not sure why things would fail in Ubuntu specifically.

Normally we have e2e tests with snapshots for error messages from server package. For example, this is a test of the error message above the one you added https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/2_cdp_spec.ts#L9:L9

**Comment by Toxicable** [comment]
@jennifer-shehane I added a test but struggling to get it  to working as expected.
As you can see by the snapshot it's throwing the error that it cant find my spec files.
I don't understand why it cant find them since the `projectDir` path definately has the  correct file.
If I remove all the read only `chmodSync` calls it still cant find the spec file.
Does `project` from the configuration object not set the dir that it should run in this testing suite?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this PR due to inactivity. Please open a new PR addressing the original issue and any requested changes.

**Comment by mrmeku** [comment]
@@jennifer-shehane I'd like to take this PR up and make the additional changes you would need for it to get merged. If you wouldn't mind, could you give some guidance on how to resolve the issue of Cypress not being able to detect spec files that @Toxicable was struggling with?

**Pull request closed without merging**
