### PR TITLE
chore: put types condition first in the syncing script

### PR DESCRIPTION
**Pull request by Andarist**
Follow up to https://github.com/cypress-io/cypress/pull/26630 , fixes what @MikeMcC399 reported in the comment here: https://github.com/cypress-io/cypress/pull/26630#issuecomment-1545594922

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Andarist 

I am still getting a diff, however this appears to be due to a typo.

Have you actually tested this yourself?

```
diff --git a/cli/package.json b/cli/package.json
index e0d0a3303f..f9c2d09f14 100644
--- a/cli/package.json
+++ b/cli/package.json
@@ -160,7 +160,7 @@
     "./svelte": {
       "types": "./svelte/dist/index.d.ts",
       "import": "./svelte/dist/cypress-svelte.esm-bundler.js",
-      "require": "./svelte/dist/cypress-selte.cjs.js"
+      "require": "./svelte/dist/cypress-svelte.cjs.js"
     }
   },
   "workspaces": {

```

**Comment by MikeMcC399** [comment]
- The typo `./svelte/dist/cypress-selte.cjs.js` was introduced by https://github.com/cypress-io/cypress/pull/26630

**Comment by Andarist** [comment]
@MikeMcC399 pushed out a fix for this typo, good catch

> Have you actually tested this yourself?

Yeah, perhaps not to the full extent. When I located what was reordering those keys I kept running the build script in only one of the directories so I missed the typo in another one.

**Review by MikeMcC399 — APPROVED** [review]
After executing

```bash
yarn
git status
```

I am no longer seeing any `git diff` generated.

**Review by chrisbreiding — APPROVED** [review]

**Comment by chrisbreiding** [comment]
Thanks for the fix, @Andarist!

**Review by AtofStryker — APPROVED** [review]

**Pull request merged**
