### PR TITLE
fix: Make querystrings consistent

### LINKED ISSUE #19407: `cy.request()`, `cy.visit()` and `cy.intercept()` query strings are inconsistent
### Current behavior

The query string generated from the query search options of `cy.request()` and `cy.visit()` are inconsistent.

`cy.request()` accepts `qs` option to generate query parameters to append to the url of the http request. Under the hood, the http request is passed to `@cypress/request` which uses the `qs` library by default to stringify & parse the qs object. `@cypress/request` does accept additional qs parameters to toggle the use of the [`qs`](https://www.npmjs.com/package/qs) library and [`query-string`](https://www.npmjs.com/package/query-string) library (provided by Node.JS) as well as takes options for the stringification/parsing configuration.

`cy.visit()` also accepts a `qs` option to generate query parameters to append to the new browser url request. This command is using the `url-parse` module, which uses `[querystringify](https://www.npmjs.com/package/querystringify)` stringify & parse the qs object.

With different libraries are being used, the query parameters are inconsistent, causing unexpected behavior for consumers. Additional because of the different library that are in use, we cannot provide additional qs configuraiton options at this time without the options diverging for `cy.request()` & `cy.visit()`. 

### Desired behavior

The query string generated from the query search options of `cy.request()` and `cy.visit()` are the same. 

_Nice to have:_ be able to provide qs configuration options once these align.

### Test code to reproduce

```js
  it.only('queries should match', () => {
    let visitURL
    let requestURL

    cy.intercept('https://jsonplaceholder.cypress.io/comments*', {
      statusCode: 200,
      headers: {
        'content-type': 'text/html',
      },
    }).as('request')

    cy.visit({
      url: 'https://jsonplaceholder.cypress.io/comments',
      qs: {
        postId: [1, 2],
        id: 3,
      },
    })

    cy.wait('@request').then(({ request }) => {
      visitURL = request.url
    }).then(() => {
      cy.request({
        url: 'https://jsonplaceholder.cypress.io/comments',
        qs: {
          postId: ['1', '2'],
          id: 3,
        },
      }).then((resp) => {
        requestURL = resp.allRequestResponses[0]['Request URL']
      })
    }).then(() => {
      expect(visitURL).to.eq(requestURL)
    })
  })
```
Screen Shot 2021-12-16 at 5 22 31 PM

### Cypress Version

9.1.1+

### Other

While investigating https://github.com/cypress-io/cypress/issues/17921, this is was discovered.

### PR DESCRIPTION
**Pull request by sainthkh**
- Partially addresses #19407

### User facing changelog

`cy.visit()` and `cy.request` generate the same querystring. 

### Additional details
- Why was this change necessary? => Given the same `qs` argument, `cy.visit()` and `cy.request()` created different querystrings. 
- What is affected by this change? => N/A
- Any implementation details to explain? => I used `mergeUrlWithParams` function used in `cy.visit()` to generate querystring in `cy.request`. I decided it this way because cy.visit() behavior is consistent with the default [`URLSearchParams` class](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

### How has the user experience changed?

**Before:**

```js
cy.visit({ url: 'https://example.com', qs: { a: [1, 2], b: 3 } }) // => https://example.com?a=1%2C2&b=3
cy.request({ url: 'https://example.com', qs: { a: [1, 2], b: 3 } }) // => https://example.com?a%5B0%5D=1&a%5B1%5D=2&b=3
```

**After:**

```js
cy.visit({ url: 'https://example.com', qs: { a: [1, 2], b: 3 } }) 
cy.request({ url: 'https://example.com', qs: { a: [1, 2], b: 3 } })
// Both => https://example.com?a=1%2C2&b=3
```

### Why this PR doesn't close the issue?

AFAIK, there are 3 APIs in Cypress that use query string object. Before this PR, they all used the different libraries. 

* `cy.visit`: [`url-parse`](https://www.npmjs.com/package/url-parse), which uses [`querystringify`](https://www.npmjs.com/package/querystringify)
* `cy.request`: [`qs`](https://www.npmjs.com/package/qs)
* `cy.intercept`: [default `URLSearchParams` class](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

This is quite a mess because the standard library(`URL` and `URLSearchParams` classes) came out really late with Chrome 49 in 2016 while the libraries above are created in 2011(`qs`, nodejs default `querystring`), 2014(`querystringify`, `url-parse`).

And Cypress was created before 2016, it's natural that those libraries are used.

This PR deprecates `qs` in `cy.request`, and uses `url-parse` for both `cy.visit` and `cy.request`. It means `cy.intercept` still uses `URLSearchParams`.

I chose this way because there are 2 ways to merge parameters in `URLSearchParams`: `append` and `set`. I couldn't be sure mimicking current behavior is right.

Currently, when you provide parameters in both `url` and `qs` and names are conflicted, values in `qs` are used like below. 

```js
cy.visit({ url: '/?a=123&b=foo', qs: { a: 456 } }) // => /?a=456&b=foo
```

(It's happening because we simply merge objects like below:)

https://github.com/cypress-io/cypress/blob/0143e1338869f54809f9dfa97f21131728e5be32/packages/driver/src/cypress/location.ts#L160-L165

But when we use `URLSearchParams`, we can preserve both of them with `append` method like below:

```js
const params = new URLSearchParams({ a: 123, b: 'foo' })
params.append('a', 456)
console.log(params.toString()) // a=123&b=foo&a=456
```

I think it is the better behavior. So, I decided to stop this PR here and seek your opinions about this. 

### PR Tasks
- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@sainthkh This looks like this change would be a breaking change, correct?

**Comment by sainthkh** [comment]
@jennifer-shehane It's somewhere between. 

If we define `qs` behavior is correct, `cy.request`'s behavior is also right, but different. In this case, it's a breaking change. 

If we define `qsq behavior is wrong because it doesn't match `URLSearchParams`'s behavior, then `cy.request`'s behavior is also wrong. In this case, it's a bug.

**Comment by jennifer-shehane** [comment]
@sainthkh Thanks for the clarification. I believe we'll need to sync on how we plan to proceed. Right now we don't have as much time to dedicate to review of this, so please be patient.

**Comment by BlueWinds** [comment]
I like the change - the consistency is valuable, but do think it's breaking. Currently proposing to the team that we merge this when we're ready to release another breaking change (but not cause 11.x immediately for this purpose alone).

**Review by BlueWinds — APPROVED** [review]
We have a merge conflict, but otherwise looks good to me, with tests covering the changes.

**Review by rachelruderman — APPROVED** [review]
I ❤️ consistency, thank you for the contribution and very detailed description!

**Pull request merged**
