### PR TITLE
fix: inline element with visibile child now is considered visible

### LINKED ISSUE #6183: Inline, zero-dimension element: erroneous visibility determination
# Current behavior:
[This](https://github.com/badeball/cypress-reproducible-issues/tree/master/zero-dimension-hover) example illustrates an element with `offsetWidth` and `offsetHeight` of zero, but is still interactable in actuality.

For reference, Firefox does not report these values to be zero, which might be of interest in regards to expanding browser support (ie. maybe not good to rely on it as it's not consistent across).

### Desired behavior:
For the element not to be reported as invisible.

### Test code to reproduce
https://github.com/badeball/cypress-reproducible-issues/tree/master/zero-dimension-hover

### Versions
Cypress v3.8.2, Arch Linux, Chrome 79.

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-85) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #6183 

### User facing changelog

Fixes an issue where a `display: inline` parent would be considered hidden if it had a visible child who had `display: block`

### Additional details

~I do not think that implementing this fix is an appropriate course of action, see this comment in the original issue: https://github.com/cypress-io/cypress/issues/6183#issuecomment-666502078.~ Updated comment: https://github.com/cypress-io/cypress/pull/8130#issuecomment-673131654

I would like to have a discussion around this before we decide to merge these changes.

### How has the user experience changed?

Given the following test case (modified here so may not work exactly, but shows the general idea, actual test case can be seen in diff):

```javascript
const element = `
<div>
  <span>
    <label style="display: block;">display: block</label>
  </span>
</div>
`

it('parent is visible if display inline and child has display block', function () {
  expect(element.find('span')).to.be.visible
  expect(element.find('span')).to.not.be.hidden
})
```

Before:

Screen Shot 2020-07-30 at 11 51 56 AM

After:

Screen Shot 2020-07-30 at 11 51 15 AM

Given the original test case from the issue:

```html
<html>
<body>
  <p>
    <span onmouseover="window.hover.style.display='block'" onmouseout="window.hover.style.display='none'">
      <label style="display: block">Hover me!</label>
    </span>
  </p>
  <p id="hover" style="display: none">
    Hovering!
  </p>
</body>
</html>
```

```javascript
it("should work", () => {
  cy.visit("index.html")
  cy.get("span").trigger("mouseover")
})
```

Before:

After:

Screen Shot 2020-07-30 at 12 10 19 PM

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Commented in issue: https://github.com/cypress-io/cypress/issues/6183#issuecomment-666981282 Yah, maybe another short discussion similar to opacity would be good.

**Comment by panzarino** [comment]
@jennifer-shehane I think that we should go ahead with this fix. Despite the concern that this goes against the DOM structure in Chrome, it does not change any behavior in Firefox. Therefore, I think we should implement the change in order to standardize our tests across Chrome and Firefox, since it is less important that our visibility algorithm is technically correct regarding an edge case for an [ambiguous W3 specification](https://www.w3.org/TR/2009/CR-CSS2-20090908/visuren.html#anonymous-block-level) and more important that our tests are consistent between browsers.

**Comment by jennifer-shehane** [comment]
Ok, I had a discussion task opened TR-232, but if you don't think that's necessary then I'll re-review.

**Comment by panzarino** [comment]
@jennifer-shehane I would be open to having a discussion, but when I mentioned it in our Slack it did not get much interest. I can ask again on <onday and see if there is more interest.

**Comment by panzarino** [comment]
@jennifer-shehane I would be open to having a discussion, but when I mentioned it in our Slack it did not get much interest. I can ask again on <onday and see if there is more interest.

**Review by jennifer-shehane — APPROVED** [review]

**Pull request merged**
