### PR TITLE
feat: client certificate selector option during e2e tests

### LINKED ISSUE #27302: Override clientCertificates configuration
### What would you like?

The Cypress configuration for clientCertificates allows to configure one certificate per URL. This configuration is currently readonly and cannot be overridden in the tests. I would like to override the clientCertificates for some tests.

```ts
it('test as admin', () => {
  Cypress.config({
    clientCertificates: [
      {
        url: 'https://localhost:8443',
        certs: [
          {
            cert: './cypress/cert/admin.crt',
            key: './cypress/cert/admin.key',
          },
        ],
      }
    ]
  });
  cy.visit('/');
})

it('test as user', () => {
  Cypress.config({
    clientCertificates: [
      {
        url: 'https://localhost:8443',
        certs: [
          {
            cert: './cypress/cert/user.crt',
            key: './cypress/cert/user.key',
          },
        ],
      }
    ]
  });
  cy.visit('/');
})
```

currently results in  
`CypressError: Cypress.config() can never override clientCertificates because it is a read-only configuration option.`

### Why is this needed?

Users authenticate with their client certificates and we need to test the behaviour for users with different roles.

### Other

An Alternative could be to allow the configuration of multiple clientCertificates for the same URL and then allow to select one when visiting a site.

### PR DESCRIPTION
**Pull request by alienkarma**
- Closes #27302, #20117 

### Additional details
Added an extra certificate filter when certificate is chosen for requests based on groups.
This can be used to tackle the problem of testing multiple certificate cases for the same URL.
Needs review and feedback.

### Implementation
Certificates will be marked with a group tag as below in config:-
``` typescript
clientCertificates: [
    {
      url: 'https://a.host.com',
      ca: ['certs/user.pem'],
      certs: [
        {
          group: "user",
          cert: 'certs/user.pem',
          key: 'certs/user.key',
        },
      ],
    },
    {
      url: 'https://a.host.com',
      ca: ['certs/admin.pem'],
      certs: [
        {
          group: "admin",
          cert: 'certs/admin.pem',
          key: 'certs/admin.key',
        },
      ],
    },
]
```
And then intended to be swapped using `cy.chooseCert(group_name)` during tests. (Null or empty can be provided for resetting the certificate selection)

### Steps to test
Need help implementing testing for this

### How has the user experience changed?
Check implementation above

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@alienkarma We would need tests to cover this new behavior in order to accept this PR. Can you add those?

**Comment by alienkarma** [comment]
> @alienkarma We would need tests to cover this new behavior in order to accept this PR. Can you add those?

Hi
Yes I initially needed help on this PR to proceed. But now I have a rough idea on how to go about it.
I will convert this PR into a draft until I am ready.
Thank you

**Comment by alienkarma** [comment]
Hi @jennifer-shehane 
I added the tests, fixed the types and few bugs
Let me know if I need to do anything else or if you have any other feedback
(I can also work on the cypress documentation once this gets checked and released)
Thank you

**Comment by alienkarma** [comment]
Added the relevant docs - [https://github.com/cypress-io/cypress-documentation/pull/5922](https://github.com/cypress-io/cypress-documentation/pull/5922)

**Comment by alienkarma** [comment]
I think the `linux-x64-contributor` workflow check has hung and cannot proceed.

**Comment by alienkarma** [comment]
Hi @jennifer-shehane
Just pinging that this PR is ready but I think it is stuck on a workflow.
If anything is needed let me know.
Thanks

**Comment by alienkarma** [comment]
Hi @jennifer-shehane 
PR is ready for review and is pending workflow approval.
It is up to date with `develop` branch.

**Comment by jennifer-shehane** [comment]
@alienkarma Let me run the tests and see if someone can pick up review in this sprint.

**Comment by jennifer-shehane** [comment]
@alienkarma Hey, we appreciate the time you put into this PR. The team did take a look over the intentions and implementation of the PR. There are a few implementation details that differ from our desired goal for this functionality. 

- Since there is existing config for the client certificates, it would be best to open up the config to be writable (instead of read only today) instead of introducing an entirely new command.
- To truly change a client certificate in the browser requires an entire restart of the browser. This is why the config is not writable today (those config values require a restart of the browser to take affect). So for this to actually take affect in the browser, we would need to code a mechanism to restart the browser midway in a test once we recognize this config is being overwritten. 

Coding these changes would be quite a rewrite and quite complex to have working across browsers. Right now we don't have the capacity to focus on this rewrite and would recommend closing this PR at this time. Sorry for the lack of communications upfront - we do appreciate your shedding more light on this problem to our team.

**Comment by alienkarma** [comment]
Hi @jennifer-shehane 
Thank you for the feedback. I am aware that changing certificates for browser midway creates other challenges, and thus this implementation was a way to introduce a solution to the problem.
I appreciate your time and consideration for this PR.

**Pull request closed without merging**
