### PR TITLE
misc: Add missing properties to Cypress.spec type

### LINKED ISSUE #27835: Cypress.spec missing properties
### Current behavior

`Cypress.spec` has a few properties `absolute, name, specFileExtension, fileExtension, relative`.

### Desired behavior

when using cy.log with Cypress.spec I get more properties than the Cypress types gives, these are the extra properties that get logged

`id, spectype, baseName, fileName`

can we please add those to the types so we can use them ?

### Test code to reproduce

`cy.log(Cypress.spec)`

### Cypress Version

13.2.0

### Node version

16

### Operating System

macOS Ventura 13.4

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by jonhermansen**
- Closes https://github.com/cypress-io/cypress/issues/27835

### Additional details
- Why was this change necessary? _Exposes missing Cypress.spec type information in your IDE_
- What is affected by this change? _This should have no effect on the application, purely a type change_
- Any implementation details to explain? _Simply added the missing fields to where the Spec type is defined_

### Steps to test
I'm not able to compile the entire project locally at the moment, but in a sample project, changing the type information was enough to see these fields now can be auto-completed in an IDE.

### How has the user experience changed?
In IDE, additional type information should be displayed:
2023-10-08T17:47:32,840821522+07:00

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@jonhermansen 

Maybe it would be a good time to update the comments here? The examples are from legacy Cypress `9.7.0` and earlier.

"config_passing_spec.js" => "config_passing_spec.cy.js"

and the default directory would be
"cypress/integration" => "cypress/e2e"

etc.

**Comment by jennifer-shehane** [comment]
@jonhermansen Any plans to pick this PR back up? It's in draft state

**Comment by jonhermansen** [comment]
@jennifer-shehane I just got the PR into a buildable state. I believe that I have changed the correct type definition, but it's possible that other types need modification as well. Can someone knowledgeable about Cypress types take a quick look? Thanks.

**Comment by jonhermansen** [comment]
> @jonhermansen
> 
> Maybe it would be a good time to update the comments here? The examples are from legacy Cypress `9.7.0` and earlier.
> 
> "config_passing_spec.js" => "config_passing_spec.cy.js"
> 
> and the default directory would be "cypress/integration" => "cypress/e2e"
> 
> etc.

Thank you for the suggestions @MikeMcC399, I've incorporated them.

**Comment by jonhermansen** [comment]
I'm not sure why CI hasn't run. The Snyk failures don't appear to have anything to do with my changes.

**Comment by maximegheraille** [comment]
Hi, will this ever be finished ? 😄

**Review by chrisbreiding — APPROVED** [review]
Thanks for the contribution! And sorry for the delay in reviewing this.

**Review by AtofStryker — APPROVED** [review]

**Pull request merged**
