### PR TITLE
Remove malfunctioning ability to stop test with keyboard shortcut while paused 

### LINKED ISSUE #6867: Using the [S] shortcut during a paused state produces some strange behavior
### Current behavior:

When `cy.pause()` is called the user is unable to press the stop button since it's not found in the toolbar in this state, so in order to stop the test, they must click the continue button to resume the test before being able to press the stop button:

a

However, if you use the stop shortcut (`S`), the test will stop and the reset button will show up in the toolbar alongside the continue button and the "PAUSED" badge as if Cypress just entered a limbo state between being paused and stopped:

b

From this point when you click the continue button, the test will remain stopped but the timer will start counting again as if the test is running:

c

### Desired behavior:

I expected the shortcut to affect the toolbar the same way as the GUI button and remove the continue button.

### Test code to reproduce

````js
context('...', () => {
    it('...', () => {
        cy.pause()
        // Press [S] to stop the test here!
        cy.log('Hello world! 🖐')
    })
})
````

### Versions
Cypress 4.2.0 (might work in earlier versions)
Windows 10
Electron (whatever version Cypress has)

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #6867 

Previously, when a test was paused and the 'S' button was pressed, the runner would get stuck somewhere in between a stopped and paused state. This prevents the keyboard shortcut from having any effect while paused.

### User facing changelog

Fixes an issue where using a keyboard shortcut to stop a test while paused would break the test

### How has the user experience changed?

When a test is paused, the UI looks as follows:

Previously, when 'S' was pressed at this stage, the test would get stuck between being paused and stopped, with malfunctioning buttons:

Now, when pressing 'S' nothing will happen.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by Bkucera** [comment]
what do you think about making the button a toggle between start/stop

**Review by kuceb — COMMENTED** [review]
what do you think about making the key a toggle between start/stop

**Comment by panzarino** [comment]
@Bkucera That's definitely viable as well, I'll go ahead and update the changes to implement that

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Having [S] as the keyboard shortcut for 'Resume' seems weird. I was kind of expecting it to 'stop' the run since it's `[S]`, but then the tests just finished? 

I feel like the keyboard shortcut for 'Resume' should be `[R]`, this shouldn't conflict when the 'Run all tests' since this key only appears when the tests are finishes executing.

Also the docs need to be updated here for this change: https://docs.cypress.io/guides/core-concepts/test-runner.html#Keyboard-Shortcuts

**Comment by Bkucera** [comment]
@jennifer-shehane oh no...let's not make the hotkeys overlap when we dont need to. If you want an mnemonic for `S` lets call it "Stop/Start", having `R` be both "resume" and "rerun tests" is really confusing to me

**Comment by jennifer-shehane** [comment]
@Bkucera But the button says Resume, so the combination of it saying `Resume [S]` is super weird, especially after I just clicked `[S]` to Stop the tests. 

I guess you could change the button text to say `Start [S]`, but I think the original intent was to mimic debugger tools which say 'Resume script execution'.

**Comment by Bkucera** [comment]
I vote we keep it `Resume [S]` since it's way more typical for the pause button to be a toggle pause/resume. I think that's more important than the mnemonic.

**Comment by jennifer-shehane** [comment]
@brian-mann said to do `[E]` for Resume. 😆 Or maybe a spacebar since that's typical for resume / pause.

**Comment by panzarino** [comment]
I agree that it might make most sense to use a shortcut that isn't used anywhere else. I'd be happy to update the PR once an agreement is reached.

**Comment by Bkucera** [comment]
@panzarino I would revert back to the original fix preventing the crash and we can merge this :smile:

**Review by kuceb — APPROVED** [review]
image

**Pull request merged**
