### PR TITLE
chore: Included markdown-link-check

### LINKED ISSUE #6420: Automate checking broken links in our Markdown files
In #6373 @CypressCecelia has noted that several links are broken in the contributing guide markdown. We need to automatically check for broken links on CI

Here is a good tool to do this: https://github.com/tcort/markdown-link-check

Here is how it finds those broken links

Screen Shot 2020-02-11 at 3 03 18 PM

Complication: some of our urls are internal links to private repos, so we need to handle that somehow

```
ERROR: 4 dead links found!
[✖] https://circleci.com/gh/cypress-io/cypress-on → Status: 404
[✖] https://github.com/cypress-io/cypress-on → Status: 404
[✖] https://circleci.com/gh/cypress-io/docsearch-scraper → Status: 404
[✖] https://github.com/cypress-io/docsearch-scraper → Status: 404
```

Second complication

```
$ npx markdown-link-check ./README.md --quiet
npx: installed 66 in 3.692s

FILE: ./README.md
[✖] /LICENSE

14 links checked.

ERROR: 1 dead links found!
[✖] /LICENSE → Status: 400
```

where we used the following in Markdown

```
[MIT license](/LICENSE)
```

### PR DESCRIPTION
**Pull request by elistone**
- Closes #6420

### User facing changelog
Running markdown link validation on commits

### PR Tasks

- [ ] Have tests been added/updated?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@elistone I see this PR is still in a Draft state, are you ready for review or have time to continue this PR?

**Comment by elistone** [comment]
@jennifer-shehane It is still in draft as I was awaiting feedback on #6420 about where to have this run automatically.

**Comment by jennifer-shehane** [comment]
@elistone Yes, the circle.yml is where we would add this job.

**Comment by jennifer-shehane** [comment]
Hey @elistone, will you have time to finish this PR? Please close if not.

**Comment by elistone** [comment]
Hi @jennifer-shehane I have added runner into circle.yml

**Comment by jennifer-shehane** [comment]
@elistone Looks like there's an error in the build. 
Screen Shot 2021-05-18 at 4 39 34 PM

**Comment by elistone** [comment]
@jennifer-shehane sorry wrong number of indentation. Have corrected it now.

**Comment by elistone** [comment]
Hi @jennifer-shehane, have now got 41 passing is this okay?

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
The `verify-markdown-link` job is not actually being run anywhere in our CircleCI. 

There are a few problems with adding this check to our CI process which is why I would suggest removing it from our build requirements. 

1. It takes over 2 mins to run. This is too much time to delay a release for something that is not critical to our product. 
2. The check doesn't actually work. It returns many links as dead which are actually working links. The majority are GitHub links returning 429 because requesting this many links is throttled by GitHub's request limit. We had this same issue when trying to check links in our docs and eventually removed those checks. Most of our links are GitHub links so this renders the check useless. 

I'm ok with leaving this as a yarn command to be run as needed to check links. It looks like it might have caught some incorrectly referenced relative links. 

So, action items:

- Remove the check from our `circle.yml` file.
- Run `yarn check:markdown` and fix any actual broken links in the repo as part of this PR.

**Comment by jennifer-shehane** [comment]
@elistone Will you have time to update the requested changes for this PR? We'll close this PR otherwise.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this PR due to inactivity. If you want to continue work on this, open a new PR addressing the original issue and any requested changes.

**Pull request closed without merging**
