### PR TITLE
bump @types/jquery

### LINKED ISSUE #2363: Latest Cypress + TypeScript results in error due to out of date jquery type definitions imported by cypress
### Current behavior:
TypeScript Error

```
node_modules/@types/jquery/index.d.ts:6107:66 - error TS2344: Type '"timeout" | "onreadystatechange"
 | "responseType" | "withCredentials" | "msCaching"' does not satisfy the constraint '"abort" | "ope
n" | "timeout" | "onreadystatechange" | "responseType" | "withCredentials" | "readyState" | "respons
e" | "responseText" | "responseURL" | "responseXML" | "status" | ... 21 more ... | "dispatchEvent"'.

  Type '"msCaching"' is not assignable to type '"abort" | "open" | "timeout" | "onreadystatechange"
| "responseType" | "withCredentials" | "readyState" | "response" | "responseText" | "responseURL" |
"responseXML" | "status" | ... 21 more ... | "dispatchEvent"'.

   interface XHRFields extends Partial<Pick<XMLHttpRequest, 'onreadystatechange' | 'respon
seType' | 'timeout' | 'withCredentials' | 'msCaching'>> { }
```

### Desired behavior:

No Error.

### Steps to reproduce:

```
npm init -y
npm install typescript cypress
npx tsc --init --lib es6,dom
npx tsc
```

image

### Versions

```
+ cypress@3.1.0
+ typescript@3.0.1
```

### Suggested fix
Bumping the jquery type definitions here : https://github.com/cypress-io/cypress/blob/68b9c91839e0ead57fcf17f8c161533bf7fd4497/cli/package.json#L42 *should* (because DefinitelyTyped is updated to TS 3.0) fix the issue :rose:

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #2363

### CODE REVIEW

**Comment by bahmutov** [comment]
@NicholasBoll I think the expected type for `Cypress.$` should be just `JQueryStatic` and not `JQueryStatic<...>`, what do you think here?

**Comment by NicholasBoll** [comment]
@bahmutov Yes, it looks like the generic was recently removed from `JQueryStatic`: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5af51abb911aa56119df050fcc82594a17726dd6#diff-38ca0d3fc099227b1c19a1df229bc03eL41

**Review by NicholasBoll — APPROVED** [review]

**Review by bahmutov — APPROVED** [review]
looks good

**Comment by sarink** [comment]
Has this been published on npm yet?

**Comment by aboutqx** [comment]
Not yet published.

**Comment by franklixuefei** [comment]
Any plan on publishing this fix to `3.1.1`? Currently the `ts` tests are broken because of this.

**Pull request merged**
