### PR TITLE
dependency: update @cypress/request to 3.0.1

### LINKED ISSUE #29863: deprecated `qs@6.10.5` dependency of `@cypress/request` not reverted to `qs@6.10.4`
### Current behavior

If a `yarn.lock` was generated before the release of [@cypress/request@3.0.1](https://github.com/cypress-io/request/releases/tag/v3.0.1) on Sept 6, 2023 it is possible for an installation of Cypress to continue to hold the deprecated [qs@6.10.5](https://www.npmjs.com/package/qs/v/6.10.5) version instead of reverting to the supported [qs@6.10.4](https://www.npmjs.com/package/qs/v/6.10.4) version.

- See also https://github.com/cypress-io/cypress/issues/27644#issuecomment-1711976935.

### Desired behavior

Any installation of [cypress@13.0.0](https://github.com/cypress-io/cypress/releases/tag/v13.0.0) or later should cause the non-deprecated version [qs@6.10.4](https://www.npmjs.com/package/qs/v/6.10.4), as a dependency of [@cypress/request](https://www.npmjs.com/package/@cypress/request), to be installed. This should be independent of the previous history of installation according to any existing `node_modules` directory or package manager lock file.

It should not be necessary to uninstall Cypress and reinstall it in order to reach a supported configuration.

### Test code to reproduce

```shell
npm install yarn@latest -g
git clone https://github.com/cypress-io/github-action
git checkout cdb79e380ec33758c5c7436e67a84243e1302c90
cd github-action/examples/yarn-classic
git clean -xfd
yarn install --frozen-lockfile
yarn add cypress@latest -D
yarn list --pattern qs
```

### Cypress Version

`13.13.0`

### Node version

`v20.15.1` LTS

### Operating System

Ubuntu `22.04.4` LTS

### Debug Logs

```shell
$ yarn list --pattern qs
yarn list v1.22.22
└─ qs@6.10.5

$ yarn list --pattern cypress
yarn list v1.22.22
├─ @cypress/request@3.0.0
├─ @cypress/xvfb@1.2.4
└─ cypress@13.13.0
```

#### Suggestion

In https://github.com/cypress-io/cypress/blob/develop/cli/package.json

https://github.com/cypress-io/cypress/blob/cbbc8ee21beea08ce0e347f9bb2e95da83b9849d/cli/package.json#L23

bump to `"@cypress/request": "^3.0.1"`

### PR DESCRIPTION
**Pull request by MikeMcC399**
- Closes https://github.com/cypress-io/cypress/issues/29863

### Additional details

Due to https://github.com/cypress-io/cypress/blob/cbbc8ee21beea08ce0e347f9bb2e95da83b9849d/cli/package.json#L23 existing Cypress installations could continue to use the deprecated [qs@6.10.5](https://www.npmjs.com/package/qs/v/6.10.5) version instead of reverting to the supported [qs@6.10.4](https://www.npmjs.com/package/qs/v/6.10.4) version.

The dependency was corrected already in [@cypress/request@3.0.1](https://github.com/cypress-io/request/releases/tag/v3.0.1), however so far it was not enforced in Cypress.

### Steps to test

```shell
npm install yarn@latest -g
git clone https://github.com/cypress-io/github-action
git checkout cdb79e380ec33758c5c7436e67a84243e1302c90
cd github-action/examples/yarn-classic
git clean -xfd
yarn install --frozen-lockfile
yarn add cypress@latest -D
yarn list --pattern qs
```

Ensure that [qs@6.10.4](https://www.npmjs.com/package/qs/v/6.10.4) is installed (not [qs@6.10.5](https://www.npmjs.com/package/qs/v/6.10.5)).

### How has the user experience changed?

User projects should no longer contain the deprecated [qs@6.10.5](https://www.npmjs.com/package/qs/v/6.10.5) in their configuration.

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Hmm, check-ts is failing 🤔 https://app.circleci.com/pipelines/github/cypress-io/cypress/62925/workflows/41a9dc41-737b-49fc-b188-fe9c71a9baf3/jobs/2604952

**Comment by jennifer-shehane** [comment]
May be related to this just merging: https://github.com/cypress-io/cypress/pull/29830 Checking up on this.

**Review by jennifer-shehane — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Thanks for fixing!

**Review by cacieprins — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
Yay finally!

**Comment by MikeMcC399** [comment]
## Verification

Ubuntu `22.04.4` LTS, Node.js `20.16.0` LTS

### Steps

```shell
npm install yarn@latest -g
git clone https://github.com/cypress-io/github-action
git checkout cdb79e380ec33758c5c7436e67a84243e1302c90
cd github-action/examples/yarn-classic
git clean -xfd
yarn install --frozen-lockfile
yarn list --pattern cypress
yarn list --pattern qs
yarn add https://cdn.cypress.io/beta/npm/13.13.2/linux-x64/develop-767ddf8584c0297f84ca868ae580e89e856ed9d1/cypress.tgz -D # from PR 29864
```

### Logs

`qs` was correctly downgraded to `qs@6.10.4` (the non-deprecated version)

```text
$ yarn list --pattern cypress
yarn list v1.22.22
├─ @cypress/request@3.0.0
├─ @cypress/xvfb@1.2.4
└─ cypress@13.1.0
Done in 0.15s.
$ yarn list --pattern qs
yarn list v1.22.22
└─ qs@6.10.5
Done in 0.16s.
$ yarn add https://cdn.cypress.io/beta/npm/13.13.2/linux-x64/develop-767ddf8584c0297f84ca868ae580e89e856ed9d1/cypress.tgz -D # from PR 29864
yarn add v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ cypress@13.13.2
info All dependencies
├─ cypress@13.13.2
└─ qs@6.10.4
Done in 71.69s.
```

**Pull request merged**
