### PR TITLE
Avoid modifying XHR proxy that no longer exists

### PR DESCRIPTION
**Pull request by mihalik**
address #761 

### Problem

The `cannot set property 'aborted' of undefined` issue in #761 stems from trying to set `.aborted` on a proxy that no longer exists.  This seems to happen quite often with things that do long-polling like Firebase.  [This Firebase example](https://github.com/mihalik/cypress-firebase) has random failures almost every run prior to this update.  

## Solution

This update checks if a proxy exists before trying to abort it.  I am not 100% why the proxies no longer exist when `abort()` is called but this prevents an exception from being thrown in that state and allows the tests to complete successfully.  

_Feel free to reject if this is hiding a more fundamental issue._

### CODE REVIEW

**Comment by mihalik** [comment]
Oops.  First commit was made from a computer without my email set.  Let me know if the broken CLA is an issue and I'll cleanup and re-submit.

**Comment by bahmutov** [comment]
@mihalik hmm, the CLA rechecking does not resolve the issue - it does need an email for the contribution, also, is it possible to make a unit test for this?

**Comment by brian-mann** [comment]
An integration/e2e test would be much better - but that means being able to reproduce the issue in a controlled manner. I think you've liked pointed us in a direction that I could investigate and figure out the root cause and then come up with a test.

This is one of those times where the test is only valuable as long as it mimics the real world conditions leading up to the point of failure which is why a unit test is not that great.

Also @bahmutov the network layer rewrite would naturally fix all these problems. Mucking with host objects has its problems (as demonstrated here).

**Comment by mihalik** [comment]
Yeah, I've been unable to reproduce this issue in a reliable fashion so it seemed weird to write a test that was 'do this X times' to see if it fails.  I was hoping the minimal 

```
if proxy
  proxy.aborted = true
```

would be safe enough but it seems like it might not be.  

I'm closing this due to my CLA failing and I've started preventing this error by loading an empty page between each test.  And, it seems like you have a better handle on the full solution.

**Pull request closed without merging**
