### PR TITLE
fix:  warn on EPERM for project directory just like EACCES

### LINKED ISSUE #16933: Read only FS throwing EPERM instead of EACCESS
### Current behavior

Running with Bazel in a read only FS it throws an EPERM error on MacOS 11.2.3 (not sure about others). Same as #1281 just different error code (EPERM instead of EACCES). 

```
Error reading from: `/private/var/tmp/_bazel_sgunther/bb523b32e1e6201f4465a5fb52d0dab0/sandbox/darwin-sandbox/1/execroot/test-generator/bazel-out/darwin-fastbuild/bin/cypress-trial.sh.runfiles/test-generator/test/acceptance/tests/basic-test/cypress.json`

`Error: EPERM: operation not permitted, access '/private/var/tmp/_bazel_sgunther/bb523b32e1e6201f4465a5fb52d0dab0/sandbox/darwin-sandbox/1/execroot/test-generator/bazel-out/darwin-fastbuild/bin/cypress-trial.sh.runfiles/test-generator/test/acceptance/tests/basic-test'`
{
  status: 'failed',
  failures: 1,
  message: 'Could not find Cypress test run results'
}
```

### Desired behavior

Print a warning like with EACCES here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/settings.js#L128-L130

### Test code to reproduce

It is a whole Bazel setup and the issue is straightforward but if needed I can put something up.

### PR DESCRIPTION
**Pull request by sooca**
- Closes #16933

### User facing changelog

Degrade EPERM error for project directory to a warning instead of error just like EACCES 

### Additional details

This change was necessary to support running in read only file systems like what Bazel sets up for testing

### How has the user experience changed?

This should enable folks to directly use `nodejs_test` and maybe even `cypress_test` (only tried `nodejs_test`) with small modifications instead of being forced into the expectations of the `@bazel/cypress` rules.

### PR Tasks

This is my first PR here. I need help. I would add a test but the existing [EACCES e2e test](https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/non_root_read_only_fs_spec.ts) is not prepended with a number (which I believe is how parallelization occurs in CircleCI) so I don't think it runs. Is it even useful to write a test then? 

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by flotwig — CHANGES_REQUESTED** [review]
> I would add a test but the existing EACCES e2e test is not prepended with a number (which I believe is how parallelization occurs in CircleCI) so I don't think it runs. Is it even useful to write a test then?

@sooca You're correct about the parallelization, but the `non_root` specs actually run in their own job, with a non-root Docker executor: https://github.com/cypress-io/cypress/blob/77880f1a0f0cecaee92e1f271cede452cc133287/circle.yml#L1092-L1104

So, if you were to extend those tests to test `EPERM`, they would run.

---

There is another test for the EACCES handling here, but it's a unit test, not an e2e test: https://github.com/cypress-io/cypress/blob/77880f1a0f0cecaee92e1f271cede452cc133287/packages/server/test/unit/project_spec.js#L778-L791

It would be ok to add another unit test instead of an e2e test for this if you want.

Once this has tests, LGTM

**Comment by sooca** [comment]
> > I would add a test but the existing EACCES e2e test is not prepended with a number (which I believe is how parallelization occurs in CircleCI) so I don't think it runs. Is it even useful to write a test then?
> 
> @sooca You're correct about the parallelization, but the `non_root` specs actually run in their own job, with a non-root Docker executor:
> 
> https://github.com/cypress-io/cypress/blob/77880f1a0f0cecaee92e1f271cede452cc133287/circle.yml#L1092-L1104
> 
> So, if you were to extend those tests to test `EPERM`, they would run.
> 
> There is another test for the EACCES handling here, but it's a unit test, not an e2e test:
> 
> https://github.com/cypress-io/cypress/blob/77880f1a0f0cecaee92e1f271cede452cc133287/packages/server/test/unit/project_spec.js#L778-L791
> 
> It would be ok to add another unit test instead of an e2e test for this if you want.
> 
> Once this has tests, LGTM

Thank you for the review! I will add the tests.

**Comment by sooca** [comment]
@flotwig I added the unit test which was easy. The situation of the e2e test is more difficult than I expected. The sandboxed FS that bazel uses [throws and EPERM](https://github.com/bazelbuild/sandboxfs/blob/master/man/sandboxfs.1#L222-L226). This is different than OS file systems. They throw and EACCES error. I have tried
* Multiple different file permission codes (all the ones I tried resulted in EACCES)
* Changing file ownership (still resulted in EACCES)
* Using [fuse-native](https://www.npmjs.com/package/fuse-native) (this required OS level setup to work at least on MacOS so I didn't go much further)

In order to get an e2e test, some potential ides are
* Creating a test that installs and runs bazel in sandbox mode to execute a single cypress test 
* Somehow getting FUSE or [sandboxfs](https://github.com/bazelbuild/sandboxfs/blob/master/INSTALL.md) setup in a test `before` step so that it would run on MacOS and linux CI

Please let me know the direction you wish to go. I am personally fine with just having a unit test but I understand if you would like an e2e test to fully exercise the change.

**Comment by flotwig** [comment]
@sooca it is ok for just a unit test in this case, I think it is enough.

**Review by flotwig — APPROVED** [review]

**Pull request merged**
