### PR TITLE
chore: fix server/lib/errors.js readability.

### LINKED ISSUE #7629: server/lib/errors.js is unreadable after decaffeination
### Current behavior:

I can't easily distinguish errors from one another in this file after it was converted from coffeescript.

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/errors.js#L516:L516

### Desired behavior:

Typically we use `stripIndent` to maintain indentation so it's readable.

### Versions

4.8.0

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #7629

### User facing changelog

Clean up decaff result.

### Additional details

- Why was this change necessary? Readability
- What is affected by this change? N/A
- Any implementation details to explain? N/A

### How has the user experience changed?

N/A

### PR Tasks

- [N/A] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by flotwig** [comment]
Looks like a couple of snapshots changed. Thanks for cleaning this up @sainthkh

**Comment by sainthkh** [comment]
I concluded that current `striptIndent` tag cannot solve our problem, because:

1. It trims the trailing whitespaces. It's the cause of [this failure](https://app.circleci.com/pipelines/github/cypress-io/cypress/11603/workflows/4794073e-d01f-4017-abfd-fc9fd8a9760a/jobs/358180/tests).
2. It makes multi-line substitution unintuitive. We need to find ways to preserve/generate whitespaces like `indent(JSON.stringify(arg1.parameters, null, 2), 8)`. It is error-prone and hard to debug.

Because of that, I decided to create a new [`strip-indent-tag-generator` package](https://github.com/sainthkh/strip-indent-tag-generator). 

It'll generate string literal tags like:

```js
const generator = require('strip-indent-tag-generator')

const stripIndent = generator({
  indent: 'first',
  trim: 'start',
});

module.exports = {
  msg(x) {
    return stripIndent`
      Hello, error message world~!

      ${x}
      `
    }
}
```

Options are:

indent: min, first, all, number
trim: none, start, end, all

**Comment by sainthkh** [comment]
Tested `html`. It solves some problems, but it doesn't work well when there is an empty line in substition.

Here's [the example](https://app.circleci.com/pipelines/github/cypress-io/cypress/11660/workflows/2c99c609-1b4e-423c-b842-0d257208240b/jobs/360815/tests):

As `response` returns:

```
StatusCodeError: 422
 
{
   "code": "SOMETHING_UNKNOWN",
   "message": "An unknown message here from the server."
}
```

`html` cannot interpret it properly because of the empty line between `StatusCodeError` and `{`.

It seems that strip-indent-tag-generator is unavoidable.

**Comment by sainthkh** [comment]
Finally. It's ready.

**Pull request merged**
