### PR TITLE
refactor: added async await functions in React examples

### PR DESCRIPTION
**Pull request by Pizzo15**

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@Pizzo15 Could you please sign our CLA?

**Comment by Pizzo15** [comment]
I've signed it, but it is not getting recognized.

**Review by lmiller1990 — APPROVED** [review]
Seems fine, but will need to find out why the CLA is not signed. You might need to revert the commits, re-commit and force push to make it recognize? Not too sure.

**Comment by jennifer-shehane** [comment]
@Pizzo15 The author of the commits, `Luca Pizzini`, does not match the email address on your GitHub account. Our CLA bot gets confused when they don't match. Here are some solutions to fixing when commits are linked to the wrong user: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by Pizzo15** [comment]
@jennifer-shehane I had the wrong mail configured on my client.
Since now it is refusing the PR because there are two different emails I will close this PR and open a new one.

**Pull request closed without merging**
