### PR TITLE
[Snyk] Upgrade esbuild from 0.14.53 to 0.17.18

### PR DESCRIPTION
**Pull request by emilyrohrbough**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade esbuild from 0.14.53 to 0.17.18.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **57 versions** ahead of your current version.
- The recommended version was released **a month ago**, on 2023-04-22.

<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/cypress-opensource/project/31cdcc8e-d0de-41d5-8f3b-c77ee7a88420?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/cypress-opensource/project/31cdcc8e-d0de-41d5-8f3b-c77ee7a88420/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/cypress-opensource/project/31cdcc8e-d0de-41d5-8f3b-c77ee7a88420/settings/integration?pkg&#x3D;esbuild&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by lmiller1990** [comment]
Is it intentional to update deps in the system tests, too? I don't know if these need to be as up-to-date as the actual production dependencies.

**Comment by emilyrohrbough** [comment]
@lmiller1990 I don't understand your question.

**Comment by lmiller1990** [comment]
This PR updates a dependency for a project inside of system-tests, as opposed to a dependency actually used in the final binary we ship to users.

We don't normally update dependencies in system tests, do we? My question: should we configure Snyk to only update dependencies inside of `npm` and `packages`, and perhaps exclude `system-tests/projects`?

**Comment by emilyrohrbough** [comment]
@lmiller1990 There is no reason not to update system-test dependencies unless we are explicitly trying to test a specific version (like react or webpack). Each system-test project should really be managed / maintained like any other package.

**Pull request closed without merging**
