### PR TITLE
feat: support cypress.js for config

### LINKED ISSUE #5218: Proposal: allow configuration file to be 'js', not 'json'
# Goal

Simplify Cypress configuration

# Why

Why is this important? Why is it a priority?

* Currently, allowing configuration from multiple different places (`cypress.json`, `cypress.env.json`, `pluginsFile`) is confusing and difficult to document well
* Users need to specify different configuration based on environment (https://github.com/cypress-io/cypress/issues/909), which doesn't work with `cypress.json`
* It's not possible to use comments in `cypress.json`

Related:
* Unable to use deeply nested configuration (https://github.com/cypress-io/cypress/issues/1736)

# Implementation

* Get rid of `cypress.json` and `cypress.env.json`
* Move the `pluginsFile` to `<projectRoot>/cypress.js`
* All configuration is from what's returned from `cypress.js`

# Questions

- Can/should we support TypeScript/CoffeeScript/etc (`cypress.ts`, `cypress.coffee`)?
- How do we handle writing the `projectId` when a user sets up their project to record
- Should we change the API of `cypress.js` to be different from the current API of the `pluginsFile`. Since it's the only way to configure Cypress, it might be good to make the use-case of only using it for configuration easier. Instead of:

```js
module.exports = () => {
  return {
    baseUrl: 'http://localhost:1234'
  }
}
```

We could allow them to export an object if they don't need to register events:

```js
module.exports = {
  baseUrl: 'http://localhost:1234'
}
```

# Research

## How other projects deal with TypeScript/CoffeeScript for config files

* Webpack supports it: https://webpack.js.org/configuration/configuration-languages/#typescript
* Jest does not support it (must be `.js` or `.json`)
* Looks like webpack is using this: https://github.com/gulpjs/interpret (Not a huge fan of that much documentation just to support configuration in typescript... but I do understand that users will want this.)

# Notes

- I would go with always requiring a function the same way we do with plugins to avoid needing to do error handling and documentation in two different ways

---

via @brian-mann 

Another change is that we will need to resolve default configuration and overrides **prior** to calling the config function so you can utilize those values.

Before it was...

- cypress.json
- env var overrides
- cli arguments

now it will be...

- env var overrides
- cli arguments
- cypress.js

which means we need to pass the defaults along with the overrides to the function so it can continue to change them.

```js
// something like this
module.exports = (defaults, overrides) => {}
module.exports = (defaultsIncludingOverrides) => {}

// or the jest approach
const { defaultConfigurationOptions } = require('cypress')

module.exports = (overrides) => {}
```

I think we also need to decide what to do with `env` and whether or not this should be set as a property of the default configuration or not.

We either need to keep it separate or merge it with the config.

```js
module.exports = (env, config) => {}
module.exports = (envWithConfig) => {}
```

Right now its confusing because you work with it separately in the driver with `Cypress.env(...)` but it ends up being a property on `config`, but is set through a separate CLI flag: `--env`.

It should be either a separate thing or a part of config.

EDIT: we may not want to change the order of resolving the env + config else this would force the user to **always** merge the overrides in, else they'd be ignored. That would also force the user to have a valid `cypress.js` which we want to make optional.

Disregard what I said above about setting overrides. We could go with the `defaultConfigurationOptions` since that is separate (or perhaps yield that in) but keep resolution to happen downstream.

---

via @brian-mann 

To make matters even more confusing... `CYPRESS_` env vars are special in that they...

1. can override configuration if they match a configuration option
2. are automatically set onto `config.env`

This was done a long time ago because without the ability to execute anything in `node` it was difficult to set environment variables in the traditional way and know that the user wanted them in the driver. It would be a vulnerability to just automatically attach everything on `process.*` onto `Cypress.env()`.

Anyway with the ability to write configuration, setting env vars becomes much easier because you can just do the ones you care about.

```js
module.exports = (something) => {
  return {
    env: {
      ...process.env,
      someValue: process.env.whatever
    }
  }
}
```

If we want to allow overriding configuration we could continue to accept env vars but namespace them like `CYPRESS_CONFIG_BASE_URL=...`

Setting a `CYPRESS_FOO` would no longer mean anything, but we could also still support a `CYPRESS_ENV_FOO=bar` which would set `{ foo: bar }`

I'm still conflicted on whether or not to make `env` a property on `config` or vice versa or keep them separate.

We could namespace them like this...

```js
module.exports = () => {
  return {
    config: {...},
    env: {...}
  }
}
```

Which would make more sense per how you work with them in the `driver`.

But then we'd also need to namespace the events you register, which is weird...

This would potentially work better through for things like `projectId` which isn't actually part of the configuration of cypress and could live outside of `config`.

---

Notes from 2/6/2018:

```js
// get
Cypress.config('baseUrl')
// set
Cypress.config('baseUrl', 'http://localhost:8080')
Cypress.config({
  baseUrl: 'http://localhost:8080'
})

// cypress run --config baseUrl=http://staging.local
// CYPRESS_BASE_URL=http://staging.local cypress run

// CYPRESS_CONFIG_BASE_URL
// CYPRESS_ENV_MY_VAR

// exports.secrets ?
exports.env = () => {
  return {
    foo: 'FOO',
  }
}

// Cypress.secrets('foo') ?
Cypress.env('foo')
Cypress.envVar('foo')

// ORDER:
// CYPRESS_ENV_* VARIABLES
// cypress.js env

const envs = {
  staging: {},
  development: {},
  production: {},
  default: {},
}

// --environment staging|development|production
Cypress.environment // ?
exports.config = (defaultConfig, environment) => {
  // how to differentiate from env above?
  // call it currentEnvironment?

  return {
    ...(envs[environment] || envs.default),

    // data
    // meta
    // user
    // etc
    // other
    custom: {
      testCases: [],

      percy: {
        id: '1234',
      }
    },
  }

  Cypress.config("custom.percy.id")
  
  // return {
  //   defaults: {

  //   },
  //   development: {
  //     baseUrl: 'http://localhost:8080',
  //   },
  //   production: {
  //     baseUrl: 'http://localhost:8080',
  //   },
  //   staging: {
  //     baseUrl: 'http://localhost:8080',
  //   },
  // }
}

// ORDER:
// default config
// cypress.js config
// CYPRESS_CONFIG_* VARIABLES
// CLI


// exports.hooks ?
// exports.plugins ?
// exports.events ?
exports.backgroundEvents = (on, config, env) => {
  // config and env|secrets are final resolved values
}

exports.projectId = '1234'
```

* remove the background file (call it config file?)
* support a new —env argument or NODE_ENV=?
* pass in the environment if one is specific in the exported function
    * tag the environment in the dashboard as a filter of the build or groups?
    * where to store the env on Cypress?
    * Cypress.env?
* remove —env-file, throw if those options are passed
* add support for arbitrary config.plugins property
* add a “migration” error helper
    * list out the problems found, with link to instructions + upgrade notes for each one
    * it looks like you’re trying to upgrade to a newer verison of cypress
    * we’ve listed out the breaking changes you must fix with an explanation of what changes were made and a link to them
* Cypress.config(‘meta’) // arbitrary storage
* remove Cypress.env() // just use Cypress.config(‘envVars.whatever’)
    * or Cypress.envVars(…)

### PR DESCRIPTION
**Pull request by lmiller1990**
### User facing changelog

You may now write your configuration in a JS file. The specifics were discussed [in this ticket](https://cypress-io.atlassian.net/browse/CT-282) and summarized [in this ticket](https://cypress-io.atlassian.net/browse/CT-305). 

This resolves #5218.

The motivation here is two-fold:

1. JS is more powerful/flexible than JSON for config.
2. From 7.0, we will have the component testing runner. Some e2e defaults don't make much sense for component testing (eg: viewport height/width, component testing specific environment variables/plugin configuration). 
 
This PR adds support for declaring config via a `cypress.js` file, but also supports different defaults depending on the runner you are using.

This new configuration is purely additive - `cypress.json` is the default and will be prioritized if it is found.

Read on for more.

#### Before (`cypress.json`)

```json
{
  "video": false
}
```

#### After: (`cypress.js` by default, but only used if `cypress.json` is not found)

```js
module.exports = {
  video: false
}
```

If both `cypress.js` and `cypress.json` are found, we default to `cypress.json`.

This means if existing users would like to use the new `cypress.js` configuration, all they need to do is `mv cypress.json cypress.js` and wrap their config in `module.exports = { /* config */ }`.

In addition, you may also configure separate files for runner specific configuration. The default file names are:

- `cypress.component.config.js` for CT runner
- `cypress.e2e.config.js` for the e2e runner

Cypress will figure out which one to use based on how you launch Cypress. If you launch with `open-ct`, `run-ct` or using the `--experimentalComponentTesting` flag, we will use `cypress.component.config.js` if is exists. Otherwise, use `cypress.e2e.config.js`.

Finally, we also support declaring configuration in  single `cypress.js` file. In this case, you can configure it with two keys: `e2e` and `component`. 

```js
module.exports = {
  e2e: {
    video: false
  },
  component: {
    video: true
  }
}
```

This is neat, since you can easily share some base defaults:

```js

const config = {
  // various
}

module.exports = {
  e2e: config,
  component: {
    ...config,
    viewportWidth: 500,
    viewportHeight: 500
  }
}
```

... or ...

```js
module.exports = {
  e2e: require('./cypress/e2e.config.js'),
  component: {
    ...require('./cypress/e2e.config.js'),
    viewportWidth: 500,
    viewportHeight: 500
  }
}
```

etc.

### Additional details

This change is necessary since e2e and component testing have different requirements. An example might be in e2e tests, having a default viewport of 660x1000 might make sense, but for a component testing, it's likely something smaller such as 500x500 might be a more useful default.

Furthermore, using JS for configuration is far more powerful and flexible than JSON. In the long run, we could also support TS natively, and then users could get strongly typed configuration for a better DX! 

### How has the user experience changed?

No change required - `cypress.json` is prioritized by default. You can opt-in to the new `cypress.js` or runner specific configuration files.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? **No. This needs to be done.**
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? **Not yet. I will do this before marking "ready for review".** [I am tracking that here](https://cypress-io.atlassian.net/browse/CT-314).
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts) **Not required.**
- [ ] Have new configuration options been added to the [`cypress.schema.json`] **Need to do this**

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@lmiller1990 This will close this issue if you can tag it https://github.com/cypress-io/cypress/issues/5218

**Comment by flotwig** [comment]
I don't think we need `cypress.component.config.js` and `cypress.e2e.config.js`, it seems to duplicate the functionality of having the `e2e` and `component` keys, and as you note users could just do `{ e2e: require('cypress.e2e.config.js') }` from their cypress.js anyways

**Comment by jennifer-shehane** [comment]
@lmiller1990 Josh is going to set up a meeting soon to discuss the implementation of this with some of the TR team so we can more quickly review.

**Comment by lmiller1990** [comment]
@jennifer-shehane thanks, I added a resolves #5218. I will sync w/ Josh to get this meeting organized.
@flotwig I think you are right, maybe got a bit too excited 😓

**Comment by lmiller1990** [comment]
Slightly changed how/when this will be implemented. First stage is to upgrade `cypress.json` and `plugins/index.js`. Eventually these two will merge into a `cypress.config.js` file.

**Pull request closed without merging**
