### PR TITLE
chore: Turn issue templates into forms

### PR DESCRIPTION
**Pull request by jennifer-shehane**
GitHub introduced the ability to have [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) on public repositories.

**This PR:**

- Turns the issue templates into forms
- Removes link to Dashboard productboard as this will no longer be used
- Adds links to Cypress Discord chat

**Tests:**

-  You can test it out  here: https://github.com/jennifer-shehane/github-issue-templates-test

### Before

Screen Shot 2021-07-09 at 4 00 17 PM

### After

Screen Shot 2021-07-09 at 4 05 51 PM

### Before

Screen Shot 2021-07-09 at 4 01 51 PM

### AFter

Screen Shot 2021-07-09 at 3 50 26 PM

### Before

Screen Shot 2021-07-09 at 4 02 01 PM

### After

Screen Shot 2021-07-09 at 3 51 10 PM

### Before

Screen Shot 2021-07-09 at 4 02 12 PM

### After

Screen Shot 2021-07-09 at 3 51 24 PM

### CODE REVIEW

**Review by elevatebart — APPROVED** [review]
Looks good!

I am always afraid of required fields, that bugs will not get reported. But I think that's a risk to take.

We can even upload screenshots and videos and use markdown.

**Comment by jennifer-shehane** [comment]
@elevatebart Yah but bugs without these fields have no way of moving forward imo. I guess we could remove the  validations for the install one with the packages/OS, but usually OS is pretty relevant.

**Comment by elevatebart** [comment]
And it's a drop down so it would be really mean if they don't provide it.

Could be a checkbox/multi select though. Less clicks, more power.

**Review by chrisbreiding — COMMENTED** [review]
Very nice!

**Review by chrisbreiding — APPROVED** [review]

**Pull request merged**
