### PR TITLE
fix: improve React `mountHook` type

### LINKED ISSUE #17236: Mount hook types for React component testing are not right
### Current behavior

While using `mountHook`, I was surprised that types are not aligned with what it returns.

<u>Types from npm</u>
```ts
export declare const mountHook: (hookFn: (...args: any[]) => any) => Cypress.Chainable<import("./mount").MountReturn>;
```

<u>Sources</u>
```ts
export const mountHook = (hookFn: (...args: any[]) => any) => {
  const { result, setValue, setError } = resultContainer()

  return mount(
    React.createElement(TestHook, {
      callback: hookFn,
      onError: setError,
      children: setValue,
    }),
  ).then(() => {
    cy.wrap(result)
  })
}
```
There's no return type, TS compiler guess the return type from the `mount` function I guess.

### Desired behavior
Have a correct typing for `mountHook`.

Also, the feature for adding a context (as a wrapper) would be welcomed ! #14672 

Also, the comment below (https://github.com/cypress-io/cypress/blob/master/npm/react/src/mountHook.ts#L67) should be updated.

### Versions
Cypress: 7.6.0
Cypress React:  5.9.1

### PR DESCRIPTION
**Pull request by edimitchel**
- Closes #17236

### User facing changelog

Cypress React mount hook have correct types . Fixes #17236.

### How has the user experience changed?
Improved types (example on `use-counter.spec.js`
**Before**
image

**After**
image

### PR Tasks

- [ ] Have tests been added/updated? _Should I add tests ?_
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? _None for the moment, but as I see, there is not documentation about the `mountHook` function_

### CODE REVIEW

**Review by lmiller1990 — DISMISSED** [review]

**Comment by lmiller1990** [comment]
LGTM, but you will need to ensure the CLA is signed before we can merge this: https://github.com/cypress-io/cypress/pull/17241#issuecomment-875986894

**Comment by edimitchel** [comment]
Thanks @lmiller1990 ! I can wait 2 weeks, not problem.

About CLA, I don't know why but I signed it twice but nothing change...

**Comment by jennifer-shehane** [comment]
@edimitchel CLA looks good now. 👍

**Comment by edimitchel** [comment]
But now some build fails even I didn't make any change.. Someone could replay the build ?

**Comment by edimitchel** [comment]
@lmiller1990 tests are green !

**Comment by lmiller1990** [comment]
I will get this merged up, nice job @edimitchel. 💯

**Review by lmiller1990 — APPROVED** [review]

**Comment by edimitchel** [comment]
Thank you @lmiller1990 ! My first contribution !

**Pull request merged**
