### PR TITLE
fix: keep spaces in formatted output in test runner

### LINKED ISSUE #23679: Formatted errors does not show as formatted in cypress test runner
### Current behavior

Cypress 10 new test runner omits formatting on errors such as new lines, tabs, etc. 

Capture

### Desired behavior

To be able to throw an error with formattings such as new lines, and tabs.
*For example see how cypress dashboard prints the error below*

### Test code to reproduce

```
it.only('fail to format in test runner', { retries: 0 }, () => {
    Cypress.on('fail', (error, runnable) => {
      throw {
        ...error,
        message: `Failed to assert  event.\n\nExpectedValue:**${JSON.stringify(
          error.expected,
          null,
          4
        )}** \nActual args: **${JSON.stringify(error.actual, null, 4)}** \n
      `,
      };
    });

    cy.wrap({
      category: 'resources',
      name: 'action',
      label: 'copy_clipboard',
      target: 'keyboard',
      location: {
        title: 'favorites',
      },
      search: {
        clientSearchId: 'favorites',
        sessionId: 'favorites',
      },
      resources: {
        message: 'match(undefined)',
      },
      jsonData: {
        'action.trigger': 'command_bar',
      },
    }).should('deep.equal', {
      category: 'resources',
      name: 'action',
      target: 'keyboard',
      label: 'copy_clipboard',
      location: {
        title: 'favorites',
      },
      resources: [
        {
          id: 'UgfdGiIVw7NklNbHWSO-fw',
          list: 'favorites',
          appId: 'mockapp',
          type: 'mockapp:item',
          position: 0,
          linkId: '631483cead6377c7a8ef5c2e',
        },
      ],
      jsonData: {
        'action.trigger': 'command_bar',
      },
    });
  });
```

### Cypress Version

10.7.0

### Node version

16.14.2

### Operating System

windows 10

### Debug Logs

_No response_

### Other

- It worked well with cypress 9 and was broken with Cypress 10.
- it actually works well in Cypress dashboard.
### Cypress Dashboard showing formatted error

Capture

### PR DESCRIPTION
**Pull request by melkstam**
- Closes #23679 

### User facing changelog

Fixes issue where spaces on newlines weren't kept in the test runner

### Additional details

The solution depends on tricking the markdown renderer into keeping any spaces by using the HTML entity `&#32;` (a space). This will make it keep those, instead of disregarding it.

### Steps to test

This is an example (taken from #23679) to reproduce.
```js
it.only('fail to format in test runner', { retries: 0 }, () => {
  Cypress.on('fail', (error, runnable) => {
    throw {
      ...error,
      message: `Failed to assert  event.\n\nExpectedValue:**${JSON.stringify(
          error.expected,
          null,
          4
        )}** \nActual args: **${JSON.stringify(error.actual, null, 4)}** \n
      `,
    };
  });

  cy.wrap({
    category: 'resources',
    name: 'action',
    label: 'copy_clipboard',
    target: 'keyboard',
    location: {
      title: 'favorites',
    },
    search: {
      clientSearchId: 'favorites',
      sessionId: 'favorites',
    },
    resources: {
      message: 'match(undefined)',
    },
    jsonData: {
      'action.trigger': 'command_bar',
    },
  }).should('deep.equal', {
    category: 'resources',
    name: 'action',
    target: 'keyboard',
    label: 'copy_clipboard',
    location: {
      title: 'favorites',
    },
    resources: [{
      id: 'UgfdGiIVw7NklNbHWSO-fw',
      list: 'favorites',
      appId: 'mockapp',
      type: 'mockapp:item',
      position: 0,
      linkId: '631483cead6377c7a8ef5c2e',
    }, ],
    jsonData: {
      'action.trigger': 'command_bar',
    },
  });
});
```

### How has the user experience changed?

**Before**
before

**After**
after

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by ryanthemanuel — APPROVED** [review]
Looks good. Thank you for the contribution!

**Comment by marktnoonan** [comment]
I like this! Will approve once I have a chance to pull it down and test.

**Review by mjhenkes — APPROVED** [review]

**Review by marktnoonan — APPROVED** [review]
We'll have to look into the CI failure 🤔 , it's unrelated to the PR.

**Comment by BlueWinds** [comment]
Thank you for your patience with our test failures - we've been working pretty heavily on stabilizing CI with 12.x, so here's hoping this latest merge of develop is the charm.

**Comment by BlueWinds** [comment]
Looks like we do have one set of genuine failures, https://app.circleci.com/pipelines/github/cypress-io/cypress/47068/workflows/85b8f7a4-c7db-421a-92f4-9ce84e0cb8b5/jobs/1971826.

Specifically, these tests https://github.com/cypress-io/cypress/blob/develop/packages/app/cypress/e2e/runner/retries.ui.cy.ts#L325 are failing because it's asserting that the replaced text (with text like `{&#32;retries:&#32;2&#32;}`) matches the base text (with text like `{ retries: 2 }`). Probably need to either decode the string before asserting on it, or encode the string it's asserted against.

**Comment by emilyrohrbough** [comment]
@melkstam are you able to take a look at these failures?

**Comment by melkstam** [comment]
> @melkstam are you able to take a look at these failures?

Yes, I will look at it!

**Pull request merged**
