### PR TITLE
driver: check hook to be defined function, close #952

### LINKED ISSUE #952: Handle undefined lifecycle callbacks better: very cryptic error message
Cypress: 1.1.1

If we pass `undefined` as a callback to `beforeEach` for example we get a very cryptic error

```js
describe('undefined beforeEach', () => {
  let foo

  beforeEach(foo)

  it('works', () => {})
})
```
Error shown 
```
TypeError: Cannot read property 'length' of undefined

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'null beforeEach'
```
Even clicking on the error and seeing the message in the console does not give any details - just cypress runner callstack.

Undefined functions often happen when importing functions from other files, renames, etc. Need to give a clear message and maybe print the callback code.

### PR DESCRIPTION
**Pull request by bahmutov**
Hmm, needs a test.

### CODE REVIEW

**Comment by brian-mann** [comment]
Yah you can't throw generic errors like this because:

1) the user would also see the error if they open the console
2) the GUI would never update 
3) the error would never make it back to the CLI and the tests would never exit

All error handling has to be done **really** carefully when its around code that is scaffolding the mocha structure. For instance, there is quite a bit of code around uncaught exception handling when it occurs outside of the first test. This is the same instance. That needs its own very specific code.

**Comment by bahmutov** [comment]
Sure, yes, this might be bad. What is the right way to report error here? I see two things inside `$utils.throwErrByPath` and `fail(err, runnable)`. And how to unit test this?

**Comment by brian-mann** [comment]
asdf

**Comment by jennifer-shehane** [comment]
Hey @bahmutov, did you ever get this test in?

**Comment by jennifer-shehane** [comment]
Closing due to inactivity.

**Pull request closed without merging**
