### PR TITLE
Only package Windows builds of ffmpeg with Windows, build for win32 and win64

### LINKED ISSUE #716: Build separate 32bit and 64bit builds for Windows, don't ship ffmpeg twice
Currently we only build `32bit` Windows, but we ship two versions of `ffmpeg` for both `32bit` and `64bit` Windows. 

This inflates the binary by almost 100mb O_O.

Need to build separate Windows arch. We've already updated the CLI and the download server to account for this.

### LINKED ISSUE #3888: Don't package non-Windows ffmpeg builds with Windows build
In 3.1.5 and onwards, there are copies of ffmpeg for every target architecture in the Windows download adding about 150mb:

image

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #3888, fixes #716

Doing `packages.forceNpmInstall(serverFolder, "@ffmpeg-installer/win32-x64")` causes the other versions of ffmpeg to be installed because `npm i --force` ignores the platform differences.

This PR deletes everything in `@ffmpeg-installer` in `server` except the Windows builds and the `@ffmpeg-installer/ffmpeg` package.

Deleting the non-Windows ffmpeg builds from the binary reduces build size significantly:

* Latest develop build: https://cdn.cypress.io/beta/binary/3.3.0/win64/appveyor-develop-36627fa68d11766d9f7d464a8a8ac8c00be3e8a0-23584050/cypress.zip
  * .zip size: 231.2 MB
  * Unzipped size: 650.0 MB
* Latest build from this PR: https://cdn.cypress.io/beta/binary/3.3.0/win64/appveyor-issue-716-ffmpeg-packaging-3f3ec50adbcc5ecbb21a189f695ac81765662806-23602481/cypress.zip
  * .zip size: **170.4 MB**
  * Unzipped size: **467.9 MB**

That's a 27% reduction in zipped size and a 29% reduction in unzipped size. Pretty nice to see.

### CODE REVIEW

**Comment by flotwig** [comment]
I'm kind of curious as to if we need to bundle 64-bit ffmpeg at all, as long as we're only building a 32-bit Cypress app.

`@ffmpeg-installer` uses this to determine the build of `ffmpeg` to use:

https://github.com/kribblo/node-ffmpeg-installer/blob/bbe5c71fce98e0450e919ba985c6560b79225039/index.js#L9

According to the Node.JS docs, `os.arch()` "returns a string identifying the operating system CPU architecture for which the Node.js binary was compiled.".

So this will always use the `win32-ia32` build, since we only compile the Electron app for 32-bit, leaving me wondering why we're packaging a `win32-x64` build at all.

**Comment by flotwig** [comment]
The plot thickens...

It turns out that we're actually shipping a **64-bit** edition of Cypress on win32, not a 32-bit version. I used the `dumpbin` utility to verify this:

```
C:\>dumpbin C:\Users\flotwig\AppData\Local\Cypress\Cache\3.1.5\Cypress\Cypress.exe /headers   
Microsoft (R) COFF/PE Dumper Version 14.16.27027.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Users\flotwig\AppData\Local\Cypress\Cache\3.1.5\Cypress\Cypress.exe

PE signature found

File Type: EXECUTABLE IMAGE

FILE HEADER VALUES
            8664 machine (x64)
               A number of sections
        5A7A2A38 time date stamp Tue Feb  6 17:20:40 2018
               0 file pointer to symbol table
               0 number of symbols
              F0 size of optional header
              22 characteristics
                   Executable
                   Application can handle large (>2GB) addresses
```

As you can see, it recognizes Cypress.exe as an x64 executable, not ia32. This explains the architecture issue seen in #787, #2095, and #3706.

Also confirmed this by dropping a `console.log(os.arch(), os.platform())` in `packages/server/index.js`, which logs "x64 win32".

So, in light of this, we should just be bundling win32-x64. Or maybe we should fix that we're shipping 64-bit Electron and just be bundling win32-ia32.

**Comment by Saibamen** [comment]
Please cleanup `issue-716-ffmpeg-packaging` branch. My comments are in https://github.com/cypress-io/cypress/commit/db752f5f9335a8f5ca30b82500c5c118d6b3d526

**Comment by brian-mann** [comment]
@flotwig can you also update your top level comments in the PR and do a new chart for the savings by pulling down the binaries?

Also can we update the issues you listed a previous comment (and the PR title) to being that we generate a 32 bit version of windows now?

You'll have to go into each issue and say it was closed by the PR since it's already been merged.

**Comment by brian-mann** [comment]
And tag all closed issues as release 3.3.0

**Pull request merged**
