### PR TITLE
Add option to upload video on tests passing. Addresses #460

### PR DESCRIPTION
**Pull request by carlos-granados**
Compressing and uploading a video to the dashboard is an expensive operation. If there have been no failures, we are not usually interested in the video as it will reveal nothing interesting, so it makes sense that we may want the video to only be compressed and uploaded if there have been any failures.

This PR adds a new `uploadVideoOnlyOnFailure` config setting that if set to true will disable compressing and uploading the video unless there have been some failures. It defaults to `false` to keep the current functionality.

Includes unit tests for the new functionality. I did not add any integration tests for the upload feature because I saw this comment in the code:

```
## TODO: add tests around uploadingAssets + upload
```

so it seems that there are no tests for this capability yet

### CODE REVIEW

**Comment by brian-mann** [comment]
You are right, there are not unit tests around uploading, but there are e2e tests around it, and we have internal projects that additionally test it.

**Comment by brian-mann** [comment]
The server unit tests are failing because env vars are not being applied on PR's. This ends up breaking some tests. I will update `develop` and fix these failing tests and then you can pull from them.

**Comment by carlos-granados** [comment]
- Changed the name of the option to `videoUploadOnPassing`, defaulting to true
- I did not write the integration test as I was not really sure on how to test what had been called or not
- I created the PR for the documentation change: https://github.com/cypress-io/cypress-documentation/pull/136 (please feel free to change the documentation, English is not my native language)

**Comment by carlos-granados** [comment]
The failing tests in CircleCI seem unrelated to this code and they pass locally, so looks like some random flake

**Comment by brian-mann** [comment]
I added some more commits and ended up renaming the config again

https://github.com/cypress-io/cypress/commit/d3aeb01b14ad919ff2e8a305c9eb66e490a18262

**Comment by brian-mann** [comment]
I couldn't find a way to make commits on top of this PR and have it automatically associate

**Comment by brian-mann** [comment]
In the future, when you submit PR's make sure the box for enabling contributors is checked so we can modify your PR's and associate the commits properly.

**Comment by carlos-granados** [comment]
That's weird, I remember setting this option. Could it have become unset when I added more commits? In any case, thanks for updating and merging this :-)

**Pull request merged**
