### PR TITLE
[WIP] Do not include special/modifier chars for input validation

### LINKED ISSUE #4325: Cannot submit value to 'react-tagsinput' when rendered input type is 'time'
### Current behavior:

Right now I'm trying to test 'react-tagsinput' with a rendered input of a 'time' type. To submit value I have to press enter inside of the input, but when I do that with `input.type('01:11{enter}')` cypress throws and error:

> CypressError: Typing into a time input with cy.type() requires a valid time with the format 'HH:mm', 'HH:mm:ss' or 'HH:mm:ss.SSS', where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999. You passed: 01:11{enter}. 

It works fine with other types of inputs.

Also tried: 

* Triggering the `keyDown`, `keyUp`, `change` and `input` events with jquery and pure js 
* Typing `{enter}` separately with the force option

### Desired behavior:

When I type some value into the 'time' input and add `{enter}` at the end of the value string it triggers event of pressed Enter key 

### Steps to reproduce:

Serve this file:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <input data-cy="input" type="time">
  </body>
</html>
```
Then execute test.

Test code:

```js
describe("Enter", () => {
    beforeEach(() => {
        cy.visit("http://127.0.0.1:8080/");
    });

    it("misbehaves", () => {
        cy
            .get('[data-cy="input"]').type("01:11{enter}")
    });
});
```

`Operating System: Ubuntu 18.04.2 LTS`
`Cypress Version: ^3.2.0`
`Browser Version: Chrome 74.0.3729.108`
`For an actual app I use ReactJS with Material UI`

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #4325

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@Bkucera In my test I'm trying to write into an input of `type='time'` with a value of `01:15{enter}`. I have the code so that it strips any special/modifier chars during validation (this used to just throw saying `01:15{enter}` was an invalid `time` value).

So it validates correctly and types in `01:15` correctly, BUT when it reaches time to execute the `{enter}` special chars, it ends up clearing the entire input from this line of code: https://github.com/cypress-io/cypress/blob/issue-4325/packages/driver/src/cypress/keyboard.coffee#L177

This is not what happens when you type into a `time` input manually and hit enter (As far as I can tell it does nothing in a `time` input besides issuing the proper events which someone may have their own logic hooked into). 

Maybe you've already addressed this in another PR - feel free to edit the PR, comment with some recommendations, or close if already addressed somewhere else. Thanks!

**Comment by Bkucera** [comment]
@jennifer-shehane yes, I'm addressing this in #2436 , is this a priority or can it wait until native events gets merged?

**Comment by jennifer-shehane** [comment]
@Bkucera It can wait, just want to make sure the verification logic is in the native events PR.

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress/pull/2436

**Pull request closed without merging**
