### PR TITLE
chore: Update Desktop GUI footer design

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Addresses [TR-352](https://cypress-io.atlassian.net/browse/TR-352)

### User facing changelog

Miscellaneous: Updated the design of the test runner GUI's footer. It now shows an indicator if there is a new version available.

## Additional Information

Changelog link query param forwarding relies on this PR being deployed: https://github.com/cypress-io/cypress-services/pull/3105

### How has the user experience changed?

**Before** (on latest version)

Screen Shot 2020-09-30 at 12 01 09 PM

**Before** (update available)

Screen Shot 2020-09-30 at 12 01 59 PM

**After** (on latest version)

Screen Shot 2020-09-30 at 11 59 36 AM

**After** (update available)

Screen Shot 2020-10-01 at 10 39 34 AM

### PR Tasks

- [x] Have tests been added/updated?
- N/A Has the original issue been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Where is the original design for this? Didn’t see it linked in TR-352. 

The changelog link is supposed to have this query param: `?source=dgui_footer` I *think* this requires it being it’s own on link?? I can’t remember if the query param will pass along correctly if it’s just `https://on.cypress.io/changelog ?source=dgui_footer`

**Comment by chrisbreiding** [comment]
> From what I see on the design, the 'Update Available' blue banner should no longer show when there is an update. The only way to update is clicking the version button with the arrow.

I'm not sure this is the case (or should be the case). We're changing the style of the update banner to be a dismiss-able toast in a later story, but I'm not sure what the plan is in the interim since this could potentially get released before then. I'll check with Adam about it. 

> The changelog link is supposed to have this query param: ?source=dgui_footer I think this requires it being it’s own on link?? I can’t remember if the query param will pass along correctly if it’s just https://on.cypress.io/changelog ?source=dgui_footer

Thanks for pointing this out. I didn't mess with the existing link since TR-352 says "The changelog should continue linking to ...", so I thought there was no change there, but I guess it is different. I'll look into how `on` links handle query params.

**Comment by chrisbreiding** [comment]
In regards to `on` links and query params, looks like it's necessary to specify in the `on` manifest for a particular redirect to `forwardQueryParams`, so I'll submit a PR to do that for changelog links.

**Comment by chrisbreiding** [comment]
Confirmed with Adam this is supposed to remove the update banner altogether.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
1. Is the hover of the changelog meant to have the margin to the right of it like this? Seems a bit weird, thought it would extend to the edge. It doesn't seem totally clear from the comp. (maybe I'm missing some way for Figma to be interactive here). @CypressAdam 

    Screen Shot 2020-10-02 at 2 21 34 PM

2. After clicking the update button, the styling of the button still appears 'focused' (You can see this in the tests also).

    

3. Can we add some percy snapshots around these tests? Cause this stuff is hard to catch if it's broken later.

**Comment by CypressAdam** [comment]
@jennifer-shehane I nixed the padding-right on `.footer` to clear up that gap. I was playing in a dream world in Figma where I had corresponding margins in the header. It now matches up. 

@chrisbreiding hope you don't mind my taking the liberty. 2 and 3 from Jennifer's list are beyond my capabilities 🧑‍🚀

**Review by jennifer-shehane — APPROVED** [review]

**Comment by Saibamen** [comment]
IMHO just icon is not enough.

I will suggest bringing back text version, and use new footer (with icon), like here:
image

**Pull request merged**
