### PR TITLE
add Loggable options to its() / invoke() command

### LINKED ISSUE #1450: The `its` command doesn't accept a log option (logging can't be disabled)
### Current behavior:
`cy.window({ log: false }).its('something', { log: false })` throws an error because no options object is supported. (The docs bear this out as well).

### Desired behavior:
I should be able to suppress logging using `its('something', { log: false })` or the `its` command should inherit the log level from the previous call (if this is currently the expected behavior I'll investigate further and create a reproduction, I didn't see a mention of this in the docs).

Also, I would think that the `its` command should accept a timeout property.

- Cypress Version: 2.1.0

### PR DESCRIPTION
**Pull request by gabbersepp**
- Closes #1450 

### User facing changelog

The commands `.its()` and `.invoke()` now accept an options object of type `Loggable` to indicate that logging should be skipped. 

### Additional details

This change does not break any existing implementations. By default logging is enabled.

#### its Before

```js
cy.get('.connectors-its-ul>li')
  .its('length')
  .should('be.gt', 2)
```

Screen Shot 2019-11-06 at 12 14 28 PM

#### its After

```js
cy.get('.connectors-its-ul>li')
  .its('length', { log: false }) // no log
  .should('be.gt', 2)
```

Screen Shot 2019-11-06 at 12 15 01 PM

#### invoke Before

```js
cy.get('.connectors-div').should('be.hidden')
  .invoke('show') // will always log
  .should('be.visible')
```

Screen Shot 2019-11-06 at 12 11 43 PM

#### invoke After

```js
cy.get('.connectors-div').should('be.hidden')
  .invoke({ log: false }, 'show') // no log
  .should('be.visible')
```

Screen Shot 2019-11-06 at 12 16 02 PM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/2205
- [x] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?

*Edited by @jennifer-shehane to add before and after headings for its and invoke + add invoke change to changelog.*

### CODE REVIEW

**Comment by gabbersepp** [comment]
Why is the rerun_spec failing?

image

**Comment by jennifer-shehane** [comment]
Hey @gabbersepp, I see some tests failing around the `its` command in our CI here: https://circleci.com/gh/cypress-io/cypress/177593

If there is still work being done, add the `WIP` to the title of the PR so that we don't review the changes before they're done. Remove this from the title when you're ready for review. 

Let us know if you have any questions we can help with in the meantime!

**Comment by gabbersepp** [comment]
> Hey @gabbersepp, I see some tests failing around the `its` command in our CI here: https://circleci.com/gh/cypress-io/cypress/177593
> 
> If there is still work being done, add the `WIP` to the title of the PR so that we don't review the changes before they're done. Remove this from the title when you're ready for review.
> 
> Let us know if you have any questions we can help with in the meantime!

Hey,
sorry did not see the failing tests.

I don't understand how the "logs immediately before resolving" can fail. 
Maybe another one can have a look at it.

What I have done and what I do not understand how this can work:
- set a breakpoint in connectors.coffee at line 175
- set a breakpoint in connectors_spec.coffee at line 892
- if the test is executed, try to step over line 175 and into the call to set() in line 176
- the code is immediatelly jumping into the breakpoint at line 892 with all the information set ("its", "foo", ....)

How can this happen? Line 175 only calls Cypress.Log() without passing anything but nevertheless line 892 is called?

@jennifer-shehane maybe you can give me a hint here. I assume this must be a bug in the source maps.

**Comment by gabbersepp** [comment]
Btw if I use following test instead:

```js
 it "logs immediately before resolving", (done) ->
          #cy.on "log:added", (attrs, log) ->
          #  if log.get("name") is "its"
          #    expect(log.get("state")).to.eq("pending")
          #    expect(log.get("message")).to.eq ".foo"
          #    done()

          cy.noop({foo: "foo"}).its("foo").then ->
            lastLog = @lastLog
            expect(lastLog.get("message")).to.eq(".foo")
            done()
```

everything is green

**Comment by gabbersepp** [comment]
ok. finally fixed the test. :-)

**Comment by jennifer-shehane** [comment]
Great. Sorry we couldn't get any eyes on this sooner to help.

**Comment by gabbersepp** [comment]
Thanks. There where some bugs in it. Hopefully I fixed all of them.
And I added some more tests.

Personally I would prefer to split up this spec file into several smaller ones as now the file has about 1500 lines of code.

**Comment by gabbersepp** [comment]
@bahmutov 
done. We will see in a few minutes, if everything is green.

But after reading through https://github.com/cypress-io/cypress/pull/5755 I am not sure if the changes made on `invoke` in this PR should be merged, because @flotwig  mentioned, that he `expect[s] invoke to have the same function signature as an its call`. This does not hold anymore now as `invoke` accepts the options as first parameter to not conflict with potential passed function arguments.

**Comment by flotwig** [comment]
> @bahmutov
> done. We will see in a few minutes, if everything is green.
> 
> But after reading through #5755 I am not sure if the changes made on `invoke` in this PR should be merged, because @flotwig mentioned, that he `expect[s] invoke to have the same function signature as an its call`. This does not hold anymore now as `invoke` accepts the options as first parameter to not conflict with potential passed function arguments.

It will make the contract a little weird, but the way you have it here is really the only way I can see to do it. :+1: on this change.

**Pull request merged**
