### PR TITLE
chore: update ramda to 0.27.1

### PR DESCRIPTION
**Pull request by k-yle**
### User facing changelog

N/A

### Additional details

Everyone who installs cypress gets an old version of ramda installed, resuling in multiple versions of the same package being installed

### How has the user experience changed?

It hasn't

### PR Tasks

- [ ] ~~Have tests been added/updated?~~
- [ ] ~~Has the original issue or this PR been tagged with a release in ZenHub?~~ 
- [ ] ~~Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?~~ 
- [ ] ~~Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?~~
- [ ] ~~Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?~~

### CODE REVIEW

**Review by prdarm — DISMISSED** [review]

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@k-yle ramda 0.27.0 is a breaking change release, so you'll need to update all of our ramda code with the breaking changes: https://github.com/ramda/ramda/issues/2978

**Comment by k-yle** [comment]
hi @jennifer-shehane, there's only one breaking change which affects cypress which is the removal of `R.memoize`. I've already made this change

**Comment by jennifer-shehane** [comment]
Having some issues with our build, let's see if the tests pass.

**Comment by jennifer-shehane** [comment]
@k-yle I think the build may be failing due to this change. Can you investigate.

**Comment by k-yle** [comment]
@jennifer-shehane I suspect the failing firefox integration tests are not my fault since they're failing on `develop` too?

**Comment by jennifer-shehane** [comment]
@k-yle Yah, they're likely just flaky :(

**Review by jennifer-shehane — APPROVED** [review]

**Pull request merged**
