### PR TITLE
WIP: Browser path 1026

### PR DESCRIPTION
**Pull request by bahmutov**
Working on passing `--browser /path/to/a/browser` option

### CODE REVIEW

**Comment by bahmutov** [comment]
Hmm, this does NOT terminate the browser when the test runner is done
```
npm start -- --run-project ~/git/cypress-test-tiny --browser /usr/local/bin/chrome
```

but the same browser does exit 
```
npm start -- --run-project ~/git/cypress-test-tiny --browser chrome
```

So somewhere we do not terminate it correctly.

**Comment by bahmutov** [comment]
Interesting - the child process we get has id `pid: 59699` with parameters
```
[ '/usr/local/bin/chrome',
...
```
but the `ps` shows the Chrome process under next id
```
59700 ttys006    0:01.75 /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --disable-gpu --no-sandbox
```

**Comment by jennifer-shehane** [comment]
Whats the holdup on this PR?

**Comment by bahmutov** [comment]
ohhh, hmm, this is old code, need to see how to salvage or start again

**Comment by jennifer-shehane** [comment]
@bahmutov Hi again, is this PR still relevant?

**Comment by flotwig** [comment]
Implemented in #3337

**Pull request closed without merging**
