### PR TITLE
Correct detection logic for Edge & Firefox Nightly

### LINKED ISSUE #6345: Firefox Nightly - no version found
### Current behavior:

Tried to launch Cypress while having Firefox Nightly installed and Cypress will not open beyond this screen.

We're unable to pull of the 'version' of Firefox Nightly so it does not continue.

Screen Shot 2020-02-06 at 4 25 04 PM

It looks like the version is `74.0a1`, maybe the letter is throwing it off. 

Screen Shot 2020-02-06 at 4 42 37 PM

### Desired behavior:

Ability to Cypress in Firefox Nightly

### Versions

firefox branch - prerelease

### LINKED ISSUE #6354: MacOS not detecting Microsoft Edge as a launch-able browser
### Current behavior:

Running cypress open fails to detect edge as selectable browser in the dropdown.  Have tried using cypress run --browser edge (which tells me it can't detect an edge browser) as well as providing an absolute path of 

cypress run --browser /Applications/Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge

That seems to run electron in the terminal instead of edge though this could just be because cypress hasn't been setup to run edge headlessly.  I double checked that I had edge installed and the binary was in the place I expected it to be.

This file https://github.com/cypress-io/cypress/blob/develop/packages/launcher/lib/darwin/index.ts

indicates where cypress is looking so I am a bit stumped.

(Just noticed that the const detectEdge doesn't provide "Microsoft Edge.app" line like say the const detectFirefox does on line 27 of the link I provided above.  Might that be the issue?

### Desired behavior:

Edge binary should be automatically detected by cypress.

### Test code to reproduce

Install edge(chromium) for MacOS
npm init
npm install cypress@latest
cypress open

### Versions

MacOS Mojave 10.14.6, Microsoft Edge (non dev or canary builds), cypress 4.0.0, node 12.0.0

### PR DESCRIPTION
**Pull request by YOU54F**
Correct detection logic for Edge & Firefox Nightly on MacOSX

- Closes #6354
- Closes #6345

### PR Tasks

- [ ] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by bahmutov** [comment]
Checked Edge variants (from https://www.microsoftedgeinsider.com/en-us/download) on Mac - this PR fixes the detection.

Screen Shot 2020-02-07 at 1 39 34 PM

and prints correct information when doing `node packages/launcher/index.js`

**Comment by flotwig** [comment]
As part of this PR, should we order the editions Stable => Beta => Dev => Canary, so it goes most stable => least stable?

**Comment by bahmutov** [comment]
Checked Firefox Nightly and Dev on Mac (from https://www.mozilla.org/en-US/firefox/channel/desktop/) - correct detection

**Comment by bahmutov** [comment]
@flotwig I really like your test in https://github.com/cypress-io/cypress/pull/6367 but it is hard to push changes to external patch PR

So I think we can: land your PR. Then land this PR. Then add tests for Edge on Mac, and then think how to order browsers - I say order by `name, major`

**Comment by YOU54F** [comment]
Feel free just to copy changes into @flotwig ‘s pr. I am not precious about it being from this PR

**Comment by bahmutov** [comment]
Thank you @YOU54F , you are the best. @flotwig can you copy this commit into your PR and close 3 issues at once? And order Edges too

**Comment by YOU54F** [comment]
Woop woop! Job’s a good un. Firefox support looks so good guys, all my work tests passed first time with exception to that that require web security disabled. Will see if I can find a workaround as per chrome, when I get some time. Thanks for all the hard work as usual

**Comment by bahmutov** [comment]
@YOU54F one other thing you can do - skip those tests on firefox selectively https://github.com/cypress-io/cypress-skip-test#imports-with-callback

**Comment by YOU54F** [comment]
> @YOU54F one other thing you can do - skip those tests on firefox selectively https://github.com/cypress-io/cypress-skip-test#imports-with-callback

Sweet, that looks really nice! For now, I invoke a single smoke test that goes through our entire journey with chromewebsecurity off and with ignore x frame headers extension in a seperate invocation of cypress and all our other tests run with the normal configuration so not an issue for now, but that is good to know 👌

**Pull request merged**
