### PR TITLE
fix: XHR stub error if response json has number/boolean

### LINKED ISSUE #4899: Error on XHR stub if resonse json only contains a number or boolean
## Current behavior:

When a `fixture.json` ONLY contains a number or a boolean, cypress throws the following error: 

```
CypressError: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at Object.<anonymous> 
```

### Desired behavior:

For Cypress to accept fixtures that contain a number or a boolean only.

### Steps to reproduce: (app code and test code)

Fixtures:

content of _my-number.json_:
```json
26
```

content of _my-bool.json_:
```
true
```

Tests:
```js
 // fails:
    it('accepts a number', () => {
        cy.server();
        cy.route({method: 'GET', url: '/getnumber', response: 'fixture:my-number.json'}).as('mynumber');
        cy.visit('/');
        cy.wait('@mynumber').its('responseBody').should('be', 26);
    });

    // fails:
    it('accepts a boolean', () => {
        cy.server();
        cy.route({method: 'GET', url: '/getbool', response: 'fixture:my-bool.json'}).as('mybool');
        cy.visit('/');
        cy.wait('@mybool').its('responseBody').should('be', true);
    });
```

repo: https://github.com/amberjs/cypress-test-tiny

### Versions

Cypress 3.2.0 - 3.4.1
Chrome

### PR DESCRIPTION
**Pull request by mrmodise**
* Closes #4899 

### User facing changelog

Fixes an issue on XHR stub where by the response json has number/boolean primitives

### PR Tasks

* [x] Have tests been added/updated?
* [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
* [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
* [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
* [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
I'm not sure why your PRs aren't triggering our circleCI tests. Maybe because you're force pushing? Maybe it's happening for other outside contributors?

**Comment by mrmodise** [comment]
> I'm not sure why your PRs aren't triggering our circleCI tests. Maybe because you're force pushing? Maybe it's happening for other outside contributors?

I checked a lot of them and they're failing but let me push without forcing and see the difference

**Comment by mrmodise** [comment]
@jennifer-shehane still hangs 😢. Do we merge or rebase to include latest develop changes?

**Comment by mrmodise** [comment]
> I'm not sure why your PRs aren't triggering our circleCI tests. Maybe because you're force pushing? Maybe it's happening for other outside contributors?

I think its happening for other outside of contributors. I tried to trace the issue and all contributors' pipelines are passing. Big ups! CircleCI 😆

**Comment by jennifer-shehane** [comment]
Usually you can do an empty commit to trigger the CI run if it didn't run the first time, but there may be something up with your commits that isn't triggering it. I made a commit to see if it will trigger.

**Review by jennifer-shehane — APPROVED** [review]
This looks good if all the tests pass. Thanks for the fix! 👍

**Pull request merged**
