### PR TITLE
fix: add baseUrl to TestConfigOverrides

### PR DESCRIPTION
**Pull request by imadx**
- Closes https://github.com/cypress-io/cypress/issues/22374
- Closes https://github.com/cypress-io/cypress/issues/22072

### User-facing changelog

Corrected the Typescript types to include `baseUrl` as a valid test config override option. Fixes [#22374](https://github.com/cypress-io/cypress/issues/22374) and [#22072](https://github.com/cypress-io/cypress/issues/22072).

### Additional details

The documentation mentions that `baseUrl` is also configurable and can be changed at run time.  
https://docs.cypress.io/guides/references/configuration#Test-Configuration

However, the types are missing `baseUrl` there for `TestConfigOverrides`.

### Steps to test

Updating `baseUrl` in a test with `Cypress.config("baseUrl", baseUrl);` can be used to test the behaviour.

#### Before
image

#### After
There is no typescript warning

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by lmiller1990** [comment]
Do we still get a warning if we do:

```ts
import { defineConfig } from 'cypress'

export default defineConfig({
  baseUrl: 'http://...'
})
```

This should be invalid. The valid way would be:

```ts
import { defineConfig } from 'cypress'

export default defineConfig({
  e2e: {
    baseUrl: 'http://...'
  }
})
```

It looks like this should still work as expected, just looking to clarify.

Also, we might want to verify (and add a test, if we haven't got one) that these types work:

```ts
it('something', { baseUrl: '...' }, () => {
  // ...
})
```

We have no way to know at compile time if the current test is `e2e` or `component`, so I think we just need to allow this.

**Comment by imadx** [comment]
[@imiller](https://github.com/lmiller1990) thanks for checking!!

> Do we still get a warning if we do:
> 
> ```ts
> import { defineConfig } from 'cypress'
> 
> export default defineConfig({
>   baseUrl: 'http://...'
> })
> ```
> 
> This should be invalid. The valid way would be:
> 
> ```ts
> import { defineConfig } from 'cypress'
> 
> export default defineConfig({
>   e2e: {
>     baseUrl: 'http://...'
>   }
> })
> ```
 :point_down: This still warns as expected when trying to use `baseUrl` in the parent level
image

---

> Also, this might fix #22072. If it's not too much extra work, could you see if this issue is fixed by your change? (and ideally add a test, if we haven't got one). This should work and be correctly typed, now, too:
> 
> ```ts
> it('something', { baseUrl: '...' }, () => {
>   // ...
> })
> ```
> 
> We have no way to know at compile time if the current test is `e2e` or `component`, so I think we just need to allow this.

There are existing `.js` tests for `testconfigOverrides` [from the looks of it](https://github.com/cypress-io/cypress/pull/22445/commits/3a6b95ee2d8a2a700a08c28ae88a7ba0648a6ee9#diff-facdf706a5238380b5e97c040bc1a5f5cb89e3116f878754dd7fb4e693787715R36). 
I updated the typings-related tests [here](https://github.com/cypress-io/cypress/pull/22445/commits/3a6b95ee2d8a2a700a08c28ae88a7ba0648a6ee9#diff-facdf706a5238380b5e97c040bc1a5f5cb89e3116f878754dd7fb4e693787715R36)

**Review by ryanthemanuel — APPROVED** [review]
Looks good and does close https://github.com/cypress-io/cypress/issues/22072 as well. I added that to the description. Thanks for the PR!

**Review by emilyrohrbough — APPROVED** [review]

**Comment by lmiller1990** [comment]
I re-pushed the same commit and created a new CI run, and the failing tests are fine: https://github.com/cypress-io/cypress/compare/issue-22445-rerun

The fails here are some unrelated. I'm confident they are not related to this change, I am going to merge this.

**Comment by lmiller1990** [comment]
I am stilli finding out the problem with CI. Please wait a bit - I'm going to get this merged as soon as I find out why your branch fails, but my identical fork doesn't.

**Comment by imadx** [comment]
@lmiller1990, is it okay if I rebase from `cypress-io:develop` and push the changes?
There seem to be quite a few changes from several contributions there.

Or if you have a passing fork, I think it's okay if we can get that merged if someone is waiting on this.

**Comment by imadx** [comment]
I actually have the rebased changes here at https://github.com/cypress-io/cypress/pull/22532
Don't have permission though to get the tests to run from the looks of it.

**Comment by lmiller1990** [comment]
Thanks, I merged in develop that should have a fix that might help with the CI. Specifically this PR landed https://github.com/cypress-io/cypress/pull/22326. Let's see how it goes.

**Comment by lmiller1990** [comment]
We did it, it's passing. Let's merge.

**Comment by imadx** [comment]
Nice one. Thanks, @lmiller1990 for getting this through :rocket:

**Comment by lmiller1990** [comment]
It should be out in 10.3.0!

**Pull request merged**
