### PR TITLE
Rename configuration option blacklistHosts

### PR DESCRIPTION
**Pull request by laiscoolblue**
- Closes N/A

### User facing changelog

Rename configuration option from `blacklistHosts` to `blockHosts`

### Additional details

- This PR renames all instances of the configuration option `blacklistHosts` to `blockHosts`.
- This PR also changes all occurrences of the word `blacklist` throughout the codebase.

### How has the user experience changed?

Now when using `blacklistHosts`, there is an error thrown and the process exits. 

Screen Shot 2020-06-26 at 11 43 11 AM

Making it more inclusive by replacing terms that can be perceived as offensive to more self-explanatory names (blacklist/whitelist can reinforce the association of black as bad and white as good).

Examples of projects that already made the change:
[Rails](https://github.com/rails/rails/issues/33677)
[Golang](https://go-review.googlesource.com/c/go/+/236857/)
[Graphite Web](https://github.com/graphite-project/graphite-web/pull/1700)
[HTML](https://github.com/whatwg/html/commit/cb3316db45e369ba31d97c5ee2dcd9c353a3cb5d)

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/2861
- [x] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@laiscoolblue Thanks for the contribution! Could you please sign our CLA?

This would be a breaking change, so wouldn't be able to go in as quickly as we may like. We would have to update all docs and some of the on shortcut links also to get this in.

**Comment by JessicaSachs** [comment]
Hmmm... Can we support both for the near-term so that people can adapt their codebases to use blocklist immediately and then we will deprecate blacklist?

**Comment by laiscoolblue** [comment]
> @laiscoolblue Thanks for the contribution! Could you please sign our CLA?
> 
> This would be a breaking change, so wouldn't be able to go in as quickly as we may like. We would have to update all docs and some of the on shortcut links also to get this in.

The CLA is signed. There's a PR open for the documentation as well: https://github.com/cypress-io/cypress-documentation/pull/2861

**Comment by jennifer-shehane** [comment]
Need to add deprecation warnings but want to wait until the error.js file is cleaned up from https://github.com/cypress-io/cypress/issues/7629

**Comment by jennifer-shehane** [comment]
I'll take another look at this Monday now that https://github.com/cypress-io/cypress/issues/7629 is in.

**Comment by zenblender** [comment]
Related but for a separate PR: I'd like to see consideration for renaming the "whitelist" Cypress options for cookies to something more appropriate as well, such as "allow list" or "persist list".

**Comment by jennifer-shehane** [comment]
I updated this to issue a deprecation warning, but it seems like we will be releasing a breaking version very soon, so I'll have to update the work again back to breaking changes. :P 

@zenblender Yes, definitely another issue/PR that we'd be happy to address.

**Comment by jennifer-shehane** [comment]
@zenblender Opened a PR for whitelist changes https://github.com/cypress-io/cypress/pull/7782

**Comment by chrisbreiding** [comment]
I feel like the equivalent to 'blacklist' is 'block' and not 'blocklist', so it should be 'blockHosts'. I also worry folks will think 'blocklist' is a typo or misread it in the docs as 'blacklist' and make the typo themselves, so differentiating it a bit more will help with that.

**Comment by jennifer-shehane** [comment]
Think I'm going to rename this to `blockHosts` after some thought honestly.

**Comment by jennifer-shehane** [comment]
@chrisbreiding This is funny, I didn't even see your comment above. I had just been thinking about it for days 😆 Glad there's consensus!

**Comment by Saibamen** [comment]
Don't make stupid breaking changes

**Pull request merged**
