### PR TITLE
fix: format special characters correctly

### LINKED ISSUE #5679: 3.6.1 Special characters wrongly displayed in runner UI assertions
### Current behavior:

cypress

### Desired behavior:

Special characters properly displayed

### Steps to reproduce: (app code and test code)

for e.g. use assertion with regex:
should('match', /width: (50.*|49.*|48.*)%;/)

### Versions

3.6.1

### PR DESCRIPTION
**Pull request by gitstart**
- Closes #5679 

#### Bugfixes:
- Updated the reporter to correctly render special characters. Previously special characters would be automatically formatted with markdown.

### Additional details

A number of users reported having faced this issue and that they needed a fix for it. Please refer to https://github.com/cypress-io/cypress/issues/5679 and https://github.com/cypress-io/cypress/issues/7419 for more context. 

Only assertions using ` to.match()` and `to.equal()` with special characters are affected by this change, the rest of the assertions and content in the reporter will stay largely unaffected.

This change checks for all messages containing `to match()` or `to equal()` and then converts the message to markdown as before but this time it does not convert the assertion. It then wraps the assertion in `<strong>${assertion}</strong>` to make it appear bold.

### How has the user experience changed?

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>Screenshot 2022-05-28 at 04 22 57
</td>
    <td>Screenshot 2022-05-28 at 04 29 27</td>
  </tr>
</table>

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by rachelruderman** [comment]
Good stuff, thank you @gitstart! Just add test coverage and we'll be good to go 🎉

**Comment by gitstart** [comment]
> > Good stuff, thank you @gitstart! Just add test coverage and we'll be good to go 🎉
> 
> Thanks @rachelruderman, Let me add that and push a commit

@rachelruderman I believe the tests for the reporter are in `packages/reporter/cypress/e2e/`. I still haven't figured out how to test this, any help offered will be appreciated 😞

**Comment by rachelruderman** [comment]
@gitstart thanks for your patience!!

I'd recommend adding a new file with some unit tests in [packages/reporter/cypress/e2e/unit](https://github.com/cypress-io/cypress/blob/develop/packages/reporter/cypress/e2e/unit). It can look something like this:
```
import { formattedMessage } from 'path/to/file'
describe('formattedMessage', () => {
   it('returns empty string when message is falsy', () => {
       const result = formattedMessage(null);
       expect(result).to.equal('');
   })
   it('maintains special characters when using "to match"', () => {
     const specialMessage = "expect '|^\' to match '|^\'"
     const result = formattedMessage(specialMessage)
     expect(result).to.equal('whateveritshouldbe')
   })
   it('maintains special characters when using "to contain"', () => {
     const specialMessage = "expect '|^\' to contain '|^\'"
     const result = formattedMessage(specialMessage)
     expect(result).to.equal('whateveritshouldbe')
   })
   it('does NOT maintain special characters when "to contain" or "to match" are not in assertion', () => {
     const specialMessage = "expect '|^\' to equal '|^\'"
     const result = formattedMessage(specialMessage)
     expect(result).to.equal('whateveritshouldbe')
   })
}
```

By the way, I see the same `formattedMessage` function in [packages/reporter/src/errors/test-error.tsx](https://github.com/cypress-io/cypress/blob/e6b2466f7b219a86da46c1ac720432ef75193ca4/packages/reporter/src/errors/test-error.tsx#L57). It seems like this one should be updated as well, per your screenshots

**Comment by v1b3m** [comment]
Hey @rachelruderman What do you think?

**Comment by gitstart** [comment]
Hey @rachelruderman What do you think?

**Review by rachelruderman — APPROVED** [review]
LGTM, thx for your contribution!!

**Comment by rachelruderman** [comment]
@v1b3m can you please sign the [CLA](https://github.com/cypress-io/cypress/pull/22215#issuecomment-1150812937)?

**Comment by gitstart** [comment]
> @v1b3m can you please sign the [CLA](https://github.com/cypress-io/cypress/pull/22215#issuecomment-1150812937)?

Signed

**Review by tbiethman — APPROVED** [review]
Thank you for the contribution @gitstart and @v1b3m ! Can you please pull in the changes from the develop branch so we can verify the builds before merging?

**Comment by gitstart** [comment]
> Thank you for the contribution @gitstart and @v1b3m ! Can you please pull in the changes from the develop branch so we can verify the builds before merging?

@tbiethman I've merged the latest develop

**Comment by rachelruderman** [comment]
Hi @gitstart ! It looks like the CI builds are hanging with status `Unauthorized`. We haven't come across this issue before but we're thinking if someone at Cypress pushes to your branch, this might solve it. I tried to push an empty commit to your branch but I'm getting `Authentication failed`. 

Is your fork protected? If so, can you disable protection so I can push? 

Thanks for your contribution and your patience! 🙏 😄

**Comment by gitstart** [comment]
> Hi @gitstart ! It looks like the CI builds are hanging with status `Unauthorized`. We haven't come across this issue before but we're thinking if someone at Cypress pushes to your branch, this might solve it. I tried to push an empty commit to your branch but I'm getting `Authentication failed`.
> 
> Is your fork protected? If so, can you disable protection so I can push?
> 
> Thanks for your contribution and your patience! 🙏 😄

Alright @rachelruderman let me get back to you on this

**Comment by gitstart** [comment]
Hi @rachelruderman, we will need to close this PR and will open a new one, the current fork(repo) does not allow the option “Allow edits by maintainers”. 

I'm so sorry about this. #22537 is the new PR with the same exact changes

**Comment by rachelruderman** [comment]
> Hi @rachelruderman, we will need to close this PR and will open a new one, the current fork(repo) does not allow the option “Allow edits by maintainers”.
> 
> I'm so sorry about this. #22537 is the new PR with the same exact changes

Thank you and no apology needed at all! Closing this PR now 🙂

**Pull request closed without merging**
