### PR TITLE
fix: Ensure binary request body is not mutated by cy.intercept

### LINKED ISSUE #15898: [7.0.1]Bug: uploading a fixture break Cypress
I upgraded Cypress from 5.5.0 to 6.8.0 noticing a issue with the uploading from images as fixtures.
This issue was present also when one manually uploads a image to the tested site.
Since this issue, manifested after the update, I updated to 7.0.0 (and to 7.0.1 for that matter).

### Current behavior

Cypress breaks when uploading an Image, thus stoping execution.

### Test code to reproduce

This is the breaking part of the test,
while "cy.wait('imageRequest')" is open during it it breaks.

Due to some uncertainty in confindelity I sadly can't publish the full test.

```js
cy.fixture('testimage.png').as('image')
cy.get('.block').last().within(() => {
    cy.get('.grid-row .grid-column .plugin-image .form input[type=file]').then(function (el) {
    cy.wait('@imageRequest')
    // cy.wait('@pageSaveRequest')
    // convert the image base64 string to a blob
    const blob = Cypress.Blob.base64StringToBlob(this.image, 'image/png')

    const file = new File([blob], 'testimage.png', { type: 'image/png' })
    const list = new DataTransfer()

    list.items.add(file)
    const myFileList = list.files

    el[0].files = myFileList
    el[0].dispatchEvent(new Event('change', { bubbles: true }))
    })
})
```

### Error Message

```
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (137)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (/path/from/userTo/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:1496:27)
    at /path/from/userTo/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (/path/from/userTo/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:545:23)
    at Immediate._onImmediate (/path/from/userTo/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:578:7)
    at processImmediate (internal/timers.js:461:21)
 {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (137)
    at write_ (_http_outgoing.js:696:11)
    at ClientRequest.write (_http_outgoing.js:661:15)
    at Request.write (/path/from/userTo/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:1496:27)
    at /path/from/userTo/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:546:20
    at Array.forEach (<anonymous>:null:null)
    at end (/path/from/userTo/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:545:23)
    at Immediate._onImmediate (/path/from/userTo/Caches/Cypress/7.0.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:578:7)
    at processImmediate (internal/timers.js:461:21)
```

### Versions
It works in 5.5.0,
from 6.0.1 it doesn't work but did not brake,
from 7.0.0 it breaks Cypress.

### LINKED ISSUE #16223: ERR_INVALID_ARG_TYPE still present after the fix
https://github.com/cypress-io/cypress/issues/15901
```
Fixed a regression in 7.0.0 that caused the Test Runner to crash with an ERR_INVALID_ARG_TYPE type error. We now correctly detect a utf8 request body with multi-byte Unicode characters. Fixes #15901.
```
It's still present in my tests. I'm using cypress-file-upload plugin and it happens when I want to upload an image file. Crashes the whole run.

```
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (45)
```

Version 7.2.0

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #15898
- Closes #16223

### User facing changelog

- Cypress no longer crashes with an error when testing a binary file upload

### Additional details

We recursively merge request properties after running the request through middleware, but in the case of a binary request body, which is a buffer, lodash identifies it as an array and the merging turns it into an array of numbers. That causes the error when it hits `request`, because it loops through the array and tries to write numbers into the request, which are invalid. It needs to remain a buffer for `request` to properly write it.

This fixes it by not trying to recursively merge binary buffers but overwriting them entirely after middleware runs.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by flotwig — APPROVED** [review]
> lodash identifies it as an array and the merging turns it into an array of numbers

:exploding_head: 

Nice fix!

**Comment by verheyenkoen** [comment]
Is there a pre-release for this PR?

**Comment by chrisbreiding** [comment]
@verheyenkoen Yes! You can find the [relevant pre-release url here](https://github.com/cypress-io/cypress/commit/5c453115334e290af66b3594a19e4e455cfa7596#commitcomment-50340512).

**Comment by verheyenkoen** [comment]
@chrisbreiding Nice. This would fix my [test case](https://github.com/cypress-io/cypress/issues/15898#issuecomment-827384864). Great work!

**Pull request merged**
