### PR TITLE
chore(deps): downgrade electron to v12.0.0-beta.14

### LINKED ISSUE #15853: [7.0.0] Performance regression from 6.8 (over 3x slower in our test suite)
I have split this off from the performance regression issue related to `6.6` - `6.7` #15779

Can also confirm our tests are taking way longer in `v7.0.0` than the were in `v6.8.0`

Also, because the tests are taking longer, we get random failing tests due to timeout issues.

Im not sure what info i can give you to help you debug this, but if there is anything you need me to do, just ask.

# Our last few CI runs
Screenshot 2021-04-07 at 10 44 13

# v6.8.0
Screenshot 2021-04-07 at 10 47 45

# v7.0.0
(including a random failing test due to a timeout)
Screenshot 2021-04-07 at 10 47 28

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #15853 

### User facing changelog

- Fixed an issue causing tests to run slowly after upgrading to 7.0.0, especially when run with constrained CPU resources.
- Downgradeded bundled Chrome version to 87.

### Additional details

Electron v12.0.0-beta.16 and above contain an unknown bug causing a major slowdown when video recording is enabled. For now maybe we can downgrade Electron to this last known good version, v12.0.0-beta.14

### PR Tasks

- [ ] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by agg23** [comment]
Can you post `time -p` measurements for Chrome and Electron headless before and after this change?

**Comment by flotwig** [comment]
> Can you post `time -p` measurements for Chrome and Electron headless before and after this change?

The Electron version has no impact on the Chrome times. If you upgrade Chrome to a version 89.0.4389 or higher, you can reproduce this in Chrome, regardless of Electron version. I haven't been able to find the Chromium bug for this yet.

I ran `actions.spec.js` using `--browser electron` inside of Docker with `--cpus=2`. The Electron measurements were:

Electron Version | Cypress Test Duration | real | user | sys | Good?
--- | --- | --- | --- | --- | ---
11.2.3 | 0:16 | 0:25 | 0:28 | 0:04 | :heavy_check_mark: 
12.0.0-beta.14 | 0:17 | 0:25 | 0:29 | 0:04 | :heavy_check_mark: 
12.0.0-beta.16 | 0:58 | 1:13 | 1:50 | 0:31 | :x:
12.0.4 | 0:47 | 1:01 | 1:31 | 0:24 | :x:

**Comment by agg23** [comment]
> The Electron version has no impact on the Chrome times. If you upgrade Chrome to a version 89.0.4389 or higher, you can reproduce this in Chrome, regardless of Electron version.

Did you experimentally confirm this? Intellectually I know that should be the case, but some of the results I was seeing was that Chrome results were changing as I changed Electron versions.

**Comment by flotwig** [comment]
> Did you experimentally confirm this? Intellectually I know that should be the case, but some of the results I was seeing was that Chrome results were changing as I changed Electron versions.

Yeah, here are my results running with Electron 12.0.4 but in `--browser chrome`:

Chrome Version | Cypress Test Duration | real | user | sys | Good?
--- | --- | --- | --- | --- | ---
88.0.4324.182 | 0:33 | 1:02 | 1:38 | 0:11 | :heavy_check_mark: 
88.0.4324.182 | 0:37 | 1:16 | 2:07 | 0:12 | :heavy_check_mark: 
89.0.4389.72 | 1:09 | 1:58 | 3:21 | 0:27 | :x:
89.0.4389.72 | 1:48 | 2:51 | 4:58 | 0:38 | :x:
90.0.4430.72 | 2:00 | 3:28 | 6:08 | 0:42 | :x:

**Comment by flotwig** [comment]
I'm not sure. Some of the difference is because Chrome has to be spawned as an independent process, I think it's faster for Electron to do `new BrowserWindow` than it is for us to do `child_process.spawn('chrome')`

**Review by agg23 — APPROVED** [review]

**Review by chrisbreiding — APPROVED** [review]

**Comment by effrenus** [comment]
@flotwig Is it possible the problem because of this change: https://github.com/chromium/chromium/blob/d7da0240cae77824d1eda25745c4022757499131/content/browser/devtools/devtools_video_consumer.cc#L25?
Some details: https://www.notion.so/effrenus/Cypress-screencast-frame-rate-62dfe13d2efa46ebaf9a90957b3ee32a

**Comment by flotwig** [comment]
@effrenus possibly, I have noticed that Electron 12.0.0-beta.16 sends roughly twice as many frames per minute as 12.0.0-beta.14. Good find.

**Pull request merged**
