### PR TITLE
chore: replace gitter badge with discord on readme

### LINKED ISSUE #26764: README links to gitter
### What would you like?

 Replace gitter in [README](https://github.com/cypress-io/cypress/blob/develop/README.md) by Discord.

 Add a Discord badge (see https://shields.io/category/chat).

### Why is this needed?

The [README](https://github.com/cypress-io/cypress/blob/develop/README.md) links to:

  <a href="https://gitter.im/cypress-io/cypress">
    Gitter chat
  </a>

  (`https://gitter.im/cypress-io/cypress`)

  which is not in alignment with the issue templates e.g. [1-bug-report.yml](https://raw.githubusercontent.com/cypress-io/cypress/develop/.github/ISSUE_TEMPLATE/1-bug-report.yml) which say:

 ### Have a question? 👉 [Ask in chat](https://on.cypress.io/discord)
 (`https://on.cypress.io/discord`)

### Other

_No response_

### PR DESCRIPTION
**Pull request by elylucas**
- closes #26764

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by elylucas** [comment]
waiting for confirmation on the correct discord url to use

**Review by emilyrohrbough — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@elylucas 

There seem to be multiple URLs used in various places to point to Discord:

- https://on.cypress.io/chat
- https://on.cypress.io/discord
- https://discord.com/invite/cypress
- https://discord.gg/cypress

That is something that perhaps could be harmonized across the repositories?

**Review by jennifer-shehane — APPROVED** [review]

**Review by MikeMcC399 — APPROVED** [review]
LGTM!
Many thanks for picking up this issue and resolving it!

**Review by nagash77 — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@nagash77 

Could this be merged now?
Many have approved. No one is assigned.

**Comment by elylucas** [comment]
@nagash77 I'll assign this one over to you as I'm not sure about the unrelated failing tests and how to resolve those.

**Comment by MikeMcC399** [comment]
Maybe sorting out the tests could be tracked in a separate issue since these are unrelated to changing the chat badge?

**Pull request merged**
