### PR TITLE
docs: add contributor instructions for Python 3.11 on Ubuntu 24.04

### PR DESCRIPTION
**Pull request by MikeMcC399**
### Additional details

Ubuntu `24.04` ships with Python `3.12`, which is not compatible with the Cypress `yarn` build process. Ubuntu `24.04` is currently available as a beta version and the [planned release date](https://wiki.ubuntu.com/Releases) is April 2024.

If the pre-installed Python `3.12` version of Ubuntu `24.04` is used by `yarn install` then the build encounters the errors described in https://github.com/cypress-io/cypress/issues/28695 when it attempts to install the npm modules:

- [registry-js](https://www.npmjs.com/package/registry-js)
- [cpu-features](https://www.npmjs.com/package/cpu-features)

The error messages include the following line caused by a breaking change in Python `3.12` which is incompatible with the version of `node-gyp` currently used by Cypress:

> ModuleNotFoundError: No module named 'distutils'

This PR adds instructions to the [CONTRIBUTING](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) document to install Python `3.11` on Ubuntu `24.04` in addition to the pre-installed Python `3.12` version. Python `3.11` is the highest version compatible with the Cypress Yarn build process.

Note: Cypress will build using the default pre-installed versions of Python on earlier versions of Ubuntu (`20.04`, `23.10` and `22.04`). These Ubuntu versions have Python versions `3.8`, `3.10` and `3.11` respectively pre-installed and so no changes in instructions are necessary for these Ubuntu versions.

### Installation instructions

These instructions are intended for Ubuntu `24.04` only:

Execute

```shell
sudo apt install python3.11
```

Add the following to `~/.bashrc`

```shell
export NODE_GYP_FORCE_PYTHON=/usr/bin/python3.11
```

### Steps to test

On Ubuntu `24.04` apply the above installation instructions, then execute:

```bash
sudo apt install git g++ make curl
curl -L https://bit.ly/n-install | bash
. ~/.bashrc
cd ~
git clone https://github.com/cypress-io/cypress
cd cypress
n auto
npm install yarn -g
yarn
```

The build log should contain the following steps with no errors recorded between these two lines:

```text
[5/6] Building fresh packages...
[6/6] Cleaning modules...
```

### How has the user experience changed?

This is a documentation change which affects only contributors to Cypress. There is no change to the user experience of end-users.

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Preview on https://github.com/MikeMcC399/cypress/blob/ubuntu-24/python-3-11/CONTRIBUTING.md#requirements

**Comment by MikeMcC399** [comment]
The section Requirements was re-arranged to accommodate the additional instructions. These are shown in the screenshot in green:

image

**Review by jennifer-shehane — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]

**Comment by MikeMcC399** [comment]
https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890#toolchain-upgrades-9 documents:

Python :snake: now defaults to version 3.12

**Comment by MikeMcC399** [comment]
- Python 3.11 has been requested for availability on Ubuntu 24.04 - see https://github.com/deadsnakes/issues/issues/282 (independent project)

**Comment by MikeMcC399** [comment]
See https://launchpad.net/%7Edeadsnakes/+archive/ubuntu/ppa

```shell
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install python3.11
```

**Pull request merged**
