### PR TITLE
chore: replace is-ci with underlying ci-info package

### PR DESCRIPTION
**Pull request by TheDevMinerTV**
### Additional details

[`is-ci` just imports the underlying `ci-info` package and exports a single field](https://github.com/watson/is-ci/blob/master/index.js). We might as well just use that package instead and safe ourselves (/NPM) the extra lookup and bandwidth (4kB).

image

`snap-shot-core` uses `is-ci` as well, but it looks unmaintained, so I'm not sure if making a PR there would make sense.

I haven't been able to figure out how to update the `v8-snapshot` cache files, which still include the `is-ci` string.

### Steps to test

Everything should work as expected in CI.

### How has the user experience changed?

This PR saves about 3kB per install, and two HTTP call to NPMs API.

```
Package info for "cypress@13.15.1": 24 MB
  Released: 2024-10-24 17:21:11.219 +0000 UTC (1d ago)
  Downloads last week: 26,802 (0.48%)
  Estimated traffic last week: 629 GB
  Subdependencies: 173

Removed dependencies:
  - is-ci@3.0.1: 31 kB (0.13%)
    Subdependencies: 1 (0.57%)

Added dependencies:
  + ci-info@4.0.0: 28 kB (0.11%)
    Subdependencies: 0 (0%)
```

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@TheDevMinerTV Thanks for your contribution. I've kicked off the tests to ensure they pass before reviewing.

**Comment by TheDevMinerTV** [comment]
The same tests seem to be failing in `develop` as well.

**Comment by TheDevMinerTV** [comment]
Seems like CircleCI is broken... Both pipelines are shown as running, but the tasks inside them are already complete.

**Comment by jennifer-shehane** [comment]
@TheDevMinerTV Yah, they were having issues yesterday 🙄

**Review by jennifer-shehane — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]

**Pull request merged**
