### PR TITLE
fix(npm/react): webpack config sample bug

### PR DESCRIPTION
**Pull request by lanshunfang**
- Closes 

### User facing changelog

Fix Webpack config sample bug in `cypress/plugin/index.js`

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@lanshunfang Could you describe the problem you were facing before this fix exactly? Also, any way to add a test around this fix?

**Comment by lmiller1990** [comment]
I guess this just demonstrates how to use the `webpackFilename` option, [shown here](https://github.com/cypress-io/cypress/blob/160170ef56cc4501b1c11585465a176541ccd729/npm/react/plugins/load-webpack/index.js#L20)?

If that assumption is correct, and we are adding this to the example, we probably should also include what/when this option is useful.

**Comment by lanshunfang** [comment]
> I guess this just demonstrates how to use the `webpackFilename` option, [shown here](https://github.com/cypress-io/cypress/blob/160170ef56cc4501b1c11585465a176541ccd729/npm/react/plugins/load-webpack/index.js#L20)? 🤔
> 
> If that assumption is correct, and we are adding this to the example, we probably should also include what/when this option is useful.

Yes it is. 

In addition to that, it's not just a demo, but a bug fix. As you could see, the code you pasted destruct `webpackFilename` from the third argument which is not passed in. That creates a JS error (couldn't read `webpackFilename` of undefined)

**Review by lmiller1990 — APPROVED** [review]

**Comment by elevatebart** [comment]
only white space changes but I don't mind merging it.

**Pull request merged**
