### PR TITLE
fix: #29605 for display: contents parent visibility with correct width check

### LINKED ISSUE #29605: Cypress incorrectly uses the box model of elements that have `display:contents` when determining visibility of child elements
### Current behavior

Elements that have overflow:hidden and an effective width or height of 0, but are set to `display: contents`, will incorrectly be determined as not visible.

### Desired behavior

Cypress should correctly disregard any calculations regarding the box model of elements that have `display: contents`, as. these elements are effectively replaced by their children. See: https://drafts.csswg.org/css-display/#valdef-display-contents

### Test code to reproduce

With the DOM:

```html
<div id="parent" style="overflow: hidden; height: 0; width: 0; display: contents;">
    <div id="child" style="height:200px; width: 200px; background: #f00"></div>
</div>
```

Cypress wil determine that `#child` is not visible:

```js
cy.get('#child').should('be.visible') // this will fail due to overflow:hidden and effective 0 width and/or height, despite display: contents
```

However, this element is clearly visible, as the browser effectively replaces the `#parent` element with `#child` when rendering.

### Cypress Version

13.11.0

### Node version

v18.17.1

### Operating System

macOS 14.3

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by senpl**
- Closes https://github.com/cypress-io/cypress/issues/29605
As discussed in https://github.com/cypress-io/cypress/pull/29224 in separate part.

### Additional details
I implemented solution proposed in https://github.com/cypress-io/cypress/pull/29224 still I have to add width and height check because without them element was still visible as with 0 width.
This time it is clear from most other commits and only core changes to make this work.

### Steps to test
html
  <div id="parent" style="overflow: hidden; display: contents;">
    <div id="child" style="height:200px; width: 200px; background: #f00"></div>
  </div>
test
    cy.get('#child').should('be.visible')

### How has the user experience changed?
Users has to use {force: true} to click such elements, checking thier visibility was not possible. Now it should be possible

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by senpl** [comment]
now it looks like internal error in build for unit tests.

**Comment by senpl** [comment]
This looks like unit-tests fail during build
lib/ca #generateServerCertificateKeys generates certs for each host:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Review by jennifer-shehane — DISMISSED** [review]
@senpl There are failures in the visibility test in firefox. Please run these locally to ensure they pass.

**Comment by jennifer-shehane** [comment]
We've decided to prioritize looking into these visibility fixes in Quarter 4 of this year, when we intend to spend time on Cypress 14 release. It will ease any concerns we have around releasing breaking changes with these fixes and also help us plan the proper time to review these. Tracking here: https://github.com/cypress-io/cypress/issues/29925

**Comment by jennifer-shehane** [comment]
Updated the base branch to go against release/14.0.0

**Review by v1w319 — COMMENTED** [review]
CV],
        "macosx": [
            "--macos=MacOSX",
            "--apple_deploy_target=13.3"
            "--apple_deploy_target=11.0"
        ],
        "iphoneos": [
            "--ios",
            "--apple_deploy_target=13.0"
        ],
        "iphonesimulator": [
            "--ios",
            "--apple_deploy_target=13.0"
        ]
    }
}``

**Review by v1w319 — COMMENTED** [review]
CV],
        "macosx": [
            "--macos=MacOSX",
            "--apple_deploy_target=13.3"
            "--apple_deploy_target=11.0"
        ],
        "iphoneos": [
            "--ios",
            "--apple_deploy_target=13.0"
        ],
        "iphonesimulator": [
            "--ios",
            "--apple_deploy_target=13.0"
        ]
    }
}``

**Review by jennifer-shehane — APPROVED** [review]
I believe this change looks good. I added some extra tests to ensure the elements that do not follow the display: contents rules are interpreted as hidden. 

I don't actually think this would introduce breaking changes and would be just a fix, but I do think it's safer to make the changes in Cypress 14.

**Review by cacieprins — APPROVED** [review]

**Pull request merged**
