### PR TITLE
misc: Update response-middleware.ts cookie expiration date

### LINKED ISSUE #29268: __cypress.initial cookie expired date causing signin side-effects
### Current behavior

Testing Login on a 3rd party website.
`__cypress.initial` cookie is set with domain of the 3rd party (target) website that expires 1970-01-01T00:00:00.000Z. This cookie is visible under the cookie tab of the login request.
As a result, subsequent calls to complete the login fail because of an expired token.

Since I don't own the login page, I can't update the logic. However, I know this is the issue because
I've retested changing the first visit url to another website in order to change the domain of the `__cypress.initial` cookie. Login is successful, but the dashboard page takes forever to load.

### Desired behavior

set `__cypress.initial` cookie with an expire property in the future like 2070-01-01T00:00:00.000Z

### Test code to reproduce

N/A

### Cypress Version

13.7.1

### Node version

v21.2.0

### Operating System

macOS 12.7.3

### Debug Logs

```shell
N/A
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by jj497**
- Addressed in [#29269](https://github.com/cypress-io/cypress/pull/29269).
- Closes [29268](https://github.com/cypress-io/cypress/issues/29268).

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@jj497 We'll need a reproduction of the original issue this is resolving as well as a test demonstrating the issue this is resolving before accepting.

**Comment by jj497** [comment]
Success without cypress initial cookie
Expired Cookie Response
Attached is a screenshot of the failure in the Cypress test suite with the __cypress.initial cookie. As you can see it has the 'athena' domain and comes back with an expired value of '1970-01-01' on the document and the error "You session has timed out....Please login again."
Also attached is another screenshot of success on the same browser, but a different tab. The complete.esp document does not contain the __cypress.intitial cookie and login proceeds as expected.

Because the login is on a 3rd party partner (athena) I can't reproduce the issue myself on our own servers but I hope the attached screenshots are sufficient evidence of the issue.

**Comment by jennifer-shehane** [comment]
@jj497 You'll need to also sign our CLA. Could you sign that?

**Comment by jj497** [comment]
> @jj497 You'll need to also sign our CLA. Could you sign that?

complete!

**Comment by jj497** [comment]
@jennifer-shehane - this PR accidentally closed when I resynced the fork. Could you please help me reopen it?
My changes are here: https://github.com/jj497/cypress/blob/patch-1

**Comment by jennifer-shehane** [comment]
@jj497 Reopened

**Comment by jennifer-shehane** [comment]
@jj497 We'll still need a test that we can run that shows the bug this is fixing. We cannot accept this otherwise. Setting the cookie to a future date has other implications that will break other parts of the codebase.

**Comment by jennifer-shehane** [comment]
Closing since the undesired behavior cannot be confirmed. This would not be a passive change to change this as well.

**Pull request closed without merging**
