### PR TITLE
chore: Fix build path for electron-builder on arm64 linux

### PR DESCRIPTION
**Pull request by kevinresol**
### User facing changelog

Fix build path for electron-builder on arm64 linux

### Additional details

N/A

### How has the user experience changed?

Not for users but for cypress developers: allow compiling the binary on arm64 linux

### PR Tasks

I have read the below but I think all of them are not applicable

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@kevinresol Can you describe in detail the problem that this is solving since there appears to be no issue associated with it. Thanks!

**Comment by kevinresol** [comment]
When building on ARM64 linux, electron-builder outputs to `linux-arm64-unpacked` instead of `linux-unpacked`

**Comment by BlueWinds** [comment]
Took a bit, but I've managed to verify the fix on linux-ARM64. In develop, you currently get the following error:
image

while this PR gets past there and lets me build the binary.

As we don't have any automated tests around the binary build scripts, I'm inclined to approve as-is.

**Comment by BlueWinds** [comment]
I also added a comment linking to this PR, which can help future developers figure out exactly why a change was made.

**Review by BlueWinds — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

**Pull request merged**
