### PR TITLE
chore(deps): update dependency cypress-example-kitchensink to v2.0.2

### PR DESCRIPTION
**Pull request by MikeMcC399**
### Additional details

Updates [packages/example](https://github.com/cypress-io/cypress/tree/develop/packages/example) to use [cypress-example-kitchensink@2.0.2](https://github.com/cypress-io/cypress-example-kitchensink/releases/tag/v2.0.2).

### Steps to test

There are no changes to tests in this release. There are only text changes to the repo's description marking it as an E2E testing example.

### How has the user experience changed?

This version changes the text on https://example.cypress.io/ to the following:

 image

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### Next steps

https://github.com/cypress-io/cypress/blob/develop/packages/example/README.md#updating-the-example-app instructs to run

```shell
yarn workspace @packages/example deploy
```

I can do this directly from a fork, however that only results in the site being deployed to the `gh-pages` branch in my fork. So it makes more sense for somebody with write access to the main repo to do it.

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
Seems we can't get the tests to pass due to recent tests added, we're looking into it: https://github.com/cypress-io/cypress/issues/29072

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Seems we can't get the tests to pass due to recent tests added, we're looking into it: #29072

- Thanks for the link to #29072! Hopefully you'll be able to remove this roadblock soon!

**Comment by jennifer-shehane** [comment]
The issue with the failing tests has been resolved, so going to work on merging this in. Hold off on pulling in develop unless there are conflicts.

**Comment by jennifer-shehane** [comment]
Seems there's another issue with a newly introduced test around the `system-tests-firefox` with the new screenshot behavior. We're investigating.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Do you still want to process this PR?

[cypress-example-kitchensink@2.0.2](https://github.com/cypress-io/cypress-example-kitchensink/releases/tag/v2.0.2) is now superseded by
[cypress-example-kitchensink@2.0.3](https://github.com/cypress-io/cypress-example-kitchensink/releases/tag/v2.0.3) and that would need to be a new PR. This latest version has content changes to the scaffolded tests regarding chaining corrections, so that should probably be processed as a fix with an entry in the changelog.

I'll leave it to you if you want to close this PR or not.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 I'll merge this and another PR can be updated. We're doing a release today so this will at least get in.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> I'll merge this and another PR can be updated. We're doing a release today so this will at least get in.

That's fine! I'll follow up again in the next couple of days as the GitHub pages sourcing https://example.cypress.io/ also need to be updated.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Yah I think that's done as part of the release process, so let us know if you don't see the changes published when the App is published. We haven't republished it in a while.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Yah I think that's done as part of the release process, so let us know if you don't see the changes published when the App is published. We haven't republished it in a while.

- I have seen PR https://github.com/cypress-io/cypress/pull/29123 picking up [cypress-example-kitchensink@2.0.3](https://github.com/cypress-io/cypress-example-kitchensink/releases/tag/v2.0.3) so that is going into the next Cypress release without any corresponding changelog entry. Using the new `cypress-example-kitchensink@2.0.3` release means that the examples automatically get updated. I don't think that this automatically publishes anything to https://example.cypress.io/ though otherwise the intro text would have already changed. Let's wait until `13.7.0` is released and take it from there.

**Comment by MikeMcC399** [comment]
It seems like https://github.com/cypress-io/cypress/commit/c161eb53cb8b404ca305091878c52681232181dd is attempting to take care of the update to https://example.cypress.io/ although the page is currently lacking formatting.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 We're looking at this

**Comment by jennifer-shehane** [comment]
@MikeMcC399 The site is fixed by rolling back the commits, so the new changes are not out. We need to investigate our deploy process. There's something that broke since we last deployed and it was never noticed. We'll open a new issue on the cypress repo to track this.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> The site is fixed by rolling back the commits, so the new changes are not out. We need to investigate our deploy process. There's something that broke since we last deployed and it was never noticed. We'll open a new issue on the cypress repo to track this.

Thanks for picking this up!

At least now the scaffolded examples are in a much cleaner condition regarding correct chaining.

**Pull request merged**
