### PR TITLE
feat: Merge in cypress-react-unit-test

### PR DESCRIPTION
**Pull request by dmtrKovalenko**

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@dmtrKovalenko Make sure to always pull against `develop` branch - nothing goes directly into `master`. I think the PR is a bit messed up since this was originally opened against master. You may need to reopen this pull request.

**Comment by dmtrKovalenko** [comment]
@jennifer-shehane set base as master was in guideline of merging project in monorepo. cc @JessicaSachs

**Comment by jennifer-shehane** [comment]
@dmtrKovalenko My bad, I see the updates now. Carry on. Although we need the CLA signed by @larrifax - there is a commit by them pulled into this PR.

**Comment by larrifax** [comment]
CLA signed

**Comment by JessicaSachs** [comment]
@jennifer-shehane FYI we do _not_ need the CLA signed, but thank you @larrifax. The reasoning is that this is equivalent to merging in a fork. Brian talked to legal etc etc.

**Comment by JessicaSachs** [comment]
This branch is broken and that is expected. The procedure is to merge in the Git history by itself into master and then merge in the "fixed" PR (#8718) right afterwards. The base of #8718 was initially against this branch, so we know that it passes once everything is merged in.

**Pull request merged**
