### PR TITLE
fix: truncate text adding ellipsis after certain length

### LINKED ISSUE #21755: Browser icons and longer names in the dropdown menu don't display correctly
Two things…

Very low priority but the launchpad browser tile design & associated list doesn’t support longer names. I don’t know of many other than FF Developer Edition. But maybe can truncate the text after a max char count to prevent this. 

Also, notice the non-standard Edge logos being squished in the app dropdown.

Screen Shot 2022-03-02 at 5 19 10 PM

Screen Shot 2022-03-02 at 5 16 57 PM

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/UNIFY-1234) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://cypress-io.atlassian.net/rest/api/2/attachment/content/11433">Screen Shot 2022-03-02 at 5.16.57 PM.png</a> | <a href="https://cypress-io.atlassian.net/rest/api/2/attachment/content/11432">Screen Shot 2022-03-02 at 5.19.10 PM.png</a>
┆author: Paul Jaffre
┆epic: UI/UX Improvements
┆friendlyId: UNIFY-1234
┆priority: Lowest
┆sprint: Unification Release Backlog
┆taskType: Bug

[UNIFY-1234]: https://cypress-io.atlassian.net/browse/UNIFY-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UNIFY-1234]: https://cypress-io.atlassian.net/browse/UNIFY-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by Manuel-Suarez-Abascal**
**After the changes:**

Screenshot 2022-11-27 at 5 29 16 PM

Screenshot 2022-11-27 at 5 24 33 PM

- Closes [issue-21755](https://github.com/cypress-io/cypress/issues/21755)

### User facing changelog

It truncates the browser name in the UI after a determined length(16) in order to avoid layout issues when the browser name is too long.

### Additional details

N/A

### Steps to test

- Install Firefox Developer Edition browser.
- Launch Cypress.

### How has the user experience changed?

An ellipsis will be added if the browser name is too long. Ellipsis will be added if the browser name is more than 16 characters.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by marktnoonan** [comment]
Thanks for the PR @Manuel-Suarez-Abascal! This strikes me as something that needs a review from our design team before we make the change. The linked issue is quite vague "maybe can truncate...". It probably should not have been labelled a "good first issue" since it's not a clearly defined task.

My initial concern is that the full browser name may sometimes be important & we should probably live with wrapping, or if we don't, we should offer a tooltip with full text. Users can define custom browsers and may give them all kinds of names that might be useful to see.

If we go with truncating, my suggestion would be that we should not do it with JavaScript but use the `truncate` utility class from Tailwind.

That said, it looks to me like one of the problems reported in the issue has already been solved differently - the dropdown no longer has the weird centering/wrapping that was in that screenshot, it looks like this, which seems fine:

Screen Shot 2022-11-27 at 9 16 02 PM

@elevatebart would you mind giving some feedback on whether there's more to do here? Should we close that old issue, or do the truncating -- or do you and team have some other design guidance?

**Comment by elevatebart** [comment]
Thank you @Manuel-Suarez-Abascal 

Good PR indeed. On a rather hard issue.
I think doing the truncation using `text-overflow: ellipsis` is a better idea.

```html
<div class="ellipsis overflow-hidden whitespace-nowrap" />
```

**Comment by elevatebart** [comment]
Also, don't forget to rebase this Branch with only commits signed with GitHub.

**Review by elevatebart — CHANGES_REQUESTED** [review]
Please use CSS to truncate the browser name.

**Comment by Manuel-Suarez-Abascal** [comment]
@elevatebart thanks, it seems that I complicated things for no reason. I have addressed the PR comments. That being said, I use the `truncate` class from Tailwind as per the docs [here](https://tailwindcss.com/docs/text-overflow). Do you want to use this instead? `class="ellipsis overflow-hidden whitespace-nowrap"`

> Also, don't forget to rebase this Branch with only commits signed with GitHub.

I am not sure what you mean about this. Hopefully, I complied with this requirement 😬

**Comment by elevatebart** [comment]
Thank you @Manuel-Suarez-Abascal, I like this new fix.

By rebasing your branch with only signed commit I was trying to get rid of the Red Cross here.

Screenshot 2022-12-05 at 11 55 06 AM

This unsigned commit prevents us from merging your PR.

**Comment by elevatebart** [comment]
I believe also that the initial problem mentioned in the ticket was fixed another way.

@marktnoonan could you confirm that so that @Manuel-Suarez-Abascal does not have to needlessly rebase his PR?

**Comment by marktnoonan** [comment]
Hi @elevatebart , sorry for my delay here. I was referring to this:

> That said, it looks to me like one of the problems reported in the issue has already been solved differently - the dropdown no longer has the weird centering/wrapping that was in that screenshot, it looks like this, which seems fine:
> 
> Screen Shot 2022-11-27 at 9 16 02 PM

I don't personally think we still need this ticket as I would prefer the full browser name to be shown, but I'll defer to you on the design.

There are two things:

1. Truncate in Launchpad cards so they look the same size always
2. Truncate in dropdown menu (this is the one where that bad centering is already fixed & it's just about menu width)

I suggest we leave the drop down alone since there is no bad overflow, and that we only truncate in the launchpad. If it turns out in the future we need the full browser name back, we can have it back easily.

@Manuel-Suarez-Abascal if you can modify this to only make the change in `OpenBrowserList.vue` I will approve. Although as Bart said we will need to make sure all commits are associated with your github user that signed the CLA: https://github.com/cypress-io/cypress/pull/24831#issuecomment-1328356604. It appears you have 2 users. 

If it's simpler feel free to make a fresh PR with your one-line change and tag me there.

**Comment by Manuel-Suarez-Abascal** [comment]
> Hi @elevatebart , sorry for my delay here. I was referring to this:
> 
> > That said, it looks to me like one of the problems reported in the issue has already been solved differently - the dropdown no longer has the weird centering/wrapping that was in that screenshot, it looks like this, which seems fine:
> > Screen Shot 2022-11-27 at 9 16 02 PM
> 
> I don't personally think we still need this ticket as I would prefer the full browser name to be shown, but I'll defer to you on the design.
> 
> There are two things:
> 
> 1. Truncate in Launchpad cards so they look the same size always
> 2. Truncate in dropdown menu (this is the one where that bad centering is already fixed & it's just about menu width)
> 
> I suggest we leave the drop down alone since there is no bad overflow, and that we only truncate in the launchpad. If it turns out in the future we need the full browser name back, we can have it back easily.
> 
> @Manuel-Suarez-Abascal if you can modify this to only make the change in `OpenBrowserList.vue` I will approve. Although as Bart said we will need to make sure all commits are associated with your github user that signed the CLA: [#24831 (comment)](https://github.com/cypress-io/cypress/pull/24831#issuecomment-1328356604). It appears you have 2 users.
> 
> If it's simpler feel free to make a fresh PR with your one-line change and tag me there.

@marktnoonan I have addressed the PR comments. However, I am not sure how to fix the issue of the CLA signature. If I open another branch/PR I am sure I will have the same issue. I got another PR opened  & it's the same 😞

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Looks good, let me try kick off CI.

**Comment by Manuel-Suarez-Abascal** [comment]
@lmiller1990 I have been trying to fix this, but I haven't been lucky. I will give it a shot in the next few days again.

**Comment by lmiller1990** [comment]
No problem. You should be able to revert and re-commit and force push, that should be enough to get the CLA to pass. Let me know if you need any more assistance.

**Comment by Manuel-Suarez-Abascal** [comment]
> No problem. You should be able to revert and re-commit and force push, that should be enough to get the CLA to pass. Let me know if you need any more assistance.

Sorry, guys. I am not able to fix it. I have spent more time trying to fix this CLA thingy than contributing to the code 🤣 if we cannot move forward with it. I might just close the PR & reopen another in the future. Let me know what's best.

**Comment by lmiller1990** [comment]
Hi @Manuel-Suarez-Abascal 

I think this issue is the CLA is not signed for another account you have, or you committed without a git user set, or something to that meaning.

image

The easiest way to fix this would be

1. checkout a new branch from cypress/develop
2. apply your change (only 1 file)
3. do a force push to your current branch

That'll wipe out all those old commits that haven't signed the CLA. Then we can merge this.

**Comment by Manuel-Suarez-Abascal** [comment]
@lmiller1990 I have closed this PR & reopened another with the same changes to get rid of the CLA issue [here](https://github.com/cypress-io/cypress/pull/25270). It seems it has solved the issue.

**Comment by Manuel-Suarez-Abascal** [comment]
**Closed in favor of:** https://github.com/cypress-io/cypress/pull/25270

**Pull request closed without merging**
