### PR TITLE
feat(npm/webpack-preprocessor): release npm/webpack-preprocessor 4.8.0

### PR DESCRIPTION
**Pull request by lmiller1990**
New minor version release.Eexperimental-ish Webpack 5 support (well, not experimental. It works, but users need to polyfill node APIs).

I cherry-picked the commit from the branch that was merged into develop.

### CODE REVIEW

**Review by agg23 — APPROVED** [review]

**Comment by ntucker** [comment]
Eagerly awaiting this release!

**Comment by lmiller1990** [comment]
@ntucker this will be live in a few hours (waiting semantic release to run on CI right now).

If you are using webpack 5, you will still need to deal with the various deprecations, summaized [here](https://github.com/cypress-io/cypress/issues/8900#issuecomment-840383538), mainly around no nodejs module polyfills.

Once the release is done, please give this a try and let me know if you have any problems still - it was difficult to test since all the big apps I have (Cypress monorepo, personal ones) are non trivial to migrate to webpack 5. It worked fine on the small apps I tested with, though.

**Comment by ntucker** [comment]
I'm using it with a custom webpack config but still getting invalid config object with a temp package release.

**Comment by lmiller1990** [comment]
Can you please share a reproduction (or if you can't, your webpack config)? It worked for the examples we have, but they are all mostly trivial.

**Comment by ntucker** [comment]
I'm getting

```
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration should be an object:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, experiments?, externals?, externalsPresets?, externalsType?, ignoreWarnings?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, snapshot?, stats?, target?, watch?, watchOptions? }
   -> Options object as provided by the user.
```

What version of the CLI is expected?

Using https://github.com/ntucker/anansi/tree/master/packages/webpack-config-anansi mostly for the config.

Joined the discord, but didn't find the same username there. Mine is the same there.

**Comment by ntucker** [comment]
https://github.com/cypress-io/cypress/blob/master/npm/webpack-preprocessor/package.json still has webpack 4 as peerdep - is this right?

**Comment by ntucker** [comment]
I can find debug statements like https://github.com/cypress-io/cypress/blob/master/npm/webpack-preprocessor/index.ts#L220 but how do I activate them? The cli doesn't seem to have an option to enable debug logging

**Comment by ntucker** [comment]
@lmiller1990 I just edited the node_modules paths directtly. Turns out we're using the function form of webpack config https://webpack.js.org/configuration/configuration-types/#exporting-a-function

**Comment by ntucker** [comment]
```  1) An uncaught error was detected outside of a test

  0 passing (324ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     ReferenceError: The following error originated from your test code, not from Cypress.

  > process is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at Object../node_modules/variable-diff/node_modules/supports-color/index.js (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:53491:12)
      at __webpack_require__ (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:53660:42)
      at Object../node_modules/variable-diff/node_modules/chalk/index.js (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:53351:21)
      at __webpack_require__ (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:53660:42)
      at Object../node_modules/variable-diff/index.js (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:53114:13)
      at __webpack_require__ (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:53660:42)
      at Object../node_modules/snap-shot-compare/src/index.js (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:42534:14)
      at __webpack_require__ (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:53660:42)
      at Object../node_modules/@cypress/snapshot/src/index.js (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:18:17)
      at __webpack_require__ (https://localhost:6080/__cypress/tests?p=cypress/support/index.js:53660:42)



```

**Comment by ntucker** [comment]
@lmiller1990 so are there plans to not use node-only modules, or release a webpack 5 plugin that makes process work? Got no response in the discord either.

**Comment by ntucker** [comment]
For others following along: this is how webpack 4 polyfilled node's process variable: https://v4.webpack.js.org/configuration/node/

This is no longer covered.

**Comment by ntucker** [comment]
How to test webpack 5 base compatibility: https://webpack.js.org/migrate/5/#test-webpack-5-compatibility

**Comment by ntucker** [comment]
Is there an alternative to @cypress/snapshot that works with webpack5?

**Comment by lmiller1990** [comment]
@ntucker I have not tested @cypress/snapshot with webpack 5, but I can look into this. What is happening when you try using it?

For webpack 5, I tested it out in a (very simple) project and it worked for me: https://github.com/lmiller1990/cypress-react-webpack-5-example. I can't say for a more complex configuration, but if you have one you can share, happy to take a look and the necessary changes to Cypress to fully support webpack 5.

**Comment by ntucker** [comment]
Process is not defined in variable-diff package. I pasted the stack trace above

**Comment by ntucker** [comment]
variable-diff relies on chalk, which is a node-only tool. Replace chalk or have solution to fake its liberal use of process

**Comment by ntucker** [comment]
@lmiller1990 if you don't trigger a codepath that does something interesting at all of course you won't trigger the chalk code to run and thus not get the problem

**Comment by ntucker** [comment]
@lmiller1990 you're not even using @cypress/snapshot in your project....

**Comment by lmiller1990** [comment]
Right, I understand. 

Short term: use a polyfill [like described here](https://stackoverflow.com/a/65556946). That would be [`node-polyfill-webpack-plugin`](https://github.com/Richienb/node-polyfill-webpack-plugin). It's likely many other packages will suffer from this problem.

I'm not sure how we should best approach this long term. The offending line is ultimately [here](https://github.com/taylorhakes/variable-diff/blob/f0f5f801e7a4fde569c18dbeb07dd77ebe3ec679/index.js#L15) in the `variable-diff` package. It's unlikely to change. We could update `snap-shot-it` to not use `variable-diff` but another library that is runtime agnostic. I created an issue in [`snap-shot-compare`](https://github.com/bahmutov/snap-shot-compare/issues/100) to raise visibility and track this.

**Comment by ntucker** [comment]
@lmiller1990 Ah yes, thanks! I was looking for a plugin like that and for some reason couldn't find it - so much appreciated there. Also thanks for bringing up the issue with the dependency. 👍

**Comment by ntucker** [comment]
```
Error: Webpack CompLooked for and couldn't find the file at the following paths:resolve 'process/browser' in '/home/ntucker/src/core/webapp/node_modules/variable-diff/node_modules/supports-color'

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

hmm, did you run into this? that's what i get after adding that plugin

**Pull request merged**
