### PR TITLE
Add ability to zoom in / out in Electron browser

### LINKED ISSUE #1231: Implement zoom in Test Runner
TBD

Useful for Cypress demos.

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Adds ability to zoom in / out in Electron browser + specs view using View menu or keyboard shortcuts. 
- tested manually also :thumbsup:
- close #1231 

Can zoom this

Screen Shot 2019-07-16 at 4 01 49 PM

Can also zoom this in Electron browser

Screen Shot 2019-07-16 at 4 00 14 PM

### CODE REVIEW

**Review by flotwig — DISMISSED** [review]
There's a failing test in `/root/cypress/packages/server/test/unit/gui/menu_spec.coffee`

**Review by chrisbreiding — DISMISSED** [review]

**Review by brian-mann — DISMISSED** [review]
When you are decaffeinating files - you **must** decaffeinate the files first AND submit a PR for that separately.

As it stands - there is no easy way to tell the actual "diff" between the changes you made to `menu.coffee` and `menu.js` or `menu_spec.coffee` and `menu_spec.js` since `menu.coffee` and `menu_spec.coffee` were first deleted.

To be clear - you don't have to submit these PR's serially. You can go ahead and decaffeinate locally first - and continue working as normal. But once you're "finished" you need to then open another PR (off of `develop`) and decaffeinate the files you ended up decaffeinating.

This second PR can then be merged, and then the first PR will correctly show the diff against the decaffeinated files in `develop`. Ask @Bkucera 	if you have any questions since he does this on a regular basis. I will do this for you this time.

**Comment by jennifer-shehane** [comment]
@brian-mann This should be clearly documented somewhere - as I thought there was a process in line, but never was told it.

**Comment by jennifer-shehane** [comment]
The only failure is the one caused by cypress.io - which is known, so merging in with this failure.

**Comment by brian-mann** [comment]
Explaining the decaffeinate process was explained at the time that it mattered, during PR / peer review.

**Pull request merged**
