### PR TITLE
reduce effect of npm silent loglevel

### LINKED ISSUE #2705: npm_config_loglevel env variable is silencing too much (--silent)
## Bug 
introduced by #817 

**Current**:
`npm_config_loglevel` is able to silent the stdout from `cypress version`, `cypress cache list`, cypress downloading message, etc 

**Desired**:
presence of `npm_config_loglevel` should not silence important messages such as the downloading message, and output from `cypress version` and `cypress cache list`, etc

### PR DESCRIPTION
**Pull request by kuceb**
fix #2705 

## changes:

- `npm i cypress --silent` has Listr verbose renderer: (previously there were no console logs)
but, we could change this to use default renderer
```
Installing Cypress (version: 1.2.3)
[xx:xx:xx]  Downloading Cypress     [started]
[xx:xx:xx]  Downloading Cypress     [completed]
[xx:xx:xx]  Unzipping Cypress       [started]
[xx:xx:xx]  Unzipping Cypress       [completed]
[xx:xx:xx]  Finishing Installation  [started]
[xx:xx:xx]  Finishing Installation  [completed]
```
- `cypress verify` ignores `--silent`
```
[xx:xx:xx]  Verifying Cypress can run /cache/Cypress/1.2.3/Cypress.app [started]
[xx:xx:xx]  Verifying Cypress can run /cache/Cypress/1.2.3/Cypress.app [completed]
 Opening Cypress...
```
- calls to `logger.log()` are no longer silenced, only calls to `logger.info`, so `cypress version`, `cypress cache list`, etc will not be silenced by `npm_config_loglevel`

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@Bkucera Merge conflict

**Comment by brian-mann** [comment]
I understand the changes made to the `cache` stuff... but why did you additionally removing silencing of `cypress install`?

I'm pretty sure that was **the point** of using `--silence` - to prevent the gazillions of installing Cypress lines that are added in situations where we don't use the `listr` renderer and instead write messages like it's in a TTY.

**Review by brian-mann — DISMISSED** [review]
See my comment

**Comment by Bkucera** [comment]
> I understand the changes made to the `cache` stuff... but why did you additionally removing silencing of `cypress install`?
> 
> I'm pretty sure that was **the point** of using `--silence` - to prevent the gazillions of installing Cypress lines that are added in situations where we don't use the `listr` renderer and instead write messages like it's in a TTY.

That's why I use the `verbose` renderer, which will max out at 6 lines of stdout

**Comment by Bkucera** [comment]
fixed merge conflict, I think this should be merged.

The comment that @brian-mann mentioned was that with these changes we go from 0 lines of stdout with `--silent` to 6. 

I think that's a fine amount of stdout, personally

**Comment by jennifer-shehane** [comment]
Closing due to inactivity. Please reopen or open a new pull request to address the changes necessary in this PR.

**Pull request closed without merging**
