### PR TITLE
Fix issue where progress bar would restart on collapse toggle

### LINKED ISSUE #7912: Timeout progress bar reset when hooks collapsed
### Current behavior:
The timeout progress bar will not maintain state when a hook is collapsed and then reopened. This also occurs for opening and closing suites, but not tests (closing a test actually prevents the content from rendering in the DOM, rather than just hiding it).

ezgif-6-7b5bfe0add82

### Desired behavior:
The progress bar should reflect the actual progress made and continue to progress as if it was never opened or closed (the same thing that happens with test).

### Test code to reproduce
Any failing test

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-105) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #7912

### User facing changelog

Fixes an issue where the progress bar would restart if it's parent collapsible was toggled

### Additional details

I searched for a way to keep css animations even when an element was no longer being displayed (but still in the DOM) but couldn't find anything. The most common (and basically only) way to restart an animation is through a re-render, so the entire collapsible will be re-rendered when opened. The progress at time of rendering is then re-calculated, leading to the correct progress being shown rather than restarting at the value calculated during the previous render.

<details>
<summary>Performance Testing Details</summary>

I thought that this would be a poor change in terms of performance, but tests (the component) already exhibited this behavior as a performance improvement (their content isn't rendered unless open, making the rendering of the initial suite/test list significantly faster). Despite that, I decided to run some performance tests to confirm.

Here's an example with a particularly intensive single test:

```javascript
describe('testing', () => {
  it('perf', () => {
    cy.visit('https://entertainment.cathaypacific.com/catalog?template=movie&parent=Movies')
    cy.get('.carouselImage > poster-image > figure > picture > source', { timeout: 40000 }).each(source => {
      cy.wrap(source)
        .invoke('attr', 'srcset')
        .should('contain', 'http')
    })
  })
})
```

_develop_

Screen Shot 2020-07-08 at 2 37 11 PM

_This PR_

Screen Shot 2020-07-08 at 2 35 04 PM

Another example with a huge suite of tests (`click_spec.js`), as a lot of this rendering revolves around actually displaying the suite/test list (performance measured to when list was completely rendered, not when test was completed)

_develop_

Screen Shot 2020-07-08 at 2 51 08 PM
Screen Shot 2020-07-08 at 3 09 20 PM

_This PR_

Screen Shot 2020-07-08 at 2 48 56 PM
Screen Shot 2020-07-08 at 3 09 34 PM

As you can see, the performance difference is minimal as expected.

</details>

### How has the user experience changed?

Before:

ezgif-6-7b5bfe0add82

After:

ezgif-6-e3ab05a74b61

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]
I manually verified this fixes the original issue. Also appreciate the writeup on performance. I also don't see this negatively affecting performance. 

I would love a test for this, but...I can see how this is a nightmare to test (just playing around with trying to write it myself). It's probably possible though. Maybe our progress bar test is a bit naive as it is already. Since it's retrying, it will always pass the assertion at some point of the progress bar progressing, even if it restarted. Maybe we need a lower retry timeout for those commands.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
This failure actually looks like it may have been introduced here. @panzarino can you look into this? Make sure there's not some introduced flake here? I did pull in develop. https://circleci.com/gh/cypress-io/cypress/396239

Screen Shot 2020-07-16 at 1 20 43 PM

**Comment by jennifer-shehane** [comment]
Still some failing tests

**Comment by panzarino** [comment]
@jennifer-shehane fixed, realized that the CSS I had removed was actually necessary for some other styles, for example one of the tests was failing because the stack trace added padding to the `collapsible-content` which made it display despite having no content inside.

**Review by jennifer-shehane — APPROVED** [review]

**Pull request merged**
