### PR TITLE
chore(types): Add initial Cypress.log API

### LINKED ISSUE #1110: Cypress.log type definition and/or documentation
The implementation of `Cypress.log` returns a chainable interface with methods like `invoke` and `snapshot`, etc. The type definitions just return `void`. The documentation doesn't say much.

I'm wondering what should the public interface returned by `Cypress.log` be? Should they reflect the implementation and the docs also get updated?

- Operating System: N/A
- Cypress Version: 1.4
- Browser Version: N/A

### Is this a Feature or Bug?
Not sure

### PR DESCRIPTION
**Pull request by NicholasBoll**
A simple pass at the Cypress.log API. Not all methods are included or the included methods documented well. Brian mentioned in #1110 that he wanted to do some work on `log.coffee`, so I just looked at what is currently in use in example code I could find an added type definitions for it.

This gives a placeholder for more `Log` interface methods and JSDoc.

Fixes  #1110

### CODE REVIEW

**Comment by NicholasBoll** [comment]
Is there anything preventing this from being merged?

**Comment by bahmutov** [comment]
I think it looks good and should be merged in to provide types for log command @brian-mann

**Comment by NicholasBoll** [comment]
This is probably a lower priority change, but it would prevent us from using `any`. If there is work in progress to change the Cypress Log API (soon), I think we should close this PR.

**Comment by bahmutov** [comment]
I don't think we plan any work soon @brian-mann so we can merge this for 3.0

**Comment by brian-mann** [comment]
I will begrudgingly merge this with the caveat that I very much dislike this API but its too low priority to spend time fixing now.

**Pull request merged**
