### PR TITLE
Wrap tests titles in reporter UI

### LINKED ISSUE #3947: Wrap scenario and step names in UI
### Current behavior:

Scenario and step names are truncated with an ellipsis in the UI, making it difficult to tell at a glance what is failing and not.

### Desired behavior:

Names should wrap to the next line.

### PR DESCRIPTION
**Pull request by coderwurst**
closes #3947

### CODE REVIEW

**Comment by coderwurst** [comment]
ok, the issue is with the inline-flex attribute I added to the runnable-content-region, it overrides what I think is old flex box code

image

**Comment by chrisbreiding** [comment]
Those lines aren't the old code, they're added by [autoprefixer](https://github.com/postcss/autoprefixer). They'd be utilized if run in an older browser that doesn't support the newest syntax.

The issue is that the icon used to have a consistent height and now the combination of flexbox and multiple lines extends its height. We need to control the height of the icon so it doesn't stretch to the full height of its container.

**Comment by coderwurst** [comment]
thanks for the pointer! I set the height on the .runnable-state element to 18px to match the line height, and the spinning icon stays in place once again :-)

I noticed during debugging that, in some of the smaller views, the text can spring down a line once the spinner has completed (see point 2 of 3): 


width- 12px

I have fixed this by changing width: 12px to a min-width: 12px

Final Question - the text collapsible headers above each section do not stay inline when they include a line break

image

I can update the header text with this ticket as well:

image

**Comment by chrisbreiding** [comment]
Great work. Yes, please fix the collapsible headers. 

Also, let's add a minimum width as [suggested here](https://github.com/cypress-io/cypress/issues/3947#issuecomment-501391752).

**Comment by chrisbreiding** [comment]
This was merged a bit prematurely. It still needed a fix for when the reporter is at a really small width. I'll create another PR to handle that.

**Comment by jennifer-shehane** [comment]
When I looked at it, it did have a min-width - I couldn't get the test titles to show down to 1 char like Ben was describing.

**Comment by coderwurst** [comment]
Hi guys - sorry for not responding more last week, was on holidays and did take the laptop with me but didn't get any time to open it 🌴 🍻 Thanks for the tidy up @chrisbreiding , and thanks also @jennifer-shehane for giving the initial pointers and making it so easy to make my first contribution to cypress and open source! On to the next!

**Pull request merged**
