### PR TITLE
Add tooltip to configuration json

### LINKED ISSUE #2075: Using cypress json schema for tooltips on configuration settings in Desktop Gui
Would be nice as I hover over each property that we show a tooltip with the `description` and even the `default` value.

The schema file is here: https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json

screen shot 2018-06-30 at 8 58 21 pm

### PR DESCRIPTION
**Pull request by nhc**
Closes #2075 

### Description of change

Configuration json which reads and displays the project settings, now displays additional information using a tooltip and pulled in from the cli schema file.

Hover over the setting name and a description is shown 

Screenshot 2019-10-02 at 13 54 43

Hover over the value and get the default setting value is shown 

Screenshot 2019-10-02 at 13 55 51

### How to use the feature
The user does not need to do anything different. It is an enhancement. 

### Notes
The information displayed is only as good as the schema file. This might need improving later. 

### Pre-merge Tasks

This is my first PR for this project, which of these do I need to do to continue ?

- [x] Have tests been added/updated for the changes in this PR?
- [ ] Has a PR to [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation) been submitted to document any user-facing changes? 
- [ ] Have the [type definitions](cli/types/index.d.ts) been updated with any user-facing API changes?
- [ ] Has the [cypress.schema.json](cli/schema/cypress.schema.json) been updated with any new configuration options?
- [ ] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by brian-mann** [comment]
@nhc thank you for taking a crack at this. @jennifer-shehane can you review? Thx.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Hey, thanks for the contribution - we definitely love the idea of bringing documentation closer to the product. I have a few comments initially after reviewing.

1. You mentioned adding tests for this PR, but I don't actually see any tests covering that these tooltips show up in our Desktop Gui at all. 

	We write Cypress tests to test Cypress itself. We have tests covering this 'Configuration' panel and it's display here: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/integration/settings_spec.js#L71

	Can you write tests that ensure when hovering over the config that a tooltip displays with the appropriate description?

	Instructions for running the tests can be found here: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/README.md#L75

2. There are a few edgecases in the tooltip that I see where it is not working as expected. Can you update the code to handle these edgecases?

	- Some of the content in the tooltip does not wrap if the content does not contain a newline and exceeds the width of the toolip. 
	
	Screen Shot 2019-10-02 at 2 56 25 PM

	- If the value is not documented in the cypress.json schema, an empty tooltip displays. We would prefer that no tooltip display at all. 
	
	Screen Shot 2019-10-02 at 2 56 35 PM

**Comment by nhc** [comment]
@jennifer-shehane Thanks for feedback and information on getting started with the tests, I was struggling to find this. 

With regard to the width of the tooltip, I used https://github.com/cypress-io/react-tooltip which is yours also ? I would suggest that the issue is with that repo, not here. It is only when there is a # in a URL. 

Happy to help either way.

**Comment by jennifer-shehane** [comment]
@nhc Sigh, true story 😢 I'll open an issue in the tooltip repo. 

If you still have time, can you add the tests and also not show the tooltip if the schema value was not found as mentioned in my review?

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
1. This branch is breaking when I run it - I'm not sure how the tests didn't catch this, when I run the tests locally it does fail, so it seems like the desktop-gui tests didn't run in CI??:

```
[14000:1008/152804.161731:INFO:CONSOLE(14)] "Invariant Violation: Objects are not valid as a React child (found: object with keys {spanValue}). If you meant to render a collection of children, use an array instead.
    in div (created by _class)
    in pre (created by _class)
    in div (created by _class)
    in _class (created by _class)
    in div (created by PanelContent)
    in div (created by PanelContent)
    in PanelContent (created by CollapsePanel)
    in AnimateChild (created by Animate)
    in Animate (created by CollapsePanel)
    in div (created by CollapsePanel)
    in CollapsePanel (created by _class)
    in div (created by Collapse)
    in Collapse (created by _class)
    in div (created by _class)
    in div (created by _class)
    in _class (created by Project)
    in div (created by Project)
    in Project (created by App)
    in Unknown (created by App)
    in App", source: cypress:///./src/lib/handle-global-errors.js (14)
```

2. We decided not to update the react-tooltip and to instead set a class using the `className` passed to react-tooltip and in that class update the max-width to be a wider value that displays the full largest url. The default is 200px.

**Comment by jennifer-shehane** [comment]
@nhc Thanks for signing the CLA, since you made another commit from a separate email, the author of the commits does not match the email address you signed the CLA with. 

Our CLA bot gets confused when they don't match. Here are some solutions to fixing when commits are linked to the wrong user: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by jennifer-shehane** [comment]
Closing as inactive. CLA never signed. We also have made significant changes to the Configuration panel, so this would require extra weworking.

**Pull request closed without merging**
