### PR TITLE
chore(deps): deduplicate #29974 yarn.lock

### PR DESCRIPTION
**Pull request by MikeMcC399**
### Additional details

Deduplicates [yarn.lock](https://github.com/cypress-io/cypress/blob/develop/yarn.lock) following on from Renovate PR:

- https://github.com/cypress-io/cypress/pull/29974

using the post-installation command:

```shell
yarn run yarn-deduplicate --strategy highest
```

- Renovate PRs need special manual attention until https://github.com/cypress-io/cypress/issues/30051 is resolved.

### Steps to test

Execute

```shell
git clean -xfd
yarn
git diff
```

and confirm that `yarn install` does not generate any uncommitted differences.

### How has the user experience changed?

Developer change only.

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
type checks are not happy ☹️

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> type checks are not happy ☹️

I don't have an explanation for why https://app.circleci.com/pipelines/github/cypress-io/cypress/63542/workflows/bed46da9-a920-42d9-91b7-c958d69f8f2c/jobs/2633249

shows failure executing

```shell
yarn workspace cypress dtslint
```

attempting to install TypeScript

```text
Installing to /root/.dts/typescript-installs/3.5...
TypeError: Class extends value #<Object> is not a constructor or null
```

Running the same command locally is able to install TypeScript and run the tests, although these do output lots of deprecations (see https://github.com/cypress-io/cypress/issues/30063) which were appearing before this PR.

I guess it might be a caching issue in CircleCI, but I can't say for sure.

- As mentioned in https://github.com/cypress-io/cypress/issues/30063 the `dtslint` version in use is a 4 year old deprecated npm module.

**Comment by MikeMcC399** [comment]
This error or similar is occurring in multiple tests. This is suspicious as it is the `yarn.lock` entry for `tar` which has been deduplicated. I still suspect that caching is responsible.

```text
TypeError: Class extends value #<Object> is not a constructor or null
    at Object.<anonymous> (/root/cypress/node_modules/npm/node_modules/tar/lib/read-entry.js:91:4)
```

**Comment by MikeMcC399** [comment]
- Defer to PR https://github.com/cypress-io/cypress/pull/30065 which is now carrying out the required deduplication due to the added Renovate config.
- Put this PR to draft state for the moment.

**Comment by jennifer-shehane** [comment]
Maybe this is only happening on contributor PRs for some reason because it's not happening on our internal PRs.

**Comment by jennifer-shehane** [comment]
Oh, I see what you're saying about the deduping there too. That makes sense. Let me try some things.

**Comment by jennifer-shehane** [comment]
@AtofStryker is going to take a look at this issue.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> @AtofStryker is going to take a look at this issue.

That's very good! I haven't been able to locate the root cause. The issue would have come up anyway the next time there was a PR with any dependency changes. This PR has just ended up highlighting the issue a little earlier.

- I've put this PR back in review, since #30065 turned out to have the same problem.

**Comment by AtofStryker** [comment]
I can't exactly figure out what is going on here. Going to try bumping the cache in circle as well as `ssh`ing into the box to see if I can replicate

**Comment by MikeMcC399** [comment]
- Deferring to https://github.com/cypress-io/cypress/pull/30077 to fix the `nx-cloud` / `tar` issue which is causing several tests to fail.

**Pull request closed without merging**
