### PR TITLE
Fix race condition where screenshot is taken before iframe resize

### LINKED ISSUE #3276: Chance of race condition when using screenshot()
### Current behavior:

When using `screenshot` command, when taking a screenshot the frame running the app get resized, this can trigger some re-render on the page. This can cause a race condition, if between the time that the element position is retrieved and the actual screenshot is taken the element is being moved.

The result is that certain part of the element we are trying to capture are actually missing, this is especially troublesome when you consider we use plugins like `cypress-plugins-snapshots` for image diffing.

### Desired behavior:

If the position moves between getting the position and taking the screenshot we should retry to ensure the element is properly captured. 

### Steps to reproduce: (app code and test code)
```js
describe('Flaky Screenshot', () => {
    it('Flaky Example', () => {
        cy.get('.container').then($container => {
            const container = $container[0];
            let i = 0;
            setInterval(() => {
                container.style.marginTop = `${i}px`;
                i += 10;
            }, 0.5);
        });

        cy.get('.container').screenshot();
    });
});
```
When executing this code (hacky) the screenshot almost always is missing a part of the element we are trying to capture.

### Versions

Cypress: 3.1.5
Chrome: 72

### Screenshots (consecutive runs on the same machine)
flaky screenshot -- flaky example 4
flaky screenshot -- flaky example 5
flaky screenshot -- flaky example 6
flaky screenshot -- flaky example 7

### PR DESCRIPTION
**Pull request by renelux**
Make the `before:screenshot` synchronous, to prevent a race condition where the screenshot could be taken before the iframe was resized and the runner hidden.

Fixes #3276

### CODE REVIEW

**Comment by renelux** [comment]
The actual root cause of the race condition is a little different then what we analyzed in the reported issue. The screenshot command sends the `before:screenshot` event, which is handled by [App.jsx:121](https://github.com/cypress-io/cypress/blob/develop/packages/runner/src/app/app.jsx#L121) if `appOnly` is true the iFrame containing the users app will be resized to full screen. If that doesn't happen in sync there is a chance for a race condition, removing the async should prevent that from happening.

**Comment by renelux** [comment]
What the fix is trying to achieve is to make the `before:screenshot` which is handled on the client side is synchronous. The iframe resize is currently not awaited it seems, and sometimes (rarely) the runner would still be visible in the screenshot even when it should not.

Are we understanding that the current flow for screenshot taking is as follows:

- cy.screenshot is called
   - before hook emits event to the runner
      - runner will resize the iframe if `isAppOnly`
   - screenshot is taken and sent to the server
      - server stores the snapshot and handles the clipping, blackout etc.

So to our understanding before hook is not `awaiting` the iframe resize and therefor can result into a race condition.

- cy.screenshot is called
   - before hook emits event to the runner
      - runner will resize the iframe if `isAppOnly`
        - screenshot is taken and sent to the server
          - server stores the snapshot and handles the clipping, blackout etc.

So the fix we propose is to change the screenshot code a little more like the callstack above. Synchronous where needed.

**Comment by renelux** [comment]
@chrisbreiding it seems that the iframe resizing is indeed called async, but still we are seeing the following behavior. As you can see from the screenshot the runner header is still visible, any idea why this is occurring?

race-condition-current
race-condition-fullscreen
race-condition-original

**Comment by chrisbreiding** [comment]
We do take efforts to ensure that the iframe is resized. This is what the entire flow roughly looks like:

* cy.screenshot is called
* [driver emits "before:screenshot" event to the runner](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/screenshot.coffee#L223)
* [runner](https://github.com/cypress-io/cypress/blob/develop/packages/runner/src/lib/event-manager.js#L249 [resizes the iframe if isAppOnly](https://github.com/cypress-io/cypress/blob/develop/packages/runner/src/app/app.jsx#L121) (this is done as synchronously as possible and awaited)
* ["take:screenshot" event is sent to server](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/screenshot.coffee#L45)
* [server takes the screenshot via the extension](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/screenshots.coffee#L99)
* [server verifies that the iframe is resized and Cypress UI is removed](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/screenshots.coffee#L147) (the verification method is [described here](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/screenshots.coffee#L50))
* server crops image as needed and saves the screenshot to disk

The key part is the verification method where we check pixels in the corner of the screen to ensure the Cypress UI is removed. We found that even though we made the DOM manipulation as synchronous as possible, the browser would not paint the page in time for when the screenshot is taken by the extension and there isn't an event or anything that lets us know the browser has finished painting after a DOM update. So we introduced the pixel check to try to guarantee that the Cypress UI is removed before the screenshot is saved to disk.

The steps above all done in order and there shouldn't be any race conditions. We have e2e tests that run to ensure the iframe resizing works consistently. In [this test](https://github.com/cypress-io/cypress/blob/develop/packages/server/test/support/fixtures/projects/e2e/cypress/integration/screenshot_viewport_capture_spec.coffee), we run 25 screenshots in a row and check that the Cypress UI is hidden in every one. 

That's not to say there isn't a bug or issue somewhere. Clearly there is since you're seeing the Cypress UI show up in screenshots where it should not. It's most likely related to the pixel check somehow. [If it takes over 1500ms](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/screenshots.coffee#L117) to capture the screenshots and verify, Cypress gives up and accepts the last screenshot taken. That would be my best guess as to what's happening.

Could you run your tests with the following and post the results when you encounter this issue? 

```
DEBUG=cypress:server:screenshot cypress run
```

This will output logs related to the server capturing the screenshots and doing the pixel verification, so it will may reveal a bit more about what's going on and hopefully lead to a solution.

**Comment by jennifer-shehane** [comment]
Closing due to inactivity.

**Pull request closed without merging**
