### PR TITLE
fix: Remove dynamic fixtures in tests.

### LINKED ISSUE #21964: Stop using dynamic fixtures for tests
## **Summary**
We use dynamically generated test data for fixtures. It’s hard to debug and write assertions against. Instead, let’s hard code some data to make it more deterministic and easy to debug.

The relevant code is here: [https://github.com/cypress-io/cypress/blob/10.0-release/packages/frontend-shared/cypress/support/mock-graphql/testStubSpecs.ts](https://github.com/cypress-io/cypress/blob/10.0-release/packages/frontend-shared/cypress/support/mock-graphql/testStubSpecs.ts|smart-link) 

## **Acceptance Criteria**
* Should not use dynamically generated fixtures

### **Resources**
Any Notion documents, Google documents, Figma Boards

### **Open Pull Requests**
Any PRs needed for review

┆Issue is synchronized with this [Jira Task](https://cypress-io.atlassian.net/browse/UNIFY-1403) by [Unito](https://www.unito.io)
┆author: Lachlan Miller
┆epic: Testing / Quality
┆friendlyId: UNIFY-1403
┆priority: Low
┆sprint: Backlog
┆taskType: Task

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #21964

### User facing changelog

N/A. It's an internal change. 

### Additional details
- Why was this change necessary? => Dynamic fixtures make hard to assert.
- What is affected by this change? => N/A

### Any implementation details to explain?

* I created a command, `generate-stub-specs`, under `frontend-shared`.
* I created spec fixtures with it and replaced `randomComponents` in the code. 

### Steps to test

N/A

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by sainthkh** [comment]
About [<SpecsList /> when testingType is unset should filter specs](https://app.circleci.com/pipelines/github/cypress-io/cypress/39314/workflows/f6707c7b-e4d6-41e6-9ccc-0f9cd004fb3e/jobs/1605179/tests#failed-test-0) failure.

It seems that there's a racing condition `cy.get('@specsListInput').clear()` and restoring the files tree vs. `cy.contains()`. `wait(50)` might solve the problem, but I left it as-is for now.

**Review by tbiethman — APPROVED** [review]

**Review by marktnoonan — CHANGES_REQUESTED** [review]
I'm still getting this failure locally, going to see if I can figure it out and recommend something


Screen Shot 2022-07-01 at 10 35 02 AM

**Comment by marktnoonan** [comment]
> About [ when testingType is unset should filter specs](https://app.circleci.com/pipelines/github/cypress-io/cypress/39314/workflows/f6707c7b-e4d6-41e6-9ccc-0f9cd004fb3e/jobs/1605179/tests#failed-test-0) failure.
> 
> https://github.com/cypress-io/cypress/blob/85f002fa39f7afdbc439a5d412a403ed7f7662cf/packages/app/src/specs/SpecsList.cy.tsx#L93-L100
> 
> It seems that there's a racing condition `cy.get('@specsListInput').clear()` and restoring the files tree vs. `cy.contains()`. `wait(50)` might solve the problem, but I left it as-is for now.

Here's a solution, we can update:

```js
cy.contains('button[data-cy="row-directory-depth-0"]', dir)
```

with a regex to make sure we are matching the start of the button text only: 

```js
cy.contains('button[data-cy="row-directory-depth-0"]', new RegExp(`^${dir}`))
```


The race condition seems to be that some of the root level directory names are also present in nested directories, so we sometimes click on this instead of the root `__tests__`, if the click happens before the DOM has updated after the search was cleared. 

Screen Shot 2022-07-01 at 10 56 11 AM

**Review by marktnoonan — APPROVED** [review]
That failing test is fixed, everything looks good. Thanks for this PR!

**Comment by marktnoonan** [comment]
will keep an eye on this and merge once CI is green

**Comment by JessicaSachs** [comment]
Just curious why this was done (I'm about to do something similar again and I continue to teach using faker, etc in workshops).

**Comment by sainthkh** [comment]
I believe it's the tradeoff between `making sure our program works in all possible cases` and `making debugging and writing assertions easier with determinisitic data`.

**Pull request merged**
