### PR TITLE
fix: route all https traffic through proxy

### PR DESCRIPTION
**Pull request by kuceb**
[TR-416](https://cypress-io.atlassian.net/browse/TR-416)

pass all https through our proxy routes instead of making direct connections
- needed for cy.sessions work for injected page setters for localStorage, and detecting domains which served html 

### User facing changelog
TBD

### PR Tasks
- [x] ensure partial injection (`document.domain`) only affects aut domain
- [ ] @flotwig should we add tests for and tag as closed the issues this may fix related to cy.route2?

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by Bkucera** [comment]
@flotwig should we add tests for and tag as closed the issues this may fix related to cy.route2?

**Review by flotwig — APPROVED** [review]
this is quite a beautiful change. very very nice!!!

**Comment by flotwig** [comment]
> @flotwig should we add tests for and tag as closed the issues this may fix related to cy.route2?

I'm not aware of any open issues that this fixes for cy.route2, we knew that there was an issue with breaking existing HTTPS connections but AFAIK no issues have been opened :shrug:

**Comment by flotwig** [comment]
Oh, actually, possibly https://github.com/cypress-io/cypress/issues/8815 is bein caused by this...

**Pull request merged**
