### PR TITLE
fix: provide feedback for old operating systems that don't support protocol

### PR DESCRIPTION
**Pull request by ryanthemanuel**
### Additional details

Provide better error messaging and feedback for old operating systems that don't support protocol

### Steps to test

The new system test handles this scenario

### How has the user experience changed?

n/a

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by MikeMcC399** [comment]
## Related

- https://github.com/cypress-io/cypress/issues/27902
- https://github.com/cypress-io/cypress/issues/27920

**Comment by MikeMcC399** [comment]
@ryanthemanuel 

- What is the plan for this PR? According to the research I did for https://github.com/cypress-io/cypress-documentation/issues/5444, this is also related to the Node.js GLIBC minimum requirement.
- The earliest supported version of Node.js is currently `18` according to the [release schedule](https://github.com/nodejs/release#release-schedule)
- Node.js `18` requires a minimum GLIBC version 2.28. See [Node.js 18 announcement](https://nodejs.org/en/blog/announcements/v18-release-announce) -> [Toolchain and Compiler Upgrades](https://nodejs.org/en/blog/announcements/v18-release-announce#toolchain-and-compiler-upgrades) and [Node.js 18 > BUILDING.md](https://github.com/nodejs/node/blob/v18.x/BUILDING.md#supported-platforms)

**Comment by ryanthemanuel** [comment]
> @ryanthemanuel
> 
> * What is the plan for this PR? According to the research I did for [Operating System support lists vendor unsupported versions cypress-documentation#5444](https://github.com/cypress-io/cypress-documentation/issues/5444), this is also related to the Node.js GLIBC minimum requirement.
> * The earliest supported version of Node.js is currently `18` according to the [release schedule](https://github.com/nodejs/release#release-schedule)
> * Node.js `18` requires a minimum GLIBC version 2.28. See [Node.js 18 announcement](https://nodejs.org/en/blog/announcements/v18-release-announce) -> [Toolchain and Compiler Upgrades](https://nodejs.org/en/blog/announcements/v18-release-announce#toolchain-and-compiler-upgrades) and [Node.js 18 > BUILDING.md](https://github.com/nodejs/node/blob/v18.x/BUILDING.md?rgh-link-date=2023-10-03T06%3A33%3A14Z#supported-platforms)

Hi @MikeMcC399, we originally were going to try and provide guidance to users to get their systems in line with minimum versions of GLIBC that is necessary for using `better-sqlite3` (which is necessary for protocol), but we are actually going to switch gears for this issue as we think we have a way to resolve it in such a way that users don't need to do anything OS-wise. Stay tuned, but I hope to have a PR out for that relatively soon.

**Comment by ryanthemanuel** [comment]
Closed in lieu of https://github.com/cypress-io/cypress/pull/27968

**Pull request closed without merging**
