### PR TITLE
chore(deps): update to mime 4.0.4

### LINKED ISSUE #30144: Update to `mime` current version 4.x
### What would you like?

1. Update the npm module [mime](https://www.npmjs.com/package/mime) to minimum [mime@4.0.0](https://github.com/broofa/mime/tree/v4.0.0) and preferably [mime@4.0.4](https://github.com/broofa/mime/tree/v4.0.4) (or current `latest`).
2. Remove the use of the deprecated npm module [@types/mime](https://www.npmjs.com/package/@types/mime).

### Why is this needed?

The npm module [@types/mime](https://www.npmjs.com/package/@types/mime) is deprecated. The [CHANGELOG](https://github.com/broofa/mime/blob/v4.0.0/CHANGELOG.md#400-2023-11-29) shows "drop CJS support, switch to TS" in [mime@4.0.0](https://github.com/broofa/mime/tree/v4.0.0) and [mime > README](https://github.com/broofa/mime/blob/main/README.md) states "Built-in Typescript types (`@types/mime` no longer needed)".

### Other

- Renovate deprecation list https://github.com/cypress-io/cypress/issues/3777

| Item                      | Value                                                                                                       |
| ------------------------- | ----------------------------------------------------------------------------------------------------------- |
| Deprecated npm module     | [@types/mime](https://www.npmjs.com/package/@types/mime)                                                    |
| npm registry message      | This is a stub types definition. mime provides its own type definitions, so you do not need this installed. |
| Other message             |                                                                                                             |
| GitHub repo               | https://github.com/broofa/mime                                                                              |
| Repo status               | Active                                                                                                      |
| Replacement npm module    | https://www.npmjs.com/package/mime                                                                          |
| Replacement repo          | https://github.com/broofa/mime                                                                              |
| Replacement documentation | https://github.com/broofa/mime                                                                              |
| Migration docs            | https://github.com/broofa/mime                                                                              |

Where used:

| Directory                                                                                         | `@types/mime` | `mime`   | Section           | ESM `import` |
| ------------------------------------------------------------------------------------------------- | ------------- | -------- | ----------------- | ------------ |
| [packages/driver](https://github.com/cypress-io/cypress/tree/develop/packages/driver)             | `^3.0.1`      | `^3.0.0` | `devDependencies` | yes          |
| [packages/net-stubbing](https://github.com/cypress-io/cypress/tree/develop/packages/net-stubbing) | `^3.0.1`      | `^3.0.0` | `dependencies`    | yes          |
| [packages/server](https://github.com/cypress-io/cypress/tree/develop/packages/server)             | `^3.0.1`      | `^3.0.0` | `dependencies`    | yes          |

- [mime](https://www.npmjs.com/package/mime) `latest` is currently `4.1.0`

### PR DESCRIPTION
**Pull request by MikeMcC399**
- Closes https://github.com/cypress-io/cypress/issues/30144

### Additional details

1. Update the npm module [mime](https://www.npmjs.com/package/mime) to [mime@4.0.4](https://github.com/broofa/mime/tree/v4.0.4) in:
  - [packages/server](https://github.com/cypress-io/cypress/tree/develop/packages/server)
2. Remove the use of the deprecated npm module [@types/mime](https://www.npmjs.com/package/@types/mime).

The npm module [@types/mime](https://www.npmjs.com/package/@types/mime) is deprecated and shows the message:

> This is a stub types definition. mime provides its own type definitions, so you do not need this installed.

### Steps to test

```shell
git clean -xfd
yarn
yarn workspace @packages/server check-ts
```

### How has the user experience changed?

No change to user experience.

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Some failures. Ran some more of the tests.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

```shell
yarn test-unit --scope @packages/server
```

Also fails locally with 

```text
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/mike/github/cypress-io/cypress/packages/server/test/unit/automation/util_spec.ts
```

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

The CI tests have highlighted that the upgrade needs significant work, so I would propose to close it. Sorry for the false start! I probably need to hand over to somebody else.

The [CHANGELOG](https://github.com/broofa/mime/blob/v4.0.0/CHANGELOG.md#400-2023-11-29) shows "drop CJS support, switch to TS" in [mime@4.0.0](https://github.com/broofa/mime/tree/v4.0.0) and [mime > README](https://github.com/broofa/mime/blob/main/README.md) states "Built-in Typescript types (`@types/mime` no longer needed)".

**Comment by MikeMcC399** [comment]
`mime` is being used in JavaScript CommonJS modules

- [packages/server/lib/screenshots.js](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/screenshots.js)
- [packages/server/lib/controllers/xhrs.js](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/controllers/xhrs.js)

It would be out of scope to convert these modules to ESM and TypeScript as part of this PR. [mime@4.0.0](https://github.com/broofa/mime/tree/v4.0.0) has however dropped CJS support.

**Comment by jennifer-shehane** [comment]
Oof. Thanks for looking into it.

**Pull request closed without merging**
