### PR TITLE
Convert command actions tests to Javascript

### PR DESCRIPTION
**Pull request by clarmso**
This PR consists of the command actions tests from the driver package converted to Javascript from Coffeescript.  The conversion has been done via the following command:

https://github.com/cypress-io/cypress/blob/844606bcede477f18eb83834f51941e4f2f165df/.vscode/tasks.json#L15

I've converted the files in as few commits as possible.  (bulk-decaffeinate creates commits for stages of the conversion.) Please do not squash this commit. :)

A part of #2690

### User facing changelog

No user facing changelog specific to these tests should be needed.  

### Additional details

This PR is a part of continuous improvement in maintaining the codebase.  We hope the codebase will be in Typescript. :)  Javascript is an intermediate step.

I've reviewed the results of the bulk-decaffeinate command.  I've ensured the following:
* arrow functions are used if applicable.  The remaining use of the function() notation is necessary. (Example: use of "this" keyword in the tests)
* Remove unnecessary returns.
* Remove variable declarations that are unnecessary.

### How has the user experience changed?

No noticeable changes should be detected by the developers and the users.  The new version of the tests should work the same as the old Coffeescript ones.

### PR Tasks

- [X] Have tests been added/updated?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@clarmso Couple of lint warnings 

```
/root/cypress/packages/driver/test/cypress/integration/commands/actions/check_spec.js
   635:43  error  Missing trailing comma  comma-dangle
  1181:43  error  Missing trailing comma  comma-dangle
```

**Comment by clarmso** [comment]
@jennifer-shehane Oh darn. I didn't catch the lint error yesterday. (Scratching head...) It should be fixed now. :)

**Comment by jennifer-shehane** [comment]
@clarmso Continuously merging in the develop branch and making more commits is going to mess up the final commit. We don't squash commits for decaffeinate, so need this PR left to the maximum of the decaffeinate commits + 1 cleanup commit. Is there any way you can clean up commits here?

**Comment by clarmso** [comment]
My git squash/rebase is a fail again. :( Let me include my change in a new branch. (It's quicker...)

**Pull request closed without merging**
