### PR TITLE
fix: make Cypress.ConfigOptions follow json Schema

### PR DESCRIPTION
**Pull request by elevatebart**
### User facing changelog
The `Cypress.ConfigOptions`, `Cypress.ResolvedConfigOptions` and `Cypress.RuntimeConfigOption` types have been updated so that `ConfigOptions` match the json schema 

### Additional details
This fixes inconsistencies in cypress externally exposed types

### CODE REVIEW

**Comment by flotwig** [comment]
> type: breaking change

@elevatebart I don't see any test updates, can you clarify for me how this is a breaking change?

**Comment by elevatebart** [comment]
@flotwig 
We never tested out types, but they were still exposed. 
A developer could have used them in a plugin or another community tool to help type their inputs. 

It is very unlikely though, since the types were *wrong* and nobody complained. 
I can remove the "breaking change" if you prefer.

**Review by flotwig — APPROVED** [review]
This makes sense. I see how this could be a breaking change even tho it's a typefix, I guess it's worth documenting in the CL as such too.

**Comment by flotwig** [comment]
@elevatebart gonna merge this, but it would be extra sweet if you could add tests that help keep these types, `server/lib/config`, and `cypress.schema.json` in sync.

**Pull request merged**
