### PR TITLE
feat: restore full spec name in run mode log

### PR DESCRIPTION
**Pull request by Narretz**
- restore full name in spec header
- restore full in result table
- don't restore in spec footer (duplicated info)

- Closes https://github.com/cypress-io/cypress/issues/22304

### User facing changelog

In the terminal log of cypress run, the full names (path + file name) of specs are now reported again, instead of just the file name.

### Additional details
I don't know why the baseName is used in Cypress 10, but the full name is better if you have spec files with the same name in different folders. So this might even be considered a regression.

### Steps to test

(I don't know if the output of the log is tested anywhere)

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by Narretz** [comment]
I assume this was changed because there's no "integrationFolder" anymore, and the full spec path would always include the "base" of the "specPattern"? Is that it?

**Comment by lmiller1990** [comment]
> I assume this was changed because there's no "integrationFolder" anymore, and the full spec path would always include the "base" of the "specPattern"? Is that it?

Yep that's right!

**Comment by lmiller1990** [comment]
This is not quite right - I tried it and got

```sh
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  cypress/e2e/nested-1/nested-2/neste      111ms        1        1        -        -        - │
  │    d-3/spec.cy.js                                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  cypress/e2e/nested-1/nested-2/neste       74ms        1        1        -        -        - │
  │    d-3/stdout_specfile.cy.js                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  cypress/e2e/nested-1/nested-2/neste      499ms        1        1        -        -        - │
  │    d-3/stdout_specfile_display_spec_wi                                                         │
  │    th_a_really_long_name_that_never_ha                                                         │
  │    s_a_line_break_or_new_line.cy.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  cypress/e2e/nested-1/nested-2/neste       89ms        1        1        -        -        - │
  │    d-3/nested-4/spec.cy.js                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        773ms        4        4        -        -        -  

```

It should be truncating `cypress/e2e`. Let me try more.

**Comment by lmiller1990** [comment]
Let's discuss here https://github.com/cypress-io/cypress/issues/22304#issuecomment-1245004059

**Comment by lmiller1990** [comment]
Gonna close in favor of https://github.com/cypress-io/cypress/pull/23794

**Pull request closed without merging**
