### PR TITLE
fix: change "resizable panels handlers" width to make it more convenient to use

### PR DESCRIPTION
**Pull request by Oustinger**
Closes #22473
Closes https://github.com/cypress-io/cypress/issues/22608

### User facing changelog
Changed resizable panels' handlers width to make it more convenient to use

### Additional details
Resizable panels' handlers have too big width that overlap scrollbar.
As user, you have troubles with scrolling tests' log window.
That's why you need to do it less.
I resolved it with changing resizable panels' handlers' className: `w-16` -> `w-10`

### Steps to test
1. Open and run any test
2. Expend inforamtion in tests' log window to see a scrollbar (if it's not  visible)
3. Try to scroll using cursor

### How has the user experience changed?
Before: [video](https://recordit.co/jRUcJrPG0V)

After: [video](https://recordit.co/z384pudkL3)

### PR Tasks
- [na] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by marktnoonan** [comment]
Nice, this was a good thing to raise. Initially this looks good and seems justified, without making the click target too small. That's the real reason it's so wide, so users don't have to be super precise with the resizing. I'll pull it down and test but seems like this does not lose too much of that.

Seems like we should do this for the `panel1ResizeHandle` as well so the behavior is the same for both. Panel 1 is the inline specs list and can also have a scrollbar in the same places.

For reference, Panel 1 can be opened by clicking the "specs" button here.

Screen Shot 2022-06-20 at 9 34 03 PM

**Comment by lmiller1990** [comment]
cc @marktnoonan

resolves: https://github.com/cypress-io/cypress/issues/22608

**Review by marktnoonan — APPROVED** [review]
Tested locally and both work great

**Comment by Oustinger** [comment]
@marktnoonan Am I need to do any thing else? Or it's ok that PR is still be opened?

**Comment by lmiller1990** [comment]
@Oustinger nothing left, just need CI green - I'll take a look.

**Pull request merged**
