### PR TITLE
fix: report header stats overlapping issue with 4 digit test count

### LINKED ISSUE #21838: Icons within stats of reporter header don't account for 4 digit test count
## **Summary**
The failure icon overlaps with the test count once it reaches 4 digits. 

Screen Shot 2022-04-17 at 3 48 41 AM

## **Acceptance Criteria**
The width of the stats should push out allowing the icons to not overlap.

[https://cypressio.slack.com/archives/C02MW5QBD4K/p1650286818707969](https://cypressio.slack.com/archives/C02MW5QBD4K/p1650286818707969|smart-card)

┆Issue is synchronized with this [Jira Task](https://cypress-io.atlassian.net/browse/UNIFY-1589) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://cypress-io.atlassian.net/rest/api/2/attachment/content/11779">Screen Shot 2022-04-17 at 3.48.41 AM.png</a>
┆author: Shawn Harris
┆epic: UI/UX Improvements
┆friendlyId: UNIFY-1589
┆priority: Lowest
┆sprint: Backlog
┆taskType: Task

### PR DESCRIPTION
**Pull request by gitstart**
- Closes https://github.com/cypress-io/cypress/issues/21838
### User facing changelog

Fixed an bug where icon within stats of reporter header don't account for 4 digit test count. Fixes #21838

### Additional details
The number of tests (greater than 999) can't be seen clearly in header since the number used to be overlap with icon

### Steps to test

Start cypress app, select the target project and then start E2E testing
Start any specs (even example specs) on the header you can see the number of tests passed/failed

### How has the user experience changed?

Before
171220139-2b4f959b-6336-453d-8320-fce29d0a175a

After
Screen Shot 2022-08-08 at 12 54 46

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by gitstart** [comment]
@marktnoonan  could you help to make pipeline run on this branch?

**Comment by gitstart** [comment]
@marktnoonan PR is good for review

**Review by lmiller1990 — APPROVED** [review]
Seems fine to me, running CI now.

**Comment by gitstart** [comment]
Hi @astone123 @AtofStryker kindly help to take a look at this PR

cc: @lmiller1990

**Review by AtofStryker — APPROVED** [review]

**Comment by mschile** [comment]
Thank you for your contribution! I am going to merge this PR.

**Comment by gitstart** [comment]
This PR was pushed through [Gitstart](https://www.gitstart.com/), with contributions from @BikashSah999, @raph941, @phunguyenmurcul.

**Pull request merged**
