### PR TITLE
fix: issue with array environment variables not being handled correct…

### LINKED ISSUE #6810: Array in environment variables CYPRESS_BLACKLIST_HOSTS, CYPRESS_testFiles not handled correctly
# Current behavior:
Setting multiple hosts via the environment variable `CYPRESS_BLACKLIST_HOSTS` as an array leads to them not picked up corretly.

Example:

```bash
export CYPRESS_BLACKLIST_HOSTS=["www.google-analytics.com","*.hotjar.com"]
```

The environment variable is always handled as a string

### Desired behavior:
The desired behavior is to analyze if an array was provided and handled each item separately.

### Test code to reproduce
```bash
export CYPRESS_BLACKLIST_HOSTS=["www.google-analytics.com","*.hotjar.com"]

cypress open
```

### Versions

Node.js Version 12.8.1
Cypress Version 4.1.0

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-189) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by dmoini**
…ly (#6810)

Signed-off-by: Donovan Moini <donovanmoini@gmail.com>

- Closes #6810 

### User facing changelog

Fixes an issue where Cypress environment variables intended to be arrays were saved as strings.

### Additional details

When setting Cypress environment variables as arrays, they are stored as a string of the array instead of an array. By default, all environment variables are stored as strings, but some environment variables are intended to be numbers or booleans. That issue gets resolved in [packages/server/lib/util/coerce.js](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/coerce.js) by checking if any Cypress environment variables are meant to be a number or boolean, and if so converting them. But there is no check to see if a Cypress environment variable is meant to be an array.

I originally looked into using `strToArray()` in [packages/server/lib/util/args.js](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/args.js), but that relies on `JSON.parse()`, which would throw an error for an environment variable formatted as `'[bar1,bar2]'` due to the array elements not containing their own quotations marks, like so: `'["bar1","bar2"]'`.

This issue is resolved by added a helper function (`toArray()`) to check if the Cypress environment variable can be converted into an array and adding `toArray()` to be checked in the `coerce` function. One important part in `toArray()` is updating the `toString()` method for the returned array. This is because the default array `toString()` method returns one string containing each array element separated by commas, but without '[' or ']'. If an environment variable is intended to be an array, it will be a string beginning and ending with '[' and ']' respectively. For example, if `export CYPRESS_ARR=[1,2,3]`, then `process.env['CYPRESS_ARR']: '[1,2,3]'`. But `[1,2,3].toString() = '1,2,3'`, so comparing the two values would return `false` and not correctly update the Cypress environment variable to be an array. To correctly compare the Cypress environment variable with the returned array from `toArray()`, the returned array's `toString()` method must be updated to include '[' and ']'.

### How has the user experience changed?

Now when setting Cypress environment variables as arrays, they are correctly converted to arrays. Below are examples from #6810.

```shell
export CYPRESS_BLACKLIST_HOSTS=["www.google-analytics.com","*.hotjar.com"]
export CYPRESS_testFiles="[\"**/196*\", \"**/475*\", \"**/476*\"]"
```

Before:
errorBlacklistHosts
errorTestFiles

After:
blacklistHosts
testFiles

The example with `CYPRESS_testFiles` was originally intended as a workaround for #6810 before this pull request. While `CYPRESS_testFiles` is technically parsed correctly, I doubt that a user would want the array elements to contain quotation marks within their strings and have an element such as `" "**/475*""` instead of `"**/475*"`. To avoid this, make sure to set array Cypress environment variables with each element in quotation marks and each element delimited by a single comma without a whitespace (i.e. `CYPRESS_testFiles=["**/196*","**/475*","**/476*"]`.

This also works when setting Cypress environment variables via `--env`. 
```shell
cypress run --env foo="[bar1,bar2,bar3]"
```
image

### PR Tasks

- [x] Have tests been added/updated?
    - Note: I have added tests for adding environment variables through the command line using `--env`, but I am stumped how to add tests by adding environment variables via exporting them in the terminal (i.e. `export CYPRESS_VAR=123`). I did however find a test [here](https://github.com/cypress-io/cypress/blob/497745037fb0b80601f7f937d04b3aa61ecb620b/packages/server/test/unit/config_spec.js#L673) that checks if the Cypress environment variable `blacklistHosts` can accept arrays successfully, and this test was passing when arrays passed in were just strings. Is there possibly an issue with how arrays being passed in as environment variables were being tested?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@dmoini I could probably argue that this coerce method is complex enough to warrant some unit tests. So, you could make a `cypress/packages/server/test/unit/coerce_spec.js` file and add some tests there for input/output values. 

But yah it would be nice to have some more integration tests - I think you can just set `process.env.CYPRESS_testFiles = ....` similar to how this test is for HTTP_PROXY env vars (making sure to clean them up in between). https://github.com/cypress-io/cypress/blob/develop/packages/server/test/unit/args_spec.js#L491:L491

**Comment by jennifer-shehane** [comment]
@dmoini Will you have time to add some more tests as described above in my comment?

**Comment by dmoini** [comment]
@jennifer-shehane Yes I have some time tomorrow to work on adding tests for the `coerce` function. Is the `args_spec.js` file that you listed above a good file to look at to get an idea of how to make tests for `coerce`?

**Comment by jennifer-shehane** [comment]
@dmoini Yes, this one is maybe a simpler example where you can just see how we structure unit tests in general: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/unit/duration_spec.js

**Comment by dmoini** [comment]
@jennifer-shehane Just added unit tests for `coerce`. Check them out whenever you have the chance.

**Comment by dmoini** [comment]
@jennifer-shehane Just added your suggestions.

**Comment by jennifer-shehane** [comment]
This seems to have introduced a regression: https://github.com/cypress-io/cypress/issues/8818

**Pull request merged**
