### PR TITLE
chore: update check-dependencies

### PR DESCRIPTION
**Pull request by flotwig**
- Closes 

### User facing changelog

n/a

### Additional details

- I think we should change ensure-dependencies to be a warning only, and /not/ to automatically run `yarn`.
- Automatically running `yarn` unexpectedly slows down developers. You expect to be running `yarn cypress:open` instantly only to wait 5 minutes for everything to complete.
- Developers can make the right choice if they need to run `yarn` again.
- Developers know running `yarn` can fix unexpected behavior locally, especially if the branch is already known to be working.
- The warning serves as a reminder - if you start seeing weird behavior, you need to try `yarn`.

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@flotwig seems like this affects the build also. The kitchensink is failing with a dep error.

**Comment by flotwig** [comment]
@jennifer-shehane yeah, looks like some of our CI (unintentionally?) relies on ensure-deps. I can fix that, but does this change look good to you tho?

**Comment by jennifer-shehane** [comment]
@flotwig I think we could discuss this in our CT e2e sync to gather some more opinions. 

I definitely have found this annoying in the past when yarn was unnecessary for the thing I was doing, but I'm also not sure that relying on the developer intuitively knowing if things aren't working that it's because they didn't run `yarn` doesn't sound like a great scalable solution.

**Comment by flotwig** [comment]
> I'm also not sure that relying on the developer intuitively knowing when things aren't working that it's because they didn't run yarn doesn't sound like a great scalable solution.

Counterpoint: It's what we did for all of time before introducing `yarn`, and IMO it was better than this.

**Comment by flotwig** [comment]
Another option would be to instead of warning or forcing `yarn install`, we could prompt each time. "You are running with an outdated node_modules. Are you sure you want to continue? (Y/N)"

**Review by lmiller1990 — APPROVED** [review]

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@flotwig So we spoke through this a bit with the CT team and decided that some people do want this, but it may not be a great default for people, especially new contributors that would see odd behavior and may not understand immediately to run yarn to fix it. 

So, the suggestion is to have a command (or flag) specifically for contributors to run to opt-out of the ensure-deps behavior. So when running `yarn skip-check-start` (or however you want to name it, frame it) then it would skip the ensure-deps check and print the console warning.

**Comment by flotwig** [comment]
> So, the suggestion is to have a command (or flag) specifically for contributors to run to opt-out of the ensure-deps behavior. So when running `yarn skip-check-start` (or however you want to name it, frame it) then it would skip the ensure-deps check and print the console warning.

The script already has this in the form of an environment variable `SKIP_DEPCHECK` that, if set, prevents it from running.

So I think I'll just add this to my `~/.zshrc` and call it a day:

```
export SKIP_DEPCHECK=1
```

**Pull request closed without merging**
