### PR TITLE
feat: support alternative replace string for CYPRESS_DOWNLOAD_PATH_TEMPLATE 

### PR DESCRIPTION
**Pull request by HarlesPilter**
### User facing changelog

Now it is possible to use CYPRESS_DOWNLOAD_PATH_TEMPLATE in an .npmrc file using this syntax
CYPRESS_DOWNLOAD_PATH_TEMPLATE={endpoint}/{platform}-{arch}/cypress.zip

### Additional details
- Why was this change necessary? - When setting environment variables through .npmrc file, npm itself does string replacement and searches for ${variableName} from the file. Due to this it wasn't possible to use CYPRESS_DOWNLOAD_PATH_TEMPLATE=${endpoint}/${platform}-${arch}/cypress.zip in an .npmrc file. To prevent breaking change I added an alternative format (instead of replacing the previous one). 
Setting the environement variable through .npmrc helps us to configure cypress for the entire repository. .npmrc gets commited with the rest of the code and every dev can just run `npm i` and have Cypress downloaded from correct url.
- What is affected by this change? - Cypress CLI. Support for alternative string replacement format

### How has the user experience changed?

Before:
`CYPRESS_DOWNLOAD_PATH_TEMPLATE=${endpoint}/${platform}-${arch}/cypress.zip`
After:
`CYPRESS_DOWNLOAD_PATH_TEMPLATE=${endpoint}/${platform}-${arch}/cypress.zip` or
`CYPRESS_DOWNLOAD_PATH_TEMPLATE={endpoint}/{platform}-{arch}/cypress.zip`

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by mjhenkes** [comment]
@HarlesPilter have you tried escaping the $ signs? CYPRESS_DOWNLOAD_PATH_TEMPLATE="\${endpoint}/\${platform}-\${arch}/cypress.zip"

**Comment by HarlesPilter** [comment]
@mjhenkes Yeah.
using `CYPRESS_DOWNLOAD_PATH_TEMPLATE=\${endpoint}/\${platform}-\${arch}/cypress.zip` skips the npm env parsing but results in an download url \...endpoint/desktop/9.3.1/\win32-\x64/cypress.zip
Since npm has this code for env parsing
```function envReplace (f) {
  if (typeof f !== 'string' || !f) return f

  // replace any ${ENV} values with the appropriate environ.
  var envExpr = /(\\*)\$\{([^}]+)\}/g
  return f.replace(envExpr, function (orig, esc, name) {
    esc = esc.length && esc.length % 2
    if (esc) return orig
    if (undefined === process.env[name]) {
      throw new Error('Failed to replace env in config: ' + orig)
    }

    return process.env[name]
  })
}
```
I also tried double escape `CYPRESS_DOWNLOAD_PATH_TEMPLATE=\\${endpoint}/\\${platform}-\\${arch}/cypress.zip` which resulted in a same url

**Comment by mjhenkes** [comment]
what package manager and version are you using? In my testing I'm seeing different behaviors between yarn v1 and npm v7

**Comment by HarlesPilter** [comment]
I was using npm v6.14.16. Tried with npm v7.24.2 and seems to be working by just using `CYPRESS_DOWNLOAD_PATH_TEMPLATE=${endpoint}/${platform}-${arch}/cypress.zip` in .npmrc. Closing the PR

**Pull request closed without merging**
