### PR TITLE
feat: create-cypress-tests auto-inject config

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
This PR is a continuation of #8857 and introduces the automatic injection of config into the user cypress plugin for component testing.

### CODE REVIEW

**Comment by elevatebart** [comment]
Given the usage of NuxtJs, it could be useful to have an integration about it.

Let's do it in another PR.

**Comment by elevatebart** [comment]
Since `create-cypress-tests` will be published to npm, can you add a `Readme.md` file to quickly describe what it does?

**Review by elevatebart — APPROVED** [review]

**Comment by elevatebart** [comment]
I believe we can still optimize by batching the installation of dependencies.

And there are still some issues with the English used in the prompts and the names of the tests.

I will make a few small PRs in the future. 

Since the tests for now are fileSystem almost e2e tests, they will take forever. I hope they will only be run if something changes in the wizard.

Did you check that CI will only be run when necessary?

**Comment by dmtrKovalenko** [comment]
@elevatebart All the tests are running for 8 seconds on CI. https://app.circleci.com/pipelines/github/cypress-io/cypress/14602/workflows/a80f9c9a-2829-47bd-b43e-a69ca90025c8/jobs/507154/parallel-runs/0/steps/0-103 (only a few tests are e2e fs based)

Moreover I am not sure that this feature with dependent-only CI builds is ready... cc @panzarino

**Comment by dmtrKovalenko** [comment]
Since Bart and Jess reviewed this I am merging this PR into the original one and will work on code review points. It will be easier to no split changes, as we already reviewed this.

**Pull request merged**
