### PR TITLE
Improvements to recently added UI updates

### LINKED ISSUE #7732: Misc minor UI improvements
Miscellaneous minor UI tweaks and fixes regarding recent UI updates:

- Top border on spec file header
- Tooltip around open in IDE
- Better display of "Print to Console" when clicked
  - Add active state when button is "pressed"
  - Display tooltip to show confirmation of print (like when a command is pinned)
- Center "assert" within red/green block (issue shown below)

Screen Shot 2020-06-16 at 3 51 10 PM

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #7732

### User facing changelog

Some minor UI updates and tweaks to improve the appearance and functionality of recently added enhancements.

### How has the user experience changed?

See comment with screenshots below

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by chrisbreiding** [comment]
Could you post some screenshots of the before and after?

**Comment by panzarino** [comment]
_Added border to separate spec header and controls header_

Before:

Screen Shot 2020-06-17 at 3 27 26 PM

After:

Screen Shot 2020-06-17 at 3 24 52 PM

_Added tooltip when hovering over links that open in IDE_

Before:

Screen Shot 2020-06-17 at 3 27 31 PM

Screen Shot 2020-06-17 at 3 27 37 PM

After:

Screen Shot 2020-06-17 at 3 22 03 PM

Screen Shot 2020-06-17 at 3 22 12 PM

_Center "assert" within label box_

Before:

Screen Shot 2020-06-17 at 3 28 54 PM

After:

Screen Shot 2020-06-17 at 3 24 29 PM

_Improve feedback when clicking "Print to console"_

Before:

ezgif-6-192072abe95c

After:

ezgif-6-b646ab8ff55e

**Comment by chrisbreiding** [comment]
I think it made more sense when it said "Open file in IDE". In the code frame or stack trace, it could be any file, not necessarily a spec. We could have it be "spec" for the header and "file" for the rest, but "file" is generically applicable.

**Comment by panzarino** [comment]
@chrisbreiding I updated it to just "Open in IDE" to be more consistent with upcoming UI changes

**Pull request merged**
