### PR TITLE
remove string as valid type for match chainer

### LINKED ISSUE #2578: Wrong type definition for 'match' - removes 'string', should be 'RegExp'
### Current behaviour:

'match' requires its argument be a 'RegExp'. You passed 'https://example.com'.

### Desired behaviour:

Since in type anotation is as fallow:
```
/**
 * Asserts that the target matches the given regular expression `re`.
 * @example
 *    cy.wrap('foobar').should('match', /^foo/)
 * @see http://chaijs.com/api/bdd/#method_match
 * @see https://on.cypress.io/assertions
 */
(chainer: 'match', value: string | RegExp): Chainable<Subject>
```
I would assume it would take string. Since it is `match` I thought it would use String.match function...

### Steps to reproduce:

```js
context('test', () => {
	it('test', () => {
		cy.wrap('hello world').should('match', 'wolrd')
	})
})
```

### Versions

Cypress: 3.1.0
OS: Windows 10
Browser: Chrome 69.x.x

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #2578

### CODE REVIEW

**Comment by Bkucera** [comment]
This should be reverted, a string can be passed to `match`  when subject is a jquery element and argument is a selector:

image

**Comment by jennifer-shehane** [comment]
oh fun. We overwrite things. 😝 https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/chai.coffee#L128

**Comment by jennifer-shehane** [comment]
@Bkucera Doesn't this definition actually meet the selector requirement for match?

https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts#L3649

**Comment by Bkucera** [comment]
@jennifer-shehane alright false alarm, you are right

**Pull request merged**
