### PR TITLE
chore: use hoisted yarn install in build binary

### PR DESCRIPTION
**Pull request by tgriesser**
### Additional details

Runs the "yarn install" from the root of the packages to de-duplicate node requires via hoisting. Reduces the overall bundle size by a considerable margin >100mb, and the compressed app by ~50mb.

Main changes:
- Moved install path to `path.join(os.tmpdir(), 'cypress-build', PLATFORM)` with a symlink to `build` in the root for convenience (per @brian-mann request)
- Loosen semver ranges from pinned to `^` for better deduplication of dependencies
- Copy `yarn.lock` from the root before `yarn --production` to ensure we are building with the same dependencies we have in the lockfile for develop/testing (allows us to use the `^` rather than pinned versions with more confidence)
- Removes [additional unused directories](https://github.com/cypress-io/cypress/blob/091582baa915851fcda73973947f06adcb714a98/scripts/binary/build.ts#L99-L108) or files `demo` / `test` that are taking up space, primarily in image libraries 

### How has the user experience changed?

- Smaller bundle
- Faster install time

Before: 

Screen Shot 2021-06-28 at 2 12 53 PM

After:

Screen Shot 2021-06-28 at 2 13 03 PM

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

**Review by lmiller1990 — APPROVED** [review]
I do not 100% comprehend everything that's going on here, but I gave it a test - ran the commands - and the size is indeed smaller, like Tim says in the description.

Probably good to get a second set of eyes on the code, but it looks like there's been a decent amount of internal discussion already.

**Comment by thlorenz** [comment]
LGTM except I have reservations with build script being TypeScript, i.e. to do the build you need to first build the scripts doing that (or at least on the fly).
I've been just adding `// @ts-check` on top of files involved in any kind of devops/building or whatever needed to prepare artifacts, i.e. https://github.com/thlorenz/cypress/blob/thlorenz/develop-ts/packages/ts/build-ts.js#L1.

This provides sufficient warnings IMHO to not waste time discovering mistakes at runtime while keeping the build requirement to just having Node.js installed and ready.

**Comment by tgriesser** [comment]
@thlorenz yeah it does build on the fly here with `ts-node`, and this script is only run when building the binary. It takes several minutes to execute (does a full production build of all modules / production yarn install / full electron bundle), so the relative overhead of transpiling on the fly is almost zero.

> This provides sufficient warnings IMHO to not waste time discovering mistakes at runtime while keeping the build requirement to just having Node.js installed and ready.

Potentially, though you'd also need all of the dependencies it references installed, meaning you'd still need the `yarn install`

I could go either way though, I sort of think if we're trying to move more things to use `.ts` it's better to be consistent, but I could be convinced to keep it in `.js` if you still think it should be moved given the above. FWIW I think your example is potentially better suited in `.js` for the reasons you noted and b/c it's run more frequently.

**Comment by thlorenz** [comment]
@tgriesser I'm not concerned about the transpile cost, merely that now you need to have `ts-node` installed additionally to just Node.js.
However if we're all good with that and given we install `ts-node` as dev dependency then it might be ok.

It's more opinion than anything same reason why people should limit bash scripts to bash features instead of requiring zsh or similar.

If you feel `.ts` buys you a lot more than a `ts-check` could then let's agree to allow typescript in build scripts.
I might then write mine in TS as well in the future :)

**Comment by thlorenz** [comment]
As per discussion in Slack we agreed that TS for build scripts is fine and we should keep writing scripts in TypeScript going forward. The only exceptions are when scripts somehow execute at runtime or for our users or are very performance sensitive.

**Pull request merged**
