### PR TITLE
fix spy badge counter being cut off

### LINKED ISSUE #4822: Stub / spy counter badge is cut off
Cypress 3.4.0 with Electron or Chrome

Recipe in https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window

Run the spec file and after it is finished click on the button "Open new window" _inside the application frame_ (like a user). The `cy.stub` counter keeps incrementing - and the badge appears, but the badge gets cut off on the left.

Screen Shot 2019-07-25 at 9 25 51 AM

Screen Shot 2019-07-25 at 9 26 23 AM

Relevant markup

Screen Shot 2019-07-25 at 9 29 42 AM

Relevant files:
- packages/reporter/src/commands/command.jsx
- packages/reporter/src/commands/commands.scss

### PR DESCRIPTION
**Pull request by hhudson**
Proposal to eliminate the 'cut-off' appearance of the counter in favor of more of a 'pillbox' look

- Closes #4822

### CODE REVIEW

**Comment by brian-mann** [comment]
Can you post screenshots of the proposed difference here?

**Comment by hhudson** [comment]
@brian-mann absolutely. Will do so before Aug 13th (I'm currently traveling in a place with poor internet service).

**Comment by hhudson** [comment]
@brian-mann thanks for your patience. Please see the screenshot for my proposed changes
Screen Shot 2019-08-13 at 11 13 05 AM

**Comment by bahmutov** [comment]
@jennifer-shehane could you review this pr and if it makes sense merge it?

**Pull request merged**
