### PR TITLE
issue-6168: added leading zero to test runner counter in stats.tsx file

### LINKED ISSUE #6168: The width of the timer in the Test Runner is 'jumpy'
### Current behavior:

Currently, the Cypress GUI has a timer that shows during test progress.  The current implementation shows the time out to two decimal places, but drops trailing zeroes. So your timer jumps from 10 to 10.53 to 10.8 to 10.92 and then to 11. (As a crude example).  This causes the visual space it takes up on the screen to frantically jump around in size.  It's a bit dis-concerting.

### Desired behavior:

Any visually cleaner implementation. I suggest just showing exactly to two decimal places at all times on the timer. 10 seconds would then be 10.00 seconds.  You could also make other adjustments to the sizing of the element container, etc. to help alleviate this as well, but those feel like half measures.

This implementation would still have the element resize, but only at non-frequent, important breaks ( on the # of digit switches)

### Test code to reproduce

Run any test suite that takes over 10 seconds to complete. A specific example is not required, as this is a visual UI improvement that should be noticeable for any long-running test.

### Versions

Noticed it enough to annoy me at the current version 3.8.x, so not sure if that element has changed or if that changing element has just finally made me roll my eyes enough to open a ticket.

I'd love other suggestions or feedback on whether this bothers anyone else, as well.

### PR DESCRIPTION
**Pull request by Manuel-Suarez-Abascal**
- Closes #6168 

### User facing changelog

The timer in the Test Runner now always displays at a consistent length.

### Additional Details

I opened this PR to fix [issue-6268](https://github.com/cypress-io/cypress/issues/6168). I solved the jumpy bug on the runner test timer by adding a leading zero to the header counter.
### How has the user experience changed?

contribution-bug-fixed

### PR Tasks

- [X] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress/issues/6168)?

### CODE REVIEW

**Comment by Manuel-Suarez-Abascal** [comment]
> @Manuel-Suarez-Abascal Thanks for the contribution! Could you please sign our CLA?

You're welcome @jennifer-shehane! I have signed the CLA. Let me know, if you have any questions about my implementation!

**Comment by Manuel-Suarez-Abascal** [comment]
> @Manuel-Suarez-Abascal There's a failing unit test in the file below. Can you address this?
@jennifer-shehane I have addressed the failing unit test.  The solution has passed all tests now!

**Comment by Bkucera** [comment]
Why not add a min-width and right-align the text? the leading zero only adds visual clutter

**Comment by jennifer-shehane** [comment]
The leading zero is only up until 10 secs and they are using .toFixed(2) to force 2 decimal places. I think this will look better than min-width with a weird space on the left.

**Pull request merged**
