### PR TITLE
fix: fail semantic release if package fails to publish

### PR DESCRIPTION
**Pull request by ZachJW34**
### User facing changelog
NA

### Additional details
`npm-release` would silently fail if a package failed to publish. This PR will catch any errors when publishing and exit if one exists.

Also includes an update to snapshots that wasn't committed.

### How has the user experience changed?
NA

### PR Tasks
NA

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by lmiller1990 — COMMENTED** [review]
Cool, you could add a test: https://github.com/cypress-io/cypress/blob/develop/scripts/unit/npm-release-spec.js

Since this is a function I think you could mock `execa` and make it throw an error for a package and verify the output. Not sure how we could exercise this fully in a production like manner, but might be good to have 🤔 

I believe there is also a `--dry-run` flag you cna pass toe `semantic-release`, that might be another way to test. https://semantic-release.gitbook.io/semantic-release/usage/configuration#dryrun

**Comment by jennifer-shehane** [comment]
@ZachJW34 Is this supposed to be against develop?

**Comment by ZachJW34** [comment]
@jennifer-shehane thanks for the catch I'll switch it over.

**Comment by ZachJW34** [comment]
@lmiller1990 I'll write a test for this when I have some time. I'll convert the PR to draft in the meantime.

**Pull request closed without merging**
