### PR TITLE
fix: get next config before requiring devserver

### LINKED ISSUE #15864: [7.0.1] Component testing not working with Next.js and future.webpack5 configuration
### Current behavior

Cypress `open-ct` and `run-ct` both get stuck while using:
Nextjs: 10.1.3
React: 17.0.2
Cypress: 7.0.1
Webpack: 5.30.0

my next.config.js file:
```js
module.exports = {
  future: {
    webpack5: true,
  },
};
```

cypress/plugins/index.js file:
```js
module.exports = (on, config) => {
  require("@cypress/react/plugins/next")(on, config);
  return config;
};
```

Screenshot_2021-04-07_16-36-33
Screenshot_2021-04-07_16-37-59

### Desired behavior
It should run normally

### Test code to reproduce

I have forked [this repo](https://github.com/bahmutov/next-and-cypress-example) and updated the packages and configurations here -> https://github.com/edusig/next-and-cypress-example

### Versions

Cypress: 7.0.1
Last working Cypress version: 6.5.0
OS: Manjaro Linux

### More information

- The integration tests are working properly.
- I have read and followed [this cypress blog post](https://www.cypress.io/blog/2021/04/06/cypress-component-testing-react/) and the [documentation migration guide](https://docs.cypress.io/guides/references/migration-guide#Component-Testing)

### PR DESCRIPTION
**Pull request by djsilcock**
- Closes #15864 

### User facing changelog
Uses nextjs instance of webpack for webpack devserver

### Additional details

NextJs uses its own bundled version of webpack instead of having it as a [peer] dependency, and adds a require hook such that calls to `require('webpack')` resolve to this bundled version. This moves the `require('@cypress/webpack-dev-server')` to after the next webpack hook has been set up, so the webpack setup proceeds as planned.
Note that projects should not require to list webpack as a dependency for this plugin to work  

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by adambrgmn** [comment]
Thanks for this, this takes at least me much closer to the goal! I just want to point out though that it still seems to be issues when setting `future.webpack5 = true` in `next.config.js`.

With these changes a project with `next@10.1.2` and `future.webpack5 = false` (and deps `webpack@4` and `html-webpack-plugin@4`) starts fine.

But if I change to `future.webpack5 = true` and upgrade `webpack` and `html-webpack-plugin` to v5 it fails.

It starts Cypress properly. But I get an infinite loading indicator and in the console I see these two errors:

```
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:58724/[my_absolute_folder_path]/node_modules/_cypress/webpack-dev-server/dist/browser.js

Uncaught (in promise) Error: Problem communicating active modules to the server: undefined undefined:undefined:undefined undefined
    at eval (webpack-internal:///./node_modules/next/dist/compiled/webpack/lazy-compilation-web.js?http%3A%2F%2Flocalhost%3A58723%2Flazy-compilation-using-:35)
    at Set.forEach (<anonymous>)
    at EventSource.activeEventSource.onerror (webpack-internal:///./node_modules/next/dist/compiled/webpack/lazy-compilation-web.js?http%3A%2F%2Flocalhost%3A58723%2Flazy-compilation-using-:33)
```

As mentioned it might be unrelated but just wanted to point it out.

For reference here's my test file:

```tsx
import { mount } from '@cypress/react';
import { useState } from 'react';

const Button: React.FC<any> = (props) => <button {...props} />;

const TestComponent = () => {
  const [count, setCount] = useState(0);
  return (
    <div>
      <Button onClick={() => setCount(count - 1)}>-</Button>
      <output>{count}</output>
      <Button onClick={() => setCount(count + 1)}>+</Button>
    </div>
  );
};

it('invokes onClick handlers', () => {
  mount(<TestComponent />);
  cy.findByRole('status').should('have.text', '0');

  cy.findByRole('button', { name: '+' }).click();
  cy.findByRole('status').should('have.text', '1');

  cy.findByRole('button', { name: '-' }).click();
  cy.findByRole('status').should('have.text', '0');
});

```

**Comment by JessicaSachs** [comment]
We've removed the html-webpack-plugin dependency. If I could get a CodeSandbox reproduction or a standalone repo, it would make testing against the different versions (including validating this PR and merging it!) much easier.

**Comment by JessicaSachs** [comment]
The lazy compilation issue should be fixed soon. As should the requirement to install html-webpack-plugin. We had to fork lazy-compile-webpack-plugin because it wasn't being maintained and didn't work with Webpack 5.

Can you send me an example repository @adambrgmn and I can test this PR against the latest versions of each? We're also putting together some system tests so make sure we test against a matrix of project configurations. That will help ensure we don't regress with these build setups.

**Comment by JessicaSachs** [comment]
Yeah our nextjs configuration is not working because, like you saw @adambrgmn, our browser.js entrypoint isn't being hosted by next. I'm not sure why browser.js isn't being hosted... we mark it as an `entry` [here](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/makeWebpackConfig.ts#L50).

**Pull request merged**
