### PR TITLE
fix: export types

### LINKED ISSUE #25705: MountOptions and MountReturn interfaces not exported from cypress/react18
### Current behavior

When trying to import interfaces `MountOptions` and `MountReturn` from `cypress/react18` it gives this error, as they're not actually exported: 

image

These are both exported from `cypress/react` and they're both documented on the React API page: https://docs.cypress.io/guides/component-testing/react/api#mount  

### Desired behavior

Could you export these from `cypress/react18` as well please?

### Test code to reproduce

`import type { MountOptions, MountReturn } from 'cypress/react18';`

### Cypress Version

12.4.1

### Node version

16.15.0

### Operating System

macOS Montery 12.4

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes https://github.com/cypress-io/cypress/issues/25705

### Additional details

Export types.

### Steps to test

No real need. You could pull the branch, build, and sure types are exported.

### How has the user experience changed?

N/A

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by samtjo — APPROVED** [review]

**Review by mike-plummer — APPROVED** [review]

**Comment by emilyrohrbough** [comment]
@lmiller1990 Isn't this a bug fix? Would need type `fix` to trigger a patch release with this change.

**Comment by lmiller1990** [comment]
@emilyrohrbough sure, good point - I changed it to `fix`.

**Comment by samtjo** [comment]
Hey @lmiller1990 @emilyrohrbough - This doesn't look like it triggered a release, it would normally be the commit message that should have type `fix` rather than the PR title, although obviously I don't work at Cypress and haven't looked in depth at your setup. 

So just checking, is there a way you can manually trigger a release for this or will we have to wait until the next release is triggered by something else? 

Thanks!

**Comment by mike-plummer** [comment]
> Hey @lmiller1990 @emilyrohrbough - This doesn't look like it triggered a release, it would normally be the commit message that should have type `fix` rather than the PR title, although obviously I don't work at Cypress and haven't looked in depth at your setup.
> 
> So just checking, is there a way you can manually trigger a release for this or will we have to wait until the next release is triggered by something else?
> 
> Thanks!

Hi @samtjo . We run on a ~2 week release cadence, so this fix should be included in our 12.6.0 release currently planned for a week from today

**Comment by samtjo** [comment]
Great thanks @mike-plummer!

**Comment by lmiller1990** [comment]
It's also possible to trigger a release by making a PR directly against master - I should have done that. If you want this feature *now* you could

1. fork master
2. cherry-pick this commit
3. make a PR against master
4. when merged, semantic release runs

Alternatively, just wait for the next release. :100:

**Comment by samtjo** [comment]
It's alright, I can wait until next week for 12.6.0 - thanks again 👍🏻

**Comment by ZachJW34** [comment]
@lmiller1990 @samtjo `master` is no longer used for releasing npm packages. Develop merges will now kick off semantic-release if applicable. This package should be released come the next green develop merge (though looks like develop is struggling to go green).  Note that the update would only apply to `@cypress/react` (downloaded via npm), the `cypress/react` package only updates per Cypress release

**Comment by samtjo** [comment]
Just to check @ZachJW34, is the next Cypress release you're referring to, the 12.6.0 one next week?

**Comment by ZachJW34** [comment]
@samtjo Yes that's the one!

**Pull request merged**
