### PR TITLE
feat: cy.submit validates inputs before sending data.

### LINKED ISSUE #6678: type / submit in Cypress not triggering HTML validation on elements
### Current behavior:

Not finding invalid elements, whether by:

1. `cy.get('<selector>:invalid')`

```js
cy.get('[data-name="name"]:invalid').should('have.length', 1);
```

2. `validity` property

```js
cy.get('[data-name="name"]').then(($input) => {
  return expect($input[0].validity.tooShort).to.be.true;
});
```

### Desired behavior:

Correctly indicate that the element is indeed invalid (so that assertions can be based on this).

### Test code to reproduce

These tests both fail in showing any problems with invalidity, despite the HTML element being queried having  `minlength` attribute of 3 and our test typing only a single letter ("a"):

```js
it('should catch invalid element by pseudo-selector', () => {
    cy.visit('http://localhost:8000/');
    const tooShortOfAName = 'a';
    cy.get('[data-name="name"]').type(tooShortOfAName);

    // Fails with or without a form click
    // cy.get('[data-name="action2"]').click();

    // Fails here
    cy.get('[data-name="name"]:invalid').should('have.length', 1);
  })

  it('should catch invalid element by JS API', function () {
    cy.visit('http://localhost:8000/');
    const tooShortOfAName = 'a';
    cy.get('[data-name="name"]').type(tooShortOfAName);

    // Fails with or without a form click
    // cy.get('[data-name="action2"]').click();

    // Fails here
    cy.get('[data-name="name"]').then(($input) => {
      return expect($input[0].validity.tooShort).to.be.true;
    });
  });
```

Here's the minimal repo to reproduce: (note that I've added a cypress install as I think you may want to do in your boilerplate also since your docs refer to installing cypress locally)

https://github.com/brettz9/cypress-test-tiny/tree/not-getting-invalidity

(i.e., on the `not-getting-invalidity` branch)

<details>
  <summary>Outdated info</summary>
I've also tacked on an environmental variable test (same as #2605 ?)

```js
it('should obtain environmental variables', function () {
  cy.log(Cypress.env('secret'))
  expect(Cypress.env('secret')).to.equal('Be good');
});
```

...which is not *consistently* getting the `secret` despite it being set in `plugins/index.js`

```js
module.exports = (on, config) => {
  config.env = config.env || {};
  config.env.secret = 'Be good';
  return config;
);
```

...consistent with the approach described for dynamically setting the environmental variables at https://docs.cypress.io/api/plugins/configuration-api.html#Switch-between-multiple-configuration-files or https://docs.cypress.io/api/cypress-api/env.html#From-a-plugin.
</details>

### Versions

4.1.0, Mac OSX 10.15.2, Chrome 80.0.3987.132 (Official Build) (64-bit)

### LINKED ISSUE #14911: cy.submit command does not check the form's validity
Cypress v6.4.0
Reproduction in https://github.com/cypress-io/cypress-test-tiny/tree/invalid-form-submit

Imagine a form with input element validation

```html
<body>
  <form id="form-validation" action="/action_page.php">
    <div>
      <label for="item">Item:</label>
      <input id="item" type="text" name="item" required />
    </div>

    <div>
      <label for="quantity">Quantity (between 1 and 5):</label>
      <input
        type="number"
        id="quantity"
        name="quantity"
        min="1"
        max="5"
        required
      />
    </div>

    <input type="submit" />
  </form>
</body>
```

The user should not be able to submit this form. If we try to use `cy.click` then we see the browser validation message, and the form is not submitted

```js
/// <reference types="cypress" />
describe('form', () => {
  it('should not be submittable', () => {
    cy.visit('index.html')

    cy.get('#form-validation').within(() => {
      // note we cannot submit by clicking the button
      // since some of the input elements on the page
      // fail the HTML validation
      cy.get('input[type=submit]').click()
    })
  })
})
```
Screen Shot 2021-02-03 at 9 56 29 PM

But if we use `cy.submit` it happily submits the form bypassing the validation

```js
/// <reference types="cypress" />
describe('form', () => {
  it('should not be submittable', () => {
    cy.visit('index.html')

    cy.get('#form-validation').within(() => {
      // note we cannot submit by clicking the button
      // since some of the input elements on the page
      // fail the HTML validation
      cy.get('input[type=submit]').click()

      // but the .submit() happily ignores the checks
      cy.root().submit()
    })
  })
})
```

Screen Shot 2021-02-03 at 9 56 43 PM

## Expected

- `cy.submit` should check the form's validity by calling `element.checkValidity()` first, it should be a built-in assertion

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #14911
- Closes #6678

### User facing changelog

`cy.submit` now fails when form validation fails. 

### Additional details
- Why was this change necessary? => `cy.submit` submitted the form even when the validation failed. It doesn't reflect the default browser behavior.
- What is affected by this change? => When validation is failed, submit is not done and an error is thrown. It's a breaking change.
- Any implementation details to explain? => I used [`checkValidity()`](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#constraint_validation_process) function and created a new error message. 

### How has the user experience changed?

**Before:**

Screenshot from 2021-02-08 15-35-28

**After:**

Screenshot from 2021-02-08 15-35-01

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? => ~Maybe [the example here](https://glebbahmutov.com/cypress-examples/6.4.0/recipes/form-validation.html) should be added to [`cy.submit` doc](https://docs.cypress.io/api/commands/submit.html)~ I think it's enough we just note that cy.submit will fail if validation fails: https://github.com/cypress-io/cypress-documentation/pull/3608

### CODE REVIEW

**Comment by sainthkh** [comment]
Flaky build?

**Comment by jennifer-shehane** [comment]
yah, we merged in a big feature into develop and there's just a lot of flake from everywhere now.

**Review by chrisbreiding — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
@sainthkh I think these `nextUntil` failures in the 7.0 branch were maybe introduced from this PR.

Screen Shot 2021-02-28 at 8 15 34 AM

**Comment by sainthkh** [comment]
@jennifer-shehane Confirmed that this PR caused the bug. Trying to find the cause and the solution.

**Pull request merged**
