### PR TITLE
chore: add a script to run all react tests in a single step

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes https://cypress-io.atlassian.net/browse/CT-274

### User facing changelog

Improve CI infra by running all npm/react project test in a single CircleCI step via a script. This reduces 12 steps into a single step.

### Additional details

Merge some circle CI jobs together so that they run on the same machine as part of the same GH status check. I am not entirely sure if there is a more CircleCI way of doing this. This approach means they won't run in parallel, but the total run time is still <10m for around 12 projects (1m / project) so it seems like a reasonable compromise.

### How has the user experience changed?

It has not.

### PR Tasks

N/A

- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
I don't understand the reason, it looks like the parallelisation was in reality the root of issue

**Comment by lmiller1990** [comment]
I wonder if there is a way to config circle to run them all in on the same machine/step. I can look more into this if needed, just went for the simplest solution here. Do you see any downsides to this solution (I guess less maintainable?)

**Comment by dmtrKovalenko** [comment]
There are several problems: 
1) When the test failed it should be immediately clear what exactly failed 
2) They should be parallelized (if we want to have 1 job we can make several containers for each package) 
3) It should be easy to disable running any project on CI for whatever reason

**Comment by lmiller1990** [comment]
At the moment if one project has a failed test this will actually exit the process - so the failure *will* be at the bottom, but it's possible subsequent projects could have failing tests that won't be revealed until the previous ones have all the tests fixed. For (3) it's actually trivial since we have that `SKIP_ON_CI` array. But I agree this is not super ideal.

I am not very familiar with parallelizing things in CIs, do we have something similar in this repo somewhere I can look at? Otherwise I can actually dive into Circle's docs and figure out how to have a single job w/ multiple containers.

**Comment by dmtrKovalenko** [comment]
Parallelizing is pretty easy https://circleci.com/docs/2.0/parallelism-faster-jobs/

> At the moment if one project has a failed test this will actually exit the process 
That's not ideal as well because if you have 3 failures in 3 different projects you will need to run CI 3 times

**Comment by lmiller1990** [comment]
Neat, I will try to implement this tomorrow.

**Pull request closed without merging**
