### PR TITLE
fix: prevent unwanted scroll on mousedown

### LINKED ISSUE #8279: cy.click() doesn't trigger click event if el to click has "tabindex=0" outside of current viewport
Hi there,

### Current behavior:

I'm using `tabindex="0"` across a vue app to be able to close forms with the ESC key. This feature introduces the following issue: In the tests the `cy.click()` calls in some cases are not triggering the actual event. Instead it seems like the click just sets the focus.

### Desired behavior:

Click event should get triggered.

### Test code to reproduce

I've tried to reproduce it with the cypress-realworld-app. You can check it out here: https://github.com/tho-masn/cypress-realworld-app/pull/1/files

To reproduce, just run the following test file: `cypress/tests/ui/bankaccounts.spec.ts`
You will see, that the click event doesn't get fired. There should appear a message below the "save" button saying "Submit worked". This issue is introduced by adding `tabIndex={0}` to the form in `BankAccountForm.tsx`

There are several options to make this example work again:

- Remove the `tabIndex={0}` attribute again
  - Not an option for me, as I need it to close the forms with ESC
- Add `{ force: true }` to the submit click call in the test.
  - Not an option for me, as I would have to add `force: true` to basically every click call
- Don't use a `div` with a click action handler for the submit button, but a real submit button
  - Not an option for me, as I have click handlers on divs which are not buttons
- Reduce the height of the div below the save button to `500`
  - This one is really weird. The issue only appears, if the page grows

### Versions

Cypress: v4.12.1
OS: MacOS 10.15.5

### PR DESCRIPTION
**Pull request by tgreen7**
- Closes #8279 

### User facing changelog
Prevent default browser scroll on mouseDown which was causing cy.click() to fail in some cases.

### How has the user experience changed?
cypress clicks should be less buggy

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@tgreen7 Can you add a test around this new behavior?

There is a Contributing Guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

Here's an example of another issue's test code:

- HTML template replicating bug: https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/fixtures/issue-565.html
- Test spec: https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/issues/565_spec.js

To run the tests:

- within `cypress` root, run `yarn`
- run `yarn workspace @packages/driver cypress:open`
- click on the test you're writing to run it within Cypress

Instructions for running the `driver` tests can always be found here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/README.md

**Comment by tgreen7** [comment]
@jennifer-shehane I added a test. Looks like there was some flake in the ci/circleci: server-e2e-tests-chrome

**Comment by jennifer-shehane** [comment]
Thanks! We'll have someone on the team review this as soon as we can.

**Comment by tnrich** [comment]
@jennifer-shehane just want to make sure this one gets the correct label. I see it still is marked as `stage: needs a test` which I don't think is accurate. Thanks!

**Review by Bkucera — CHANGES_REQUESTED** [review]
This change looks good however the test passes without the changes, I'll see if I can quickly rewrite it

**Review by Bkucera — APPROVED** [review]

**Pull request merged**
