### PR TITLE
fix: use legacy-peer-deps for semantic-release process

### PR DESCRIPTION
**Pull request by ZachJW34**
### User facing changelog
na

### Additional details
The `npm-release` job is broken due to peer-dependency issues. Before reverting the semantic-release dep (which has security implications), I'd like to try the `NPM_CONFIG_LEGACY_PEER_DEPS` option.

Link to latest master `npm-release` failure: https://app.circleci.com/pipelines/github/cypress-io/cypress/41450/workflows/e56453d4-5d77-4e96-8262-82517d9668aa/jobs/1716530

### Steps to test
I have no good way to test this since semantic-release requires valid npm_tokens. The build is failing when running `npm version` but I can't reproduce this locally.

### How has the user experience changed?
na

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by rachelruderman — APPROVED** [review]
Here's hoping! 😸

**Comment by emilyrohrbough** [comment]
@ZachJW34 Do you have a link to the broken job?

**Comment by ZachJW34** [comment]
@emilyrohrbough updated the description with a link to the latest master build, I tried to fix it last week. All `npm-release` builds since the [semantic-release bump](https://github.com/cypress-io/cypress/pull/22238) have been failing (at least, the jobs that actually detect packages to publish)

**Comment by emilyrohrbough** [comment]
> I have no good way to test this since semantic-release requires valid npm_tokens. The build is failing when running npm version but I can't reproduce this locally.

Could you update the script to perform a dry-run and test on this branch it provides the correct dry-run output?
https://github.com/semantic-release/semantic-release/blob/master/cli.js#L37

**Comment by ZachJW34** [comment]
@emilyrohrbough `--dry-run` passes locally, but it skips the semantic-release steps that are actually throwing the error
Screen Shot 2022-08-09 at 5 42 23 PM

**Review by lmiller1990 — APPROVED** [review]
let's give it a try

**Pull request merged**
