### PR TITLE
Update logic of actionability to check for "writability" only if the action is "typing"

### LINKED ISSUE #4874: Cannot click on 'readonly' inputs / textarea
### Current behavior:

As noted initially from this comment https://github.com/cypress-io/cypress/pull/4783#issuecomment-516174805, Cypress now errors since 3.4.1 release when attempting to click on a `readonly` input or textarea. 

### Desired behavior:

Unlike an input being `disabled`, having a `readonly` attribute does not restrict clicking, focusing, selecting, or triggering events on the element. These actions should be allowed and only typing should be restricted.

### Steps to reproduce: (app code and test code)

```js
cy.get('input[readonly]`).click()
```

### Versions

Cypress 3.4.1

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #4874
- Write tests to ensure other actions happen appropriately on readonly elements

### CODE REVIEW

**Comment by Bkucera** [comment]
I wouldn't pass `actionType` like that into actionability, I would let actionability take configuration on which `ensures` to verify not let it know about what command it is verifying for. This way it is a proper abstraction.

I've got that logic in a (wip) PR here #4870 

Unless this needs to go out in a patch I suggest we close in favor of that PR

**Comment by brian-mann** [comment]
@Bkucera 	can you help extract that logic and apply it to this PR?

**Comment by Bkucera** [comment]
@brian-mann sure, so patch it is

**Comment by jennifer-shehane** [comment]
@Bkucera  Yeah, I didn't like my own implementation haha. But wasn't sure how else to do it.

This PR will likely go out in 3.5.0, unless there are some other patch fixes in the meantime that necessitate 3.4.2. Not sure if your simulated type fixes will go in that fast. But - it's a regression that needs to be fixed asap.

**Comment by Bkucera** [comment]
@jennifer-shehane 	well, thanks for the tests!

**Comment by Bkucera** [comment]
closing in favor of #4881

**Pull request closed without merging**
