### PR TITLE
Run tests against Chrome 73, Node 8.2.1

### PR DESCRIPTION
**Pull request by flotwig**
This PR moves the Circle config to use `cypress/browsers:node8.21-chrome73`.

This PR also re-enables the HTTPS performance tests, now that `--disable-http2` is available as a Chrome arg so they'll work.

### CODE REVIEW

**Comment by flotwig** [comment]
@Bkucera can you take a look at the failing driver integration tests? Seems like something in Chrome 73 could be breaking `commands/actions/type_spec.coffee` tests and others, could use your expertise in getting these to work on this new Docker image.

https://circleci.com/gh/cypress-io/cypress/93313

**Comment by jennifer-shehane** [comment]
@flotwig @Bkucera Relevant open issue about failing driver tests - https://github.com/cypress-io/cypress/issues/3907

**Comment by flotwig** [comment]
Weirdly enough, `type_spec` is actually passing in CI: https://circleci.com/gh/cypress-io/cypress/94323#tests/containers/2

It's some other tests that are failing.

**Comment by flotwig** [comment]
Superseded by #4001

**Pull request closed without merging**
