### PR TITLE
Add "PATCH" to HTTPMethod type

### PR DESCRIPTION
**Pull request by naseem-qadium**
One liner to support the PATCH Http Method:

https://restfulapi.net/http-methods/#patch

### CODE REVIEW

**Comment by bahmutov** [comment]
Could you also add a test in cli/types/tests/kitchen-sink.ts please? To make sure the PATCH is accepted

**Comment by naseem-qadium** [comment]
Sorry guys have been busy. working on it now

**Comment by naseem-qadium** [comment]
`[electron:install   ]
[electron:install   ] @packages/electron needs: npm run build
[electron:install   ] up to date in 6.114s
[example:install    ]
[example:install    ] > @packages/example@0.0.0 postinstall /Users/naseemal-naji/Expander/cypress/packages/example
[example:install    ] > echo '@packages/example needs: npm run build'
[example:install    ]
[example:install    ] @packages/example needs: npm run build
[example:install    ] up to date in 8.322s
[extension:install  ]
[extension:install  ] > @packages/extension@0.0.0 postinstall /Users/naseemal-naji/Expander/cypress/packages/extension
[extension:install  ] > echo '@packages/extension needs: npm run build'
[extension:install  ]
[extension:install  ] @packages/extension needs: npm run build
[extension:install  ] up to date in 9.697s
[driver:install     ] npm ERR! path /Users/naseemal-naji/Expander/cypress/packages/driver/node_modules/npm/node_modules/dezalgo
[driver:install     ] npm ERR! code ENOENT
[driver:install     ] npm ERR! errno -2
[driver:install     ] npm ERR! syscall rename
[driver:install     ] npm ERR! enoent ENOENT: no such file or directory, rename '/Users/naseemal-naji/Expander/cypress/packages/driver/node_modules/npm/node_modules/dezalgo' -> '/Users/naseemal-naji/Expander/cypress/packages/driver/node_modules/npm/node_modules/.dezalgo.DELETE'
[driver:install     ] npm ERR! enoent This is related to npm not being able to find a file.
[driver:install     ] npm ERR! enoent
[driver:install     ]
[driver:install     ] npm ERR! A complete log of this run can be found in:
[driver:install     ] npm ERR!     /Users/naseemal-naji/.npm/_logs/2018-05-29T21_43_13_437Z-debug.log
[cli:install        ] npm WARN @cypress/sinon-chai@1.0.0 requires a peer of sinon@>=1.4.0 <2 but none was installed.
[cli:install        ] npm WARN tslint@5.10.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev but none was installed.
[cli:install        ]
[cli:install        ] up to date in 11.036s`


Seeing errors when running npm install (using Node v8.2.1 and NPM 5.3.0). Is there something I'm missing here..?

**Comment by brian-mann** [comment]
This is a common issue with npm in the `5.x.x` range. Don't think it's related to Cypress. I've seen it before and can't remember how I fixed it...

Googling this: https://www.google.com/search?q=.dezalgo.DELETE&oq=.dezalgo.DELETE&aqs=chrome..69i57.231j0j7&sourceid=chrome&ie=UTF-8

**Comment by egucciar** [comment]
@naseem-qadium 

delete node_modules and packages folder and git reset to the head. This will revive packages folder sans node_modules. Repeat `npm install`. i upgraded to `6.1.0` but i dont think that makes a big difference as long as you wipe out node modules first.

**Comment by naseem-qadium** [comment]
Ahhh very clever

**Comment by bahmutov** [comment]
doing this addition in https://github.com/cypress-io/cypress/pull/1874

**Pull request closed without merging**
