### PR TITLE
misc: Replace LayerCI reference with Webapp.io

### PR DESCRIPTION
**Pull request by ianwalter**
- Closes 

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Context: https://webapp.io/blog/layerci-has-rebranded-to-webapp-io/

**Comment by emilyrohrbough** [comment]
These changes look good to me, though we also need update our CI docs found here to
1. remove the stale example referencing LayerCI
2. add a note that Cypress versions less than 3.15.0 will need to manually provide the CI ENVs to correctly send their SCM to the Cloud. https://docs.cypress.io/guides/continuous-integration/introduction#Git-information

**Comment by emilyrohrbough** [comment]
@ianwalter Let us know when this is ready for review!

**Comment by jennifer-shehane** [comment]
@ianwalter Do you have time to complete this PR?

**Comment by ianwalter** [comment]
@jennifer-shehane Sorry, still trying to find the time! 😅

**Comment by ianwalter** [comment]
Closing in favor of https://github.com/cypress-io/cypress/pull/28874

**Pull request closed without merging**
