### PR TITLE
Replace deprecated Mocha interfaces

### LINKED ISSUE #5795: Typescript declarations are using deprecated Mocha interfaces
### Current behavior:

```js
  Cypress.on('test:after:run', (test, runnable) => {
    if (test.state === 'failed') {
      // leads to 'parent' is deprecated. `.parent` has type `Mocha.Suite | undefined` in `Mocha.Test`.
      const screenshotFileName = `${runnable.parent!.title} -- ${test.title} (failed).png`;
    }
  });
```

### Desired behavior:
Should not be deprecated.

### Versions

3.6.1

### PR DESCRIPTION
**Pull request by CSchulz**
- Closes #5795

### User facing changelog

Replace deprecated Mocha interfaces with their replacements

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Hey @CSchulz, could you give some more context on where you tracked this down? Where the changes were made in Mocha's type reference that made these deprecated vs not deprecated? Thanks!

**Comment by CSchulz** [comment]
@jennifer-shehane Our linting tools were complaining about deprecated mocha interfaces because I want to use the different events.
You are using the mocha types 5.2.7 which already declaring the used interfaces as deprecated.

**Comment by jennifer-shehane** [comment]
@CSchulz The Mocha version packaged in Cypress 3.7.0 is mocha 3.5.3, so we would need the type definitions to support that. I'm not completely familiar with how their types semver works.

**Comment by jennifer-shehane** [comment]
@CSchulz Any updates?

**Comment by brian-mann** [comment]
We recently bumped mocha to the latest version as part of releasing `4.x.x`.

We now just need to bump `@types/mocha` to `7.x.x` and also bump the other packages to all use the same mocha version, which I believe will supersede this PR.

**Comment by jennifer-shehane** [comment]
Closing since this requires different updates due to our recent mocha upgrade

**Pull request closed without merging**
