### PR TITLE
chore(deps) update lodash to address CVE

### PR DESCRIPTION
**Pull request by zacharoth**
just ticking lodash to address a lodash vulnerability

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Closing. We use renovate to manage our updates - and use set versions as noted in our [Contributing guide](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#dependencies). I'll make sure their PR runs through.

**Comment by zacharoth** [comment]
👍 thanks!

**Comment by lukeapage** [comment]
Note that the security issue is for web servers / services not for tooling so it isn’t important to upgrade.

**Comment by jennifer-shehane** [comment]
@lukeapage Yeah, we know, but people feel cozy not seeing the security warnings - and this is a pretty easy update to push through. Thanks for noting.

**Comment by hugomn** [comment]
Thanks for addressing it. When will this be released?

**Comment by jennifer-shehane** [comment]
Released in [`3.4.1`](https://on.cypress.io/changelog#3-4-1).

**Pull request closed without merging**
