### PR TITLE
Simpler git parsing 841

### PR DESCRIPTION
**Pull request by bahmutov**
`gift` really breaks on PGP signature. It tries to parse everything, I switched this to simple git commands that just get exactly what we need in each case. Still a few unit tests to rework.

Factored out git commands into https://github.com/cypress-io/commit-info which simplifies our code a lot. Also, bunch of tests are moved into commit-info

### CODE REVIEW

**Comment by brian-mann** [comment]
I'm going to merge this in, but would like https://github.com/cypress-io/commit-info/issues/3 fixed asap

**Comment by bahmutov** [comment]
Hmm, I now see PGP signatures here!

screen shot 2017-10-29 at 10 05 57 pm

**Comment by brian-mann** [comment]
Will you update `package.json` to reflect the new version of the commit module?

**Comment by bahmutov** [comment]
I am working on release, there is a test that is failing on CI :(

**Comment by bahmutov** [comment]
Pushed `@cypress/commit-info@1.2.2` version bump straight to `develop` branch.

**Pull request merged**
