### PR TITLE
Update blob-util, remove @types/blog-util

### LINKED ISSUE #6001: Replace dep @types/blob-util (it's deprecated)
### Current behavior:

We include `@types/blob-util` as a dep in the cli here: https://github.com/cypress-io/cypress/blob/v4.0-release/cli/package.json#L64:L64

As mentioned in this PR https://github.com/cypress-io/cypress/pull/5684#pullrequestreview-316174984, this dep has been deprecated since blob-util provides it's own types in their package as mentioned here: https://www.npmjs.com/package/%40types/blob-util

### Desired behavior:

Replace use of `@types/blob-util` to include the types correctly.

### Versions

3.8.0

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Close #6001

### CODE REVIEW

**Comment by sainthkh** [comment]
I don't remember correctly. But I failed at the last attempt, because the API has been changed in blob-util 2.x. So, some codes and even documentation should be changed because of the breaking change. 

I'll check them out tomorrow.

**Comment by jennifer-shehane** [comment]
@sainthkh Thanks, I'm not sure what needs to be changed but wanted to get it started. We're planning a 5.0 release, so thought we could get this in. Feel free to commit or start a new PR if necessary.

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress/pull/7795

**Comment by jennifer-shehane** [comment]
@bahmutov Why do you keep reopening this PR? The work for this is being done in https://github.com/cypress-io/cypress/pull/7795 now, please do not reopen.

**Pull request closed without merging**
