### PR TITLE
bump @babel/plugin-proposal-object-rest-spread

### PR DESCRIPTION
**Pull request by Keeknast3**
- Closes 

### Pre-merge Tasks

- [ ] Have tests been added/updated for the changes in this PR?
- [ ] Has a PR to [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation) been submitted to document any user-facing changes? 
- [ ] Have the [type definitions](cli/types/index.d.ts) been updated with any user-facing API changes?
- [ ] Has the [cypress.schema.json](cli/schema/cypress.schema.json) been updated with any new configuration options?
- [ ] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Hey @Keeknast3, could you explain why you are merging this into the `jsdoc-examples-loc-should` branch? It seems that branch has a higher version of this plugin.

**Comment by Keeknast3** [comment]
Why not

**Comment by jennifer-shehane** [comment]
@Keeknast3 All PR's should be made against our `develop` branch as explained in our contributing doc: https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#committing-code

**Comment by jennifer-shehane** [comment]
Closing due to inactivity.

**Pull request closed without merging**
