### PR TITLE
Add Cypress.dom.* to TS type declarations

### LINKED ISSUE #4408: Cypress.dom.isDetached missing from Typescript types
### Current behavior:

The method `Cypress.dom.isDetached()` type errors in Typescript projects.

### Desired behavior:

The method `Cypress.dom.isDetached()` does not type error in Typescript projects.

### Steps to reproduce: (app code and test code)

1. Set up a Typescript Cypress project as described in https://docs.cypress.io/guides/tooling/typescript-support.html
2. Write the following test:

```Typescript
describe('Demonstrates bug', function() {
  beforeEach(() => {
    cy.setup();
  });
  
  it('demonstrates Typescript error'), function() {
    cy.get('button').then(($el) => {
      Cypress.dom.isDetached($el)
    });
  });
});
```
3. Get the following error:
```
Property 'isDetached' does not exist on type '{ isHidden(element: HTMLElement | JQuery<HTMLElement>): boolean; }'
```

### Versions

Cypress 3.2.0
Typescript 3.4.5
Chrome 74.0.3729.169
macOS 10.14.5

### PR DESCRIPTION
**Pull request by kylerob**
Closes #4408 

### User facing changelog

Cypress.dom.isDetached no longer throws a type error in TypeScript projects.

### Additional details

We may want to include all Cypress.dom.* functions in the index.d.ts. If so, I can add the rest of them in this PR.

### PR Tasks

- [x] Have tests been added/updated? (Not sure which test file covers this)
- [x] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?

### CODE REVIEW

**Comment by flotwig** [comment]
@kylerob This PR looks good, but it would be helpful to have the rest of the `dom` methods as well if you want to go ahead and add them.

**Comment by kylerob** [comment]
@flotwig I just pushed up the rest of the declarations. Some of the functions were tougher to nail down types for, so I'm not 100% confident in all my declarations. Is there a good automated way to test these before we publish them?

**Comment by flotwig** [comment]
> @flotwig I just pushed up the rest of the declarations. Some of the functions were tougher to nail down types for, so I'm not 100% confident in all my declarations. Is there a good automated way to test these before we publish them?

The easiest way to test these definitions is probably to exercise them in actual Typescript. There are already tests for `Cypress.dom` here:

https://github.com/cypress-io/cypress/tree/develop/packages/driver/test/cypress/integration/dom

You could rename these `.js` files to `.ts`, ensure that the type for `Cypress.dom` is inferred correctly, and ensure that the types that you've created don't cause any type errors in the tests.

**Comment by jennifer-shehane** [comment]
Hey @kylerob, did you have time to add tests for these changes? If you no longer have time, please close the PR.

**Comment by jennifer-shehane** [comment]
@kylerob Unfortunately we have to close this PR due to inactivity.

**Comment by rovshenn** [comment]
Any plans to continue on this? Seem that PR was almost there :)

**Comment by jennifer-shehane** [comment]
@rovshenn You are welcome to open a new PR to continue the work. We can't maintain stale PRs that have had no commits in 4 months.

**Comment by flotwig** [comment]
I can get this one done, it just needs some tests.

**Comment by flotwig** [comment]
> @flotwig the tests for typedefs should go in `cli/types/tests`. can you add tests to `cli/types/tests/cypress-tests.ts` ?

sure, i figured converting the existing tests to TS would be enough coverage though

**Comment by Bkucera** [comment]
an alternative would be making Cypress.dom an `any` type, which would fix the type errors

**Comment by rovshenn** [comment]
Yes @Bkucera , but that reduces the value of the typing :) it is a trade off. Thank you very much @flotwig ! Hopefully I will get my hands dirty with cypress one day

**Comment by rovshenn** [comment]
@jennifer-shehane could you please tag which release this will be in? Thank you very much for all your assistance!

**Comment by jennifer-shehane** [comment]
This will go out in `4.1.1` or `4.2.0` depending on whether there are other features that make it in the next release. Either way - that release is scheduled for Mar 13 at the latest.

**Comment by rovshenn** [comment]
Thank you very much @jennifer-shehane , I am looking forward to that!

**Pull request merged**
