### PR TITLE
fix: cy.request allows nested objects as qs

### LINKED ISSUE #27745: Array and Objects in "qs" params incorrectly parsed in cy.request() after updated to the latest Cypress version
### Current behavior

**Current behavior**
After updating Cypress version to the latest some of my tests started falling. The tests that affected contain cy.request() with qs wich is represented like
```js
{
        limit: 10,
        page: 1,
        where: {
            commission: {filterCommissionType: commissionType},
            types: {klickly_orders: 1, shopify_orders: 0},
            date: {
                startDate: startDate || moment().subtract(1, 'day').toISOString(),
                endDate: endDate || moment().toISOString()
            }
        },
        order: [ 'processed_at', 'desc' ]
    };
```

When the request is being sent I see this code in the console:
`"https://brands-dashboard-api.klickly-dev.com/orders?limit=10&page=1&where=%5Bobject%20Object%5D&order=processed_at%2Cdesc";`

But it should be:
`"https://brands-dashboard-api.klickly-dev.com/orders?limit=10&page=1&where%5Btypes%5D%5Bklickly_orders%5D=1&where%5Btypes%5D%5Bshopify_orders%5D=0&where%5Bcommission%5D%5BfilterCommissionType%5D=all&where%5Bdate%5D%5BstartDate%5D=2023-08-05T00%3A00%3A00.000Z&where%5Bdate%5D%5BendDate%5D=2023-09-04T23%3A59%3A59.999Z&order%5B0%5D=processed_at&order%5B1%5D=desc";`

**My software details:**
Cypress v13.1.0
Chrome instance v116
Macbook - Apple M2 Max, Ventura 13.0
Node v16.15.0

### Desired behavior

_No response_

### Test code to reproduce

// support.cy.js
```js
const orderApiQS = (data) => {
    const {startDate = null, endDate = null, commissionType = 'all'} = data || {};
    return {
        limit: 10,
        page: 1,
        where: {
            commission: {filterCommissionType: commissionType},
            types: {klickly_orders: 1, shopify_orders: 0},
            date: {
                startDate: startDate || moment().subtract(1, 'day').toISOString(),
                endDate: endDate || moment().toISOString()
            }
        },
        order: [ 'processed_at', 'desc' ]
    };
};

Cypress.Commands.add('apiGetOrdersList', () => {
    return cy.request({
        method: 'GET',
        url: 'https://brands-dashboard-api.klickly-dev.com/orders',
        qs: orderApiQS(),
        timeout: 60000
    });
});
```

```js
Cypress.Commands.add('loginBrandDashboard', (email = brandEmail, password = brandPass) => {
    cy.session(email, () => {
        cy.request({
            method: 'POST',
            url: 'https://brands-dashboard-api.klickly-dev.com/auth/login',
            body: {
                email,
                password
            },
            timeout: 60000
        }).then((resp) => {
            expect(resp.status, 'Brand Dashboard login').to.eq(200);
        });
    });
});
```

// file.cy.js
```js
it.('should ', () => {
        cy.loginBrandDashboard('klickly.e2e+development@gmail.com');
        cy.apiGetOrdersList();
    });
```

### Cypress Version

13.1.0

### Node version

16.15/0 

### Operating System

MacOS Ventura 13.0

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by S-Tornqvist**
- Closes #27745 

### Additional details

`cy.request()` now correctly parses nested objects and arrays for the query string (qs), which is the intended behavior. The behavior was lost in 12.0.0 (see #27745). As the qs functionality is shared between `cy.visit()` and `cy.request()`, the behavior of `cy.visit()` also changes. 

Note that the behavior only changes when using nested objects for the query string. Previously these would be parsed as `"[object Object]"`, so no useful behavior is lost.

### Steps to test

Example usage:

```javascript
cy.request({
    url: "http://localhost:3000",
    qs: { foo: { bar: "baz" } }
});
```

### How has the user experience changed?

na

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@S-Tornqvist Does this introduce a breaking change? I'd like tests around the change in visit behavior. Let us know when this is ready for review.

**Comment by S-Tornqvist** [comment]
> @S-Tornqvist Does this introduce a breaking change? I'd like tests around the change in visit behavior. Let us know when this is ready for review.

Hi @jennifer-shehane,

I'm pretty new here so I was gonna finalize the draft and then ask some questions regarding the dependencies, changelog etc. I'm struggling a bit with the semantic pr check, but I'm getting there :) No breaking changes introduced, so I'll set the version to 13.3.1. Thanks for the heads up.

**Comment by S-Tornqvist** [comment]
@jennifer-shehane the pr is now ready for review. Tests for nested querystrings has been added to `cy.request` and `cy.visit`. Only the behavior for nested querystrings should be affected, and as these were previously serialized as `"[object Object]"` no useful behavior should be lost. Previous qs tests proves that non-nested behavior is unchanged

**Comment by S-Tornqvist** [comment]
@jennifer-shehane @AtofStryker @nagash77 could you review the pr?

**Comment by S-Tornqvist** [comment]
Is there anything I can do more or did wrong here? @jennifer-shehane

**Comment by AtofStryker** [comment]
@S-Tornqvist sorry for the delay in response here as I have been out of office for a few months. From a glance, the code looks fine and don't think it should introduce a breaking change as it is just serializing the nested object. I am going to pull from `develop` and get this PR running again!

**Comment by S-Tornqvist** [comment]
> @S-Tornqvist sorry for the delay in response here as I have been out of office for a few months. From a glance, the code looks fine and don't think it should introduce a breaking change as it is just serializing the nested object. I am going to pull from `develop` and get this PR running again!

Thanks! I pulled develop and resolved the changelog conflict

**Comment by AtofStryker** [comment]
@S-Tornqvist looks like there is still a conflict?

**Comment by emilyrohrbough** [comment]
@jennifer-shehane @AtofStryker Changing the query parsing dependency would indeed be a breaking change. It would change the results of the parsed query people are expecting as a response. The `cy.visit()`, `cy.intercept()` and `cy.request()` query logic are not aligned, see: https://github.com/cypress-io/cypress/issues/19407.

**Comment by AtofStryker** [comment]
> @jennifer-shehane @AtofStryker Changing the query parsing dependency would indeed be a breaking change. It would change the results of the parsed query people are expecting as a response. The `cy.visit()`, `cy.intercept()` and `cy.request()` query logic are not aligned, see: #19407.

Yeah this unfortunately seems to be the case 🙁 . I relooked and tracked my [comment](https://github.com/cypress-io/cypress/issues/27745#issuecomment-1734243588) back to https://github.com/cypress-io/cypress/pull/20302 and missed the breaking change label. Sounds like we might need a broader strategy to align parsed queries through `cy.visit()`, `cy.intercept()` and `cy.request()` and verify complex query structures are serialized correctly and release in a major version?

**Pull request closed without merging**
