### PR TITLE
fix: cy.task() can pass undefined as default argument.

### LINKED ISSUE #5913: cy.task passes null as default argument
Seems `cy.task` calls task with `null` value instead of `undefined` if the argument was NOT specified in the spec call

Cypress v3.7.0

Reproduction in https://github.com/cypress-io/cypress-test-tiny/tree/default-arg-in-task https://github.com/cypress-io/cypress-test-tiny/commit/c899a7967a1a0383a3c6ff70fd2fa54e488a28ed

Imaging we have a task and use default value for its argument like

```js
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('task', {
    hello(name = 'world') {
      console.log('hello ', name)

      return null
    }
  })
}
```

When we call `cy.task('hello')` I expect the terminal to print `hello world` but it prints 

```
ET /__cypress/tests?p=cypress/integration/spec.js-609 200 2.326 ms - 619
GET /__cypress/tests?p=cypress/support/index.js-949 200 1.387 ms - -
hello  null
```

## Expected behavior

`cy.task` methods should respect default arguments (we should not be passing `null` values)

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #5913

### User facing changelog

When we pass no argument to `cy.task`, it converted it to `null`, not `undefined`. This PR fixes this bug.

### Additional details

- Why was this change necessary? It's impossible to use default argument.
- What is affected by this change? N/A
- Any implementation details to explain? IPC converts `undefined` to `null`. To prevent this, we now pass an object with a special property when args is `undefined`.

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by sainthkh** [comment]
Flaky failure.

**Review by bahmutov — CHANGES_REQUESTED** [review]
I like this - makes sense. But could you add a test that more explicit about its purpose (right now you are using `undefined` to default parameter, which is fine to leave as is too)

```js
it('returns the default value when no argument is given', () => {
  cy.task('arg:is:undefined').should('eq', 'arg was undefined')
})
// where the task is
'arg:is:undefined' (arg) {
  if (arg === undefined) {
    return 'arg was undefined'
  }
  throw new Error(`Expected arg to be undefined, but it was ${arg}`)
}
```

**Comment by sainthkh** [comment]
Unlucky. Hit 5 flaky tests.

**Review by bahmutov — APPROVED** [review]
nice, thanks for addressing the feedback

**Pull request merged**
