### PR TITLE
feat(breaking): Remove whitespaces from screenshot names to make it terminal friendly

### LINKED ISSUE #23510: saved screenshots and videos names be saved in a terminal friendly way
### What would you like?

that the saved screenshots and videos names be saved in a terminal friendly way so we can cmd+click them to immediately open it

### Why is this needed?

minor annoyance to have to open finder to open the screenshot

### Other

this name is not terminal friendly since it has spaces and its broken with the pixels description.

it should have the name without spaces and the pixels description separate from it
image

### PR DESCRIPTION
**Pull request by artem-s-test**
- Closes https://github.com/cypress-io/cypress/issues/23510

### User facing changelog
The saved screenshots and videos names  saved in a terminal friendly way so we can cmd+click them to immediately open it

### Additional details
Removed whitespaces from the failed test screenshot name

### Steps to test
Run a test that fails and try to cmd+click the screenshot link

### How has the user experience changed?
зображення
зображення

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by nagash77** [comment]
Hello @Art-auto !  Thank you for opening a PR with Cypress.  After some internal discussions about your PR we have a few things we would like you to investigate and potentially change:

1.  Are you sure this wont break VS code and other IDEs?  What about other terminals?  
2. Does this change actually work?  Can you attach a short video or gif of this functionality working?
3.  Is there a “magical” space character we can use rather than dashes or underscores that makes it clickable but remains more readable?

**Comment by artem-s-test** [comment]
> Hello @Art-auto ! Thank you for opening a PR with Cypress. After some internal discussions about your PR we have a few things we would like you to investigate and potentially change:
> 
>     1. Are you sure this wont break VS code and other IDEs?  What about other terminals?
> 
>     2. Does this change actually work?  Can you attach a short video or gif of this functionality working?
> 
>     3. Is there a “magical” space character we can use rather than dashes or underscores that makes it clickable but remains more readable?

Hello @nagash77, thank you for your attention to my PR. I'll try to describe each of your points:
1. The change is only in the file name, it shouldn't brack existing functionality. I tested it in VS code, iTerm and native macOS Terminal.
2. I'll attach gifs with my tests.
3. The only "magical" space I know is "Non-breaking Space": &nbsp;. Unfortunately, it doesn't work in terminal

VS Code: Both screenshot and video redirection works
vs_code
iTerm: Only video redirect works
iTerm
Native macOS terminal: redirection does not work

**Comment by mschile** [comment]
@Art-auto, thanks for the update! We may need to look into this further since it's not working for me in VS Code. We will also want it to work in the native terminal as well. I wonder if we'll need to put the screenshot path on its own line so its not affected by line breaks.

**Comment by lmiller1990** [comment]
Hi all, what are we doing this with PR? I don't think we can merge this outside of a major - changing the name of the generated artifacts could break a lot of automations.

I'll raise this internally and see if we can figure out what's next for this PR.

**Comment by lmiller1990** [comment]
I am having some issues on VS Code + Linux.

https://user-images.githubusercontent.com/19196536/209035137-ebb8acb2-3908-4314-a621-beaf46a14580.mp4

I will try MacOS now.

I had a similar but different problem:


https://user-images.githubusercontent.com/19196536/209035933-b2a0fa49-76c3-49e9-a605-1ff1b0fd03da.mov

This fix will be good, but I think it needs work.

**Comment by nagash77** [comment]
@lmiller1990 can you lay out the changes you would like to see @Art-auto make to this PR?

**Comment by lmiller1990** [comment]
@nagash77 Same as mentioned here https://github.com/cypress-io/cypress/pull/24355#issuecomment-1306313886

Cmd + Click should open the file in the native explorer (finder, explorer, etc). Right now the terminal doesn't realize the file name wraps around when you hold your mouse over it (see videos). This is supposed to be fixed here - the PR description says "Run a test that fails and try to cmd+click the screenshot link". When I tested it, that wasn't working. Either I am missing something, or the PR doesn't fully address the problem.

**Comment by lmiller1990** [comment]
I wonder if https://github.com/cypress-io/cypress/pull/23915/ solves this?

**Comment by AtofStryker** [comment]
@lmiller1990 @Art-auto I think this is solved by #23915 which was released in `12.4.0` yesterday. Should we close this PR?

**Comment by lmiller1990** [comment]
I think so - although this PR did not land, the problem is targets looks solved. @Art-auto can you try the latest Cypress, 12.4.x, that should implement this fix.

**Pull request closed without merging**
