### PR TITLE
Fix for issue 599

### PR DESCRIPTION
**Pull request by austinfox**
Fix for #599 

My company uses some javascript for internally-guarded pages that intercepts XHRHttpRequests and patches them to use OpenID Connect authentication semantics. Cypress runner also attempts to define onreadystatechange for these requests, resulting in the following error being thrown:

```
TypeError: Cannot redefine property: onreadystatechange
    at Function.defineProperty (<anonymous>)
    at [path hidden for privacy]/__cypress/runner/cypress_runner.js:67377:25
    at Array.forEach (<anonymous>)
    at XMLHttpRequest.XHR.open ([path hidden for privacy]/__cypress/runner/cypress_runner.js:67371:15)
    at XMLHttpRequest.onReadyStateFn ([path hidden for privacy]/__cypress/runner/cypress_runner.js:67360:27)
```

I have confirmed this change fixes the bug, Cypress is able to run successfully afterwards.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@austinfox Could you look into writing a test around this?

**Comment by austinfox** [comment]
I'll look into it today, but I'm rather busy at the moment. Do you have a specific place in mind where I should add a test for this?

**Comment by tdaniely** [comment]
Is this going in at some point?

**Comment by austinfox** [comment]
thanks @lilaconlee 👍

**Pull request merged**
