### PR TITLE
Replace deprecated babel-preset-es2015

### PR DESCRIPTION
**Pull request by jennifer-shehane**
Partially adresses #6730

`babel-preset-es2015` is deprecated, replaced by `@babel/preset-env`

```
WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```

Followed instructions at https://babeljs.io/docs/en/env/ for upgrade - `babel-preset-env` was moved to main `@babel/preset-env`

### CODE REVIEW

**Comment by chrisbreiding** [comment]
I wonder if we can just remove this babel dep entirely. @bahmutov, does the `cli` even use `babel`? I can't really see that it does...

**Comment by jennifer-shehane** [comment]
@chrisbreiding looks like the `babel-cli` dep is used here: https://github.com/cypress-io/cypress/blob/develop/cli/scripts/start-build.js#L17:L17 which was initially added in this PR https://github.com/cypress-io/cypress-monorepo-test-runner/pull/484

**Comment by bahmutov** [comment]
We need to transpile the CLI code, otherwise, we could be using some JS construct accidentally that Node v8.0.0 does not support. We could probably replace `babel-cli` with an alternative, but I feel we still need to transpile.

**Comment by bahmutov** [comment]
We need to transpile the CLI code, otherwise, we could be using some JS construct accidentally that Node v8.0.0 does not support. We could probably replace `babel-cli` with an alternative, but I feel we still need to transpile.

**Pull request merged**
