### PR TITLE
chore: merge develop into 13.0.0

### PR DESCRIPTION
**Pull request by emilyrohrbough**
Merge develop into 13.0.0

### CODE REVIEW

**Review by nagash77 — APPROVED** [review]

**Comment by emilyrohrbough** [comment]
The **Semantic Pull Request / Semantic Pull Request (pull_request_target)** check is broken because we bump the version used in develop and it has not yet been updated in the `release/13.0.0` branch.

**Comment by AtofStryker** [comment]
Do we know why the build is failing?

**Comment by emilyrohrbough** [comment]
@AtofStryker I assume snapshots

**Comment by emilyrohrbough** [comment]
Created https://github.com/cypress-io/cypress/compare/v13?expand=1 to compare the v13 changes with these changes merged in to develop. Looks like we should be in a good state.

**Review by AtofStryker — APPROVED** [review]
is there an issue with the semantic pull request job?

**Pull request merged**
