### PR TITLE
fix: bump resource class for tests that require node_modules install

### PR DESCRIPTION
**Pull request by ZachJW34**
### Details
`npm-webpack-preprocessor` and `npm-webpack-dev-server` were flaky on CI. These tests both require a `yarn install` which was causing the agent to run out of memory. This PR bumps the `resource_class` for both of these tests to medium

Before:
https://app.circleci.com/pipelines/github/cypress-io/cypress/27313/workflows/48943cd1-1381-42ef-b5c3-93a50b68f424/jobs/1031151/steps
Screen Shot 2021-11-23 at 4 52 41 PM

After:
https://app.circleci.com/pipelines/github/cypress-io/cypress/27315/workflows/ebc15162-ae83-430f-97d8-add2ac352620/jobs/1031282
Screen Shot 2021-11-23 at 5 22 01 PM

### CODE REVIEW

**Review by marktnoonan — APPROVED** [review]
It'll be really nice to not have to rerun these for this reason 🎉

**Comment by lmiller1990** [comment]
Will leave merging this one to @flotwig

**Comment by flotwig** [comment]
In a perfect world, we wouldn't be doing any `yarn install` outside of the root `node_modules_install`. It's just for the example projects that we need it for these 2 jobs, right? 

If so, I think that when #18574 merges we can go ahead and convert these tests that have dependencies to use `system-tests` instead, and maybe even drop these circle jobs altogether.

**Review by flotwig — APPROVED** [review]

**Comment by ZachJW34** [comment]
@flotwig Though these tests aren't for testing examples, I believe they can still be converted to system tests. They were installing different deps so as to rerun the unit tests against them (for example, Webpack 4 vs Webpack 5), but having two different system tests (one to cover each dep we support) will suffice.

**Pull request merged**
