### PR TITLE
check if parentNode is document-fragment and if yes, stop recursion. …

### LINKED ISSUE #4373: RangeError: Maximum call stack size exceeded error thrown on DocumentFragments
### Current behavior:

Currently i am start using cypress in a Salesforce based web, but when i try to use the Lightning elements that salesforce provides i receive the error for maximum call stack
Just for the record for every element it works fine only in elements like this one:

The element is the following: `label lightning-input_input=""`
 
image

### Desired behavior:

I want that elements such as `lightning-input` can be clickable or you can write on them

### Steps to reproduce: (app code and test code)

.
### Versions

3.3.1

### PR DESCRIPTION
**Pull request by gabbersepp**
…otherwise .parent() will yield no element because a document-fragment has no parent

- Closes  #4373

### User facing changelog

We now more thoroughly ensure the parent of an element exists when recursively calling visibility and existence checks in order to prevent some maximum call stack errors. 

### How has the user experience changed?
- fix `maximum callstack exceeded` error being thrown when testing salesforce lightning components

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
I also confirmed this fixes the bug in https://github.com/jennifer-shehane/sf-lightning-bug

**Comment by Bkucera** [comment]
we have recursive/while fns all around our code that similarly crawls the element's parent nodes. Likely we should abstract this into a utility and replace all those instances

**Comment by gabbersepp** [comment]
> Hey @gabbersepp, this is awesome! We would love to have an internal test to cover this behavior (that isn't as big as the example repo we were previously using to reproduce).
> 
> Probably adding another test case for the visibility spec would be best: https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/dom/visibility_spec.js#L821
> 
> Let us know if you need any help!

Hi,
thanks! As stated in the issue, I tried several combinations of custom elements and shadow doms in order to create a situation like in your example repository. Unfortunatelly I found no possibility to create a documentFragment that stays in the DOM after appending it. 
Maybe it is related to custom elements/shadow-dom and this stuff.

Am I able to create a useful test without having the possibility to create this situation?

@Bkucera I will have a look at that

**Comment by gabbersepp** [comment]
Let's give it a try: https://stackoverflow.com/questions/58633517/create-document-fragment-that-stays-in-dom

**Comment by gabbersepp** [comment]
> we have recursive/while fns all around our code that similarly crawls the element's parent nodes. Likely we should abstract this into a utility and replace all those instances

Hey @Bkucera can you give me a hint were I can place such a shared logic? I did not found any common utils class that can be used in all packages

**Comment by Bkucera** [comment]
@gabbersepp 
https://github.com/cypress-io/cypress/blob/issue-1096-firefox-support/packages/driver/src/dom/elements.ts#L535
https://github.com/cypress-io/cypress/blob/issue-1096-firefox-support/packages/driver/src/dom/elements.ts#L545
https://github.com/cypress-io/cypress/blob/issue-1096-firefox-support/packages/driver/src/dom/elements.ts#L831
https://github.com/cypress-io/cypress/blob/issue-1096-firefox-support/packages/driver/src/dom/elements.ts#L856
https://github.com/cypress-io/cypress/blob/issue-1096-firefox-support/packages/driver/src/dom/elements.ts#L896

these stand out to me, but they might not all need changing

**Comment by jennifer-shehane** [comment]
From what I can gather in the comments, this will address this one instance and is good to merge in as is. @gabbersepp Can you confirm by removing the WIP and opening a new issue to address the other recursive issues? Would like to get this in. Thanks.

**Comment by gabbersepp** [comment]
@jennifer-shehane Sorry for the delay. I found no time to refactor all places. But you are right. This PR do not require a full refactoring to fix the original issue.
I opened a new issue here: https://github.com/cypress-io/cypress/issues/6002

I have not written any test because I don't know how I can create a real HTML example that produces this situation. I tried several things like shadow dom, webcomponents, ... without success. 

So maybe this function can be unit tested?

**Comment by jennifer-shehane** [comment]
@gabbersepp Yeah, basically this was the exact situation I ran into - where I could not create a simple small example outside of the lightning components. Ideally we want to have a single test so that we always have this situation covered in the future and make sure we don't introduce regressions.

**Comment by JasonFairchild** [comment]
Is the fix for this going to allow a document-fragment to work better with Cypress, or is it more like catch the problem and return a better error for what is actually going on? I imagine the latter, as the title simply says to stop the recursion, but I wanted to double check.

I'm particularly keen on this as I've just recently started getting the "RangeError: Maximum call stack size exceeded" error as I am trying to interact with a document-fragment from a lightning web component. I would like to see if this merge might help. What kind of time frame is it usually for this to become generally available with cypress? I know it is probably special with holidays...

Here is some other documentation on this for context if it helps: 
https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.testing_dom_api
https://lwc.dev/guide/composition#shadow-dom

**Comment by DesignByOnyx** [comment]
I have created a simple reproducible example of a document fragment in the dom. It happens with shadow structures - the shadowRoot element is a document fragment:

https://jsfiddle.net/Lgfa9273/

I know Cypress is working on support shadow elements, so fixing this might actually be part of that larger more holistic task. In reality, the document fragment actually has a parent in the form of a "host", and the crawler should be aware of this.

**Comment by JasonFairchild** [comment]
@gabbersepp or @jennifer-shehane it looks like all the checks passed for this. I was just wondering what more needs to be done for this? Sorry, I imagine there are answers in the contributor guidelines, but there is a lot to read there. Maybe there is a way I could contribute to moving it along, I would be open to learning about that.

**Comment by JasonFairchild** [comment]
I just got around to looking into this a bit more. Was just trying to fork the develop branch and apply @gabbersepp fixes to there. But it appears that the visibility.js file has changed a lot recently. Maybe for native events support? So are the changes you had for that file even necessary any longer?

**Comment by RandallKent** [comment]
@JasonFairchild - I just merged `develop` into `issue-4373. To my knowledge, the issue this PR addresses is still present in the latest release of Cypress.

**Comment by BradenM** [comment]
@RandallKent @JasonFairchild, 

Can confirm. Currently running `cypress 4.0.2` with all related plugins updated and am seemingly randomly having CI builds fail on to me due to this bug.

* See [Run Cypress Git action step](https://github.com/CrisisCleanup/crisiscleanup-3-web/pull/160/checks?check_run_id=448454731).
* See [package.json](https://github.com/CrisisCleanup/crisiscleanup-3-web/blob/master/package.json).
* See the cut-down (only the meaningful stuff) logs [here](https://github.com/cypress-io/cypress/files/4209324/7_run_cypress_no_webpack.txt)

Essentially hits [this spec](https://github.com/CrisisCleanup/crisiscleanup-3-web/blob/3e78943555efb771ec67e127e68048abd5d2d8a6/cypress/integration/authenticated_spec.js#L8) first and immediately raises this error:
```
2020-02-16T03:18:02.8153966Z Authenticated Layout
2020-02-16T03:18:03.7048403Z RangeError: Maximum call stack size exceeded
2020-02-16T03:18:03.7048803Z     at get (internal/bootstrap/pre_execution.js:286:8)
2020-02-16T03:18:03.7049753Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:44:3)
2020-02-16T03:18:03.7050336Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
2020-02-16T03:18:03.7050899Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)

             <-- hasBinary error continues to repeat for hundreds of lines -->

2020-02-16T03:18:04.1677190Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
2020-02-16T03:18:04.1677700Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress/resources/app/packages/socket/node_modules/has-binary2/index.js:58:59)
2020-02-16T03:18:04.1678248Z     at hasBinary (/home/runner/.cache/Cypress/4.0.2/Cypress percy [39m] stopping percy...
2020-02-16T03:18:04.1678694Z [[35mpercy[39m] waiting for 0 snapshots to complete...
2020-02-16T03:18:04.1679070Z [[35mpercy[39m] done.
2020-02-16T03:18:04.1679768Z [[35mpercy[39m] finalized build #17: [34mhttps://percy.io/Crisis-Cleanup/crisiscleanup-3-web/builds/4175160[39m
2020-02-16T03:18:14.0064823Z Error: The process '/usr/local/bin/npx' failed with exit code 1
2020-02-16T03:18:14.0067190Z     at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1.21.0/dist/index.js:894:25)
2020-02-16T03:18:14.0074960Z     at Timeout.HandleTimeout (/home/runner/work/_actions/cypress-io/github-action/v1.21.0/dist/index.js:917:15)
2020-02-16T03:18:14.0075340Z     at listOnTimeout (internal/timers.js:533:17)
2020-02-16T03:18:14.0075586Z     at processTimers (internal/timers.js:475:7)
2020-02-16T03:18:14.0076942Z ##[error]The process '/usr/local/bin/npx' failed with exit code 1
2020-02-16T03:18:14.0123488Z ##[error]Node run failed with exit code 1
```

The really strange thing is... sometimes it works fine. Passes without a problem and uploads to percy. I'd say it tends to fail more often then do this, but it's still very strange.

Hope we can figure this one out!

**Comment by jennifer-shehane** [comment]
So I've added a test for this, albeit not a great one. I got the lightning web components to the smallest pieces I could and just threw the whole thing into an HTML file to test against. 

I actually think that we can just simplify this to check if `$el[0]` is `undefined` - which I have done. The nodeType check didn't always work in every lightning component I made - because sometimes the `$el[0]` was undefined. It seems to fix the test case I added to the tests (where I kind of messed up the components rendering tbh) and also the previous test case from my repo.

I have no idea why these components have an undefined `$el[0]` except to say that Salesforce does very very weird things in their component code.

**Comment by JasonFairchild** [comment]
@jennifer-shehane Thanks a lot for following through on this! No arguing from me, I agree SF does unique stuff with lightning web components. Is part of what you mean that these $el[0] are specifically not document-fragments, or are you not sure? Anyway, I never figured out exactly how they used document-fragments to contain things that apparently are attached to the DOM whenever needed. I think it could be safe to at least conclude that whatever the weird thing they did, it was probably to support their polyfilled shadow-like DOM, so they can both support many browsers and conform to Web component principles in the way they see fit.

**Comment by JasonFairchild** [comment]
> In reality, the document fragment actually has a parent in the form of a "host", and the crawler should be aware of this. So the real fix (IMO) has more to do with cypress being aware of shadow structures than to simply stop crawling at a document fragment. Applying the fix in this PR might cause a false sense of security and actually fail to detect things such as sticky positioned elements, detached elements, visibility, et al.

I keep wondering if there is something about what @DesignByOnyx said here as well, for a more complete approach/perspective. It sounded like he was onto something closer to the root anyway.

**Comment by jennifer-shehane** [comment]
Yes, it likely is some combination of shadow root and document fragment. Either way, this is an improvement and the rest of our tests pass in this situation. Not to say this is a complete fix for any DOM structure using shadow dom or document fragments.

**Comment by JasonFairchild** [comment]
Just thought I would add here that I have confirmed that this fix is working for me on my sites that use Salesforce LWCs. Still need to figure out some things salesforce is doing to actually select elements to interact with, but at least I get as f can get to a point where I know it is their Locker service or polyfilled shadow like DOM structure that is the problem. We tried to turn off their locker service entirely, as they have just recently added the capability, but that is not working, changes very minimal aspects, or has bugs on their end. Not sure if I'll ever really figure it out as well, as my current position is soon ending here.

**Comment by JasonFairchild** [comment]
I thought I would post this kind of summary as to where I ended up with testing salesforce Lightning web components (LWCs) with cypress. The last result I would get, after this fix was introduced, when I would try to select an element inside a lightning web component, Cypress would tell me that the element was detached from the DOM. This was true whether I tried to select the element the 'salesforce' suggested way with their .shadowRoot method called on the component as described here (primarily in the note at the bottom): https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.testing_dom_api 
Or whether I reclaimed the querySelector methods (as described in #6058 ) and instead tried to select the element more traditionally/directly. IE cy.get('element-selector-only)

So one final idea that might be helpful for someone in the future, for salesforce LWCs: A colleague of mine theorized that the their locker service is returning some type of copy of the element, not the actual node that exists in the DOM. That could explain why it is detached from the DOM according to cypress, and be a hint as to how they use this document-fragment structure. The problem with this idea though, it makes it sound like it is impossible to get a handle on any lightning element, to actually be able to use it in any type of end to end test in any framework. But according to the SF documentation, they imply e2e tests should at least be possible... as per the document I already linked and this one https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.create_dom

So maybe it is possible, somehow, but if so, I think SF has really got to make that more clear. Their suggestion as of now is basically: We recommend jest tests, but if you must use e2e tests, have whoever maintains your testing framework fix these issues for you. Which is not a very helpful or feasible suggestion for most. (this screenshot comes from the bottom of the 2nd link in this post)
image

This is also why we tried to turn the locker service off entirely for testing purposes (see link in post before this). That didn't accomplish anything close to enough or just didn't do what we thought it would. So if SF makes that option work like we thought it would, that might be all it takes to allow selecting LWC elements for cypress in the future.

P.S. If you come find this without much context, please realize that the polyfilled shadow-like DOM that salesforce uses for LWCs is really different from native shadow DOM. SF does say this, but I don't think they make it clear/explicit enough. Principles may be much the same, but the implementation is very different. So if you read about the many articles that are out there that deal with native shadow DOM for selenium and cypress (#144) understand that SF shadow DOM is a whole different ball game, and what you read there may not help you at all with SF's implementation.

**Comment by jennifer-shehane** [comment]
@JasonFairchild Yes, they're doing very unconventional things aside from just Shadow DOM. Some of which is explained here: https://github.com/cypress-io/cypress/pull/6787#issuecomment-602453835

**Pull request merged**
