### PR TITLE
WIP: Remove 'Timed out retying' for timeout errs

### PR DESCRIPTION
**Pull request by jennifer-shehane**
addresses #887

### CODE REVIEW

**Comment by brian-mann** [comment]
I really feel like this doesn't actually help with much. After our internal discussion we decided that it made sense to remove this one line, but that we should further explain the retrying effect **underneath** the error.

**Comment by brian-mann** [comment]
Maybe we could add something like: It retried for XXXXms and failed.

**Comment by jennifer-shehane** [comment]
I would definitely be up for adding this text at the end of the error as opposed to reverting back to how it is now. I can revisit adding this to the bottom, but I'd have to investigate if this `xxxxms` data is readily available to add to the error. 

What about adding the 'for xxxxms' at the end of the error, I'd have to look at each situation to see if this verbiage works. Like:

> CypressError: Expected to find element: '.text-input', but never found it. queried from element: #my-form for 4000ms

**Comment by brian-mann** [comment]
Another thing we talked about was not displaying `CypressError`. That will take a bit more logic, but is definitely do-able.

**Comment by jennifer-shehane** [comment]
Yes, we should probably split that into a separate issue. This issue is also related to the 'CypressError' wording: https://github.com/cypress-io/cypress/issues/825

**Comment by jennifer-shehane** [comment]
Closing. Was not approved. Hopefully these doc improvements help cypress-io/cypress-documentation#1314

**Pull request closed without merging**
