### PR TITLE
feat: Support for arm64

### PR DESCRIPTION
**Pull request by guilhermestorck**
Closes https://github.com/cypress-io/cypress-docker-images/issues/431

### User facing changelog
Supports for arm64 architecture

### Additional details
- Electron version upgraded to one that supports arm64

### How has the user experience changed?
- no changes on the user experience

### CODE REVIEW

**Comment by flotwig** [comment]
@guilhermestorck this PR will not cause Cypress to build for linux-arm64, it requires more updates than this. Basically anywhere `linux-x64` is mentioned, `linux-arm64` needs to be added, and then a build step in Arm CircleCI needs to be added. We don't yet have access to the Arm CircleCI.

**Review by lodenrogue — APPROVED** [review]

**Comment by shwetasingh-hunter** [comment]
Can i get some help.I am also running into same issue.
i tried the whole set up mentioned in the page below
https://cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/
docker run --platform linux/amd64/v8 -it -v $PWD:/e2e -w /e2e --entrypoint=cypress cypress/included:6.2.0
Usage: cypress <command> [options]

Options:
  -v, --version      prints Cypress version
  -h, --help         display help for command

Commands:
  help               Shows CLI help and exits
  version            prints Cypress version
  run [options]      Runs Cypress tests from the CLI without the GUI
  open [options]     Opens Cypress in the interactive GUI.
  install [options]  Installs the Cypress executable matching this package's version
  verify [options]   Verifies that Cypress is installed correctly and executable
  cache [options]    Manages the Cypress binary cache
  info [options]     Prints Cypress and system information
shwetakumari@Shwetas-MacBook-Air oilex-wa-qa-automation % docker ps -a
CONTAINER ID   IMAGE                    COMMAND         CREATED              STATUS                          PORTS     NAMES
db0a748079fb   cypress/included:6.2.0   "cypress"       15 seconds ago       Exited (0) 13 seconds ago                 exciting_proskuriakova
329e10073196   cypress/included:6.2.0   "cypress"       About a minute ago   Exited (0) About a minute ago             busy_hellman

**Comment by jcpeden** [comment]
Exact same issue for me. @jennifer-shehane, happy to fix but not sure what is required.

**Comment by oscrx** [comment]
@flotwig A circleci arm build agent shouldn't be required. [Docker Buildx](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images) could be used.
Like [this](https://github.com/oscrx/caddy/blob/main/.github/workflows/docker.yml) for example.
It'll be some work to fit it in the [build pipeline](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml), but it can be done.

**Comment by binarykitchen** [comment]
Has this been really merged? Still cannot install on latest Apple M1 ARM Architecture!

**Comment by mayteio** [comment]
@binarykitchen no it was closed without merging. Still needed!

**Comment by binarykitchen** [comment]
Yes. Then let's do something about it now!

**Pull request closed without merging**
