### PR TITLE
feat: Add support for Chrome Beta

### LINKED ISSUE #16376: Add support for Chrome Beta
As a corollary to #3096, in order to test Cypress itself in Chrome Beta, Cypress needs to support detecting and running tests in Chrome Beta. This will enable all users to test with Chrome Beta.

### PR DESCRIPTION
**Pull request by chrisbreiding**
- Closes #16376

### User facing changelog

- Cypress now detects and supports testing in [Chrome Beta](https://www.google.com/chrome/beta/)

### How has the user experience changed?

We now detect and display Chrome Beta as an option.

Screen Shot 2021-05-14 at 9 35 26 AM

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/3927
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Works on Mac. 

Does not work on Windows. Chrome Beta should detect on Windows for this feature.

Looks like on my machine the location is at '/c/Program files/Google/Chrome Beta/Application/chrome.exe'

Screen Shot 2021-05-14 at 10 50 07 AM


I think we may need a new image for docs, pasted one below since I have all the shiny browsers.

Screen Shot 2021-05-14 at 11 05 05 AM

**Comment by chrisbreiding** [comment]
Should be properly detected on Windows now. Would you mind verifying that please, @jennifer-shehane?

**Review by flotwig — APPROVED** [review]
Works on Linux :+1: and LGTM once Jennifer can re-check on Windows
image

**Review by jennifer-shehane — APPROVED** [review]
Yeah, it works on Windows. Checked all the other browsers too and they all seem good on Windows.

Screen Shot 2021-05-14 at 2 28 27 PM

**Pull request merged**
