### PR TITLE
Screenshot fixes/enhancements

### LINKED ISSUE #1766: If more than 1 screenshot is taken per test, screenshot names stay same and overwrite previous
### Current behavior: 
With code below, I am expecting 2 screenshots to be taken. 
1. The screenshot from `.screenshot()` command
2. The screenshot on failure from my `.contains()` failing to find the content.

```js
it('cy.screenshot() - take a screenshot', () => {
  cy.get('.misc-table')
    .screenshot()
  cy.contains('Cheryl') // failure here
})
```

In the process output, you can see the 2 screenshots have the same name:

```bash
  (Screenshots)

  - /.../cypress/screenshots/Misc -- cyscreenshot - take a screenshot.png (672x300)
  - /.../cypress/screenshots/Misc -- cyscreenshot - take a screenshot.png (2560x1440)
```

This behavior strangely works in regards to displaying in the Dashboard - both screenshots still appear. But, in my local `cypress/screenshots` folder, it causes the first screenshot to be overridden by the second, leaving me with 1 final screenshot. 

screen shot 2018-05-24 at 1 53 20 pm

### Desired behavior

I should have uniquely named screenshots regardless of whether they were captured in the same test. 

### Versions  

Ran in Cypress `develop` - future 3.0.0 release

### LINKED ISSUE #1771: Update cy.screenshot() to accept directory location + filename
### Current behavior: 

The code below saves the screenshot as the name `foobarbazquux.png` within the `screenshotsFolder`

```js
cy.screenshot('foo/bar/baz/quux')
```

### Desired behavior:

The above code should create the necessary directories in order for the screenshot to be saved at `foo/bar/baz/quux.png` within the `screenshotsFolder`.

### LINKED ISSUE #1826: Proposal: Nest screenshot path based on spec path by default
Instead of saving screenshots all directly in the screenshots directory, nest them based on where the spec file is relative to the integration directory. So if running 

`cypress/integration/app/login/user_spec.js`

a screenshot will be saved as 

`cypress/screenshots/app/login/user_spec.js -- login -- users -- can log in.png`.

### LINKED ISSUE #1881: Pare down the typescript kitchensink tests, add tscheck to circle.yml for kitchensink
This file: https://github.com/cypress-io/cypress/blob/develop/cli/types/tests/kitchen-sink.ts

This is confusing since its written in the perspective of the kitchensink but it now deviates from it. Rather than have some mirror and diverge and be inaccurate let's instead pare it down it a single `describe` + `it` and just test all the things once that you intend to cover with typescript. It'll be less intimidating and also make a lot more sense.

I would also explain this in the contributing guide somewhere about adding tests here if the types have changed.

Lastly please add `tscheck` to the actual kitchensink during the test example projects build process.

### LINKED ISSUE #1919: Add Cypress.browser to the driver
We should yield you the spec because it may be useful in the driver.

```bash
cypress run --browser chrome
```

```js
const browser = Cypress.browser

// return
{
  name: 'chrome',
  displayName: 'Chrome',
  version: '67.123.456.90',
  majorVersion: '67',
  path: '/path/to/browser'
}
```

### LINKED ISSUE #1923: Failure screenshots should append `(failed)` to the screenshot name
```js
// cypress/integration/app/users/list.spec.js

describe('table', () => {
  it('paginates users', () => {
    throw new Error('fail whale')
  })
})

// outputs screenshot to:
// cypress/screenshots/app/users/list.spec.js/table -- paginates users (failed).png

```

### PR DESCRIPTION
**Pull request by chrisbreiding**
Fixes #1766 

If multiple non-named screenshots are taken in a single test, after the first one they're appended with a number, i.e. `test name (1).png`.

Fixes #1771 

Passing `foo/bar/baz` as the name of spec `app.spec.js` will result in the screenshot being saved to `screenshots/app.spec.js/foo/bar/baz.png`.

Fixes #1826 

By default, screenshots will be saved in a directory structure matching the spec's path. `cypress/integration/foo/bar/baz_spec.js` will save a screenshot as `screenshots/foo/bar/baz_spec.js/test name.png`.

Fixes #1923

We now append `-- failed` to screenshots taken automatically during failure

Also fixes #1919 and #1918 

Documentation PR: https://github.com/cypress-io/cypress-documentation/pull/675

closes #1881

### CODE REVIEW

**Comment by chrisbreiding** [comment]
Some of the changes regarding the spec path is refactoring, so not everything in the diff is necessarily related to the screenshot path. 

We were already parsing the spec path out of the URL. It's more-or-less the source of truth for the currently selected spec. 

AFAIK, the [only place we hold onto the currently running spec](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/socket.coffee#L71) in the server is in `lib/socket` and it's pretty much constrained to one function. I figured holding on to that state in the driver was a safer and potentially easier bet than adding more state to the server. 

That said, I'm open to a better solution if there is one.

**Comment by brian-mann** [comment]
@chrisbreiding right. So it's currently architected that way, but with the new 3.0 spec isolation changes it should be trivial to bootstrap the spec into the driver.

That would get rid of parsing the URL entirely (you'd just get it from this state) and we could expose a property on Cypress: `Cypress.spec` that points to this as well.

I get that in interactive mode it's a bit trickier holding onto the open spec than say run mode, but it'll likely be cleaner keeping all the state in a single place. I can take it from here - just wanted to make sure I wasn't missing something.

**Comment by jennifer-shehane** [comment]
This will require some updates to the documentation. I opened an issue here: https://github.com/cypress-io/cypress-documentation/issues/671

**Comment by brian-mann** [comment]
Also fixes #1919 and #1918

**Comment by brian-mann** [comment]
@bahmutov need your made typescript skillz for #1919 and #1918 

Gonna release tomorrow

**Comment by bahmutov** [comment]
@brian-mann I have added types for `Cypress.spec` and `Cypress.browser` using the test from b68c5498602cb86d4c4c41f277b28a7f8580b6f6 

also trimmed duplicate kitchensink code

**Comment by brian-mann** [comment]
I'm making a few changes here:

- a failure screenshot will be called `failed` as opposed to `failure`.
- instead of a named screenshot being placed at the root `screenshotsFolder` it is nested based on `specName`
- named screenshots will also have duplicate numbers `(1)` appended to them
- i moved the state out of the driver / runner and kept it entirely in the server minus `takenPaths`
- i'm not sanitizing the folder names as much, I'm leaving in dots `.` since after doing some research it should not matter and i'd rather keep it closer to what the spec was called

**Pull request merged**
