### PR TITLE
feat(issue-3741): added keyboard support for folder

### LINKED ISSUE #3741: Add keyboard support for folders inside desktop GUI
### Current behavior:
Currently, folders are omitted during keyboard navigation in the desktop GUI because `onClick` event for folders are attached to a non-interactive element (`div`).

### Desired behavior:

It should be possible to interact with folders (collapsing/expanding) with a keyboard.

### Steps to reproduce: (app code and test code)

See the gif below. Folders don't participate in keyboard navigation.

Mar-18-2019 21-43-16

### PR DESCRIPTION
**Pull request by Manuel-Suarez-Abascal**
- Closes #3741

### User facing changelog
This PR closes issue #3741. Now we'll support navigation for folders in the Desktop GUI.

### Additional details
Users will be able to navigate through the folders in the Desktop GUI using the `Tab` keyboard input, plus they will be able to close/open the folder's content with `Enter` & `Space` keyboard input.

### How has the user experience changed?

https://user-images.githubusercontent.com/32891808/111035140-046f0200-83e7-11eb-9055-90d779521d2c.mov

### PR Tasks
- [X] Can the user navigate through folders with keyboard inputs?

### CODE REVIEW

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane It seems the build is fixed now.

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane I'm sure you guys are insanely busy with all the changes in Cypress 7. However, I would like to make a friendly reminder to any member of the team to review this PR 🙂  🙏

**Comment by Manuel-Suarez-Abascal** [comment]
Hi @CypressJosh, out of curiosity... what's the label `internal-priority` stands for? 🙂

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@Manuel-Suarez-Abascal When the label is added, it adds the issue to our internal Jira board. 

Sorry for the delay in reviewing. We'll need some tests written to verify this new behavior. Did you try to test this behavior in Cypress in our Desktop-GUI tests?

---

There is a Contributing guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

To run the tests:

- within `cypress` root, run `yarn`
- cd to `cypress/packages/desktop-gui` and run `yarn watch`
- In `cypress/packages/desktop-gui` run `yarn cypress:run`
- click on the test you're writing to run it within Cypress

Instructions for running the `desktop-gui` tests can always be found here: https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/README.md

**Comment by Manuel-Suarez-Abascal** [comment]
> We'll need some tests written to verify this new behavior. Did you try to test this behavior in Cypress in our Desktop-GUI tests?

@jennifer-shehane thanks for your review. I have added some assertions for all new user event inputs (`click`, `spacebar` & `enter`). I have also added a screenshot showing the test suites are passing successfully. Let me know if there is anything else that needs to be addressed. 😃

**Review by jennifer-shehane — APPROVED** [review]
Just updated the outline style so that it only shows on keyboard highlight instead of on click (which looked out of place of other styles). 

Also updated the test to remove test for clicking since we have other tests covering that.

Thanks for the feature!

**Pull request merged**
