### PR TITLE
feat: filter by test status in Test Runner

### LINKED ISSUE #6261: Feature request: quickly isolating the failing tests
### Current behaviour:

When running multiple (and long E2E tests), it's hard to quickly find which ones are failing in the list.

Actual behaviour

### Desired behavior:

Having a quick way to jump on the failing tests without losing time scrolling. Filtering by test suite state could be an option.

### PR DESCRIPTION
**Pull request by Manuel-Suarez-Abascal**
- Closes #6261

### User facing changelog
Added feature to filter out passing & skipped test results, only showing failed test results on the test runner.

### Additional details
Users wanted to have the possibility of quickly verifying only failed test results. Now, users will be able to filter out `passed` & `skipped` test results to just focus on fixing/checking the failed test results.

### How has the user experience changed?

**Filtering available failed test results:**

https://user-images.githubusercontent.com/32891808/122133062-08f1ef00-ce0a-11eb-9a2b-de57292a1862.mov

**Filtering no available test results:**

https://user-images.githubusercontent.com/32891808/122133125-21faa000-ce0a-11eb-8171-779b305839ba.mov

**Notes:** 

All these note descriptions can be seen in the video recording.

1 - The functionality is disabled by default unless at least one of these two conditions are met:

- [X] there're is a failing test available,
- [X] the run is over.

2 - I have added the same styling as the `pinned` assertions in the test runner to the filtering button.

3 - I have added a tooltip, which is disabled by default until one of the two conditions on note number 1 is met.

### PR Tasks

- [X] Have tests been added/updated?
- [X] Users can filter tests by failed tests only

### Possible improvements 

@jennifer-shehane

- I just added a simple test for checking the button to filter tests are disabled by default. I'm not sure how to proceed to add the rest of the assertions since it'll be required to wait for the test run to finish & a failing `it()` block at least. Can I get a suggestion on this?

- When there are no failing tests the test runner looks empty & it might confuse the users? Should I add a message saying that no failing tests were found? Can you provide me with a mock design to recreate it? Otherwise, we can keep it outside of the ticket's scope if you think it's not important at the moment. I could also try disabling the functionality if not failed tests are found. 🤷

### CODE REVIEW

**Comment by bahmutov** [comment]
Ohhh good idea!

**Comment by jennifer-shehane** [comment]
@Manuel-Suarez-Abascal Thanks for opening a PR. We had someone open a PR for this in the past and it died because we couldn't get clear consensus on the design. I wanted to bring your attention to the previous review and the questions it raised so you can consider if it's covering these cases: https://github.com/cypress-io/cypress/pull/6239#pullrequestreview-350677708

**Comment by Manuel-Suarez-Abascal** [comment]
> @Manuel-Suarez-Abascal Thanks for opening a PR. We had someone open a PR for this in the past and it died because we couldn't get a clear consensus on the design. I wanted to bring your attention to the previous review and the questions it raised so you can consider if it's covering these cases: [#6239 (review)](https://github.com/cypress-io/cypress/pull/6239#pullrequestreview-350677708)

I see, I haven't noticed it. To answer the questions:

> Is this a single filter or multi-filter?

It's a single filter. Users will able to filter only `failing tests`. This feature could be expanded if necessary. However, I don't think it's useful to filter the passing tests. [The original issue was asking for failing tests](https://github.com/cypress-io/cypress/issues/6261#issue-556119955).

> What happens when tests rerun (clicking 'rerun' button or being triggered by testfile changes)

It will clear the filter & show all tests.

> The filter should look more like a clickable button

I agree. I took the liberty to add the same styles as when a `user` pinned an `assertion` as shown in the video below. If you provide me with a mock design, I could recreate it if needed.

https://user-images.githubusercontent.com/32891808/122299670-4b7c0000-cecc-11eb-9fda-6831c9abe806.mov

> We're worried that users may get 'stuck', like...where are all my tests if the filter is not obvious enough that it is on. Maybe there should be a message underneath the filter telling them there is a filter in place with an x to remove.

I agree that's why I added the pinned styles to the filter. If this is not sufficient, I have two other suggestions:

- disabled the filter(button won't be clickable) if no failing spec files are found.
- Add a toast in the test runner, stating: "No failing tests were found during the run" or any other message, the team agrees upon. What do you think?

> What happens if you filter it while the run is currently running? Likely the button should be disabled if running.

As explained in the PR template, the button is disabled by default. It'll only work when either of these two conditions are met:

- there is at least a failing test available.
- the run is over.

We could change it to both conditions are met instead. Depending on what we decided on the previous point.

> What happens if you’ve ‘paused’ the runner (similarly should probably disabled filter).

Yes, it's already disabled. Again, the run is not over so the condition is not met & the filter is disabled.


https://user-images.githubusercontent.com/32891808/122300948-05c03700-cece-11eb-98c5-6b0782f85996.mov

@jennifer-shehane let me know if, I answered all your questions & which changes do you want to add to this PR. Thanks!

**Comment by elevatebart** [comment]
@lmiller1990 this feature looks like it will be filtering tests like [your focus idea](https://github.com/cypress-io/cypress/issues/16599).

Can you check that the 2 features will not collide when merged?

**Comment by elevatebart** [comment]
@Manuel-Suarez-Abascal it feels odd that one status would be clickable and not the other.
We might also want to focus on the test we are working on or on a suite of tests.

I like your idea of re-using the real estate we have.
In this case, all the interactive icons appear on the right hand side, I would find more logical that a clickable filter be there, maybe in a dropdown.

This being said, if your design and implementation does not conflict with @lmiller1990 I really like this improvement and we can move the interactivity somewhere later.

I am off today, but I will review it on Monday.

**Comment by lmiller1990** [comment]
@elevatebart I think this feature is quite different to the exclusive tests. This is purely a UI improvement - we still execute all the specs here, the goal of this PR is just to make it easier to identify failures in a large run.

@Manuel-Suarez-Abascal Regarding the design, what's the reasoning behind waiting for the entire run to be over before we allow filtering? If the idea is to help you find out what's failing as soon as possible, shouldn't we allow filtering before all the specs have executed?

As for the implementation, I think we need to let the state drive the UI, instead of manually updating the UI. I think we can do this is a more React, data driven manner way. Rather than determine the pass/fail state based on CSS selectors, what we could do is use the data in the store. We define a `[test-model`](https://github.com/cypress-io/cypress/blob/d0b809cab071931c03d334ec5d3591c1f65babcc/packages/reporter/src/test/test-model.ts#L35). A test is basically everything associated with a given `it` block. The state can be:

```ts
export type TestState = 'active' | 'failed' | 'pending' | 'passed' | 'processing'
```

This is where things get a bit confusing. We have the concept of a `Runnable`, which can be a `Suite` or a `Test`. Something that Cypress can execute.  Just to clarify, `describe` would be a `Suite`, and `it` represents a `Test`. Suites are just logical groups. Tests fail. A suite is considered failed when at least one of the contained tests fails.

What I think we need to do for this feature is determine if a suite has any failing tests, and if it does, not render the `<Runnable>`.

That logic is [here](https://github.com/cypress-io/cypress/blob/d0b809cab071931c03d334ec5d3591c1f65babcc/packages/reporter/src/runnables/runnable-and-suite.tsx#L55). We'd need to return early, and not render the `<Runnable>` if there is a failed test *and* we are using the filter feature.

**Comment by Manuel-Suarez-Abascal** [comment]
@elevatebart @lmiller1990 thanks for your review. If I understood well your comments, we'll do the following:

- We want to expand the filter to include `passing`, `failing` & `skipped` tests? Should I include `pending` 🤔 ? In that case, we'll need to have to clear the applied filters? I think I'll need to be provided with a mock design for these changes?

To answer your questions:

> what's the reasoning behind waiting for the entire run to be over before we allow filtering? 

I felt it was weird to allow filtering without waiting for a run to be over. In retrospect, I agree with your point. I'll allow filter before the run is over.

> shouldn't we allow filtering before all the specs have executed?

It's already like so. You're allowed to filter test if two conditions are met:

1 - there's a failing test
2 - the run is over. 

I'll be removing condition number 2 as discussed previously.

 > This is where things get a bit confusing. We have the concept of a Runnable, which can be a Suite or a Test. Something that Cypress can execute. Just to clarify, describe would be a Suite, and it represents a Test. Suites are just logical groups. Tests fail. A suite is considered failed when at least one of the contained tests fails.

What I think we need to do for this feature is determine if a suite has any failing tests, and if it does, not render the <Runnable>.

I'm not sure if I understand this idea 100%, but I disagree we filter out the `Runnable` in his entirety. As you mentioned, a `Runnable` could be a `describe` block. A `describe` block could have `context` & `it` blocks, I think we should filter at the `it` block level and not the entire `Runnable`. Is that what you meant? Maybe I understood wrong.

**Comment by jennifer-shehane** [comment]
It's great seeing all the feedback on this feature. 

@Manuel-Suarez-Abascal I would hold off on making any more UI changes. We're going to try to see if we can get some more consensus on how this design should be from our design team. I'll make sure to update the thread with any updates.

**Comment by jennifer-shehane** [comment]
@Manuel-Suarez-Abascal I spoke with @ryanjwilke. We appreciate the effort spent for getting the filters to work. While this is something that is relatively simple to implement code-wise, the UX impact is rather large. We'll be putting in some time soon to dedicate on the design for the reporter's header that can accommodate the new functionality of filtering as well as the other purposes it serves today. 

We'll be closing this PR until we can dedicate the time on those design initiatives. Thanks again.

**Pull request closed without merging**
