### PR TITLE
allow file:// base urls

### PR DESCRIPTION
**Pull request by quentinus95**
Allow file:///urls in Cypress, I need to do e2e testing on a final static compiled files with no intermediate server.

### CODE REVIEW

**Comment by quentinus95** [comment]
@jennifer-shehane please tell me if there is anything more I can do to get this merged.

**Comment by jennifer-shehane** [comment]
@quentinus95 	We would definitely need tests to ensure this is working. Also, what is your use case for wanting this feature exactly?

**Comment by quentinus95** [comment]
I have some webapps which are not deployed on a webserver, they are only used locally using the file:// protocol.

This pull request allows to start with http, https or file protocol.

Currently I have to run a local server to run my tests, but I actually do not need it.

I'll add a test.

**Comment by quentinus95** [comment]
@jennifer-shehane can you tell me where tests should be written for this file? I can't find any.

**Comment by jennifer-shehane** [comment]
@quentinus95 	You should also be able to do a `cy.visit()` to a local file. So assuming the following file structure:

```
- my-project
  - cypress
    - integration
      - spec.js
  - src
    - index.html
  - cypress.json
```

You could write `cy.visit('src/index.html')` - the file you want to navigate to should be relative to your project root. 

Would this satisfy your requirements or do you need the `file://` protocol specifically for your testing purposes?

**Comment by quentinus95** [comment]
@jennifer-shehane thanks for your answer. However, I don't get it. What should be the baseURL?

Also my project is located in another folder, I need to pass an absolute link to it (`/root-folder/sub-folder`).

Finally, if the file is served using `http`, it's an issue because it may hide some errors (e.g. security enabled in the browser only when using the `file://` protocol, CORS, ...).

**Comment by brian-mann** [comment]
I don't believe we will be able to support the raw `file://` protocol for complex reasons such as how the HTTP protocol works when proxies are involved.

In your notes you mention not wanting to spin up a webserver to test - this is already supported inside of Cypress. You simply provide a relative path via `cy.visit(...)` and Cypress will act as your webserver and serve the file itself.

**Comment by Bkucera** [comment]
Closing as @quentinus95 's use case is already covered. Give `cy.visit()` a path relative to your project root and Cypress will act as the static web server

ex)
```sh
project/
  dist/
    index.html
  cypress/
   integration/
     index.spec.js
```

```js
// index.spec.js
it('works', ()=>{
  cy.visit('/dist')
})
```

**Comment by quentinus95** [comment]
@brian-mann using a HTTP server does not answer my need; I need to be able to test my app using the `file://` protocol to spot the exact risks you're mentioning.

@Bkucera my use case is not covered: I can't access a file using the `file://` protocol.

**Comment by Bkucera** [comment]
@quentinus95 you are right, cypress does not currently cover that use case. I'm going to keep this closed because I think significantly more work would need to be done to get it working. But please see #1965 as it's tracking a similar issue

**Comment by quentinus95** [comment]
@Bkucera when you write 

> I think significantly more work would need to be done to get it working

do you mean it **may** already work? If so please tell me, I can compile this branch and run my tests locally with it to ensure it does.

**Comment by Bkucera** [comment]
@quentinus95 No, I'm certain it will not work without a lot more changes.

**Pull request closed without merging**
