### PR TITLE
fix: CT app icon to have correct sizes

### PR DESCRIPTION
**Pull request by estrada9166**
- Closes  [UNIFY-1730](https://cypress-io.atlassian.net/jira/software/projects/UNIFY/boards/20?assignee=5ea883deddd45f0b94f5d98d&selectedIssue=UNIFY-1730)

### User facing changelog

Fix CT icon size on the app which was not being consistent with the e2e icon
image

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@estrada9166 Can you create a corresponding Jira issue so this is track int he sprint?

**Comment by estrada9166** [comment]
@jennifer-shehane done! also, I updated the PR description to link it!

**Comment by marktnoonan** [comment]
Rerunning CI to get a full percy build, but manual testing of this PR looks good. I checked migration and setup flows as well, no other icons look out of place.

**Review by marktnoonan — APPROVED** [review]
Percy and manual testing look good. The icon that wasn't caught last time is now in a percy snapshot generated from a component test.

**Review by flotwig — APPROVED** [review]
so beautiful!!!

**Comment by lmiller1990** [comment]
Are we good to merge @estrada9166 ? I wonder why `license/cla` is not reported? 🤔

**Pull request merged**
