### PR TITLE
chore: better validation messages for experimental retries

### PR DESCRIPTION
**Pull request by MuazOthman**
- Closes [CYCLOUD-1765](https://cypress-io.atlassian.net/browse/CYCLOUD-1765)

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

[CYCLOUD-1765]: https://cypress-io.atlassian.net/browse/CYCLOUD-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by emilyrohrbough — COMMENTED** [review]
Could you add screenshots of these error combinations?

**Review by mabela416 — CHANGES_REQUESTED** [review]
Not passing `passedRequired` for `detect-flake-and-pass-on-threshold` and `stopIfAnyPassed` for `detect-flake-but-always-fail` is NOT erroring but it's supposed to return an error. 
image
image

**Comment by mabela416** [comment]
For this legacy config, I'm also NOT getting an error when starting the run but I do after the run is done
``` 
  retries: {
    openMode: true,
    runMode: true,
  },
```
image

BUT in develop, I do get an error when trying to start my run 

image

**Comment by mabela416** [comment]
this config should also error out but instead it lets me do a run which ends with this error
```
  retries: {
    runMode: true,
    openMode: true
  },
```

image

**Comment by MuazOthman** [comment]
@mabela416 I fixed the validation for the last 2 comments. Validating fields within `experimentalOptions` are beyond the scope of this PR since adding that would be a change of behavior. cc: @ryanpei for feedback on that.

**Comment by mabela416** [comment]
> @mabela416 I fixed the validation for the last 2 comments. Validating fields within `experimentalOptions` are beyond the scope of this PR since adding that would be a change of behavior. cc: @ryanpei for feedback on that.

@MuazOthman  Validating fields within `experimentalOptions` is already happening in develop and it's being removed in this PR which should not be happening

**Comment by mabela416** [comment]
This is the error i get in develop when I don't pass `passesRequired` or `stopIfAnyPassed`

image

image

**Review by mabela416 — COMMENTED** [review]
One small nitpick:
When I pass a config without the `runMode` and `openMode`, I get this message but I think it should say the value passed was undefined
image

image

**Comment by MuazOthman** [comment]
@mabela416 it shows `0` in that error message because this is the default value, we can probably make this less confusing once strategy-based retries becomes GA.

**Review by mabela416 — APPROVED** [review]

**Comment by MuazOthman** [comment]
@emilyrohrbough validation error messages can be seen under `packages/config/__snapshots__/validation.spec.ts.js`

**Review by cacieprins — APPROVED** [review]

**Pull request merged**
