### PR TITLE
chore: Reduce iconify footprint

### PR DESCRIPTION
**Pull request by emilyrohrbough**
We are using `@iconify` to pull in svgs for `computer`, `laptop`, `code` and the vs code logos. This change directly installs the iconify packages that provide these svgs. For the most part we provide our own custom icons. @elevatebart Not sure if we someday want to own these for ourselves.

## Before:
Locally:
```sh
du -sh ./node_modules/** | sort -nr | grep '\dM.*'
...
130M	./node_modules/@iconify
```
[CircleCI Cache size: 910 MiB](https://app.circleci.com/pipelines/github/cypress-io/cypress/58961/workflows/f1400584-61b2-4e4e-bd64-759004ec65e7/jobs/2447995)

## After
Locally:
```sh
du -sh ./node_modules/** | sort -nr | grep '\dM.*'
...
 11M	./node_modules/@iconify-json
1.3M	./node_modules/@iconify
```
[CircleCI Cache size: 844 MiB](https://app.circleci.com/pipelines/github/cypress-io/cypress/58959/workflows/a79e85e7-2eac-49e0-81ce-5f0d0bec5f9b/jobs/2447754)

### Additional details
We are also importing the [alrra/browser-logos](https://github.com/alrra/browser-logos) project for browser icons and it would be nice if we used the used the direct dependencies for the icons used vs installing the git project.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by AtofStryker — APPROVED** [review]

**Comment by elevatebart** [comment]
We do want to own them ourselves indeed. I wonder if don't have copies of those icons already. Let me check.

[EDIT] we do not have copies of the editors logos yet in the design system. It would make sense to add them.

For reference here is the list of editors logos we would need

```
VSCode, Atom, Webstorm, Vim, SublimeText, Emacs
```

CC @ryanjwilke @rmullenax 

[/EDIT]

**Comment by elevatebart** [comment]
I see we are using `<i-mdi-check/>` for the select component (probably could be replaced with design system icons)

**Comment by elevatebart** [comment]
Though laptop seems to come from our own.

**Review by elevatebart — APPROVED** [review]
Given how much improvement this brings on the size of Circle Cache, I say LGTM and merge ASAP ;)

**Pull request merged**
