### PR TITLE
Move dependency-check into release step

### LINKED ISSUE #1997: dependency-check is in prebuild, should be in release
Currently, we run `dependency-check` as part of our `prebuild` step:

```
"scripts": {
    "test": "npm run test-unit",
    "test-unit": "npm run dtslint && npm run unit",
    "test-watch": "npm run unit -- --watch",
    "test-dependencies": "bin-up deps-ok && dependency-check . --no-dev",
    "test-debug": "node --inspect --debug-brk $(bin-up _mocha)",
    "test-cov": "nyc npm run unit",
    "unit": "BLUEBIRD_DEBUG=1 NODE_ENV=test bin-up mocha --reporter mocha-multi-reporters --reporter-options configFile=../mocha-reporter-config.json",
    "lint": "bin-up eslint --fix *.js bin/* lib/*.js lib/**/*.js test/*.js test/**/*.js",
    "dtslint": "dtslint types",
    "prebuild": "npm run test-dependencies && node ./scripts/start-build.js",
    "build": "node ./scripts/build.js",
    "prerelease": "npm run build",
    "release": "cd build && releaser --no-node --no-changelog",
    "size": "t=\"$(npm pack .)\"; wc -c \"${t}\"; tar tvf \"${t}\"; rm \"${t}\";"
  },
```

While reporting [an issue](https://github.com/maxogden/dependency-check/issues/89) with `dependency-check` on FreeBSD, several of their developers [suggested](https://github.com/maxogden/dependency-check/issues/89#issuecomment-398940325)  we should be running it as a release step instead:

> > > hmm that also seems like incorrect behavior. the idea of this module is to catch things before you publish, not when you install. i would just remove it in your port
> >
> > Oh, okay. I might raise an upstream PR to move this, then, as it sounds like the problem lies with Cypress.
> >
> > If I understand you correctly, the fix would be to move test-dependencies into the release script above? (Which is also not called by the port :) ).
>
> Correct

Unless otherwise directed by more knowledgable folks here, I will submit a PR to do fix this, thereby closing this issue.  (That will also have the entirely selfish benefit of unblocking my work on a FreeBSD port by moving this step outside the port compilation phase :wink: ).

### PR DESCRIPTION
**Pull request by duncan-bayne**
Currently, we run `dependency-check` as part of our prebuild step.  

The dependency-check developers have [suggested](https://github.com/maxogden/dependency-check/issues/89#issuecomment-398940325) that this is incorrect, and that we should be running the check as part of our release step.

This PR makes that change.  Fixes #1997.

### CODE REVIEW

**Comment by bahmutov** [comment]
I disagree with the comment in dependency-check. Imagine somewhere in your code you are using `require('foo')` but it is not listed among the dependencies in `package.json`. I don't want to discover this during local run, or testing. I want to know right away! otherwise there can be very cryptic errors due to a missing dependency or ... and this is much much worse - if you have this as a dependency but installed by some other package. 

So having this check early helps avoid pain down the road when we actually build a merged pull request only to discover that some dependency is missing ... and who knows how it was supposed to work, because the original author of the PR might not be available.

**Comment by jennifer-shehane** [comment]
Yeah, I'd like more insight on why dependency-check contributors feel this is an 'incorrect' usage exactly. Will the package not behave correctly when run in a `prebuild` step? If it's just an opinion, then yes, I also disagree with this change.

**Comment by duncan-bayne** [comment]
@Bkucera @jennifer-shehane I'll ask the `dependency-check` folks to drop by here and comment.  I personally have no opinion on where it's run.

**Comment by jennifer-shehane** [comment]
Hey @bahmutov, any thoughts on where this PR is at?

**Comment by Bkucera** [comment]
@jennifer-shehane I would vote to close this.

**Pull request closed without merging**
