### PR TITLE
Fix getFocused when activeElement is inside an iframe

### LINKED ISSUE #2124: Calling .blur() on elements inside iframes throws an error
### Current behavior:
When using Cypress together with Storybook there is an issue when calling `.blur()` on an element. Storybook render inside an iframe so my guess is that there is a bug in the `document.activeElement` check inside the `.blur()` function. We should probably loop through all iframes and find the correct `activeElement`. Using the `force` option solves the issue but I feel that this should work without that.

Note that this worked before 3.0.2. 

Error message
```
CypressError: cy.blur() can only be called on the focused element. Currently the focused element is a: <iframe id="storybook-preview-iframe" title="preview" src="iframe.html?" allowfullscreen="" style="width: 100%; height: 100%; border: 0px; margin: 0px; padding: 0px;"></iframe>
```

### Desired behavior:
To not throw an error.

### Steps to reproduce:

https://github.com/alexandernanberg/cypress-test-tiny

Install dependencies and start storybook + cypress
`npm install && npm start`

Run the basic test and the `blur` will throw an error.

### Versions

Cypress: 3.0.2

### PR DESCRIPTION
**Pull request by alexandernanberg**
## What
Fixes #2124 

## How
I modified the `getFocused` function to take iframes into account.
Also switched manual checks for `activeElement` to use the `getFocused` instead and added a test case for blurring elements inside iframes.

Note that I've not worked with Coffescript before so please tell me if I'm not following best practices.

### CODE REVIEW

**Comment by brian-mann** [comment]
Awesome, this is super helpful. No real quibbles, I think we'll take the PR from here and add a few extra tests to ensure the events are bubbling correctly to the elements inside the iframe and don't propagate out.

This PR has edit access so we'll layer on a few commits and then merge this in.

**Comment by alexandernanberg** [comment]
Yea that would be really great! Happy to assist more if needed though 👍

**Comment by alexandernanberg** [comment]
Is there anything more I can do to get this going? If you can give me some more pointers on the tests I could try to solve that as well 😊

**Comment by brian-mann** [comment]
This PR needs some additional work such as handling situations in which there is a cross origin iframe. As it stands it will throw if that's the case.

We had a big update to the driver that I merged into here so we'll see if all the tests pass before I add more test cases and handle edge cases like cross origin iframes.

**Comment by alexandernanberg** [comment]
Closing this because I won't have more time to look at this

**Pull request closed without merging**
