### PR TITLE
fix(server): bail out on close if server does not exist

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes https://github.com/cypress-io/cypress/issues/15089

### User facing changelog

I did not test this super thoroughly yet, but it fixes the bug reproduced in #15089.

### PR Tasks

- [ ] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

**Review by flotwig — COMMENTED** [review]
Nice, tested manually and confirmed this fixes the issue.

Before merging, it would be good to have a regression test in packages/server/test/integration/server_spec.js or packages/server/test/unit/server_spec.js

**Comment by lmiller1990** [comment]
@flotwig how would you recommend testing this? We can test that some stub is/is not called, but I am not sure how to test against this specific race condition. What did you have in mind?

**Comment by flotwig** [comment]
@lmiller1990 for me, it's not a race condition, it happens whenever "reloading" a project via the desktop-gui. That should be reproducible inside a test, I think

**Comment by lmiller1990** [comment]
This isn't consistent for me. Only if I click "back" really fast.

Anyway, I added a basic test. Fixing this entire test file to run is really hard (maybe impossible with `ensureProp`, or require so much stubbing it's not really worth it).

For now we have a fix and a basic test, this should at least fix the bug for 7.0 while we figure out what to do with these tests. LMK if I missed something @flotwig.

**Review by flotwig — APPROVED** [review]

**Pull request merged**
