### PR TITLE
Use node module resolution to find reporters

### LINKED ISSUE #5083: Globally-installed custom reporters cannot be used
### Current behavior:
An error is raised when launching the tests using a custom reporter (e.g., mochawesome) that is only installed locally. 

This is the cypress run output:
```
Could not load reporter by name: mochawesome

We searched for the reporter in these paths:

- /e2e/mochawesome
- /e2e/node_modules/mochawesome

The error we received was:

SyntaxError: /e2e/mochawesome.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>:null:null)
    at Object.Module._extensions..json (module.js:661:27)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.Reporter.loadReporter (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/reporter.js:378:16)
    at Project.watchSettingsAndStartWebsockets (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/project.js:266:20)
    at /root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/lib/project.js:146:39
    at tryCatcher (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:507:35)
    at Promise._settlePromise (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:143:14)
    at PromiseArray._iterate (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:113:31)
    at PromiseArray.init [as _init] (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:77:10)
    at Promise._settlePromise (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/root/.cache/Cypress/3.4.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

### Desired behavior:
I would like Cypress to search the required module also in the globally-installed packages. This would make it possible to extend the Cypress docker image (where Cypress is installed globally) with custom reporters and use them.

### Steps to reproduce: (app code and test code)
create a new docker image like this

```
FROM cypress/included:3.4.1

RUN npm install -g mocha@5.2.0 mochawesome@4.1.0 mochawesome-merge@2.0.1 mochawesome-report-generator@4.0.1 mocha-multi-reporters@1.1.7 mocha-junit-reporter@1.23.1
```

then launch the tests with `docker run` using a cypress.json based on 

```
{
 ...
  "reporter": "mochawesome",
  "reporterOptions": {
    "reportDir": "cypress/results",
    "overwrite": false,
    "html": true,
    "json": true
  }

}
```

Following the stacktrace I guess the problem is here:
https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/reporter.coffee#L310
but I'm not sure if not trying a direct `require` of the custom module is a design choice or not

### Versions
Cypress 3.4.1

### PR DESCRIPTION
**Pull request by penx**
- Closes #5083 #1192

(I need some advice on testing this)

### User facing changelog

Use node module resolution to find reporters

### Additional details

Use require.resolve to find reporters.

Allows reporters to be located if:
- globally installed
- in a parent directory e.g. as part of a monorepo
- using `yarn link` or `npm link`
- using yarn 2 (modules not stored on disk alongside project)

https://nodejs.org/api/modules.html#modules_require_resolve_request_options

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Thanks for the contribution! We will need some tests written to verify this new behavior. 

There is a Contributing Guide that covers how to contribute and get Cypress running locally  here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

@chrisbreiding Do you have any idea where tests for this might live? Only thing I found was maybe https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/8_reporters_spec.js

**Comment by jennifer-shehane** [comment]
@penx Do you still have time to address the changes requested in this PR? We will have to close this PR due to inactivity otherwise.

**Comment by penx** [comment]
hi @jennifer-shehane - sure I'd like to add some tests, but it wasn't very clear to me how I'd write a test for this feature so I was hoping @chrisbreiding would respond to your question!

**Comment by chrisbreiding** [comment]
It's probably possible to test the "in a parent directory" scenario in [/packages/server/test/e2e/8_reporters_spec.js](https://github.com/cypress-io/cypress/blob/develop/packages/server/test/e2e/8_reporters_spec.js) by adding a simple reporter to the [fixtures directory](https://github.com/cypress-io/cypress/tree/develop/packages/server/test/support/fixtures). It would be tricky or perhaps impossible to test the other scenarios. 

I would recommend adding a unit test for the `Reporter.getSearchPathsForReporter` method to [/packages/server/test/unit/reporter_spec.js](https://github.com/cypress-io/cypress/blob/develop/packages/server/test/unit/reporter_spec.js) as well.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this PR due to inactivity. Please open a new PR addressing the original issue and any requested changes.

**Pull request closed without merging**
