### PR TITLE
feat: make grepFilterSpecs work with negative grep

### PR DESCRIPTION
**Pull request by Narretz**
Since find-test-names 1.18, it's possible to output the full test names, i.e. prepended with the parent
suite names.
This allows grepFilterSpecs to filter
spec files when negative grep matches test but
not suite and vice versa.

Benefit:
The log is less cluttered, especially
with a lot of specs.
The speed improvement is minor,
about 1.5 seconds per filtered spec file.

@jordanpowell88 can you tell me where the integration tests for cypress/grep are now? Since you moved the package into this repository. cypress-grep used to have a github actions test job, see here https://github.com/cypress-io/cypress-grep/blob/56afce9e920583d38ada30e13560e8372491d115/.github/workflows/ci.yml

I can't find any of these commands in the cypress repo. To me this suggest the cypress-grep tests aren't running anymore.

### User facing changelog

`@cypress/grep`

- grepFilterSpecs now works with negative grep

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by jordanpowell88 — CHANGES_REQUESTED** [review]
Thank you so much for the PR! Can you add a test to `cypress/e2e/unit.js` to assert this negative scenario?

**Comment by Narretz** [comment]
Hi @jordanpowell88 I don't think this can be tested in a unit test. The changes are in the plugin.js, and the unit tests only test the util functions. I think this must be tested in an e2e test, same as it was in the old cypress.grep package.

**Comment by jordanpowell88** [comment]
I misspoke on where the test should be, can you add an E2E test for this work?

**Comment by Narretz** [comment]
Hi @jordanpowell88 I would like to add an e2e test but I don't know where they are defined anymore. They previously were defined here https://github.com/cypress-io/cypress-grep/blob/56afce9e920583d38ada30e13560e8372491d115/.github/workflows/ci.yml but the file / the tests are not in the cypress repository after cypress-grep was moved here. This suggests that there are actually no e2e tests running for cypress-grep at the moment. Can you clarify this?

**Comment by jordanpowell88** [comment]
@Narretz 
I am working on adding these tests to the repo! https://github.com/cypress-io/cypress/pull/24992

**Comment by romankhomitskyi** [comment]
I am wondering what is the status of this MR

**Comment by Narretz** [comment]
I'm waiting for @jordanpowell88 to add the test framework for cypress-grep to the repository. No tests, no party 😉

**Comment by jordanpowell88** [comment]
@Narretz I apologize for the delay on this. I moved teams and no longer work on this plugin anymore 😞 . At this time, I don't intend to be able to get those e2e tests in the repo for the `grep` plugin. Hopefully this is something the App team will be able to prioritize in the near future

**Comment by nagash77** [comment]
Hi @Narretz , the E2e Team will not be able to prioritize this work in the near future.  I am going to close this PR for the time being.  If we have a change in priorities that allows us to pick this up we will reopen this.  

If you are able to take on the work @jordanpowell88 was going to do feel free to comment back here to pick this back up and we can reopen.  Check out our [community chat](https://discord.gg/cypress), it can be helpful if you have questions on the pieces needed to wrap up this PR and add tests.

**Pull request closed without merging**
