### PR TITLE
feat: added wait before and after screenshot

### PR DESCRIPTION
**Pull request by galr52**
added wait after screenshot

- Closes 

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [x] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@galr52 Could you give an explanation on why this new feature is necessary or link to an existing issue where people have requested this feature? 

We'd like an understanding on why anyone would want this feature. We're not likely to add features without understanding the benefit because it is more to maintain in the future. Thanks.

**Comment by galr52** [comment]
> @galr52 Could you give an explanation on why this new feature is necessary or link to an existing issue where people have requested this feature?
> 
> We'd like an understanding on why anyone would want this feature. We're not likely to add features without understanding the benefit because it is more to maintain in the future. Thanks.

in my app i have a screen that rerender on window resize.
when i was trying to make a screenshot tests for that screen i faced an issue when the screen size is changing (the left panel is closing and etc).

i found this open issue https://github.com/cypress-io/cypress/issues/9443 

with this feature i can workaround the issue, wait a few ms and let my screen rerender before the screenshot

**Comment by jennifer-shehane** [comment]
@galr52 Can you provide a failing test cast that would now be passing with this solution? We need tests for all fixes and new features. 

Is there a reason adding `cy.wait(xxx)` instead would not work in your case?

Just off of this information, I think it would be more worthwhile to investigate the window:resize triggers on the screenshot than add an arbitrary wait feature. This seems to be adding a new feature to fix an issue instead of just fixing the issue outright.

**Comment by galr52** [comment]
@jennifer-shehane  the only solution i could think about that can fix the resize issue is to wait for all the "before:screenshot" subscribers.

i cant provide a failing test because the image resolution is changing on screenshot events

`cy.wait(xxx)` wont fix the problem the because  the screen is changing on 'before:screenshot' is emitted, and this occurs only when you take a screenshot (raise 'take:screenshot' event)

**Comment by jennifer-shehane** [comment]
@galr52 Thanks for taking the time with this PR. We'd like to see a solution for the resize events triggers overall instead of adding a generic wait before/after screenshot as a feature. Going to close this PR for now.

**Pull request closed without merging**
