### PR TITLE
feat(component-testing): Cli changes

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
This PR moves CLI changes from #14479

## Description

It adds a new **command** `open-ct`. Unfortunately, there is no way to preserve the `flag` for component testing and make it hidden without allowing unknown options (https://github.com/tj/commander.js/issues/811). 

It is hidden for now to not confuse users until all the component-testing changes will be merged in and released.

But component testing IMHO should leave as separate command naturally.

### CODE REVIEW

**Comment by brian-mann** [comment]
I am not sure we want to merge this in because for spawning component-testing, we shouldn't be using the CLI at all, and should instead just be invoking the binary directly.

Additionally, we will likely need to discuss what the **actual** user facing CLI changes will be when we release CT as MVP or GA.

We could go the flag route, or we could go the command route. Likely command, since certain options would be namespaced for a particular type of testing.

**Maybe**
```bash
cypress ## open GUI
cypress open ## open GUI (same as above but likely will deprecate)

cypress open-e2e ## open GUI + browser in E2E mode
cypress open-ct ## open GUI + browser in E2E mode

cypress run ## run e2e
cypress run-e2e ## run e2e
cypress run-ct ## run CT
```

Alternatively we could go with a `--type e2e` or `--type ct` kind of flag, but then the top level command options would be inherited, which is problematic if we diverge the top level options for each testing mode.

**Review by JessicaSachs — APPROVED** [review]
This looks good to me. As per @brian-mann, we will need to have a larger discussion on if this will be our public API, but that will happen in the future. This API will serve us well for the next few weeks.

**Review by flotwig — CHANGES_REQUESTED** [review]
@dmtrKovalenko this looks good, but since the server implementation is not active, can you please make the server crash when it receives `--componentTesting`? `throw new Error('component testing not implemented` or something.

Reason being is that I tried to use open-ct and got confused about why it just opened Cypress and not CT, and a clear error would've prevented that

After that, lgtm

**Review by flotwig — APPROVED** [review]
🥳 lgtm

**Review by JessicaSachs — APPROVED** [review]

**Pull request merged**
