### PR TITLE
fix: resolve "project" breadcrumb problems

### PR DESCRIPTION
**Pull request by marktnoonan**
- Closes https://github.com/cypress-io/cypress/issues/21911

Keeping in draft till some related changes here land: https://github.com/cypress-io/cypress/pull/22073

### User facing changelog

In the Launchpad, the project's name will no longer link to the "Choose Testing Type" step of the the launchpad. This behavior was removed because in many situations it is not valid to go back to the testing type picker, and in the situation where it is valid, there's already a "Switch testing types" link on the same page.

### Additional details

Being able to "go back" midway through a migration, set up, or during an error state can lead to problems and confusion, but having a piece of text that only becomes a link on one screen doesn't seem that helpful to users. It should be a link, or not.

I considered making the rules more complex, or finding a way to safely clean up and navigate to this screen, which would address the the problem in the linked issue as well, but both options seem to me like we'd be maintaining these rules long term for quite low value. 

After discussion with Ryan, we have design approval to not make this a link.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by marktnoonan** [comment]
@emilyrohrbough I know you like this link, let me know if you like it enough we should talk more about it before this PR happens.

**Comment by emilyrohrbough** [comment]
@marktnoonan If Ryan has signed off, I trust he has considered the tradeoffs and user impact of removing this.

Thanks for tagging me! I appreciate it 😄  You're right that I do like it and am sad to see this go. It feels very natural to navigate from here given its a fairly upper left corner is an established pattern for browsers and filesystem finders. This area is where I tend to go for navigation (after keypad swipes) for navigating forward/back.

**Comment by marktnoonan** [comment]
@tbiethman this is good feedback for design, I'm happy for now to be able to prevent the user reaching an invalid/confusing state, but it's a good point about the overall sense of how navigation works in the launchpad.

**Review by ZachJW34 — APPROVED** [review]
Sorry for the late review! Works great

One small nit: You can remove `isLoadingNodeEvents` from the query in `HeaderBarContent.vue`.

**Comment by lmiller1990** [comment]
Looks like once https://github.com/cypress-io/cypress/pull/22648#pullrequestreview-1043521781 is addressed we can merge?

**Comment by lmiller1990** [comment]
LGTM, are we going to do https://github.com/cypress-io/cypress/pull/22648#pullrequestreview-1043521781?

Otherwise let's get CI green and merge this up.

**Comment by marktnoonan** [comment]
@lmiller1990 👍 , updated. 

The reason I didn't do this right away was I got slightly distracted with wondering how many other places we could potentially remove `isLoadingNodeEvents` - it looks like there were several files where it is present in the GQL data requested but not actually being referenced elsewhere in those components. So I started to wonder if it was included for some other reason than directly affecting the UI, like it has some side effect that we want, and I wanted to look a little further. After checking the history, it seems safe to remove the `isLoadingNodeEvents` from HeaderBarContent.vue, since it was added at the same time it was used, so I've done that.

@tgriesser there's [this PR](https://github.com/cypress-io/cypress/pull/19572/files#diff-99636480d4ea376f639524746fcddf8126cd1ad0abf0f5a2b570d6bb56085722) where the some of the change is just to add some fields including `isLoadingNodeEvents` to the some queries, and those fields are not actually referenced by the components. What's the purpose of that? These are the usages that made me ever so slightly cautious before removing.

**Pull request merged**
