### PR TITLE
Fix long error in the app iframe cannot be fully scrolled

### LINKED ISSUE #6898: The webpack error in the app iframe cannot be fully scrolled
Cypress v4.3.0

If there is a webpack error with a long text line, I can only scroll it horizontally for a few characters, but never to fully read it

overflow

### PR DESCRIPTION
**Pull request by adancarrasco**
Closes #6898 
### User facing changelog

Set position: absolute; and remove left positioning for .iframes-container

### Additional details
Apparently the issue got introduced when adding support for Firefox, I verified and Firefox and 
Chrome are working fine after this change.

### How has the user experience changed?
After:
*Firefox*
issue-6898-firefox

*Chrome*
issue-6898-chrome

### PR Tasks

- [ ] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by adancarrasco** [comment]
Setting it as WIP to verify failing checks.

**Comment by jennifer-shehane** [comment]
Hi, we're changing our contributing workflow to use Draft PRs instead of `[WIP]` in the title. I've converted this PR to a Draft PR and removed `[WIP]` from the title. 

Please [mark the PR as **Ready for Review**](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review) when you're ready for a Cypress team member to review the PR.

**Comment by adancarrasco** [comment]
Removing **Draft** from this PR. 
* I pulled latest from `develop` and tests run again
* The failing tests are the same as in `develop` branch

**Comment by chrisbreiding** [comment]
Looks like the issue I referred to in my last comment is still possible with this fix: #7443. I think we need to go back to `position: fixed` and find a better solution to the error scrolling issue.

**Comment by jennifer-shehane** [comment]
This PR will be reverted in https://github.com/cypress-io/cypress/pull/7448 due to a newly introduced bug https://github.com/cypress-io/cypress/issues/7443

**Pull request merged**
