### PR TITLE
[WIP] Update JQuery to 3.0.0

### LINKED ISSUE #1215: Upgade jQuery dependency to 3.x
GitHub has security vulnerability against our 2.x version in packages/server/package.json. We should just upgrade to 3.x

screen shot 2018-01-22 at 12 38 13 pm

screen shot 2018-01-22 at 12 38 39 pm

### PR DESCRIPTION
**Pull request by Saibamen**
Ref: #1229 
Closes #1215

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Hey @Saibamen, if you could, rename the PR title to have `[WIP]` if you are still working through this issue. 

When you're ready for an official pull request review, choose a reviewer (if possible) and remove the `[WIP]` from the title.

**Comment by Saibamen** [comment]
`can type into an iframe with designmode = 'on'` is failing. I don't know how to fix this

**Comment by jennifer-shehane** [comment]
Test failures:

Screenshots are different sizes in jQuery update in `cypress/packages/server/test/e2e/5_screenshots_spec.coffee`

```
-  - /foo/bar/.projects/e2e/cypress/screenshots/screenshots_spec.coffee/taking screenshots -- really long test title aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.png (1000x660)
-  - /foo/bar/.projects/e2e/cypress/screenshots/screenshots_spec.coffee/taking screenshots -- really long test title aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (1).png (1000x660)
+  - /foo/bar/.projects/e2e/cypress/screenshots/screenshots_spec.coffee/taking screenshots -- really long test title aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.png (1000x548)
+  - /foo/bar/.projects/e2e/cypress/screenshots/screenshots_spec.coffee/taking screenshots -- really long test title aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (1).png (1000x548)
 ```

`undefined` printing in error message instead of element in
- `cypress/packages/server/test/e2e/3_issue_173_spec.coffee`
- `cypress/packages/server/test/e2e/2_config_spec.coffee`
- `cypress/packages/server/test/e2e/1_caught_uncaught_hook_errors_spec.coffee`

```
-     CypressError: Timed out retrying: Expected to find element: 'element_does_not_exist', but never found it.
+     CypressError: Timed out retrying: Expected to find element: 'undefined', but never found it.
```

**Comment by Saibamen** [comment]
Merged latest `develop` branch.
Need help with that PR

**Comment by chrisbreiding** [comment]
Closing in favor of https://github.com/cypress-io/cypress/pull/1229

**Pull request closed without merging**
