### PR TITLE
fix: Tooltip issues with ACI

### LINKED ISSUE #22628: Remove tabindex="0" from RunStatusDots.vue
### Current behavior

Implementation currently contains tabindex="0"

### Desired behavior

_No response_

### Test code to reproduce

NOne

### Cypress Version

10.3.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by mike-plummer**
* Replace manual tabindex with `button`, update styles accordingly
* Fix tooltip styling so all headers can appear above if space permits

- Closes #22628, #22597

### User facing changelog
* Improve keyboard navigation for Latest Runs data in Specs Explorer
* Accessibility and styling improvements around Specs Explorer tooltips

### Additional details
`tabindex=0` was being used to make `div` elements focusable which isn't ideal for a11y - replacing these usages with `button` which is a semantically interactive element. Additionally, the "Latest Runs" items shouldn't be focusable when there is no data to display (user is logged out, etc)

There are existing e2e tests that validate tooltip behaviors & focusability, and percy snapshots should capture styling changes

### Steps to test
1. Log into Cypress app
2. Open a project that has cloud run(s) recorded
3. Log into app with a user that **_does not_** have access to the project
4. Mouse over the "Average Duration" column header, observe tooltip appears _above_ the header by default
5. Using keyboard navigation, move focus through the specs list
    * Observe that the "Last Updated", "Latest Runs", and "Average Duration" headers open tooltips as they receive focus
    * Observe that the inactive "Latest Runs" items do not receive focus
6. Logout and log back in with a user that **_does_** have access to the project. Observe "latest runs" data loads
7. Using keyboard navigation, move focus through the specs list
   * Observe that the "Latest Runs" item opens the tooltip as it receives focus

### How has the user experience changed?
**Before**

https://user-images.githubusercontent.com/11482842/176921884-ce79a155-0a35-43e0-a5a8-a5d7aa420bc0.mov

**After**

https://user-images.githubusercontent.com/11482842/176922351-2454041d-b067-43a6-88c5-cc757f58d2b2.mov

### PR Tasks
- [x] Have tests been added/updated? _Styling changes should be covered by existing Percy snapshots_
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by rachelruderman** [comment]
@mike-plummer regarding the `Steps to test`, do you have test user logins we can use for this? I don't usually work in cloud so I don't have any go-to ones myself 😸 

> Log into Cypress app
Open a project that has cloud run(s) recorded
Log into app with a user that does not have access to the project

**Comment by mike-plummer** [comment]
> @mike-plummer regarding the `Steps to test`, do you have test projects/user logins we can use for this? I don't usually work in cloud so I don't have any go-to ones myself 😸

@rachelruderman Hmm, that's a good question. I don't know of an easy way to set up temporary test users in the dashboard, I've just been using one linked to my GH and another to my Cypress email. Off the top of my head the easiest approach that should work for you might be the following - this at least saves you from having to create any projects or record any runs:

1. If you don't already have it, clone the [cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) repo. This project has runs already recorded in Staging
1. Open the kitchensink project in the app
2. Log in using your GitHub - this should add you to the Cypress org automatically. There are a few questions you may need to fill out if this is your first time.
3. Go back to the app, statuses should now populate. At this point you can validate test steps 6-7
4. Open the `cypress.config.js` file for your kitchensink project, replace the project ID with `9fyu35`
5. Go back to app, statuses should no longer populate and tooltips should display "Request Access" state. At this point you can validate test steps 3-5

**Comment by lmiller1990** [comment]
I tried it out, works great :+1:

**Review by lmiller1990 — APPROVED** [review]

**Review by rachelruderman — APPROVED** [review]
Accessibility overall is a bit of a bummer, but that's a larger design question than this PR. Thank you for pushing the needle in the right direction! 🙏

**Pull request merged**
