### PR TITLE
Fix parsing error in parseNestedValues

### PR DESCRIPTION
**Pull request by HugoGiraudel**
Hello,

This is a fix for https://github.com/cypress-io/cypress/issues/620. Instead of splittings pairs on all occurrences of the `=` character, we split on the first one only. This makes it possible values to contain equal signs.

### CODE REVIEW

**Comment by brian-mann** [comment]
As simple as this change looks - we **have** to have tests for every single modification. We are still working on our contributing guides, but the goal here is that you should be able to write the unit tests for this and submit it alongside the PR.

@bahmutov is on vacation this week, but if you can't figure out how to write the server unit tests one of us can probably do it for you. It's definitely a bit daunting knowing where to write these tests, but it's in `packages/server` and you'll write unit tests. Not integration or e2e tests.

**Comment by HugoGiraudel** [comment]
I wanted to write tests but I didn’t find any for this file; I’ll see what I can do. By the way, Coffeescript makes it very hard and annoying to work on this. :/

**Comment by HugoGiraudel** [comment]
Found them! All good, I’ll update the PR.

**Comment by brian-mann** [comment]
Yeah Cypress was written well before there was ES2015 or babel or typescript (it wasn't popular i mean). At this point it is not really feasible to dedicate the resources we do have to a huge rewrite. New code goes in as JS, but there is a lot of coffeescript still.

Atom is still 32% coffeescript, and they get along. For the most part coffeescript looks like es2015...

**Comment by HugoGiraudel** [comment]
I updated the `.toObject -> backs up hosts + environmentVariables` test to add a value containing an equal sign. :)

**Pull request merged**
