### PR TITLE
feat: Add vue2 package from npm/vue/v2 branch

### PR DESCRIPTION
**Pull request by BlueWinds**
- Closes https://cypress-io.atlassian.net/browse/UNIFY-1253

### User facing changelog

- bundles `npm/vue2` in the binary, accessible via `cypress/vue2`.

### Additional details

Part of the component testing rearchitecture, to allow us to easily bring updates to users w/o requiring them to install anything other than `cypress`.

### PR Tasks
- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by tgriesser — CHANGES_REQUESTED** [review]
2 things - I thought we had landed on `vue-2` for the package name

Also, we should skip copying over all of the Cypress tests & `examples` dir from the existing Vue project

**Comment by BlueWinds** [comment]
> 2 things - I thought we had landed on `vue-2` for the package name
> 
> Also, we should skip copying over all of the Cypress tests & `examples` dir from the existing Vue project

The only discussion I saw was in the Jira ticket, where Lachlan commented:

> Can we name it vue2 instead of vue-2? I think it looks way nicer. Also there is some existing literature, like jest27-vue2, etc.

and it seemed reasonable to me. If there was any further discussion, I was unaware, vue2@1.0.0 looks quite nice to me, vs vue-2@1.0.0. The dash feels weird in contexts where we don't see *only* the module name. But I'm not married to the idea if other people have strong preferences / there was discussion I missed.

**Comment by tgriesser** [comment]
> and it seemed reasonable to me. If there was any further discussion, I was unaware, vue2@1.0.0 looks quite nice to me, vs vue-2@1.0.0. The dash feels weird in contexts where we don't see only the module name. But I'm not married to the idea if other people have strong preferences / there was discussion I missed.

That's fine - I was just going based on the Jira ticket title/body, didn't see that comment. @brian-mann or @ZachJW34 do you have a strong opinion on naming here

**Comment by brian-mann** [comment]
`vue2` is fine

**Comment by lmiller1990** [comment]
Regarding names, I see @brian-mann's point now - in the project I maintain, `vue-jest`, we actually have `vue2-jest27` and `vue3-jest27`, so there's no ambiguity. We aren't doing that here, though, so I'm not sure if `vue2` or `vue-2` is better.

**Review by lmiller1990 — APPROVED** [review]

**Review by tgriesser — APPROVED** [review]

**Pull request merged**
