### PR TITLE
fix: Google Chrome for testing - version not parsed correctly

### LINKED ISSUE #28123: Google Chrome for testing - version not parsed correctly
### Current behavior

When using Google Chrome for testing, Cypress cannot parse the browser version correctly:
```
bash-5.1$ chrome --version
Google Chrome for Testing 118.0.5993.70
```

`browser: { name: 'chrome', family: 'chromium', channel: 'stable', displayName: 'Chrome', version: 'for', path: 'chrome', minSupportedVersion: 64, majorVersion: 'for', isHeadless: true, isHeaded: false }`

### Desired behavior

Cypress should add "Google Chrome for Testing" for the browser detection.

### Test code to reproduce

Not applicable

### Cypress Version

13.3.2

### Node version

18.18.2

### Operating System

Red Hat Enterprise Linux release 9.2 (Plow)

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by Crustum7**
- Closes #28123 

### Additional details

This change should ensure that Google Chrome for Testing is parsed so the version number can be used. The only issue is that it assumes that the version is stable which might lead to some issues. If there is a good way of checking what channel it is, using the version number, that could be used to make a more robust change.

### Steps to test

Download a version of Google Chrome for Testing, for example: `npx @puppeteer/browsers install chrome@canary`

Add the path to Google Chrome for Testing: `export PATH=$PATH:/full/path/to/chrome/directory/` (note: this is the path to the **directory** that the executable `chrome` lives in, not the path to the executable itself)

### How has the user experience changed?

image
Before
image
After

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
@Crustum7 Can you share how you verified this change? I was following the [How Can I Get Chrome For Testing Binaries](https://developer.chrome.com/blog/chrome-for-testing/#how-can-i-get-chrome-for-testing-binaries) install directions to validate this change. 

I ran 
```sh
➜  ~ npx @puppeteer/browsers install chrome@canary
Downloading chrome r121.0.6109.0 - 154.4 MB [====================] 100% 0.0s 
chrome@121.0.6109.0 /Users/emily/chrome/mac-121.0.6109.0/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
```

and it appears the Test Chrome download landed in `Users/emily/chrome` instead of `Users/emily/Applications` like the Chrome [detect logic expects for Mac machines](https://github.com/Crustum7/cypress/blob/46843e9dcc3ae2285fe27d95997e1ee04002233a/packages/launcher/lib/darwin/util.ts#L73). I started with Canary to see if we could get any other details from the download!

**Comment by Crustum7** [comment]
Hi @emilyrohrbough! I added the directory of the chrome version I downloaded to my path.
`export PATH=$PATH:/full/path/to/chrome/directory/`
I'm on WSL which might work differently in that regard though.

**Comment by MikeMcC399** [comment]
@emilyrohrbough

```shell
npx @puppeteer/browsers install --help
```

provides the following information:

>  --path      Path to the root folder for the browser downloads and installation. The installation folder structure is
>              compatible with the cache structure used by Puppeteer.       [string] [default: Current working directory]

Unlike other browser installations, Chrome for Testing does not attempt to install in a common location. It installs into the current working directory by default and uses a version-dependent path.

I was able to successfully test this PR using Ubuntu `22.04` with Node.js `18.15.0` and Chrome for Testing `r120.0.6099.109`.

```shell
npx @puppeteer/browsers install chrome@stable --path ~/chrome-for-testing
```
```text
Downloading chrome r120.0.6099.109 - 150.2 MB [====================] 100% 0.0s 
chrome@120.0.6099.109 /home/mike/chrome-for-testing/chrome/linux-120.0.6099.109/chrome-linux64/chrome
```

It seems like it would be worthwhile to progress this PR.

**Comment by REPLicated** [comment]
@Crustum7 : Regarding your question about the appropriate "channel" value: As far as I understand, Chrome for Testing is not released in "channels". Channels as a concept make sense to control how fast you get updates. As pointed out on https://developer.chrome.com/blog/chrome-for-testing, the idea is that you get versioned browser binaries and pin a particular version for reliable testing.

There seems to be an API endpoint returning information which Chrome for Testing version _currently_ corresponds to each channel (see https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints). However, given the currently installed Chrome for Testing version, it seems likely that it may not correspond to the current version in any channel.

**Comment by alexsch01** [comment]
any update on this?

**Comment by MikeMcC399** [comment]
@REPLicated 

```shell
npx @puppeteer/browsers install chrome@stable
```

understands `stable` and `beta`. It also drops a file `.metadata` in the download directory, which currently would have the following contents:

```json
{
  "aliases": {
    "stable": "127.0.6533.72",
    "beta": "127.0.6533.57"
  }
}
```

**Comment by Roemer** [comment]
Any chance to get this merged somewhen?

**Comment by MikeMcC399** [comment]
@mschile / @AtofStryker 

The issue which this PR is supposed to resolve is causing problems in GitHub self-hosted runners.

After installing a selected Chrome browser version using the action [browser-actions/setup-chrome](https://github.com/browser-actions/setup-chrome), Cypress fails because "Chrome for Testing" is installed.

- See for instance issue https://github.com/cypress-io/github-action/issues/1307

Can this PR be reviewed soon?

It will need rebasing.

@Crustum7 

Are you still interested in this? It's been a year since you submitted your PR.

**Comment by alexsch01** [comment]
This looks like a really nice change for testing Cypress behaviors with specific versions of Chrome

**Comment by alexsch01** [comment]
Would be great to get this in the next release

**Review by MikeMcC399 — COMMENTED** [review]
I was able to test this PR successfully against Chrome for Testing `stable` on Ubuntu `24.04.1` LTS

```shell
mkdir ~/chrome-for-testing
cd ~/chrome-for-testing
npx @puppeteer/browsers install chrome@stable
```
with

```shell
--browser ~/chrome-for-testing/chrome/linux-131.0.6778.69/chrome-linux64/chrome
````

There was also no regression, running against Chrome.

For better maintainability, there should be a CircleCI test which runs against Chrome for Testing.

**Comment by alexsch01** [comment]
What else needs to be done for this to be pushed to develop?

**Comment by AtofStryker** [comment]
The team and I were talking about this yesterday, and we are thinking its best to recognize "Chrome For Testing" as it's own browser as we do this with different channels already. What I think remains here is that we would like the expression to not detect "Chrome for Testing" for Chrome release channel, and add a separate detection for "Chrome for Testing" .

This is a bit more involved than the current PR implements, but I am hoping to take a look at this soon as this PR as been open for almost a year and think we should considering getting this in sooner rather than later.

**Comment by mschile** [comment]
I'm closing this PR in favor of https://github.com/cypress-io/cypress/pull/30751/.

**Pull request closed without merging**
