### PR TITLE
server(fix) cleanup integrationFolder in filePath, close #1704

### LINKED ISSUE #1704: Spec file path contains invalid WIN32 path characters
### Current behavior: 

In windows, tests can't be executed because of a wrong path:

```
Error: 'C:\Users\IEUser\AppData\Roaming\Cypress\cy\production\projects\cypress-7eb3901bf157c6ad003d43bb347783df\bundles\C:\Users\IEUser\my-project\test-e2e' contains invalid WIN32 path characters.
```

The "C:" repetition inside the path makes it invalid.

### Desired behavior:

Error mentioned above should not be thrown.

#### Possible solution

The problem is located here:
https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/plugins/preprocessor.coffee#L77

When `integrationFolder` option is defined, the `filePath` include both `projectRoot` and `integrationFolder`

replace: 
```js
outputPath: getOutputPath(config, filePath.replace(config.projectRoot, ""))
```
by: 
```js
outputPath: getOutputPath(config, filePath.replace(config.projectRoot, "").replace(config.integrationFolder, ""))
```

### Steps to reproduce:

```sh
cypress open --config=integrationFolder=C:\Users\IEUser\my-project\test-e2e --project=C:\Users\IEUser\another-folder\cypress-project
```

### Versions 
Windows 10
Cypress 2.1

### PR DESCRIPTION
**Pull request by davidbarna**
closes #1704

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Thanks for the contribution! Could you please sign our CLA?

**Comment by jennifer-shehane** [comment]
Hi @davidbarna could you sign our Contributor License Agreement please? Thanks!

**Comment by davidbarna** [comment]
@jennifer-shehane sorry for the delay. Just signed it !

**Comment by davidbarna** [comment]
@jennifer-shehane Hi ! The build `ci/circleci: server-e2e-tests-3` seems to be broken in develop.
Is it blocking my PR to be reviewed?

**Pull request merged**
