### PR TITLE
chore: fix paths for windows

### PR DESCRIPTION
**Pull request by emilyrohrbough**
Thank you @flotwig for noticing I broke windows. OOPS 😅 

broken build: https://app.circleci.com/pipelines/github/cypress-io/cypress/42795/workflows/a549ce5a-eae5-48d6-ace6-060d274f02c3/jobs/1781183

### CODE REVIEW

**Comment by rachelruderman** [comment]
Oopsie daisy! To cover our bases, can you add a link to a passing build with windows? I think you just need to add your branch to `windowsWorkflowFilters` in `circle.yml` and wait for it to build

**Comment by rachelruderman** [comment]
@emilyrohrbough looks like there may be [some tests to look at here](https://dashboard.cypress.io/projects/sehy69/runs/15362/test-results/1c41b6fd-db69-459e-a800-16b2846d7384):
Screen Shot 2022-08-31 at 4 21 53 PM

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Looks like `before:spec` has a legitimate failure: https://app.circleci.com/pipelines/github/cypress-io/cypress/42809/workflows/ff2dd185-cbb0-4e10-a90b-1308eda93064/jobs/1781890, should be a quick one -- code looks fine, will approve.

**Comment by lmiller1990** [comment]
Pushed a quick fix, we cannot use `path.join` for these tests since they run in the browser - surprised these even worked? Also I think `cy.readFile` can work with `/` on windows, it will figure out what to do - most likely it does `path.resolve` under the hood and figures it out depending on the OS.

:crossed_fingers:

**Comment by lmiller1990** [comment]
Ok seems fine now after https://github.com/cypress-io/cypress/pull/23649/commits/389b751c5768b8396e4411f2ccd74aa64b5573e0

@rachelruderman please re-review :pray:

**Comment by rachelruderman** [comment]
@lmiller1990 i think we need to double check the other windows failure, I don’t recognize it as a flaky test so it may be related

**Comment by lmiller1990** [comment]
@rachelruderman I will DM you about this, I am sure it's flake and unrelated to this PR.

**Review by mjhenkes — APPROVED** [review]

**Pull request merged**
