### PR TITLE
Change lodash to caret semver range

### PR DESCRIPTION
**Pull request by karlhorky**
### User facing changelog
Change `lodash` to use caret semver range due to frequent security issues.

### Additional details
This allows consumers to update `lodash` versions to address security issues without using special tools like Yarn Resolutions or npm overrides. Since `lodash` is a volatile package in regards to security updates, this seems like a good tradeoff to make.

This changes the Renovate configuration originally specified by @bahmutov in https://github.com/cypress-io/cypress/pull/2992

Renovate `rangeStrategy` Docs:
https://docs.renovatebot.com/configuration-options/#rangestrategy

### How has the user experience changed?
* Users can update `lodash` without updating `cypress`
* Bots such as Dependabot can do this automatically

### PR Tasks
None applicable.

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-136) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
As noted before, will have to bring this up to discuss with the team, if we want to change this strategy. https://github.com/cypress-io/cypress/issues/7921#issuecomment-655880311

**Comment by karlhorky** [comment]
Ok, I thought this may be something going in the strategy direction.

To provide an example for the discussion, here `wp-calypso` has a `lodash` pull request with `mergeStrategy: 'bump'`:

https://github.com/Automattic/wp-calypso/pull/43928

**Comment by jennifer-shehane** [comment]
@karlhorky Our team has decided that this is a change we would like to make. The body of work is a bit larger than is covered here in this PR, since there are some stickier things with version control going on when we build the binary. So, I've created a new issue to outline the work necessary. https://github.com/cypress-io/cypress/issues/8046 We'll have a new PR to address the full changes, so I'll be closing this one. 

Thanks for bringing this up! I think it helped get the ball rolling on things.

**Comment by karlhorky** [comment]
Thanks for the update @jennifer-shehane, sounds good. Glad to help :)

**Pull request closed without merging**
