### PR TITLE
chore: Fix percy all snapshots are new

### PR DESCRIPTION
**Pull request by dmtrKovalenko**

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Hey, @Bkucera is it a proper way to make new Percy snapshots be combined with the other snapshots during the build?

**Review by elevatebart — APPROVED** [review]
Good !!

**Comment by elevatebart** [comment]
oops, seems to still have 119 Percy changes

**Review by elevatebart — COMMENTED** [review]
that does not look as good as I hoped

**Comment by dmtrKovalenko** [comment]
That is expected. We need to bring them back, for the next PRs base

**Comment by dmtrKovalenko** [comment]
Percy snapshots auto approving when merging so this is the latest approved version of both runner-ct and other snapshots

**Pull request merged**
