### PR TITLE
feat: access to Angular's DI

### LINKED ISSUE #24429: Angular Component Testing: provide access to DI
### What would you like?

Angular's CT `mount` function should return an `inject` function that allows  DI.

e.g.:
```ts
const {inject} = cy.mount(...);
const service = inject(MyService);
```

where `inject` is nothing more than a wrapper of `TestBed.inject` just to hide the implementation detail which is `TesBed`.
we might also provide a `cy.inject` command, that does something like this to provide a better DX:
```ts
cy.then(() => TestBed.inject(...))
```

What do you think?

cc. @jordanpowell88 

### Why is this needed?

As an advocate for fakes (vs. stubs/spies/mocks), I often end up with stateful services that I might want to access & check manually afterward in my test. But of course, there are way many other use cases like arranging the test etc...

```ts
cy.mount(MyComponent, {providers: [{provide: Cart, useClass: CartFake}]})

cy.contains('Buy').click()

cy.inject(CartFake).invoke('getItems').should('have.length', 1);
```

or

```ts
const { inject } = cy.mount(MyComponent, {providers: [{provide: Cart, useClass: CartFake}]})

cy.contains('Buy').click()

cy.then(() => inject(CartFake).getItems()).should('have.length', 1);
```

cc. @jordanpowell88

### PR DESCRIPTION
**Pull request by rainerhahnekamp**
- Closes #24429

### User facing changelog

Add the possibility to access Angular's DI with the new command `cy.inject`.

### Additional details

Sometimes, we need to run our assertions on an Angular service. This feature integrate Angular's DI into Cypress.

### Steps to test
inject.cy.ts contains the tests and demonstrates the typical use case.

### How has the user experience changed?
Cypress' testing scope in Angular will increase.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by rainerhahnekamp** [comment]
@jordanpowell88 @ZachJW34 

I'm leaving that to you. If something is missing, please let me know. 

Cheers

**Comment by ZachJW34** [comment]
I'm leaning toward having this recipe in the docs rather than a first class API. I think we would need to expand and add more functionality for us to bring this in. One concern I have is the usage of observables, not sure how `cy.inject(Cart).invoke('getItems').should('have.length', 0)` would look if `getItems()` returned an observable. 

We are also exploring having all Angular unit tests exist within CT as well, which would involve users getting familiar with utilizing the `TestBed` methods (like explicitly calling `TestBed.configureTestingModule({...})` if they are testing a service.

**Comment by rainerhahnekamp** [comment]
Hi @ZachJW34, I share your concern about pulling in all the Angular testing tools into the Cypress API. It shouldn't be that way, or it has to be thought about very carefully.

Let me explain the use case: In an E2E test, when my users click on the buy button, there would be some basket component in the header where I can visually assert that it increases its count. With component testing, though, that basket is missing. The only way I can assert is to directly go against the service.

I think that this scenario is so common that it supports a dedicated inject command.

For Observables and similar cases, you can always provide a function in the `should` method.

---

Maybe @yjaaidi can also share his version of the story ;). In the end, he created the original issue #24429

---

Either way, it is up to you. I just wanted to make sure you understand the use case :)

Cheers!

**Comment by ZachJW34** [comment]
I like the use case and think this could be documented in a recipes section of the docs for Angular if you're interested in contributing to the docs. Going to close for now but appreciate the work!

**Comment by muhamedkarajic** [comment]
I don't see that cypress added the inject keyword in the latest version?

**Comment by rainerhahnekamp** [comment]
@muhamedkarajic 

Yup, there will be no `cy.inject` for the time being. You can create your own command, though:

```typescript
import { mount, inject } from 'cypress/angular'

declare global {
  namespace Cypress {
    interface Chainable {
      mount: typeof mount
      inject: typeof inject
    }
  }
}

Cypress.Commands.add('mount', mount)
Cypress.Commands.add('inject', (token: ProviderToken<T>): Cypress.Chainable<T> => 
  cy.wrap(TestBed.inject(token))
);
```

That should do it. Let me know, if you encounter some issues with that.

**Comment by muhamedkarajic** [comment]
@rainerhahnekamp I owe you one, thank you so much. My first day in cypress turned out to be a success after all :)

**Comment by muhamedkarajic** [comment]
Edited.

@rainerhahnekamp I would be interested in your oppinion how to use the setup properly:
E.g.
```typescript
cy.mount(TableComponent).then(env => {
    cy.inject(ResponseService).then(responseService => {
        // click some button
        const fakeResponse =  {};
        responseService.response(fakeResponse);        
    })
```

Also I had an error:
```typescript
zone-testing.js is needed for the fakeAsync() test helper but could not be found. 
Please make sure that your environment includes zone.js/testing.
Because this error occurred during a before each hook we are skipping all of the remaining tests.
```
Fixed by going to command.ts and including:
`import 'zone.js/testing';`
However now I'm wondering if I have to configure something differently cause intelisence isnt catching the TestBed in the command.ts. Using Nx setup with Angular v15.

**Comment by jordanpowell88** [comment]
Just an FYI, we are working on providing a more official and ergonomic solution for testing Angular Services with CT soon in https://github.com/cypress-io/cypress/issues/26243

**Comment by tobmaster** [comment]
@jordanpowell88 I think the ticket you referring to is a bit too focussed on ng services. I have other cases as well where I would like to have access to DI. 
One prominent one is state managment, where I may want to not only set an initial store (that i might be able to inject via imports/providers) but also simulate state changes over time (dispatching new actions that result in a new state).
It probably can be done by #26243 too but should be directly planned in.

You might argue that UI components should not know the app state directly. But reality shows people are doing it and we should be able to test it.

**Comment by jordanpowell88** [comment]
That's understandable. You still have full access to `TestBed` directly in your tests to handle situations like this. What are you proposing?

**Comment by tobmaster** [comment]
But then it comes just magically out of the scope and it comes with a lot more than just the inject.

**Comment by jordanpowell88** [comment]
@tobmaster to be clear we are working a solution (probably what @rainerhahnekamp proposed) that would just handle injecting the service (either in a component or a service).  What we are exploring is what is an additional step we can take to improve DX and ergonomics for those testing Angular Services that expands beyond a `cy.inject()` function

**Comment by rainerhahnekamp** [comment]
@jordanpowell88, just to be sure: did you mean to say "...we are NOT working on a solution..." or are you actually working on a solution similar to mine?

Because your last sentence kind of indicates that you are looking for a more general approach than just targeting the DI in Angular.

**Comment by jordanpowell88** [comment]
It is still up in the air. But I feel pretty confident we will expose something like the `inject` function you created. However, we are doing a SPIKE into additional ways we can make service testing in Angular easier.

**Pull request closed without merging**
