### PR TITLE
Read additional optional GH actions environment variables

### LINKED ISSUE #6450: Re-running failed workflow in GitHub Actions does not generate new Dashboard run
Cypress v4

- if you run Cypress using GH Actions and record to the dashboard AND a test fails, and you hit "re-run checks", we don't get a new workflow run id. Instead we use same commit SHA and workflow name, which causes the error on the Dashboad "run already finished".

As a workaround, we suggest pushing an empty commit to trigger new check with different SHA.

We should detect the re-run better somehow.

### PR DESCRIPTION
**Pull request by estrada9166**
- Closes #6450

### User facing changelog
This PR updates the env vars that we can get from GH actions to get the correct branch and also the run id making possible to build the correct url to the GitHub job.

### Additional details

When re-running checks in GH Actions we need to create a new run. This change reads optional variables set by [cypress-io/github-action v1.21.0](https://github.com/cypress-io/github-action/releases/tag/v1.21.0) after querying the GH API. The read values if available will be passed to the Dashboard where they can used to create a unique run id, even if checks are re-run.

### How has the user experience changed?

User should be able to re-run checks in GH Actions if using `cypress-io/github-action@v1`

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Review by bahmutov — CHANGES_REQUESTED** [review]
add 1 more test, since you have added an OR condition `branch: env.GH_BRANCH || env.GITHUB_REF` - but the existing test only confirms the github ref

**Review by bahmutov — APPROVED** [review]
super

**Comment by jennifer-shehane** [comment]
@estrada9166 You mention:

>This PR is blocked by changes on the Cypress Github action and on the dashboard.

If this is not ready to be merged in, I suggest added `[WIP]` to the title otherwise someone may merge this in not seeing this note.

**Comment by estrada9166** [comment]
@jennifer-shehane sorry, I didn't remove that note, it's ready to merge

**Review by bahmutov — APPROVED** [review]
nice, tests added

**Pull request merged**
