### PR TITLE
User-provided options immutability.

### LINKED ISSUE #3171: Clone command options before passing into commands
### Current behavior:

When commands receive options, it is the original object and not a clone. This has resulted in a few bugs (#2707, #365), and probably some more I couldn't quickly track down.

### Desired behavior:

This should be done before options are passed into commands so all commands receive options in the same frozen state.

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #3171

Breaking down #5762 into 3 PRs.

### User facing changelog

* Clone `options` object so that they're not mutated by the `cy` commands.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by sainthkh** [comment]
Failed because of a flaky test.

**Comment by sainthkh** [comment]
I created #6459 and am waiting for review and merge.

**Comment by Bkucera** [comment]
fixed some small issues I saw, trying to get this in

**Comment by sainthkh** [comment]
@jennifer-shehane It's waiting to be merged.

**Pull request merged**
