### PR TITLE
fix: Cleanup RunStatusDots component

### LINKED ISSUE #22629: RunStatusDots refactor
### Current behavior

runs.values.length === 1 is confusing 

### Desired behavior

_No response_

### Test code to reproduce

NOne

### Cypress Version

10.3.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by mike-plummer**
- Closes #22629 , #22598 

### User facing changelog
* Styling fixes to "Latest Runs" tooltip to keep it centered over the latest run entry

### Additional details
* Logic cleanup - conditional that wraps a for loop wasn't being as restrictive as it could be

### Steps to test
1. Open a project with cloud recordings in the app, ensure you're logged in so that Latest Run data is loaded
2. In Specs Explorer, verify that mousing over Latest Runs data opens tooltip and that tooltip arrow is centered on the latest run status icon
3. Verify that status is reflected for prior runs in latest runs "dots"

### How has the user experience changed?
**Before** - tooltip arrow is _ever so slightly_ off center to the left
before

**After** - tooltip arrow is perfect and amazing
after

### PR Tasks
- [x] Have tests been added/updated? _Covered by Percy_
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by tbiethman** [comment]
Screen Shot 2022-07-14 at 9 56 49 AM

It looks like the tooltip is off-center for the success svg now. These svgs must be filling their 16px slightly differently?

**Comment by mike-plummer** [comment]
> It looks like the tooltip is off-center for the success svg now. These svgs must be filling their 16px slightly differently?

@tbiethman Hmm, it looks good on my local (M1, chrome (latest)). Are you on a different browser?

One other possibility: the "Passed" icon is inherently a little deceiving since the point of the checkmark isn't horizontally centered within the circle. I manually tweaked the SVG to add a centering crosshair so I could ensure it wasn't some unconscious bias. Is it obviously off-center if you add this to `passed-solid_x16.svg` and reopen the app?

```
<line x1="8" y1="0" x2="8" y2="16" style="stroke:red; stroke-width:0.2;" />
<line x1="0" y1="8" x2="16" y2="8" style="stroke:red; stroke-width:0.2;" />
```

|   |   |   |
| --- | --- | --- |
| Screen Shot 2022-07-14 at 12 10 46 PM  |  Screen Shot 2022-07-14 at 12 12 39 PM |  Screen Shot 2022-07-14 at 12 11 56 PM |

**Review by tbiethman — APPROVED** [review]

**Comment by mike-plummer** [comment]
@tbiethman Yeah, ideally we would just have the latest run be the tooltip target which would make the centering happen automatically, but Product wants the entire set of runs (all four) in the hitbox which means we have to do this manual shifting. I'm not sure there's a reliable way to make it perfect at all zoom levels, but at least now it's the same alignment (and a bit closer to center) for all of our different status icons

**Review by marktnoonan — APPROVED** [review]
LGTM

**Pull request merged**
