### PR TITLE
feat: change cy.intercept override behavior

### LINKED ISSUE #7788: Implement response middleware pattern for net-stubbing
### Current behavior:
Request handlers can be chained:

```ts
req.reply(async (req) => {
	const foo = await something()
	req.headers['x-foo'] = foo
})

req.reply((req) => {
	// more req handling...
})
```

There is not yet a similar system for response handler chaining.

### Desired behavior:
1. Decide if response handler chaining can make sense, and what the rules would be for chaining.
1. Implement an API similar to the req.reply chaining API for res.send.

### LINKED ISSUE #9302: [Cypress 6.0.0] Overriding interceptors doesn't work.
### Current behavior
With Version <6.0.0, if you used `c.route` with a stub, you could then use it again with a new stub and it would take the second fixture for the second request.

With version >6.0.0 It doesn't happen, the override doesn't work with `cy.intercept` and it always returns the initial fixture.

```typescript
cy.intercept(
  {
     method: 'GET',
     url: 'items',
  },
   { fixture: 'items/empty-list.json' }
);

// Some more testing of the app, and then fetching again -

cy.intercept(
  {
     method: 'GET',
     url: 'items',
  },
   { fixture: 'items/list-1.json' }
);
```

The use case is very simple. 
Imagine my app loads with 0 items, using a GET.
Then, I do some stuff, do a POST, and then GET those items again.
I want to stub it with `[item]`, instead of the initial `[]`.

So what happens is that it always return `[]`, not `[item]` as it used to. 
I'm quite sure it's not a problem with my code, used to work perfectly fine till today.

The first image is the initial intercept, you can see it gets `2`
image
The second image is what is shown for the second GET, the one that should've matched and return `[item]`
image

### Desired behavior
I want to be able to override interceptors

### LINKED ISSUE #15209: cy.intercept / force404
Cypress should allow disabling forwarding of requests which are unmatched with cy.intercept.

This will prevent unwanted latency and make it easier to spot missing stubs. This used to be supported with cy.server(). 

Related to:

https://github.com/cypress-io/cypress/issues/9358#issuecomment-750231567
https://github.com/cypress-io/cypress/issues/9302

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #9302
- Closes #7788
- Closes #15209

### User facing changelog

- BREAKING CHANGE: Request handlers supplied to `cy.intercept` are now matched starting with the most-recently-defined request interceptor. This allows users to override request handlers by calling `cy.intercept` again. This matches the previous behavior that was standard in `cy.route`.
- There are now new events on the `req` object for `cy.intercept`: `before:response`, `response`, `after:response`.
- Response handlers (supplied via event handlers or via `req.continue(cb)`) supplied to `cy.intercept` will be called in reverse order until `res.send` is called or until there are no more response handlers. 
- A new option, `middleware`, has been added to the `RouteMatcher` type. If `true`, the supplied request handler will be called before any non-middleware request handlers.
- A new function, `req.continue(cb)`, is available on request objects yielded by `cy.intercept`. It is functionally the same as `req.reply(cb)` - the request will stop propagating to other event handlers, will be sent outgoing, and the response will be handled by `cb`.
- `cy.intercept` can now be called with a new overload: `cy.intercept(url, routeMatcher, handler)`. `routeMatcher` will be merged with `url`, and the handler is required.
- Fixed an issue where the `response.body` would be incorrect after stubbing a response using `res.send({ fixture })` in a `req.continue` callback or a `before:response` or `response` handler.

### Additional details

See changes to `net_stubbing_spec` for new + updated tests.

### How has the user experience changed?

* New `RouteMatcher` option: `middleware: boolean`
    * Handlers with `middleware: true` will be called in the order they are defined and chained.
    * With `middleware: true`, only dynamic handlers are supported - makes no sense to support `cy.intercept({ middleware: true }, staticResponse)`
* `req` now emits events (regardless of `middleware` setting)
* Events on `req`: https://github.com/cypress-io/cypress/blob/762d6eb22d27e371e3d004bac76543800b236640/packages/net-stubbing/lib/external-types.ts#L207-L226
* `req.continue(cb)` has been added. `req.reply(cb)` still works.
* A third overload of `cy.intercept` has been added, to allow users to more easily do things like `cy.intercept('/url', { middleware: true }, ...)` to set middleware, etc: https://github.com/cypress-io/cypress/blob/042050c460a16293fd707d362eeb7bce68f3e268/packages/net-stubbing/lib/external-types.ts#L459-L470

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/3715
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by kevinold** [comment]
@flotwig I think I have found a regression with this patch against the RWA with request modifications not being honored in some way.

In v6.6.0, when I remove the `if-none-match` header from a request (https://github.com/cypress-io/cypress-realworld-app/pull/676/files#diff-553f62c7d670ed3411a618d14b703ed95485dac575be4993025c3d263d099751R16-R18)
```js
cy.intercept("GET", "/notifications", (req) => {
  delete req.headers["if-none-match"];
}).as("getNotifications");
```

Subsequent `cy.wait`'s do not return a `304` from the endpoint

Screen Shot 2021-03-12 at 11 02 11 AM


Under this branch, the response is `304` instead of the results:

Screen Shot 2021-03-12 at 11 11 13 AM

**Comment by kevinold** [comment]
As of commit, https://github.com/cypress-io/cypress/pull/14543/commits/c52133c9aa0507b8870e19d1b5af6a3498a9af02
Screen Shot 2021-03-12 at 1 40 09 PM
 it broke this regular intercept for loginUser https://github.com/cypress-io/cypress-realworld-app/pull/676/files#diff-6c107e2390c5ad84e123f3be09d7b91ba35de8f8cc550d1f358c75806df47645R140-R148

**Review by chrisbreiding — APPROVED** [review]
LGTM 👍

**Comment by flotwig** [comment]
The 2 failing stages are currently failing in 7.0-release as well, merging.

**Pull request merged**
