### PR TITLE
Replace hardcoded "/" in getPrefixedPathToSpec

### LINKED ISSUE #2692: specUrl will not be properly formed due to hardcoded `/`
### Current behavior:

When launching Cypress from Windows, the specUrl will not be properly formed due to hardcoded `/`

Honestly, I'm not sure what impact this is having on Windows users. I have seen several issues with Windows and paths though.

### Desired behavior:

Use `path.sep` instead of `/` to use correct OS path separator

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- add unit tests for getPrefixedPathToSpec
- remove unused “agent” import from spec-helpers
- close #2692 

This unit test is failing, I thought that updating the "/" to path.sep would resolve the path correctly for Windows paths, but it doesn't seem to be. 

```
#getPrefixedPathToSpec
      ✓ prefixed path to spec
      x) prefixed path to spec for Windows path
```

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
This unit test is failing, I thought that updating the "/" to path.sep would resolve the path correctly for Windows paths, but it doesn't seem to be. 

```
#getPrefixedPathToSpec
      ✓ prefixed path to spec
      x) prefixed path to spec for Windows path
```

**Comment by brian-mann** [comment]
The unit test is failing because `path.sep` is still `/` in OSX + linux, which is where the tests will run, which don't match what you passed into the test.

**Comment by chrisbreiding** [comment]
Also, that [path.sep](https://github.com/cypress-io/cypress/blob/1ce35c6f30081b6a6f2b974232be34c07f1fb6aa/packages/server/lib/project.coffee#L384) gets replaced [when it gets passed](https://github.com/cypress-io/cypress/blob/1ce35c6f30081b6a6f2b974232be34c07f1fb6aa/packages/server/lib/project.coffee#L368) to [this function that joins with "/"](https://github.com/cypress-io/cypress/blob/1ce35c6f30081b6a6f2b974232be34c07f1fb6aa/packages/server/lib/project.coffee#L389)

**Comment by chrisbreiding** [comment]
Are there specific user issues this addresses? Is https://github.com/cypress-io/cypress/issues/2678 one of them? I don't think this area of the code is related to that issue as this code is 'normalizing' the url for the browser, and isn't the spec path sent to the API from what I can tell. 

Ideally, we need a test that reproduces the issue users are having to make sure we're solving the right problem.

**Comment by jennifer-shehane** [comment]
Yeah #2678 may be one of them. I'm not sure why the spec path would be passed in that way with the `//` if the specUrl is working completely as intended. 

But yeah, I have not reproduced this myself. It seems possibly related to Windows and even possibly related to Git Bash in Windows?

But also, maybe this PR fixes #2678 already https://github.com/cypress-io/cypress/pull/2400/files#diff-6529739171e5d780651fc627e0217629

Feel free to close if you think this is insufficient.

**Comment by jennifer-shehane** [comment]
@chrisbreiding Should we just close this issue then?

**Comment by chrisbreiding** [comment]
Yeah, might as well. I think it needs a bit more work.

**Pull request closed without merging**
