### PR TITLE
Decaff helper jscodemods.

### PR DESCRIPTION
**Pull request by sainthkh**
- Part of #2690

### User facing changelog

N/A

#### Why was this change necessary?

To decaff faster by doing repetitive and error-prone things with code. 

#### What is affected by this change?

* `jest` is added to dependency as `jscodeshift` only provides jest test utils. 
* 6 more steps are added. Details are below.

#### Any implementation details to explain?

N/A

### How has the developer experience changed?

6 more steps are added to decaff process. 

#### 1\. Remove sharp comment.

`//#` -> `//`

CoffeeScript:
```coffee
## This is a comment
```

Decaffeinated:
```js
//# This is a comment
```

After this PR:
```js
// This is a comment
```

#### 2\. Add eslint-disable-line to empty catch

CoffeeScript
```coffee
try
  # Do something
```
Decaffeinated:
```js
try {
  // Do something
} catch (e) {}
```

After this PR:
```js
try {
  // Do something
} catch (e) {} // eslint-disable-line no-empty
```

#### 3\. switch (false) -> if-else

CoffeeScript:
```coffee
switch
  when a.isGood:
    it.shouldBeDone()
    break
  when !b.isBad():
    it.checksOK()
    break
```

Decaffeinated:
```js
switch(false) {
  case !a.isGood:
    it.shouldBeDone()
    break
  case b.isBad():
    it.checksOK()
    break
}
```

After this PR:
```js
if (a.isGood) {
  it.shouldBeDone()
} else if (!b.isBad()) {
  it.checksOK()
}
```

Note: As we all know, `switch (false)` is rarely used in human-written code. And the conversion process is really tedious and error-prone by hand because conditions are reversed. 

That's why I've created this mod to fix this easier and in more human-friendly way. 

#### 4\. Remove comment between arrow and block

CoffeeScript:
```coffee
reduceMemory = (attrs) ->
  ## comment
  attrs.doSomething()
```

Decaffeinated:
```js
const reduceMemory = (attrs) =>
// comment
{
  attrs.doSomething()
}
```

After this PR:
```js
// comment
const reduceMemory = (attrs) =>
{
  attrs.doSomething()
}
```

Note: Moving `{` up next to => will be done by eslint. 

#### 5\. no-cond-assign

CoffeeScript:
```coffee
if a = c()
  doSomething()
```

Decaffeinated:
```js
let a

if (a = c()) {
  doSomething()
}
```

After this PR:
```js
let a

a = c();
if (a) {
  doSomething()
}
```

#### 6\. test functions should not return.

This is reverted because mocha `it` function can return promise. 

### PR Tasks

- [x] Have tests been added/updated?
- ~~Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? ~~
- ~~Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?~~
- ~~Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?~~

### CODE REVIEW

**Comment by sainthkh** [comment]
Failed because of a flaky test.

**Comment by jennifer-shehane** [comment]
Very cool. The first 2 are great, the last one scares me a little 😅 - will get @Bkucera to look over since he's been heading up the decaff process.

**Comment by sainthkh** [comment]
Added 2 more codemods.

**Comment by Bkucera** [comment]
@sainthkh wow, this is awesome. I'll pull this down and try it out.

**Comment by sainthkh** [comment]
It would be better to add these unit tests to CI.

**Comment by sainthkh** [comment]
I realized that `packages/server` doesn't set up `webpack` yet. So, `exportify` and `require` -> `import` don't work properly.

**Comment by Bkucera** [comment]
still need to try this locally

**Comment by Bkucera** [comment]
added small fix for errors I encountered during a decaf

**Comment by Bkucera** [comment]
going to push this as a separate PR so we can have parallel tests

**Comment by Bkucera** [comment]
Going to keep a running list of minor issues I found with these codemods:

- no-cond-assign: does not account for `return` if last statement:
**current:**
_coffee_
```coffeescript
getBar = () ->
  if foo = getFoo()
    bar = 'bar'
myBar = getBar()
```
_js_
notice how `bar` is not returned
```js
const getBar = () => {
  let foo
  foo = getBar()
  if (foo) {
    const bar = 'bar'
  }
}
const myBar = getBar()
```
**desired:**
```js
const getBar = () => {
  let foo
  foo = getBar()
  if (foo) {
    const bar = 'bar'
    return bar
  }
}
const myBar = getBar()
```

**Comment by sainthkh** [comment]
@Bkucera After a little bit of investigation, I found out that that removing `return` problem came from `fix-implicit-return-assignment`. 

It has nothing to do with this PR.

**Without helpers in this PR**
```js
const getBar = function () {
  let foo

  if (foo = getFoo()) {
    let bar

    bar = 'bar'
  }
}
const myBar = getBar()
```

**Without `fix-implicit-return-assignment`**
```js
const getBar = function () {
  let foo

  if (foo = getFoo()) {
    let bar

    return bar = 'bar'
  }
}
const myBar = getBar()
```

**Comment by Bkucera** [comment]
thanks @sainthkh! I think it's fine to leave as is, I'll open an issue with the decaffeinate folks. 

This also happened while decaffeinating, I can confirm this time it doesn't happen after commenting out the no-cond-assign codemod
 
image

**Pull request merged**
