### PR TITLE
Update <head> element regex to avoid testing positive on <header> elements

### LINKED ISSUE #2026: When visiting a page with <header> but not <head>, Cypress injects incorrectly
The following HTML response fails to inject correctly:

```html
<html> <body><nav>some nav</nav><header>header</header></body> </html>
```

### PR DESCRIPTION
**Pull request by distracteddev**
This was breaking the app I was trying to test since the app code was not expecting a randomly inserted text node within the header element. 

Happy to add tests or anything else if needed.

Fixes #2026

### CODE REVIEW

**Comment by Bkucera** [comment]
@distracteddev thanks! Could you add a small unit test for this?

**Comment by distracteddev** [comment]
@Bkucera Done! I didn't see anything in the contribution guidelines about coffeelint, but I tried to mimic the coffee styles I saw elsewhere in the project.

Off topic, but curious what method y'all are using to populate the magical `root` global variable.

**Comment by brian-mann** [comment]
Also - not a big deal, I will open an issue, but we like to have all PR's connected to an existing issue so it can be milestoned and tracked. In that issue it should be explained how to demonstrate/reproduce the bug.

**Comment by brian-mann** [comment]
After taking a second look at this - I actually agree with your approach to unit test this.... but since all of the functionality is already covered in `http_requests_spec` I'm still going to remove the unit tests.

Since the `rewriter.coffee` module does not deal with streams it would be a good candidate for unit tests, but we generally opt for higher up tests that offer higher coverage and better self documenting functionality when its behavior is part of a more complex system.

**Comment by bahmutov** [comment]
Can you leave an empty unit test spec file that just explains that this should be tested higher up?

**Comment by distracteddev** [comment]
No worries! Thanks for taking the time to review and pick this up. No rush, but curious what the release cadence is like for these kinds of bug fixes? Apologies if this is already outlined somewhere and I missed it.

**Comment by brian-mann** [comment]
Our release cycle is best described by the [Cicada](https://en.wikipedia.org/wiki/Cicada). Sometimes dormant underground for long periods of time, and then its hatching season and becomes rapid and explosive.

We're shooting for every couple weeks but really it just depends on the severity of the bugs, how close we are to fixing other bugs, or getting out new features, etc. Releases still have a lot of manual effort that ends up being "loss" and so we try to minimize those as much as we can and chunk together as many things as we can per release.

**Comment by brian-mann** [comment]
For instance, a release Monday and a release Tuesday will account for greater loss and less efficiency than a release Tuesday containing the same fixes from Monday.

But there's obviously a limit to that, and waiting too long to release fixes ends up creating more work and loss in aggregate from all the people running up against those problems. So yeah, a two week cycle wouldn't be bad. A one week cycle would be even better.

**Pull request merged**
