### PR TITLE
chore: Add CircleCI job to test projects from cypress-component-testing-examples

### PR DESCRIPTION
**Pull request by kevinold**
- [x] Define new `test-binary-against-repo-folder` CircleCI job

CI jobs to validate v10 release against 

- https://github.com/cypress-io/cypress-component-testing-examples/tree/10.0.0
- [CRA + Tailwind with Cypress v10 by kevinold · Pull Request #79 · cypress-io/cypress-component-testing-examples](https://github.com/cypress-io/cypress-component-testing-examples/pull/79)
- [vue-cli-2 app + quasar UI with Cypress 10 by robertguss · Pull Request #87 · cypress-io/cypress-component-testing-examples](https://github.com/cypress-io/cypress-component-testing-examples/pull/87)
- [CRA + Ant Design with Cypress 10 by robertguss · Pull Request #85 · cypress-io/cypress-component-testing-examples](https://github.com/cypress-io/cypress-component-testing-examples/pull/85)
- [CRA + react-bootstrap with Cypress 10 by robertguss · Pull Request #84 · cypress-io/cypress-component-testing-examples](https://github.com/cypress-io/cypress-component-testing-examples/pull/84)
- [CRA + Chakra UI with Cypress 10 by robertguss · Pull Request #83 · cypress-io/cypress-component-testing-examples](https://github.com/cypress-io/cypress-component-testing-examples/pull/83)

- Closes 

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@kevinold Let me know if you need anything from our team to get this merged.

**Comment by kevinold** [comment]
@jennifer-shehane I will bring this branch up to date this morning and it is ready to merge.  Feel free to merge as your team is ready.

**Review by amirrustam — DISMISSED** [review]

**Comment by kevinold** [comment]
@jennifer-shehane @flotwig @amirrustam  In bringing this branch up to date with `10.0-release`, I'm running into the following eslint fixes that need to be applied.  Outside of that, this branch is ready to merge and our CT Example PR's are accurately passing/failing.

Screen Shot 2022-02-14 at 11 47 05 AM

**Comment by kevinold** [comment]
@jennifer-shehane @flotwig @amir Disregard my previous comment, I was able to get the latest merged into this branch.

This PR is ready for merge.

https://github.com/cypress-io/cypress/pull/19923#issuecomment-1039378719

**Comment by flotwig** [comment]
@kevinold is this ready for review? It looks like the jobs added are failing.

**Comment by kevinold** [comment]
@flotwig The v10 binary isn't loading from the CDN for those jobs.  See the failing part of any of those jobs.  Any ideas how to resolve?

**Comment by flotwig** [comment]
@kevinold is it older than 31 days? The retention policy on the `beta` folder is 31 days. Could try bumping it to a newer .zip.

**Comment by kevinold** [comment]
@flotwig I update the other PR's with a newer binary but isn't the binary built for this branch what those jobs are/should be using?  Especially since it is listed here: https://github.com/cypress-io/cypress/pull/19923/files#diff-21b1fe66043572c76c549a4fc5f186e9a69c330b186fc91116b9b70a4d047902R38

**Comment by flotwig** [comment]
@kevinold The job seems to work by cloning the remote branch, doing `npm install` or `yarn`, and then doing `npm install https://cdn.cypress.io/beta/npm/10.0.0/linux-x64/circle-10.0-release-9cad97a3c838733dd8d8768cd972b0b1204f2ed8/cypress.tgz`. So both have to exist for it to work.

**Comment by kevinold** [comment]
@flotwig @jennifer-shehane @baus The failure for the `test-binary-against-cy-ct-examples-cra-ant-design` job is a valid failure for component testing and was tracked in https://cypress-io.atlassian.net/browse/UNIFY-940 (which was closed) and is now being tracked in https://github.com/cypress-io/cypress/issues/20341

**Comment by flotwig** [comment]
@kevinold can you create a new PR to add that test, since it's currently failing, and remove it from this PR? I'd prefer to not merge failing tests into 10.0-release, right now we are aiming for green builds in that branch.

**Comment by kevinold** [comment]
> @kevinold can you create a new PR to add that test, since it's currently failing, and remove it from this PR? I'd prefer to not merge failing tests into 10.0-release, right now we are aiming for green builds in that branch.

@flotwig Yes, but I have another caution before we merge this PR.  The jobs added in this PR use a binary that will expire from the CDN in 30 days if I understand correctly.  This means that in 29 days we need to go and update all of these (and more, if added) to keep things green.  We might consider holding this PR until we have non-expiring binaries we could depend on to eliminate false negatives.

**Comment by jennifer-shehane** [comment]
We decided against merging these repos to be testing in the Cypress App.

**Pull request closed without merging**
