### PR TITLE
Clone setCookie options instead of mutating

### LINKED ISSUE #2701: cy.setCookie always sets the same cookie if you pass the same options object
`cy.setCookie` always sets the same cookie if you pass the same options object.

### Current behavior:

Calling `cy.setCookie` multiple times always sets the same cookie as the first call if you pass the same options object each time. For example, the following sets two cookies named "foo" and "baz". 

```js
'use strict';
  
Cypress.Cookies.debug(true);

const options = {};

describe('cookie reuse', function() {
    it('sets the expected cookie', function() {
        cy.setCookie('foo', 'bar', options);
        cy.setCookie('baz', 'qux', {});
        cy.setCookie('apple', 'banana', options);

        cy.getCookie('foo').its('value').should('equal', 'bar');
        cy.getCookie('baz').its('value').should('equal', 'qux');
        cy.getCookie('apple').its('value').should('equal', 'banana');
    });
});
```

The Cypress log shows the names and values of all three cookies I tried to create, but the console shows that only two cookies were created:

setcookie-always-sets-same-cookie-when-options-object-is-the-same

The cookies section in the Chrome dev tools also shows only two cookies, "foo" and "baz":

setcookie-cookies-list

The "apple" cookie was never created. The call to `cy.setCookie('apple', 'banana', options);` just set the "foo" cookie again.

### Desired behavior:

If I call `cy.setCookie` twice with different cookie names and values, but use the same options object in both calls, I expect to create two separate cookies.

### Steps to reproduce:

See code snippet above.

### Versions

Cypress 3.0.3, Mac OS 10.13.6, Chrome 70.0.3538.77

### PR DESCRIPTION
**Pull request by lilaconlee**
- Fixes #2701

### CODE REVIEW

**Comment by brian-mann** [comment]
So - this is totally all 👍 but as I mentioned to @jennifer-shehane 	this is not actually the first issue related to this problem - there are other issues open for this (that i'd have to dig out).

I remember one being about `Object.freeze` - and there are likely others. The better approach here would be to fix this problem in a single place so that all options received by the commands are actually **already** cloned - and that cloning them per command is not necessary.

I'll keep this PR open, but won't merge it until more discussion happens and if there's an easy way to fix these in 1 shot I'd prefer it.

**Comment by jennifer-shehane** [comment]
I think that this should be merged in today. Regardless - I do agree with brian in this being a larger issue that should be opened and investigated.

**Comment by jennifer-shehane** [comment]
Hey @brian-mann, can we merge this fix in? 

Also, @lilaconlee, can you open an issue to address the larger issues brian referenced in his comment above?

**Comment by lilaconlee** [comment]
I think if we wanted to merge this in, we'd want to reset it to a previous commit. I tried solving the problem earlier in the process as Brian suggested, but couldn't quite get it.

I'll reset to that commit and make the new issue.

**Pull request merged**
