### PR TITLE
Add a local filter for specs by displayName

### PR DESCRIPTION
**Pull request by marceloemanoel**
This pull request adds the functionality of filtering the specs by display name.

### CODE REVIEW

**Comment by marceloemanoel** [comment]
Thank you @jennifer-shehane. At first, I didn't find them, but now I know where and what to change. I'm working on fixing the broken tests and adding new ones. I'll send the updates tonight.

**Comment by marceloemanoel** [comment]
Hey, @jennifer-shehane could you review it again?

**Comment by jennifer-shehane** [comment]
Thanks for the work. I have looked through the project and made some style fixes. It functionally works great. 👍  

This is what the filter/search of specs currently looks like:

screen shot 2017-12-12 at 12 27 41 pm

**Ultimately, after getting feedback from the team, we'd like more changes made before merging this in, specifically:**
- The search bar feels too prominent. We don't feel like this is a feature that would be used by the majority of our current user base. Because of this, we'd like the search bar to maybe only display after clicking a 'search' icon. Something that takes up less space in the Desktop.

**Comment by brian-mann** [comment]
Yes, either hide the search behind an explicit click - or just "mute" the background, by removing the white input, and simply let the search be the same color as the background, maybe with a bottom border to indicate it's typable. That would at least make it much less prominent.

Maybe something like this...

https://codropspz-tympanus.netdna-ssl.com/codrops/wp-content/uploads/2015/01/TextInputEffects_Haruki.png

Or this...

https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3andXbVU3QUw1NjQ/patterns-errors-userinput3.png

**Comment by marceloemanoel** [comment]
Is it ok like this?

Without focus:
screen shot 2017-12-12 at 19 32 43

With focus:
screen shot 2017-12-12 at 19 32 50

**Comment by marceloemanoel** [comment]
@jennifer-shehane @brian-mann  is this what you're looking for? If so, I can push it. If you want other changes I can do it. I'd really want this feature, our suite has more than 50 specs and it's becoming difficult to find them manually.

**Comment by brian-mann** [comment]
We'll try to look at this today, thx.

**Comment by jennifer-shehane** [comment]
@marceloemanoel Sorry, yes, please commit the changes above with the styling?

**Comment by jennifer-shehane** [comment]
@marceloemanoel nevermind, I went ahead and made the visual changes. Sorry for the delay on review, but it should be going out here soon.

**Comment by jennifer-shehane** [comment]
Close https://github.com/cypress-io/cypress/issues/1098

**Comment by marceloemanoel** [comment]
Thanks!

**Pull request merged**
