### PR TITLE
fix(ui): display duplicate aliases in command log

### LINKED ISSUE #9588: Cy intercept needs to provide more information in the command log
Using Cypress v6.1.0 as described in https://glebbahmutov.com/blog/cypress-intercept-problems/

- if several interceptors match the request, only the first one is in the badge, while the count shows the number of interceptors. We should show all matched interceptors' alias names

badge

In the above picture, two interceptors matched, but we only know the name of the very first one

- the interceptors do not show if the matcher spied or stubbed the network request. We no longer show `(XHR)` vs `(XHR STUB)` in the command log, thus we don't know if the request continued or not

stub

### PR DESCRIPTION
**Pull request by flotwig**
- Partially addresses #9588

### User facing changelog

- Improved the way that `cy.intercept()` and `cy.route()` requests with multiple aliases are displayed in the command log.

### How has the user experience changed?

The aliases are now displayed in one line (ignore the lack of badge background, this is just a test):

image

But the list can still be expanded, in which case it's unjoined:

image

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — COMMENTED** [review]
Why don't the tests have the proper classes for the display? 

**Inside test**

Screen Shot 2021-05-07 at 8 41 59 AM


**Outside test**

Screen Shot 2021-05-07 at 8 42 37 AM

I feel like this should reflect reality.

Anyway, I fixed the css so that: 

- the weird circular alias shouldn't show anymore.
- there is a max width on the matched aliases because it was really gnarly if there were more than 5 matches or so.



Not sure how great of a solution this is for people reviewing videos of the run.

**Comment by flotwig** [comment]
Changes look great @jennifer-shehane. Finally, the weird cut-off-pill shape has been fixed!

**Comment by jennifer-shehane** [comment]
@flotwig So the percy screenshots looks a little off with my css changes, but...again, I'm not sure if this is accurate to real situations that would happen. I can try to recreate locally, but at least the dup one in the screenshots doesn't look like that usually. https://percy.io/cypress-io/cypress/builds/10298521

**Comment by jennifer-shehane** [comment]
I think the percy discrepencies are a zoom issue or something, because the css doesn't display the same as the snapshots when at 100%.

@flotwig Is this what's meant to be addressed in the other command log issue, but why are there duplicate logs for requests in this example 5 - 10 - 10?

It looks a lot clearer with the aliases displayed in this PR anyway.

```js
it('test cy.intercept()', () => {
  cy.intercept('/u*').as('getUrl1')
  cy.intercept('/us*').as('getUrl2')
  cy.intercept('/use*').as('getUrl3')
  cy.intercept('/user*').as('getUrl4')
  cy.intercept('/users*').as('getUrl5')

  cy.visit('https://example.com')
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })

  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })

  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })
  cy.window().then((win) => {
    const xhr = new win.XMLHttpRequest()
    xhr.open('GET', '/users')
    xhr.send()
  })

  cy.wait('@getUrl1')
  cy.wait('@getUrl2')
  cy.wait('@getUrl3')
  cy.wait('@getUrl4')
  cy.wait('@getUrl5')
})
```

Screen Shot 2021-05-07 at 10 29 58 AM

**Comment by flotwig** [comment]
> Is this what's meant to be addressed in the other command log issue, but why are there duplicate logs for requests in this example 5 - 10 - 10?

@jennifer-shehane the browser is probably retrying the request, since presumably it's failing?

**Review by bahmutov — APPROVED** [review]
super

**Pull request merged**
