### PR TITLE
fix(cli): don't include workspaces.nohoist in public NPM package

### LINKED ISSUE #22147: nohoist config is ignored
### Current behavior

when installing the cypress package via yarn, i get a warning saying the nohoist config is ignored

### Debug logs

warning nohoist config is ignored in "cypress" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.

### Cypress Version

10.0.3

### Package Manager

yarn

### Operating system

Mac

### Other

_No response_

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #22147

### User facing changelog

Fixed an issue causing a "nohoist config is ignored" warning when installing `cypress` with yarn.

### Steps to test

Install latest prerelease comment on this branch on Linux, note there is no warning.

### PR Tasks

- [ ] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by ryanthemanuel — COMMENTED** [review]
Looks good. Is there a way to write a test for this change?

**Comment by flotwig** [comment]
@ryanthemanuel I don't see an obvious way to test it since it's in the build step. I could add an assertion in buiild.js or post-build.js, but it would be overly unit testy imo.

I think this script should be updated in general, we shouldn't need to do all this wacky merging of 2 package.jsons, I think all of the should be all in one place as much as possible. So no `_.extend(json`. We'd be better off since changes to `cli/package.json` couldn't have this unintended impact.

**Comment by ryanthemanuel** [comment]
> @ryanthemanuel I don't see an obvious way to test it since it's in the build step. I could add an assertion in buiild.js or post-build.js, but it would be overly unit testy imo.

I figured as such. Approved!

**Review by ryanthemanuel — APPROVED** [review]
Looks good!

**Review by ZachJW34 — APPROVED** [review]

**Pull request merged**
