### PR TITLE
test: add tests for special sequences {moveToStart} / {moveToEnd}

### LINKED ISSUE #5502: add tests for {moveToStart} / {moveToEnd} special sequences
add better tests for {moveToStart} / {moveToEnd} special char sequences

they were added in #4870 but not called out in changelog / documented / or tested, making it one of those "undocumented features")

* after this is fixed, we can open PR for adding to docs

### PR DESCRIPTION
**Pull request by w0wka91**
- Closes #5502 

### User facing changelog

Added tests for the special sequences {moveToStart} / {moveToEnd}
### Additional details

N/A
### How has the user experience changed?

N/A
### PR Tasks

- [X ] Have tests been added/updated?

### CODE REVIEW

**Comment by Bkucera** [comment]
hi @w0wka91 for #5502 to be closed we'll need tests for `textarea` and `contenteditable` as well.

**Comment by w0wka91** [comment]
hi @Bkucera! I've also added some tests for `textarea` and `contenteditable`.
So if you dont mind I would also add this feature to the docs

**Comment by Bkucera** [comment]
@w0wka91 docs PR would be greatly appreciated. thanks for adding the tests!

**Comment by jennifer-shehane** [comment]
@w0wka91 Unfortunately this PR was merged in prematurely - without the tests passing after being merged in from develop. We had to revert this PR in https://github.com/cypress-io/cypress/pull/6469 in order to get our latest release out.

Please feel free to open a new PR for the work contained in this PR.

**Pull request merged**
