### PR TITLE
fix: improve decoding of special chars in source paths

### LINKED ISSUE #14659: Studio unable to save to files with special characters in path
### Current behavior
Studio throws an error when trying to save to files that have a space somewhere in their path. If the space is removed, the saving works fine. I assume that a similar thing could be happening with `open in ide` since they share some of the same logic here but I'll have to test that.

### Desired behavior
Studio should be able to save to all file names.

### Test code to reproduce
See comment below

Originally reported by @ChaseBig https://github.com/cypress-io/cypress/discussions/14339#discussioncomment-297047

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #14659

### User facing changelog
Fixes issues where special characters in file names would not be decoded correctly.

### Additional details
This improves the display of file names in the codeframe and stack trace. In addition, it fixes the `Open In IDE` button for these specs and allows Studio to properly save to these files.

### How has the user experience changed?
For a file named `cypress/integration/spec%with space &^$ emoji👍_你好.js`

Previous code frame:
Screen Shot 2021-01-21 at 8 35 43 PM

New code frame:
Screen Shot 2021-01-21 at 8 36 06 PM

In addition to fixing the display, opening in ide and saving to file in studio now also work.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]
Nice. I appreciate the thorough comments. I manually tested the Studio and IDE opening with files with special characters and it works fine.

Files with `%` character in them don't even open in the TR. The code is fine covering this but I don't think this is an actual use case until we fix that. 

Screen Shot 2021-01-22 at 10 16 58 AM

**Comment by jennifer-shehane** [comment]
Ignore percy snapshots - going to fix flake in https://github.com/cypress-io/cypress/pull/14687

**Comment by panzarino** [comment]
@jennifer-shehane Are you sure that's not just an empty test file? The screenshots that I provided in the initial comment show an example of a spec with `%` in the title.

Looks like e2e tests are legitimately failing so I'll have to figure out why before this can be merged.

**Comment by jennifer-shehane** [comment]
lol. yeah, I did not read the error message 🙈

**Comment by panzarino** [comment]
@jennifer-shehane Could you check out the failing e2e tests? I've rerun them a couple times and they continue to fail which indicates its not flake but they're passing locally for me.

**Comment by jennifer-shehane** [comment]
@panzarino Didn't they pass this time? I think it's that new stdio PR introducing flake. :/

**Comment by panzarino** [comment]
@jennifer-shehane Yup - probably flake so I'm gonna go ahead and merge

**Pull request merged**
