### PR TITLE
moved

### PR DESCRIPTION
**Pull request by alexsch01**
## moved to https://github.com/cypress-io/cypress/pull/30517 since I can't reopen this pull request

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Outlining the requirements from product

[Internal initiative link.](https://app.clickup.com/t/18033298/PM-4268)

#### In Scope
- The config option should be named `browser` since it is the same behavior as the --browser flag
- The config option when used during `cypress run` should run the browser
- The config option when used during `cypress open` should pre-select browser - (behave the same as --browser flag)
- The `–browser` flag overrides any value of configuration `browser` via `cypress run` or `cypress open`
- The `browser` config should available on top level config and also via the e2e and ct testing types to specify a different browser for each testing type
- If CYPRESS_CONFIG={browser: chrome} –browser firefox passed to terminal, –browser overrides browser config
- The `browser` config should accept args just like the --browser flag, including channels (chromiu, chrome:beta, etc)
- Should error when an invalid or not found browser is passed to `browser` config, just like –browser flag
- Should be able to write config.browser within the setupNodeEvents since `browser` is now on main config

#### Not in scope
- Allowing to specify a headed or headless option for the browser is **not in scope**
- The `browser` config will not be settable on spec/suite level config
- The `browser` config will not be available via Module API (could always pass browser flag at this point)
- Do not need to update the GitHub action

@alexsch01 As this PR stands, we would not accept these changes because they don't match the requirements that we'd want in the product for this feature.

**Comment by alexsch01** [comment]
@jennifer-shehane There's an issue, `browser` is already used in the internal config `Cypress.PluginConfigOptions`

**Comment by alexsch01** [comment]
> * The config option should be named `browser` since it is the same behavior as the --browser flag

What config options have the same name as their CLI flags?

**Comment by alexsch01** [comment]
@jennifer-shehane It would in my opinion hurt the Cypress codebase if we use `browser` instead of `defaultBrowser`

**Comment by alexsch01** [comment]
@jennifer-shehane 

There's an issue, variable `browser` (type: `Cypress.Browser`) is used in `Cypress.RuntimeServerConfigOptions`

If we have a new variable `browser` (type: `string`) in `Cypress.ResolvedConfigOptions`, then `browser` in `Cypress.RuntimeServerConfigOptions & Cypress.ResolvedConfigOptions` would have a type of `Cypress.Browser & string` which doesn't work

image
image

Also `config.defaultBrowser` makes a lot of sense, considering a person could get confused that `config.browser` is the same as the browser that will get launched - since it's not in cases where `--browser chrome` is passed to the CLI

---

Please look this over with the product team

**Comment by alexsch01** [comment]
@jennifer-shehane please let contributor-pr step run

**Comment by dkasper-was-taken** [comment]
@alexsch01 I kicked off the build, but I also pulled develop into the branch, there have been some build/cli changes. Apologies if there's any inconvenience.

**Comment by alexsch01** [comment]
@dkasper-was-taken Thank you

**Comment by alexsch01** [comment]
> @jennifer-shehane
> 
> There's an issue, variable `browser` (type: `Cypress.Browser`) is used in `Cypress.RuntimeServerConfigOptions`
> 
> If we have a new variable `browser` (type: `string`) in `Cypress.ResolvedConfigOptions`, then `browser` in `Cypress.RuntimeServerConfigOptions & Cypress.ResolvedConfigOptions` would have a type of `Cypress.Browser & string` which doesn't work
> 
> image image
> 
> Also `config.defaultBrowser` makes a lot of sense, considering a person could get confused that `config.browser` is the same as the browser that will get launched - since it's not in cases where `--browser chrome` is passed to the CLI
> 
> Please look this over with the product team

**Comment by alexsch01** [comment]
I really believe this should be merged, but unforunately it won't be accepted

**Pull request closed without merging**
