### PR TITLE
fix: move types condition to the front

### PR DESCRIPTION
**Pull request by Andarist**
I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 

Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.

⚠️ note that this only fixes one problem (`🐛 Used fallback condition`) but this package still won't be completely correct: [arethetypeswrong](https://arethetypeswrong.github.io/?p=cypress%4012.11.0).

### CODE REVIEW

**Review by lmiller1990 — COMMENTED** [review]
Did not know about this ordering. I wonder if we can link for this.

Can you add a CHANGELOG entry? https://github.com/cypress-io/cypress/actions/runs/4840113756/jobs/8625561864?pr=26630#step:4:18. This should guide you - we lint the changelog, too.

**Comment by Andarist** [comment]
> Did not know about this ordering. I wonder if we can link for this.

This is mentioned [here](https://nodejs.org/api/packages.html#conditional-exports):
> Within the ["exports"](https://nodejs.org/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.

--- 

> Can you add a CHANGELOG entry? https://github.com/cypress-io/cypress/actions/runs/4840113756/jobs/8625561864?pr=26630#step:4:18. This should guide you - we lint the changelog, too.

Done.

**Review by lmiller1990 — APPROVED** [review]

**Review by jordanpowell88 — APPROVED** [review]

**Comment by jordanpowell88** [comment]
@Andarist Can you update the commit body to match our Issue template? It's causing the Semantic Pull Request step in CI to fail

**Comment by Andarist** [comment]
@jordanpowell88 I **think** i've corrected this as needed right now.

Offtopic... I'm Changesets maintainer and it seems that this fairly popular project could help you to manage CHANGELOG generation and stuff like that. Might not be a perfect fit right now if you have custom needs but a lot can probably be scripted/automated around it and you could open feature requests for missing things. You probably run into a lot of such merge conflicts and stuff when editing `CHANGELOG.md` manually on different branches so I would expect that a tool like this would be quite useful for your team.

**Comment by jordanpowell88** [comment]
> 

Thanks @Andarist! Yeah we currently manage our `CHANGELOG` manually but we will consider this if we reevaluate the way we handle our releases in the future.

**Comment by lmiller1990** [comment]
Seeing some unrelated flake, going to try fix it here: https://github.com/cypress-io/cypress/pull/26630/commits/9d6ba66b89e4dccaf929f25b96cddc8486391756

**Comment by lmiller1990** [comment]
Still hitting CI weirdness... debugging. I am sure it's unrelated to the changes here. I don't know why it's flaking.

**Comment by MikeMcC399** [comment]
executing `yarn` reverts the order in [cli/package.json](https://github.com/cypress-io/cypress/blob/develop/cli/package.json) leaving a git diff

for example:

```
     "./vue": {
-      "types": "./vue/dist/index.d.ts",
       "import": "./vue/dist/cypress-vue.esm-bundler.js",
-      "require": "./vue/dist/cypress-vue.cjs.js"
+      "require": "./vue/dist/cypress-vue.cjs.js",
+      "types": "./vue/dist/index.d.ts"
     },
```

**Comment by Andarist** [comment]
It seems that you depend on https://github.com/keithamus/sort-package-json through https://github.com/kuceb/eslint-plugin-json-format . I can file an issue there and maybe even fix this but it might take a moment. What about disabling this ESLint rule temporarily?

**Comment by Andarist** [comment]
Ok, it turned out that actually your own scripts were at "fault" here so I managed to fix it without any delays: https://github.com/cypress-io/cypress/pull/26743

**Comment by MikeMcC399** [comment]
@Andarist 

- Thank you for addressing this. We can continue the follow-up in #26743.

**Pull request merged**
