### PR TITLE
Replacing "\\" with "/" for Windows tests to be rendered in folders

### LINKED ISSUE #1335: Tests are not rendered in folders in the desktop-gui on windows
- Operating System: Windows 10
- Cypress Version: 2.0.1
- Browser Version: Chrome 63

### Is this a Feature or Bug?
Bug

### Current behavior:
Tests are incorrectly rendered in groups/folders on windows.
image

### Desired behavior:
Tests should be organized by groups

### How to reproduce:
Load a folder with tests organized in sub-folders on a Windows PC.

### PR DESCRIPTION
**Pull request by corneliutusnea**
closes #1335

### CODE REVIEW

**Comment by brian-mann** [comment]
Need you to accept the CLA. Plus we'll need one test for this. The tests are written in Cypress :-P

You'd need to modify a fixture somewhere to ensure this works correctly. All bugs in production definitely need a test around them. I can have someone on our team do it if you'd like.

**Comment by corneliutusnea** [comment]
I signed the CLA. Happy to write a test if you can point me to the right file. I was a bit lost in the .coffee files as I'm not familiar with the language.

**Comment by brian-mann** [comment]
the CLA assistant we use does not think you signed it unfortunately.

**Comment by corneliutusnea** [comment]
Odd, I can see this "You have signed the CLA already but the status is still pending? Let us recheck it."
Let's wait a bit maybe?

**Comment by brian-mann** [comment]
Click the "let us recheck it"

**Comment by brian-mann** [comment]
@corneliutusnea we are trying to get this merged in - but until the CLA is signed we cannot merge any of your changes. I'm having a team member of ours work on this, but the CLA is a blocker.

Can you go through the CLA signing process again?

**Comment by corneliutusnea** [comment]
@brian-mann  I did sign the CLA several times. I raised an issue with cla-assistant https://github.com/cla-assistant/cla-assistant/issues/308

**Comment by bahmutov** [comment]
Could you have used a different email perhaps?

**Comment by corneliutusnea** [comment]
@bahmutov I don't have a different email for GH

**Comment by brian-mann** [comment]
Inside of CLA assistant I do see that it has been signed, so I think we're good.

**Comment by jennifer-shehane** [comment]
@corneliutusnea It looks like our CLA is checking against the `OneSaasDev` username for this PR. You may want to make sure the email in your commits are linked correctly with the email address you used to sign the CLA. https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user

screen shot 2018-02-20 at 12 02 05 pm

**Comment by brian-mann** [comment]
@corneliutusnea Jennifer is exactly correct - when you logged into CLA Assistant you logged into a user who did not make open the PR. That's why its not linking up.

**Comment by brian-mann** [comment]
You likely need to log into CLA assistant with the user who made the PR - and then it will work.

**Comment by brian-mann** [comment]
CLA assistant shows the missing contributor here:

screen shot 2018-02-20 at 3 17 03 pm

We are trying to release `2.0.3` tonight (we have a workshop tomorrow) but if we don't get this signed then we cannot pull this in.

**Pull request merged**
