### PR TITLE
chore: Remove storybook related data-context and tests

### PR DESCRIPTION
**Pull request by BlueWinds**
- Closes https://cypress-io.atlassian.net/browse/UNIFY-1557

### User facing changelog
No user facing changes. This removes non-functional code related to using storybook which we've already removed from the UI.

### Additional details
Cleans up storybook detection code and related tests

### PR Tasks
- [x] Have tests been added/updated?
- [n/a] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [n/a] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by tgriesser — COMMENTED** [review]
This is sad that we're removing it, I thought adding this back in was going to be a fast-follow to release and we were just going to hide it on the frontend. I guess it's always in git if we need it.

**Review by tgriesser — APPROVED** [review]

**Comment by BlueWinds** [comment]
> This is sad that we're removing it, I thought adding this back in was going to be a fast-follow to release and we were just going to hide it on the frontend. I guess it's always in git if we need it.

Yeah, agreed. I think it may be one of those times though when it's actually easier to do from scratch than keep code up to date with all the refactoring around it.

**Review by tbiethman — APPROVED** [review]
Did a quick search, only found a few minor things:
* Do a quick build to ensure the `fixtureDirs.ts` file gets updated with project removals
* The `no-specs` project has a `.storybook` directory that can be removed

**Comment by BlueWinds** [comment]
> Did a quick search, only found a few minor things:
> 
>     * Do a quick build to ensure the `fixtureDirs.ts` file gets updated with project removals
> 
>     * The `no-specs`/`no-specs-custom-pattern` projects each have a `.storybook` directory that can be removed

Unclear to me which yarn command maps to the gulp task rebuilding that file. I ran a whole bunch of them (`yarn build`, `yarn dev`), none seemed to change the file (beyond the changes already in there in this PR).

Removed .storybook dirs.

**Comment by tbiethman** [comment]
@BlueWinds Sorry, looks like `fixtureDirs.ts` is now in the `.gitignore`, you should be good to go.

**Comment by BlueWinds** [comment]
Failing tests are just flake, I had it passing just a moment ago. Merging.

**Pull request merged**
