### PR TITLE
chore: support vite 2.5

### PR DESCRIPTION
**Pull request by JessicaSachs**
We need to upgrade to the latest version of Vite in order to use our application to test out the Vite team's fix for Cypress component testing. We need to get all the way from 2.4.4 to 2.7.x (and be able to test against 2.8.0-beta.5 internally, even if we don't use it in our normal day-to-day).

The main issue when going from 2.4.4 to 2.5 is that previously, we were (incorrectly) able to import types alongside normal imports. Our linter forced us to do this.

```ts
// Old linter requires this, but Vite will throw an exception when we run this code
import { Ref, ref} from 'vue'

// Vite 2.5+ requires two separate imports
import type { Ref } from 'vue'
import { ref } from 'vue'
```

I updated the linter to support a Typescript-friendly version of "no-duplicate-imports". More information can be found [here](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-duplicates.md).

### CODE REVIEW

**Review by lmiller1990 — DISMISSED** [review]
Seems fine, just syntax changes.

**Comment by lmiller1990** [comment]
I assume anyone on Vite 2.5x in the wild will already be separating `import` and `import type`?

**Comment by JessicaSachs** [comment]
> I assume anyone on Vite 2.5x in the wild will already be separating `import` and `import type`?

Yeah. I asked already.

Screen Shot 2022-02-08 at 3 31 52 AM

**Review by lmiller1990 — DISMISSED** [review]
Code is :100: . Have some CI fails for app integration but they seem to also happen in 10.0-release.

**Pull request merged**
