### PR TITLE
WIP: add IE11 support

### PR DESCRIPTION
**Pull request by kuceb**
_in backlog_
- [x] wait on firefox support #1359 
- [ ] implement native events protocol for keyboard
- [x] use proxy pac for proxy configuration for all browsers #2539  
- [x] build custom IEDriver to fix bug with no respecting per-process proxy settings 
 - [x] gateway to webdriver commands for native events 
 - [ ] fix performance problems causing freezing test runs
 - [ ] fix various js issues, unsupported APIs
 - [ ] capture video, possibly with IEDiagnosticsServer + screencast API

### CODE REVIEW

**Comment by RicardoVaranda** [comment]
Hi Guys has there been any development on this? My team doesn't want to go near Cypress until IE and Firefox are supported.

**Comment by niemeczek** [comment]
The same in my company. Many companies still use IE 11, especially in banking sector and stops us for switching to Cypress.

**Comment by jennifer-shehane** [comment]
Those conflicts though 😓

**Comment by tbredin** [comment]
Just adding to the conversation: my team's biggest need for getting our test suite going is to give better coverage for IE11 — where some big corporate/govt clients are still locked in by their IT departments unfortunately, which also happens to be a sizeable revenue stream for us. And knowing how much of a total pain in the butt IE is, just want to say thanks for this, we're eagerly awaiting updates :)

**Comment by jennifer-shehane** [comment]
Hey everyone, please add your comments about needing of this feature in the issue itself. https://github.com/cypress-io/cypress/issues/3207 

The PR comments are critical for work concerning the code and implementation. We will need to lock down conversation to the team only since this is an important space to keep code discussions clean and readable.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this PR due to inactivity - it's gone way out of date with the current develop. The work is still here to reference when needed in the future or can be reopened.

**Pull request closed without merging**
