### PR TITLE
feat: Add user's log option to cy.tick

### PR DESCRIPTION
**Pull request by saturninoabril**
- Closes https://github.com/cypress-io/cypress/issues/15180

### User facing changelog
This PR adds a user option to disable/enable log of `cy.tick(ms, {log: false})`. Currently, it's always logging but in some cases, disabling log helps eliminate noise and gives more focus on other interesting item.

### Additional details
See https://github.com/cypress-io/cypress/issues/15180 for more details.

### PR Tasks
- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by hahmadia** [comment]
LGTM 👍

**Review by jennifer-shehane — APPROVED** [review]
Looks good, I manually tested. Thanks for testing and adding types! 💯

**Comment by jennifer-shehane** [comment]
Oh, this will need an update to the docs, but I can open the PR for this because we're in the middle of a docs transition, so it's a little tricky.

**Comment by jennifer-shehane** [comment]
This is blocking merge https://github.com/cypress-io/cypress/pull/15589

**Pull request merged**
