### PR TITLE
dependency: bump @cypress/request to ^3.0.4

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Closes 

### Additional details

This bumps some dependencies of our @cypress/request library. TBH I was trying to address some vulnerabilities that a user surfaced. (I need to investigate why these wouldn't be surfaced by our Snyk scans.) At the end of the day, this update didn't actually fix those vulnerabilities since those deps exist on other deps we have also. 

This should be a good fix regardless as it updates dependencies below which all contained fixes:
- updates dependency form-data to ~2.5.0
- updates dependency qs to v6.13.0
- updates dependency http-signature to ~1.4.0

### Steps to test

Tests pass

### How has the user experience changed?

It's possible this could have fixed some issue for users.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
I don't know why my commit history keeps being weird when I open new PRs....

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> I don't know why my commit history keeps being weird when I open new PRs....

It sounds like you need to reset your local copy of the `develop` branch so that it matches the commit history on GitHub. That should remove all the merge commits you apparently have in your local copy.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 I reset everything on my side and it seems to be playing nicer.

**Review by ryanthemanuel — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Would you want to update to [@cypress/request@^3.0.5](https://github.com/cypress-io/request/releases/tag/v3.0.5) now?

**Review by mschile — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
@MikeMcC399 I'll merge this first just in case that introduces something that breaks when we run it.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> I'll merge this first just in case that introduces something that breaks when we run it.

Understood.

New installations of Cypress in the field are going to pull `@cypress/request@3.0.5` anyway, since the dependency is semver `@cypress/request@^3.0.4`.

**Pull request merged**
