### PR TITLE
fix: proxy authorization type Basic

### PR DESCRIPTION
**Pull request by Buluc-Celik-Ozbul**
- Closes https://github.com/cypress-io/cypress/issues/22383

### User facing changelog
The Proxy-Authorization header when present with basic authorization will read "Basic" with a capital "B".

### Additional details
When I set up a proxy with username and password, the Proxy-Authorization header is created with basic type but it says "basic" with a small "b" and this fails with some proxies. The Proxy-Authorization header should have been created with "Basic" keyword with a capital "B"

### Steps to test
[na]

### How has the user experience changed?
[na]

### PR Tasks
[na]

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by emilyrohrbough — APPROVED** [review]

**Comment by emilyrohrbough** [comment]
@Buluc-Celik Thank you for the contribution! Can you please sign the CLA Agreement so we can move forward with this change?

**Comment by Buluc-Celik-Ozbul** [comment]
hi @emilyrohrbough I have signed it, I think it needs a bit of time to reflect though

**Comment by emilyrohrbough** [comment]
@Buluc-Celik are you toggling between two git accounts?

**Comment by Buluc-Celik** [comment]
Sorry about that, signed with both now

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Looks good. We've got some flake blocking merging, but I can take it from here - it's not related to your change. Thanks!

**Comment by Buluc-Celik** [comment]
Thank you!

**Comment by lmiller1990** [comment]
Sure, I think the flake is fixed now. I will re-run.

**Comment by lmiller1990** [comment]
Less flake but still something isn't passing - figuring it out, thanks for waiting.

**Comment by lmiller1990** [comment]
@Buluc-Celik-Ozbul] please wait a moment - I am going to get this merged. If you keep back merging, it re runs everything. I can run "only from failed" which is more likely to succeed. I can take it from here.

**Comment by Buluc-Celik-Ozbul** [comment]
Sure, thank you

**Comment by lmiller1990** [comment]
Thanks for your patience @Buluc-Celik-Ozbul - this will be in the next release. Those are usually every two weeks at maximum.

**Comment by Buluc-Celik-Ozbul** [comment]
Thanks again!

**Pull request merged**
