### PR TITLE
fix(launcher): add alternative binary names for edge

### LINKED ISSUE #8930: Microsoft Edge (dev channel) is not detected on Linux
### Current behavior
When Microsoft Edge Dev is installed on a Linux system, it is no recognized by the Cypress runner, and it's not available in the browser dropdown.

### Desired behavior
Microsoft Edge Dev should be detected with the binary `microsoft-edge-dev`

### Versions

Cypress 5.4.0
Microsoft Edge Dev 88.0.673.0

### PR DESCRIPTION
**Pull request by MattMattV**
In the recent packaging of Edge Dev for Linux, the binary is named 'microsoft-edge-dev'

* Closes #8930 

### User facing changelog
Microsoft Edge should now be properly detected on Linux systems.

### PR Tasks

* [x] Have tests been added/updated?
* [x] Has the original issue or this PR been tagged with a release in ZenHub? 
* [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
* [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
* [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by MattMattV** [comment]
I would be very happy to add some tests to this fix, but would it be possible to  have some guidance ?

**Review by flotwig — APPROVED** [review]

**Comment by MattMattV** [comment]
Would you mind adding the label Would it be possible to have the label `hacktoberfest-accepted` applied on the PR ?

**Comment by MattMattV** [comment]
@jennifer-shehane @flotwig Would it be possible to have the label `hacktoberfest-accepted` applied on the PR ?

**Comment by flotwig** [comment]
@MattMattV tagged :)

**Pull request merged**
