### PR TITLE
chore: upgrade Lerna to v5 and use Nx

### LINKED ISSUE #23688: Upgrade to Lerna 5+ with Nx
### What would you like?

I would like to propose we upgrade the repo to use Lerna 5 and enable Nx. This will enable Nx's caching capabilities as well as bring it up to date with the most recent version of Lerna. 

https://blog.nrwl.io/lerna-used-to-walk-now-it-can-fly-eab7a0fe7700

### Why is this needed?

This will speed up our builds by leveraging Nx caching and update Lerna to be on the most recent version.

### Other

_No response_

### PR DESCRIPTION
**Pull request by astone123**
- Closes https://github.com/cypress-io/cypress/issues/23688

### Additional details

This PR upgrades Lerna to version 5.4.3. This is the newest version that we can upgrade to without needing to upgrade any of our other dependencies, and still gives us the ability to use Nx as the task runner under the hood of Lerna. It also gives us the ability to view [Nx's dependency graph](https://nx.dev/core-features/explore-graph) for our project to analyze each package's dependencies and the structure of our monorepo. 

This should be a good starting point that will allow us to move forward with leveraging Nx features like [task result caching](https://nx.dev/core-features/cache-task-results), [task distribution](https://nx.dev/core-features/distribute-task-execution) and others to improve our build and test processes.

### Steps to test

Run `yarn` and make sure that everything still works as expected - console output has changed slightly.

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by lmiller1990 — APPROVED** [review]
Do we get any benefits right now from the `useNx` key? Or will more work be needed (is the `useNx` a no-op right now, basically?)

**Comment by astone123** [comment]
@lmiller1990 the only benefit that we get is clearer (imo) console output during our build steps. The other benefits will require us to configure some things

**Comment by lmiller1990** [comment]
Great, seems like a low risk : high value PR.

**Review by mike-plummer — APPROVED** [review]

**Review by warrensplayer — APPROVED** [review]
Code update is super simple.

I did compare the time of just running `yarn` between this branch and `develop`.  For me, this branch would take about 160-170 seconds while `develop` took 130-140.  I ran them several times in a row and did not count the first one after switching branches.  So, this branch is somewhat slower, but it does not seem to affect the timings noticeably in CI.

**Comment by astone123** [comment]
@warrensplayer Yeah that does seem to be the case. I'm hoping to write up some issues soon for how we can start to enable some Nx task result caching which should allow us to dramatically decrease build times 👍🏻

**Pull request merged**
