### PR TITLE
Issue 962 - Skip invalid cookies instead of crashing

### LINKED ISSUE #962: Invalid cookies crash Cypress
- Operating System: macOS 10.12.6 (16G29)
- Cypress Version: 1.1.1
- Browser Version: Chrome 62

### Is this a Feature or Bug?
Bug

### Current behavior:
When a server responds with an invalid `Set-Cookie` header (e.g. containing a unicode character) then Cypress crashes.

### Desired behavior:
When a server responds with an invalid `Set-Cookie` header (e.g. containing a unicode character) then Cypress could:
* ignore the invalid cookie and log that
* or maybe have a configuration option to ignore invalid cookies

### How to reproduce:

See test code below.

#### Test code:

```js
describe('HomeAway', () => {
    it('Search Landing Page', () => {
        cy.visit('https://www.homeaway.com/d/1540e08a-4d04-41f1-9795-526cd5217516/new-york-city');
    });
});
```

### Additional Info (images, stack traces, etc)

Our WAF (Incapsula) might be dropping that invalid cookie intentionally. 

The error thrown:
```
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/Users/cpalfi/cypress/packages/server/node_modules/express/lib/response.js:700:10)
    at ServerResponse.append (/Users/cpalfi/cypress/packages/server/node_modules/express/lib/response.js:670:15)
    at /Users/cpalfi/cypress/packages/server/lib/controllers/proxy.coffee:193:14
    at Object.getHttpContent (/Users/cpalfi/cypress/packages/server/lib/controllers/proxy.coffee:233:7)
```

### PR DESCRIPTION
**Pull request by csabapalfi**
Fixes #962 (verified locally on my use-case but might break some other things)

I can see that all proxy unit tests are commented out at the moment. 

Can definitely add some for this. Should I? 😃

### CODE REVIEW

**Comment by brian-mann** [comment]
Thank you providing a reproducible example showing invalid cookies. Users have complained about this before but we've never been able to reproduce.

We can take the issue from here and fix it and write some tests for it. The unit tests for the proxy are commented out because they're fairly useless and we have a gazillion other integration and e2e tests that truly test it all working correctly.

There is a cookie module we already have that can help sanitize invalid cookies prior to setting them. We likely need to run them through that first to strip out the invalid ones and then set the valid ones.

Your PR breaks other areas of Cypress - which is why we've mostly written integration and e2e tests. Cypress is so complex that is really the only way we can guarantee changing one area of the system doesn't inadvertently break another.

I'll edit your PR directly and apply the fixes. 👍

**Comment by csabapalfi** [comment]
Perfect, thanks so much! I had an idea that my PR was just roughly OK (fixed the error for me locally) and the integration test failures confirmed that.😄😄 Thanks again for looking into this!

**Comment by brian-mann** [comment]
Pushed a commit. We'll see if that passes all the tests. I spent a lot of time researching this and you basically found the right area to fix this - all that was missing was normalizing the cookies into an array to loop over. Sometimes they could just be a regular string.

**Comment by csabapalfi** [comment]
Brilliant, thanks!

**Pull request merged**
