### PR TITLE
fix: checked-for-updates event properly sends, and update banner is displayed

### LINKED ISSUE #15829: Checked for Updates event not firing due to malformed http header
The "Checked for Updates" event is not firing in version `7.0.0` and users will not see the update banner when we release `7.0.1`.

### PR DESCRIPTION
**Pull request by brian-mann**
- Closes #15829 

### User facing changelog
The update banner will now display again when there are updated versions of cypress

### PR Tasks
- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

**Review by JessicaSachs — APPROVED** [review]

**Review by Duc56789 — COMMENTED** [review]
packages/server/test/unit/updater_spec.js

**Review by Duc56789 — COMMENTED** [review]
packages/server/test/unit/updater_spec.js

**Comment by Duc56789** [comment]
packages/server/test/unit/updater_spec.js

**Review by Duc56789 — COMMENTED** [review]
packages/server/test/unit/updater_spec.js

**Review by Duc56789 — COMMENTED** [review]
packages/server/test/unit/updater_spec.js

**Comment by Duc56789** [comment]
packages/server/test/unit/updater_spec.js

**Review by Duc56789 — COMMENTED** [review]
packages/server/test/unit/updater_spec.js

**Comment by Duc56789** [comment]
packages/server/test/unit/updater_spec.js

**Review by Duc56789 — COMMENTED** [review]
Rùn

**Review by Duc56789 — COMMENTED** [review]
Dfff

**Review by Duc56789 — COMMENTED** [review]
Vgg

**Comment by Duc56789** [comment]
Đi

**Review by majid1-2030 — COMMENTED** [review]
majid1-2030

**Review by Duc56789 — COMMENTED** [review]
Gdh

**Review by msigoo33 — COMMENTED** [review]
@msigoo33

**Review by Duc56789 — COMMENTED** [review]
Ù

**Comment by Duc56789** [comment]
CVC

**Pull request merged**
