### PR TITLE
fix incorrectly using Window.length as subject length

### LINKED ISSUE #4396: Cypress reads Window.length as number of subjects passed from cy.window()
https://developer.mozilla.org/en-US/docs/Web/API/Window/length

> Window.length: Returns the number of frames (either <frame> or <iframe> elements) in the window.

in commands we check `options.$el.length`, so this will falsely tell us that a `window` subject is "multiple elements" if the window has more than 1 iframe

### PR DESCRIPTION
**Pull request by kuceb**
fix #4396

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
test?

**Comment by Bkucera** [comment]
I added I frames to the test fixture as a test

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
I see, we already have a test that calls `cy.window().focus()`, etc, but there's nothing guaranteeing that these iframes remain present in the DOM.html file, someone could delete them out if they 'think' there's no tests involving iframes in our suite. 

Can you add an assertion in that test that's more explicit to assert the iframes are present and the `cy.window().focus()` doesn't fail? Looks good otherwise.

**Comment by Bkucera** [comment]
@jennifer-shehane agreed, should be much better now

**Review by jennifer-shehane — DISMISSED** [review]
Yay! Much better 💯

**Comment by jennifer-shehane** [comment]
Maybe a legitimate failure?

```
  1) src/cy/commands/screenshot #screenshot element capture passes through window:
     AssertionError: expected false to be true
      at getRet (http://localhost:3500/__cypress/runner/cypress_runner.js:71734:16)
      at tryCatcher (http://localhost:3500/__cypress/runner/cypress_runner.js:132224:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3500/__cypress/runner/cypress_runner.js:129598:29)
      at Context.thenFn (http://localhost:3500/__cypress/runner/cypress_runner.js:71748:26)
      at Context.then (http://localhost:3500/__cypress/runner/cypress_runner.js:72014:21)
      at Context.<anonymous> (http://localhost:3500/__cypress/runner/cypress_runner.js:79052:21)
      at http://localhost:3500/__cypress/runner/cypress_runner.js:78757:33
      at tryCatcher (http://localhost:3500/__cypress/runner/cypress_runner.js:132224:23)
      at Promise._settlePromiseFromHandler (http://localhost:3500/__cypress/runner/cypress_runner.js:130242:31)
      at Promise._settlePromise (http://localhost:3500/__cypress/runner/cypress_runner.js:130299:18)
      at Promise._settlePromiseCtx (http://localhost:3500/__cypress/runner/cypress_runner.js:130336:10)
      at Async._drainQueue (http://localhost:3500/__cypress/runner/cypress_runner.js:127153:12)
      at Async._drainQueues (http://localhost:3500/__cypress/runner/cypress_runner.js:127158:10)
      at Async.drainQueues (http://localhost:3500/__cypress/runner/cypress_runner.js:127032:14)
```

**Review by jennifer-shehane — APPROVED** [review]

**Pull request merged**
