### PR TITLE
fix(vite-dev-server): windows `supportFile` + preserve optimize entries

### LINKED ISSUE #18261: Vite dev server optimize entries
### Current behavior

I have a problems with component tests
If I add node_modules dependency into support file - this dependency wouldn't be pre-bundled by Vite. This is because Cypress pass `supportFile` into optimizeDeps.entries as is - and this is wrong for windows.

[cypress/npm/vite-dev-server/src/startServer.ts](https://github.com/cypress-io/cypress/blob/2c381ed3c34ff0dd953f7b163a6469d20feb7d39/npm/vite-dev-server/src/startServer.ts#L60)
image

`optimizeDeps.entries` is array of [fast-glob patterns](https://github.com/mrmlnc/fast-glob#basic-syntax)

### Desired behavior

All node_modules dependencies which are imported inside `supportFile` must be pre-bundled on windows too

### Test code to reproduce

I've created repo for reproduce this
https://github.com/edikdeisling/test-cypress-cmp-tests-pre-bundling

Make sure there is no .vite in node_modules and run `yarn test:component:run`
image

### Cypress Version

8.4.1

### Other

There is another issue here to be honest. I think this is wrong to rewrite `optimizeDeps.entries`. Because of this behaviour I can't add my own `optimizeDeps.entries`
image

### PR DESCRIPTION
**Pull request by userquin**
### Context
This PR fix and closes #18261 

- preserve `optimizedDeps.entries` configured on target project
- ~~transform windows absolute paths to relative~~
- transform windows paths to use `/` to match fast glob patterns

### How to test
1. Follow the CONTRIBUTING.md guide
2. clone my branch, `yarn && yarn build --scope npm/vite-dev-server && cd npm/vite-dev-server && yarn link`.
3. clone the repo on #18261 , `yarn && yarn link "@cypress/vite-dev-server"`
4. edit `package.json` and change `"@cypress/vite-dev-server": "2.1.0"` with `"@cypress/vite-dev-server": "0.0.0-development"`
5.  run `yarn test:component:run`: the result should be the expected
6. if running `yarn test:component:run` from previous step again, delete `node_modules/.vite` directory before run it again

Once finished testing, unlink from `npm/vite-dev-server` package and from target project.

### Current Behavior
see #18261 

### New Behavior
* works on windows.
* target project `optimizeDeps.entries` entries  should be preserved

### Tests
PENDING (this is why is on draft)

### CODE REVIEW

**Comment by userquin** [comment]
@lmiller1990 feel free to change to ready to review if there is no need to add tests for preserve optimizeDeps entries and merge when necessary.

**Review by lmiller1990 — COMMENTED** [review]
Nice, exactly what I was expecting when I was thinking about how to fix this. I think this is fine for now, might be nice to investigate using AppVeyor to run the Vite tests at some point in the nearish future.

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
I will hold off on merging until our semantic release step is fixed, it's currently failing on CI. It should be resolved soon. Thanks!

**Comment by userquin** [comment]
@lmiller1990 adding the `supportFile` shouln't be outside this if statement `if((options.specs && options.specs.length))`?

**Comment by JessicaSachs** [comment]
> @lmiller1990 adding the `supportFile` shouln't be outside this if statement `if((options.specs && options.specs.length))`?

We can add the support file if there are no specs. That's fine. We can go either way, honestly.

**Review by JessicaSachs — APPROVED** [review]

**Pull request merged**
