### PR TITLE
chore(deps): update listr dependency

### PR DESCRIPTION
**Pull request by matheo**
listr@0.12.0 relies on rxjs@^5.0.0-beta.11

### Pre-merge Tasks

- [ ] Have tests been added/updated for the changes in this PR?
- [ ] Has a PR to [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation) been submitted to document any user-facing changes? 
- [ ] Have the [type definitions](cli/types/index.d.ts) been updated with any user-facing API changes?
- [ ] Has the [cypress.schema.json](cli/schema/cypress.schema.json) been updated with any new configuration options?
- [ ] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Closing. We use renovate to manage our updates - and use set versions as noted in our [Contributing guide](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md). I'll trigger the automated PR to run through renovate.

**Comment by jennifer-shehane** [comment]
New PR here: https://github.com/cypress-io/cypress/pull/4963

**Comment by jennifer-shehane** [comment]
This bump to listr requires > Node 4, so we cannot patch it - requires major breaking version. Work for this is already done in https://github.com/cypress-io/cypress/pull/4226

**Comment by matheo** [comment]
Ok, thanks @jennifer-shehane!

**Pull request closed without merging**
