### PR TITLE
fix: within followed by should correctly changes the scope.

### LINKED ISSUE #2106: `within` does not yield the subject from previous command
### Current behavior:

I am having trouble with `.within()` and `.should()`. `.within()` seems to yield the last subject that was yielded inside its scope rather than the subject from the previous command.

```javascript
    cy.get('.query-list')
    .within(() => {
      cy.get('li.first');
    })
    // `should` should run assertion against '.query-list'.
    // Instead runs against 'li.first'
    .should('be.visible')
    // `get` should get '#query-btn'
    // Instead tries to get 'li.first #query-btn'
    .get('#query-btn');
```
screen shot 2018-07-06 at 9 04 37 am

The `.within()` command yields the `li.first` subject instead of `.query-list`.
And I'm not sure if this is a separate issue, but I found it at the same time: when I run the `.get()` command on `#query-btn` after the `.should()` command, it tries to find `li.first #query-btn`

```javascript
    cy.get('.query-list')
    .within(() => {
      cy.log('inside the `within`');
    })
    // Assertion should run against '.query-list' subject
    .should('be.visible')
    .get('#query-btn');
```
screen shot 2018-07-06 at 9 07 09 am

In this example, I expected `.should()` to assert that `.query-list` was visible, but it instead receives `null`.

### Desired behavior:
The [docs](https://docs.cypress.io/api/commands/within.html#Yields) state:
> `.within()` yields the same subject it was given from the previous command.

But in my examples it seems to yield the last subject that was yielded from within its own scope.

### Steps to reproduce:

Reproduction repo: [https://github.com/hooskers/cypress-test-tiny](https://github.com/hooskers/cypress-test-tiny)
```bash
npm i
npm run cypress:open
```
Test cases are in `cypress/integration/spec.js`

### Versions

Cypress: 3.0.2
Browser: Chrome 67.0.3396.99
OS: MacOS 10.13.5

### LINKED ISSUE #4672: `within` followed by `should` permanently limits scope
### Current behavior:

When `within` is used to find and return some element within some other element and then followed by `should` to test the returned element, this breaks _all_ subsequent commands (all, not just in the same chain) by permanently setting the root to the aforementioned other element.

In other words, `cy.get('#scope').within(() => cy.get(…)).should(…)` breaks the rest of the test, because it makes it impossible to find anything outside `#scope`.

### Desired behavior:

`cy.get(…).within(() => cy.get(…)).should(…)` shouldn't impact subsequent commands at all. E.g. `cy.get(…)` used after it should search the entire document as usual.

### Steps to reproduce: (app code and test code)

```html
<div id="foo"><p>foo</p></div>
```

```javascript
cy.root().should('match', 'html') // passes, as it always should

cy.get('#foo')
  .within(() => cy.get('p')) // returns `#foo p`
  .should('match', 'p') // passes, but causes the scope of preceding `within` to become global

cy.root().should('match', 'html') // fails! root is still `div#foo`
```

_Obviously this example is contrived, it's just a minimum reproducible sample._

### Versions

Cypress 3.3.2
Chrome 75.0.3770.100 (Official Build) (64-bit)
MacOS 10.14.5 (18F132)

### LINKED ISSUE #4757: cy.within does not yield as documented
### Current behavior:

The [`cy.within` doc states that](https://docs.cypress.io/api/commands/within.html#Yields) it "yields the same subject it was given from the previous command". However, it seems to yield the last subject in the `within` function. Only an empty `within` function will yield the subject from the previous command.

### Desired behavior:

Not sure if the documentation or the implementation is wrong. Depending on that, the documentation or the implementation should be fixed.

### Steps to reproduce: (app code and test code)

```html
<article class='post'>
  <h1>My Blog Post</h1>
</article>
```

```javascript
cy
.get('article')
.within(() => {
  cy.get('h1')
})
.should('have.class', 'post')
```

This fails because the `within` yields the `h1` instead of the `article`.

### Versions

Cypress: 3.4.0
OS: MacOS Mojave 10.14.5
Browser: Electron

### LINKED ISSUE #5183: Cannot combine within, should, and contains commands as expected
### Current behavior:

Taken this example:
```js
cy.get(`article`).within(() => cy.get(`h1`)).should(`have.text`, `My Blog Post`);
cy.contains(`span`, `Hello World!`).should(`exist`);
```
The first assertion passes but the second assertion fails. This is because it looks for `article span` instead of `span`.

### Desired behavior:

Taken this example:
```js
cy.get(`article`).within(() => cy.get(`h1`)).should(`have.text`, `My Blog Post`);
cy.contains(`span`, `Hello World!`).should(`exist`);
```
I expect that it looks for `span` instead of `article span` and I expect both assertions to pass.

### Steps to reproduce: (app code and test code)

```html
<article class='post'>
    <h1>My Blog Post</h1>
</article>

<div>
    <span>Hello World!</span
</div>
```

```js
cy.get(`article`).within(() => cy.get(`h1`)).should(`have.text`, `My Blog Post`);
cy.contains(`span`, `Hello World!`).should(`exist`);
```

### Versions

Cypress: 3.4.1
OS: MacOS Mojave 10.14.5
Browser: Electron 61 + Chrome 77

### PR DESCRIPTION
**Pull request by sainthkh**
* Closes #2106
* Closes #4672
* Closes #4757
* Closes #5183

These all 4 issues cover the same problem and this PR solves that.

### User facing changelog
When a command is chained after `cy.within()` and `cy.get()` is called inside it, the scope was permanently changed. This PR solves this problem. 

#### Why was this change necessary?
The command didn't work as the documentation says.

#### What is affected by this change?
Some codes that use this bug will be broken. Example below:

```html
<article class='post'>
    <h1>My Blog Post</h1>
</article>
```

```js
cy.get(`article`).within(() => cy.get(`h1`)).should(`have.text`, `My Blog Post`);
```

This should fail because the `article` has text `\n My Blog Post \n`.

#### Any implementation details to explain?
When running tests, Cypress queues commands and runs them later. 

```js
cy.get('article').within(() => {
  cy.get('h1').should('contain.text', 'Blog')
})
.should('have.class', 'post')
```

In the example above, Cypress creates a queue like below:

```
get('article')
within
should('have.class', 'post')
```

After running `within`, the queue becomes like below:

```
get('article')
within
get('h1', { withinSubject: 'article' })
should('contain.text', 'Blog')
should('have.class', 'post')
```

Because `within` inserts commands inside the callback to the queue after itself.

But the problem happens here. Because the code below generates the identical queue state.

```js
cy.get('article').within(() => {
  cy.get('h1').should('contain.text', 'Blog').should('have.class', 'post')
})
```

And Cypress interprets that the code is written in that way. That's why the code failed. 

The solution is to insert the divider between the commands like below:

```
get('article')
within
get('h1', { withinSubject: 'article' })
should('contain.text', 'Blog')
within-restore <= This is necessary.
should('have.class', 'post')
```

And this PR inserts that internal command to the queue. 

### How has the user experience changed?
N/A

### PR Tasks
* [x] Have tests been added/updated?
* [ ] Has the original issue been tagged with a release in ZenHub? 
* [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
* [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
* [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by sainthkh** [comment]
Flaky failures.

**Review by jennifer-shehane — COMMENTED** [review]
Manually tested - this fixes #5183, #4757, #4672 and #2106

**Review by chrisbreiding — APPROVED** [review]
Clever solution! And knocking out 4 issues as well 👏

**Comment by dthomason** [comment]
I just opened this issue.  https://github.com/cypress-io/cypress/issues/9064  Is it related to this?  Seems like it is.  When is the fix expected to be released?

**Comment by jennifer-shehane** [comment]
@dthomason This has already been released, this was previously fixing an issue with within and is available in 5.4.0+

**Pull request merged**
