### PR TITLE
[WIP] refactor(cli.js): stick with the arg parser API to get things done

### LINKED ISSUE #6005: chore: switch to commander.js API
It seems that you guys aren't leveraging the API as provided by `commander.js` in order to get things done.

For instance

1. `commander.js` warns by default on firing in unknown options. 
https://github.com/cypress-io/cypress/blob/720bc470e9c7a42fff0d98d2b649ef11ee338239/cli/lib/cli.js#L13
I can see a manual implementation here which is kinda weird IMO.

2. Make use of the `version()` API in order to print version information.
https://github.com/cypress-io/cypress/blob/720bc470e9c7a42fff0d98d2b649ef11ee338239/cli/lib/cli.js#L193

3. There is a regex matcher to catch unknown commands:- 

```js
// error on unknown commands
program.on('command:*', function () {
  console.error('Invalid command: %s\nSee --help for a list of available commands.', program.args.join(' '));
  process.exit(1);
});
```

https://github.com/cypress-io/cypress/blob/720bc470e9c7a42fff0d98d2b649ef11ee338239/cli/lib/cli.js#L311

IMO all these manual workarounds can be dropped and it makes a lot more sense using the `commander.js` API for the purpose.

### PR DESCRIPTION
**Pull request by jamesgeorge007**
- Closes #6005 

### User facing changelog
Make use of the `commander.js` API to get things done rather than the manual approach.

### Additional details
N/A

### How has the user experience changed?
It improves DX.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
It seems that the snapshots are to be updated. I'm not that familiar with the test setup here. Any help would be appreciated :clap:

**Comment by jennifer-shehane** [comment]
@jamesgeorge007 Instructions on running the `cli` package tests can be found here: https://github.com/cypress-io/cypress/blob/develop/cli/README.md#automated including instructions on how to updates screenshots from the `snap-shot-it` package. You will have to run the tests locally to update them.

**Comment by jennifer-shehane** [comment]
I will be adding [WIP] to the title to show it still requires work (getting the tests to pass). Please remove [WIP] when you are ready for rereview.

**Comment by jennifer-shehane** [comment]
Hey @jamesgeorge007, will you have time to address the changes asked of this PR and fix the conflicts? We will have to close the PR due to inactivity otherwise.

**Comment by jamesgeorge007** [comment]
I would really appreciate any help on updating the test snapshots.

**Comment by jennifer-shehane** [comment]
@jamesgeorge007 When you run the tests locally (that require snapshot updates), you set the env var `SNAPSHOT_UPDATE=1` before running the tests to update the snapshots and commit.

See `snap-shot-it` instructions: https://github.com/bahmutov/snap-shot-it#advanced-use

**Comment by jennifer-shehane** [comment]
Hey @jamesgeorge007, will you have time to address the changes asked of this PR and fix the conflicts? We will have to close the PR due to inactivity otherwise.

**Comment by jamesgeorge007** [comment]
@jennifer-shehane apologies for the delay in response, I'm a bit caught up with couple of projects that I'm involved in. It would be great if you could lend a helping hand to finish off what's leftover :clap:

**Comment by jennifer-shehane** [comment]
@jamesgeorge007 Sorry, no, we have priorities of PRs and issues to focus on within our team and outside contributions are the responsibility of the contributor to see through.

The PR requires merge conflicts be fixed, changes have been made to the cli since this was opened - and to update the snapshots which I've given instructions on how to do above. If you cannot complete the work required, please close the PR.

**Comment by jamesgeorge007** [comment]
I don't have enough bandwidth at the moment to continue the work here.

**Pull request closed without merging**
