### PR TITLE
feat: add `bail` cli arg/module option

### LINKED ISSUE #518: Option to abort on first failure
### Environment

* Operating System: n/a
* Cypress Version: 0.13.1
* Browser/Browser Version: n/a

### Are you requesting a feature or reporting a bug?

Requesting a feature.

### Current behavior:

All tests are run even if one fails.

### Expected behavior:

Providing an option to abort the test suite as soon as a test fails.

### How to reproduce the current behavior:

Make a test fail.

### PR DESCRIPTION
**Pull request by loren138**
* Closes #518

### User facing changelog
Adds a new option `--bail` to the CLI which will bail if a test fails and not run the rest of the test suite

### Additional details
Provides the option to stop e2e runs early when a test fails using `--bail`

### How has the user experience changed?
Users can now use `--bail` to bail.

### PR Tasks
* [x] Have tests been added/updated?
* (n/a) Has the original issue been tagged with a release in ZenHub? (internal team only)
* [x] Docs https://github.com/cypress-io/cypress-documentation/pull/2959
* (n/a) Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
* [x] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by loren138** [comment]
@jennifer-shehane Is there a change I can make to help or will this PR be on hold until the product team makes decisions?

**Comment by ianldgs** [comment]
Maybe make this option only available when tests are not running in parallel? Think this might be most of the use cases?

**Comment by jennifer-shehane** [comment]
As part of Cypress’s [new pricing](https://www.cypress.io/blog/2021/03/16/new-pricing-that-scales-seamlessly/), we’ve included the ability to [cancel test runs when a test fails](https://on.cypress.io/smart-orchestration#Cancel-test-run-when-a-test-fails). This setting is accessible from the Dashboard for organizations starting at the [Business Plan](https://www.cypress.io/pricing/).

This offers a solution for those running tests using the Cypress Dashboard - and also ensures a parallelized run is cancelled so that all parallel running specs will also be cancelled to save time on the run.

**To get this feature, you will need to update to Cypress 6.8.0 and also be a member of an organization subscribed to a [Business Plan](https://www.cypress.io/pricing/).**

---

This feature was implemented with parallelized runs in the Dashboard in mind since this was the hardest use case to address. We had to build this feature specifically to continue to receive all of the tests in a cancelled run to ensure proper reporting. Now that we have a mechanism to cancel runs across these channels of communication, we can now consider a way to initiate cancelling test runs when a test fails from the Test Runner when not recording to the Dashboard. (Likely this would be implemented by some CLI flag or config specifying `cancelOnFailures: true)

**This issue associated with this PR will remain open to address the use case of cancelling test runs when a test fails from the Test Runner when not recording to the Dashboard.**

**Comment by jennifer-shehane** [comment]
Closing due to inactivity. We will reopen or credit the original author of the PR for work if this initiative becomes prioritized in the future.

**Pull request closed without merging**
