### PR TITLE
chore: commit packages/graphql/schemas/schema.graphql from PR #29420

### LINKED ISSUE #29656: Uncommitted change to packages/graphql/schemas/schema.graphql after PR #29420
### Current behavior

- PR https://github.com/cypress-io/cypress/pull/29420 leaves change to autogenerated [packages/graphql/schemas/schema.graphql](https://github.com/cypress-io/cypress/blob/develop/packages/graphql/schemas/schema.graphql) uncommitted.

### Desired behavior

Running `yarn` after a PR has been merged (and in general in the `develop` branch) should not produce any differences.

### Test code to reproduce

Ubuntu `22.04.4` LTS, Node.js `18.17.1`, Yarn `1.22.22`

```shell
git clone https://github.com/cypress-io/cypress
cd cypress
git checkout ceb11a355a4e60f9833412cb03d56756b0dc4800 # commit before PR 29420
git clean -xfd
yarn
git status
```

`git status` shows:

```text
HEAD detached at ceb11a355a
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   yarn.lock
```

- (The above uncommitted change is related to issue https://github.com/cypress-io/cypress/issues/29653.)

- Now advance to commit from PR https://github.com/cypress-io/cypress/pull/29420

```shell
git checkout ec1d7994dddc4e3fe0f85d62ba49ad18f703ec51 # commit for PR 29420
yarn
git status
git diff
```

`git status` shows:
```text
HEAD detached at ec1d7994dd
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   packages/graphql/schemas/schema.graphql
	modified:   yarn.lock
```

`git diff packages/graphql/schemas/schema.graphql` shows:

```text
$ git diff packages/graphql/schemas/schema.graphql
diff --git a/packages/graphql/schemas/schema.graphql b/packages/graphql/schemas/schema.graphql
index 658f055c06..88a8155c28 100644
--- a/packages/graphql/schemas/schema.graphql
+++ b/packages/graphql/schemas/schema.graphql
@@ -1236,6 +1236,8 @@ enum ErrorTypeEnum {
   PORT_IN_USE_LONG
   PORT_IN_USE_SHORT
   PROJECT_ID_AND_KEY_BUT_MISSING_RECORD_OPTION
+  PROXY_ENCOUNTERED_INVALID_HEADER_NAME
+  PROXY_ENCOUNTERED_INVALID_HEADER_VALUE
   RECORDING_FROM_FORK_PR
   RECORD_KEY_MISSING
   RECORD_PARAMS_WITHOUT_RECORDING
```

### Cypress Version

`13.11.0` ec1d7994dddc4e3fe0f85d62ba49ad18f703ec51

### Node version

`v18.17.1` LTS

### Operating System

Ubuntu `22.04.4` LTS

### Debug Logs

See above

### Other

FYI @BernardoSousa03

### PR DESCRIPTION
**Pull request by MikeMcC399**
- Closes https://github.com/cypress-io/cypress/issues/29656

### Additional details

- PR https://github.com/cypress-io/cypress/pull/29420 leaves change to autogenerated [packages/graphql/schemas/schema.graphql](https://github.com/cypress-io/cypress/blob/develop/packages/graphql/schemas/schema.graphql) uncommitted.

### Steps to test

Execute:

```shell
git clean -xfd
yarn
git status
```

and confirm that there are no differences reported for `packages/graphql/schemas/schema.graphql`

### How has the user experience changed?

This issue affects contributors only.

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by jennifer-shehane — APPROVED** [review]

**Review by ryanthemanuel — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Please avoid merging develop if you can as it extends the time for us to merge in the PRs

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

I'll leave it to you then. I was just doing this because there were CI failures.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Yes I know. We can rerun failed only so it's a bit faster. No worries.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

Thank you for explaining! It would be good to add guidance to the Contributing document about what to do after PR submission, as it is not clear what external contributors should be doing exactly. Let me put this into a new issue to be clear about what questions need to be answered for optimal PR handling.

**Pull request merged**
