### PR TITLE
Append to cy.writeFile

### LINKED ISSUE #1249: Add feature to append instead of overwrite with cy.writeFile
- Operating System:
- Cypress Version:
- Browser Version:

### Is this a Feature or Bug?
Feature Request

### Current behavior:
`cy.writeFile` will only overwrite. In order to append, you have to read a file (making sure it already exists...), add the contents of that file to what you want to append to it in memory, and then do another writeFile call. 

### Desired behavior:
add a `{"append": true}` option to `cy.writeFile`.

Since I am dynamically generating tests, this would allow me to aggregate specific metrics from each test into a single JSON file without working around it.

### PR DESCRIPTION
**Pull request by lilaconlee**
Adds `options.flag` to `cy.writeFile`, which allows appending to a file with a flag like so:
```js
cy.writeFile('path/to/message.txt', 'Hello World', {flag: "a+"}))
```

- fixes #1249

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Where do these flags come from? I'm unfamiliar.

**Comment by jennifer-shehane** [comment]
Nevermind, found it in the docs PR. I was not familiar as I have very limited experience of fs.

**Comment by chrisbreiding** [comment]
Has this been tested with all the flags supported by `fs.writeFile`? Certain flags are supposed to error if the path either exists or does not exist. 

I'm worried one of the following is the case:

* It won't error, which might confuse users because it doesn't match what `fs.writeFile` documents. In this case, we need to choose whether to truly mimic `fs.writeFiles`'s documented behavior or add a note to the `cy.writeFile` document that certain flags won't error as they do with `fs.writeFile`.
* It does error, but it's a non-user-friendly error. In this case, we should wrap the error with a friendlier message.

**Comment by lilaconlee** [comment]
Think the error is okay and doesn't require any additional logic, but I would be down to wrap it if we think the `fs` error is unclear. I'm on the side of keeping the `fs` error as it'd be more google-able and the fix for`fs.writeFile` and `cy.writeFile` would be similar. 

screen shot 2018-09-28 at 10 20 07 am

**Comment by jennifer-shehane** [comment]
Docs PR: https://github.com/cypress-io/cypress-documentation/pull/942

**Pull request merged**
