### PR TITLE
Set window size to a better default size when running Chrome headless

### LINKED ISSUE #6210: Cypress screenshot and video size are restricted to 800 x 600 in Chrome Headless
### Current behavior:
When running cy.screenshot(), the screenshot differs when running in Chrome Headless vs Chrome Headed vs Electron Headless:

Electron Headless:
test1

Chrome Headed:
test1

Chrome Headless:
test1

### Desired behavior:
It seems as though any screenshot taken while running headless chrome will produce an image that is only 800x600 pixels. This is an issue because i would like to run all tests using headless chrome, however the screenshots headless chrome produces are not large (wide/tall) enough to fully capture my application.

When running chrome headless, changing the size using cy.viewport only works when the given size is less than 800x600. For example if i call cy.viewport(1920,1080) then call cy.screenshot(), the screenshot will be 800x600. However if i call cy.viewport(700,500) then call cy.screenshot(), the screenshot will be 700x500.

### Test code to reproduce
```js
cy.visit('https://google.com/')

cy.screenshot('test1') //produces a 800x600 pixel image

cy.viewport(700,500)
cy.screenshot('test2') //produces a 700x500 pixel image

cy.viewport(1920,1080)
cy.screenshot('test3') //produces a 800x600 pixel image
```

### Versions
Cypress 3.8.2
Windows 10
Resolution 1920x1200
node 12.13.1
npm 6.12.1

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- Closes #6210 

### User facing changelog

We now set the default window size when running Chrome headlessly to 1280x720.

### Additional details

- This isn't a completely wholistic fix for our windowsize discrepancies, but this sets a better default for Chrome headless runs. (1280x720 is the max window size when run in xvfb headed, so it likely what most users are used to seeing).
- The original scope of this PR was to also set a default for Firefox, but it seems Firefox --headless records screenshots/videos at maxsize of `1366×694`??? Anyway, I don't have the expertise to figure this out and nobody has opened an issue for this yet, so I've removed it from the scope of this PR.

## Before

(unless overridden by user)

- Chrome `--headless` screenshot & video size: 800x600

## After

(unless overridden by user)

- Chrome `--headless` screenshot & video size: 1280x720

### PR Tasks
- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by brian-mann** [comment]
This is a good start - I'll take it over from here.

**Comment by jennifer-shehane** [comment]
@brian-mann I tried to push in the window size the exact same as `xulStorePath` is set here: 

https://github.com/cypress-io/cypress/blob/issue-6210-increase-default-headless-size/packages/server/lib/browsers/firefox.ts#L374:L374

But I do not see any effective change in the sizing when running headlessly in Firefox. Please just push this in as is and we will open a new issue for firefox since people only want the Chrome sizing fix and this is an improvement to the code base.

**Review by kuceb — CHANGES_REQUESTED** [review]
This needs an e2e test that verifies the browser is the correct dimensions. I'll add one

**Review by kuceb — APPROVED** [review]
Test added

**Comment by brian-mann** [comment]
We're still not doing this for firefox right?

**Comment by brian-mann** [comment]
If not can we open an issue and reference this PR? The code for doing this in firefox should be extremely minor / easy to write.

**Comment by brian-mann** [comment]
Also - worth noting - although we are setting the screen size when running headlessly in Chrome - we ideally want to also set a default screen size when running in CI - or alternatively if we detect XVFB...

That would standardize the videos for all users recording in CI, etc.

**Comment by brian-mann** [comment]
cc @Bkucera @jennifer-shehane

**Pull request merged**
