### PR TITLE
chore(component-testing): add pwa plugin to example repo

### LINKED ISSUE #15968: [7.1.0] Vue Component testing - not working when trying to use with PWA plugin
### Current behavior
The cypress test runner crash when using Vue with the [PWA plugin](https://cli.vuejs.org/core-plugins/pwa.html#vue-cli-plugin-pwa)

image
image
image

### Desired behavior
To work with the PWA plugin added to a Vue project

### Test code to reproduce
Here is the project made with vue-cli that includes the pwa plugin already install and cypress ct that was being used to test and make the screenshots
https://github.com/xanxuz/vue-cypress-ct

### Versions
Cypress v7.1.0
Yarn v1.22.5
Node v15.14.0
Windows 10

### PR DESCRIPTION
**Pull request by lmiller1990**
- Related #15968

### User facing changelog

Add an example of how to conditionally remove plugins that are currently not compatible with component testing.

### Additional details

Component testing uses `html-webpack-plugin` internally. The latest version is 5.x. We support 4.x and 5.x Some projects still have plugins depending on html-webpack-plugin lifecycle hooks deprecated in 3.x.

We will need some way to support these projects - [around 500 repos still use that hook](https://github.com/search?p=2&q=htmlWebpackPluginBeforeHtmlProcessing&type=Code), and who knows how many users depend on those plugins.

Until we have a robust solution, instead of patching our dev-server intermittently, I added an example showing how to filter out plugins in userland. Typically plugins depending on `html-webpack-plugin`  don't make sense in component testing anyway (for example PWA with service worker, noted as production only in their own readme).

### How has the user experience changed?

No change.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by agg23** [comment]
Why are we filtering out `HtmlPwaPlugin`? I understand that we want to give an example, but it's not very clear why it's necessary/when the user would have to apply this change.

**Comment by lmiller1990** [comment]
@agg23 good question... the PWA plugin relies on webpack-html-plugin@3 specific APIs, and currently we only support webpack-html-plugin 4x and 5x. So I filtered it out.

I am not sure where or how to document this 🤔

**Comment by xanxuz** [comment]
> @agg23 good question... the PWA plugin relies on webpack-html-plugin@3 specific APIs, and currently we only support webpack-html-plugin 4x and 5x. So I filtered it out.
> 
> I am not sure where or how to document this 🤔

Well, there could be a Vue/React/Angular sub-section in the Component testing section of the docs. that way, if the cypress team finds more issues targeting a particular framework, they could put it in those sub-sections.

**Review by elevatebart — APPROVED** [review]
Should we have 2 examples?

**Pull request merged**
