### PR TITLE
fix: label text should be clickable to toggle snapshot highlight

### PR DESCRIPTION
**Pull request by marktnoonan**
- Closes https://cypress-io.atlassian.net/browse/UNIFY-1384

### User facing changelog

Fixes switch label to be clickable, not just the switch itself. Switch is also labelled correctly in the Accessibility Tree after this PR. @lmiller1990 noticed this in a PR review on a related part of the code, but it was merged before this could be updated.

### Additional details

Updated test to use `cy.findByLabelText(highlightsLabel)` instead of `cy.get('[id="toggle-highlights"]')` to catch regressions.

### How has the user experience changed?

Previously, text was not clickable to active the switch:

https://user-images.githubusercontent.com/8340719/163885723-a556b235-ae1e-4ab6-8548-704c57a198c6.mov

Now, it is:

https://user-images.githubusercontent.com/8340719/163885752-901bc288-f605-4a4c-9aaf-78a1f757d863.mov

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by rachelruderman** [comment]
Now that the label is clickable, whaddya think about adding `cursor: pointer` on hover?

**Comment by marktnoonan** [comment]
@rachelruderman good point. On a general form field it seems like too much, but here I can see it making it easier for users to discover how it works and not having to be so precise.

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Nice, this has been a pain point for me for a while. Thanks for following up on this.

**Comment by marktnoonan** [comment]
@rachelruderman done!

**Review by rachelruderman — APPROVED** [review]

**Pull request merged**
