### PR TITLE
feat: <ExternalLink /> component enhancements

### PR DESCRIPTION
**Pull request by estrada9166**
- Closes  [UNIFY-1318](https://cypress-io.atlassian.net/jira/software/projects/UNIFY/boards/20?assignee=5ea883deddd45f0b94f5d98d&selectedIssue=UNIFY-1381)

### How has the user experience changed?

Prevent opening external links whit the spacebar

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by marktnoonan — APPROVED** [review]
Looks good!

**Comment by emilyrohrbough** [comment]
@estrada9166 why do we want to change the behavior of the ExternalLink component to not behave like a link and open when the space key is pressed?

**Comment by marktnoonan** [comment]
> @estrada9166 why do we want to change the behavior of the ExternalLink component to not behave like a link and open when the space key is pressed?

Regular links only open with the enter key, the space behavior we added originally here is not standard - so it would be unexpected behavior if a user whose keyboard is focused on a link hits spacebar to do its default thing (usually scroll the page) and we open the link.

**Review by emilyrohrbough — APPROVED** [review]
LGTM - just needs the duplicate test removed.

**Pull request merged**
