### PR TITLE
fix: fix behavior when only using inverted tags

### PR DESCRIPTION
**Pull request by nyghtly-derek**
### User facing changelog
The npm package @cypress/grep now supports configurations that only use inverted tags.

### Additional details
Follow up for: https://github.com/cypress-io/cypress-grep/pull/149

### Steps to test
Run tests in `npm/grep/cypress/e2e/unit.js`

### How has the user experience changed?
N/A

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by nyghtly-derek** [comment]
@jordanpowell88 I fixed the semantic naming failure, but I think that the remaining failures are out of my control.

**Comment by nyghtly-derek** [comment]
I guess I'll just keep on pressing this update branch button...

**Comment by nyghtly-derek** [comment]
Fixed the linting errors by following this part of the contributors guide: https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#getting-started

**Comment by nyghtly-derek** [comment]
I think it's just a matter of re-trying now, but it seems that I need to wait for another branch update opportunity in order to trigger that.

**Comment by nyghtly-derek** [comment]
@jordanpowell88 Think you can help me out here?

**Comment by BlueWinds** [comment]
Thank you for your patience with all our test failures. ^^;;  I'll take a look at this tomorrow once we're done getting Cy12 out the door.

**Review by BlueWinds — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

**Comment by nyghtly-derek** [comment]
Yay 😄

**Pull request merged**
