### PR TITLE
fix: update visibility to support parent overflow:clip without height/width

### PR DESCRIPTION
**Pull request by senpl**
- Closes https://github.com/cypress-io/cypress/issues/23852

### Additional details

[overflow:clip](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#browser_compatibility) was added in Chrome 90 and was never incorporated back into the visibility logic. Added `clip` to the `OVERFLOW_PROPS` to correctly handle visibility checks.

Note: this PR does not address the [overflow-clip-margin](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-clip-margin) property which has limited support in browsers.

### Steps to test
Verify when a parent element has `overflow:clip` and no height/width, a child element now returns as `hidden`.

### How has the user experience changed?
Before:
Screenshot 2024-11-19 at 3 07 26 PM

After:
Screenshot 2024-11-19 at 3 07 44 PM

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by jennifer-shehane — DISMISSED** [review]
@senpl The visibility spec is failing in Firefox for this PR. Please address.

**Comment by senpl** [comment]
Fixed for firefox. Fix is now not that general but still fix reported issue.

**Comment by jennifer-shehane** [comment]
We've decided to prioritize looking into these visibility fixes in Quarter 4 of this year, when we intend to spend time on Cypress 14 release. It will ease any concerns we have around releasing breaking changes with these fixes and also help us plan the proper time to review these. Tracking here: https://github.com/cypress-io/cypress/issues/29925

**Comment by jennifer-shehane** [comment]
Updated the base branch to go against release/14.0.0

**Review by ryanthemanuel — APPROVED** [review]

**Review by AtofStryker — APPROVED** [review]

**Pull request merged**
