### PR TITLE
fix: "type" action with {upArrow} and {downArrow} arguments to simula…

### LINKED ISSUE #29611: Typing `{{arrowUp}}` should trigger event on `input[type=number]`
### Current behavior

Currently, `get('input[type=number]').type('{{arrowUp}}')` has the same behavior as calling `input.stepUp()` only which will not trigger any event, like when we press arrow up on the input.

### Desired behavior

Typing `{{arrowUp}}` should be equal as pressing arrow up button on a focused number input. Pressing real arrow up button will trigger `input` event.

### Test code to reproduce

This will not show any alert:

```html
<input type="number" oninput="alert('Testing')" value=3>

cy.get('#a input').type('{upArrow}').should(haveValue(4))
```

versus

```html
<input type="number" oninput="alert('Testing')" value=3>

cy.get('#a input').type(4).should(haveValue(4))
```

which will show an alert. Or try the input DOM in browser and press arrow up button.

### Cypress Version

13.2.0

### Node version

18.16.0

### Operating System

NixOS 23.11

### Debug Logs

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by thevladisss**
…te native behavior of input[type=number]

- Closes https://github.com/cypress-io/cypress/issues/29611

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@thevladisss Thanks for the contribution! Can you add a changelog entry to resolve this failure: https://github.com/cypress-io/cypress/actions/runs/9451020052/job/26030988869?pr=29636

Running all of the tests now to ensure nothing else broke.

**Comment by thevladisss** [comment]
> @thevladisss Thanks for the contribution! Can you add a changelog entry to resolve this failure: https://github.com/cypress-io/cypress/actions/runs/9451020052/job/26030988869?pr=29636
> 
> Running all of the tests now to ensure nothing else broke.

Just added

**Review by jennifer-shehane — APPROVED** [review]
I manually tested that this does resolve the issue of input and change events not being triggered although they are triggered when manually typing up and down arrow on the element. 

I'm actually surprised we had no tests around this stepUp functionality. 

Additionally, I think the stepUp logic should be expanded to more input types. See support described in: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/stepUp where we could just remove this line (or be more specific on it if there are perf implications). 

```js
if ($elements.isInputType(el, 'number')) {
```

This is a separate issue however and can be done in a separate PR. As this is now, it is an improvement and is good to merge in.

**Comment by thevladisss** [comment]
> I manually tested that this does resolve the issue of input and change events not being triggered although they are triggered when manually typing up and down arrow on the element.
> 
> I'm actually surprised we had no tests around this stepUp functionality.
> 
> Additionally, I think the stepUp logic should be expanded to more input types. See support described in: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/stepUp where we could just remove this line (or be more specific on it if there are perf implications).
> 
> ```js
> if ($elements.isInputType(el, 'number')) {
> ```
> 
> This is a separate issue however and can be done in a separate PR. As this is now, it is an improvement and is good to merge in.

Great to hear this.  

With regard to other input types and how they interact with stepper functions, I'd be happy to work on it as on separate issue

**Comment by thevladisss** [comment]
Is anything else from my end expected on this PR apart from keeping it up-to-date with "develop" ?

**Comment by jennifer-shehane** [comment]
@thevladisss No, I need to get another reviewer on my side in our sprint next week.

**Review by ryanthemanuel — APPROVED** [review]

**Pull request merged**
