### PR TITLE
feat: cy.selectFile() (#19332)

### LINKED ISSUE #170: Adding Ability to Submit File to Input Element From Local Filesystem (file upload)
**Description**
Our app takes a file from an user, does some work with it, and produces outputs based on the input the user provides.  A bunch of things happen in the system during the processing and we expect project pages to be generated in a certain fashion after a project successfully completes.  We need to be able to submit files through our webpage to test the affects of this process.

### PR DESCRIPTION
**Pull request by BlueWinds**
- Closes #170

### User facing changelog
Adds [`Cypress.Buffer`](https://docs.cypress.io/api/utilities/buffer), exposing the Buffer polyfill for working with binary data.

Adds native support for `.selectFile()`, allowing interaction with file input elements as well as simulating a user drag-dropping files over the document.

```javascript
cy.get('input[type="file"]').selectFile('cypress/fixtures/myfixture.json');
```

The API is similar to [cypress-file-upload](https://github.com/abramenal/cypress-file-upload), and we have provided a [migration guide](https://docs.cypress.io/guides/references/migration-guide#Attaching-Files) for previous users of that plugin.

For full details, see the [`.selectFile()` documentation](https://docs.cypress.io/api/commands/selectfile).

### Additional details
The documentation and migration guide contain extensive information about all the options and features of this new command.

### PR Tasks
- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? TODO - waiting on https://github.com/cypress-io/cypress-documentation/pull/4241 to merge into `unification`, will then make a docs PR against `master`.
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by AtofStryker — APPROVED** [review]

**Comment by BlueWinds** [comment]
@cowboy - Added `Cypress.Buffer` to this branch rather than its own PR, because it was a small change and it also didn't make sense to do separately (I would still have to update this PR as well, to use it in the tests / type docs).

**Review by AtofStryker — COMMENTED** [review]
@BlueWinds looks like theres an issue adding the `type BufferModule = import("buffer/")` to the declaration file. Is that right?

**Comment by BlueWinds** [comment]
> @BlueWinds looks like theres an issue adding the `type BufferModule = import("buffer/")` to the declaration file. Is that right?

Ah, I thought I'd fixed that. Pushed a new change that should address it for real this time.

**Review by AtofStryker — APPROVED** [review]

**Review by cowboy — APPROVED** [review]

**Comment by tnrich** [comment]
A heads up that the changelog link to the blog about the new functionality is broken: 

https://cypress.io/blog/2022/01/18/uploading-files-with-selectfile/

image

**Comment by BlueWinds** [comment]
We released the code late in the evening and didn't publish the blog post until the following day. Fixed now, thanks for the report.

**Pull request merged**
