### PR TITLE
feat: cypress init command

### LINKED ISSUE #619: Proposal `cypress init` command
We no longer seed anything when running `cypress run` on a fresh project. 

Instead we now error: #618 

For that reason we should give users the ability to seed / scaffold out files from the command line instead of using the GUI.

Proposal add a `cypress init` command which does this.

Bonus points if we offer an `inquirer` view enabling the user to select what they want to. We could even explain what each one does.

### PR DESCRIPTION
**Pull request by sainthkh**
* Closes #619

### User facing changelog
Scaffold Cypress with `cypress init`. 

#### Options
Screenshot from 2020-04-15 15-04-34

#### Questions
Peek 2020-04-15 15-08

#### Why was this change necessary?
Many developers wanted to control how Cypress is scaffolded. 

#### What is affected by this change?
You can control how Cypress is scaffolded.

#### Any implementation details to explain?
* I only wrote unit tests because AFAIK, console input cannot be e2e-tested. If there is a way to do that, please help.
* I used `prompts` rather than `inquirer` because it's small.

### How has the user experience changed?
Check above.

It doesn't change anything. It just adds `cypress init` command.

### PR Tasks
* [x] Have tests been added/updated?
* [ ] Has the original issue been tagged with a release in ZenHub? 
* [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
* [N/A] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
* [N/A] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by sainthkh** [comment]
flaky test.

**Comment by sainthkh** [comment]
* I was thinking about the case of the folder name, `false`. Maybe, I went too much.
* When no-fixtures=true and fixtures-path is given, it throws an error. The lines below do that job.

https://github.com/cypress-io/cypress/blob/9bf8fabbdf86f9a8fa436cf7f8810f4f655278c6/packages/server/lib/modes/init/scaffold/args.ts#L35-L45

**Comment by jennifer-shehane** [comment]
We're going to have to dedicate some time to reviewing this implementation. At the moment we've decided to postpone a full review until a later sprint.

**Comment by sainthkh** [comment]
It's fine. I can wait.

**Comment by sainthkh** [comment]
It seems that [`create-cypress-tests`](https://www.npmjs.com/package/create-cypress-tests) replaces this PR. Close it.

**Pull request closed without merging**
