### PR TITLE
chore: use CircleCI M1 runners

### PR DESCRIPTION
**Pull request by flotwig**
- Closes 

### Additional details

- This is a branch for testing out the beta CircleCI M1 runners, and switching off of our self-hosted runner.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by flotwig** [comment]
This is currently failing: https://app.circleci.com/jobs/github/cypress-io/cypress/2013226

The cause seems to be that there is no active desktop session for the M1 user.

This user fixed it by logging in via VNC, however, this is not an option since it's Circle's machine: https://developer.apple.com/forums/thread/707858

Reaching out to Circle to see what they recommend. E: according to Circle, this is a known issue that will be fixed before stable M1 runners are released.

**Comment by flotwig** [comment]
The issue mentioned above still seems to exist as of now: https://app.circleci.com/pipelines/github/cypress-io/cypress/49002/workflows/31c51525-6197-4c2a-94ff-d5ac996f370a/jobs/2039308

**Comment by flotwig** [comment]
Circle is making the M1 support public: https://circleci.com/blog/m1-mac-resource-class/

However, it still seems to be unable to run Electron: https://app.circleci.com/pipelines/github/cypress-io/cypress/50111/workflows/e1c824a2-f308-4869-815e-f6bb864984c9/jobs/2079977 Contacting their support again.

**Comment by emilyrohrbough** [comment]
Closing draft. Will re-open once CircleCI supports running Electron on their M1 instances.

**Comment by jennifer-shehane** [comment]
@emilyrohrbough Can you open a ticket with CircleCI around this? That was the last task remaining to followup on this. https://support.circleci.com/hc/en-us/requests/new?ticket_form_id=855268

**Comment by emilyrohrbough** [comment]
@jennifer-shehane I assume Zach already opened a ticket since he said he was contacting support again.

**Comment by flotwig** [comment]
@emilyrohrbough I did not open a ticket because I wouldn't be around to resolve it 😛 but this PR is ready to go once they fix the bug preventing Electron from spawning during the smoke test.

**Comment by AtofStryker** [comment]
closing in favor of #27319

**Pull request closed without merging**
