### PR TITLE
[WIP] allow bearer auth and make #4837

### LINKED ISSUE #4837: Optional values: bearer and sendImmediately are missing in Cypress.Auth interface (TypeScript)
### Current behavior:

The current interface for Auth:

```js
 interface Auth {
    username: string;
    password: string;
  }
```

### Desired behavior:

Both `bearer` and `sendImmediately` should be optional props:

```js
  interface Auth {
    username: string;
    password: string;
    bearer?: string;
    sendImmediately?: boolean;
  }
```

### Steps to reproduce: (app code and test code)

Try passing either `bearer` or `sendImmediately` as options

### Versions

Cypress 3.3.2

### PR DESCRIPTION
**Pull request by gabbersepp**
- Closes #4837

### User facing changelog

The VisitOptions type definitions were extended to allow Bearer Authentication.

### Additional details

`cy.visit()` can be used to authenticate through basic auth:
`cy.visit('http://localhost:3000', { auth: {username: "xxx", password: "xxxx} });`
 
the JS code allows authentication through bearer auth but this was not reflected in the type definitions.

### How has the user experience changed?

N/A

### PR Tasks
https://github.com/cypress-io/cypress-documentation/pull/2168

### CODE REVIEW

**Comment by gabbersepp** [comment]
Thanks for your review. I will hopefully find a solution. Will take some time I think :-)

**Comment by flotwig** [comment]
> Thanks for your review. I will hopefully find a solution. Will take some time I think :-)

No worries, just let me know if you have any questions.

**Comment by jennifer-shehane** [comment]
Hey @gabbersepp, will you have time to address the changes asked? We will have to close this due to inactivity if not.

**Comment by gabbersepp** [comment]
@jennifer-shehane Hey, there are unanswered questions in the issue https://github.com/cypress-io/cypress/issues/4837 regarding cypress internals that stopped me from finish the work. But I will close the PR to enable other people to work on the issue who have more experience.

**Pull request closed without merging**
