### PR TITLE
add "cypress info" command

### LINKED ISSUE #4540: Having a dedicated command to show up local environment information 'cypress info'
## Feature Request

Most CLI tools these days are shipped with a dedicated `info` command which shows up local environment information. Also, the present issue template includes a section which expects to have information regarding the local environment.

With this all the user has to do is just copy and paste the information as shown by `cypress info` within the respective section.

### PR DESCRIPTION
**Pull request by bahmutov**
- Closes #4540

### User facing changelog

Run the command `cypress info` to see the locally detected browsers and other information related to Cypress. See images below for screenshots

```
$ npx cypress info
Displaying Cypress info...

Detected 8 Browsers installed

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 79.0.3945.130
  - Path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/chrome-stable

2. Canary
  - Name: chrome
  - Channel: canary
  - Version: 82.0.4054.0
  - Path: /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/chrome-canary

3. Edge
  - Name: edge
  - Channel: stable
  - Version: 80.0.361.48
  - Path: /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge-stable

4. Edge Dev
  - Name: edge
  - Channel: dev
  - Version: 81.0.410.1
  - Path: /Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge-dev

5. Edge Canary
  - Name: edge
  - Channel: canary
  - Version: 82.0.418.0
  - Path: /Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge-canary

6. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 72.0.2
  - Path: /Applications/Firefox.app/Contents/MacOS/firefox-bin
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox-stable

7. Firefox Developer Edition
  - Name: firefox
  - Channel: dev
  - Version: 73.0
  - Path: /Applications/Firefox Developer Edition.app/Contents/MacOS/firefox-bin
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox-dev

8. Firefox Nightly
  - Name: firefox
  - Channel: nightly
  - Version: 74.0a1
  - Path: /Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox-nightly

Note: To use these browsers, pass their name and channel to the '--browser' field, consult https://on.cypress.io/launching-browsers

Examples:
- cypress run --browser firefox:dev
- cypress run --browser chrome:canary

Cypress Version: 0.0.0
System Platform: darwin (19.2.0)
System Memory: 2.1 GB free 1.2 GB

Application Data: /Users/gleb/Library/Application Support/cypress/cy/development
Browser Profiles: /Users/gleb/Library/Application Support/cypress/cy/development/browsers
Binary Caches: /Users/gleb/Library/Caches/Cypress
```

### Additional details

- `cypress info` CLI calls into the test runner with `--mode=info`, where we just query the launcher and pretty-print found browsers
- in the future we can expand the command and print more utility information, like proxy
- I moved error display in `environment.coffee` to `debug` module to stop showing `Cannot read property 'commandLine' of undefined` on every run

### How has the user experience changed?

See documentation PR and visual snapshots

### PR Tasks

Test locally with `node cli/bin/cypress info --dev`

- [x] need to use `@packages/launcher` from CLI - probably need to call into Cypress binary for this
- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/2509

## Blockers

- Add more information
  * [x] System info
  * [x] Memory / ~~CPU~~
  * [x] App data path
  * [x] Profiles for browsers
  * [x] Cypress cache

## Questions to be answered by the reviewer

- Do we need browser profile path? https://github.com/cypress-io/cypress/pull/6372#issuecomment-584312732
- Combine the name and the version? https://github.com/cypress-io/cypress/pull/6372#issuecomment-584336238

### CODE REVIEW

**Comment by brian-mann** [comment]
```
Displaying Cypress info...

Detected 8 Browsers installed:

1. Chrome
  - Name: chrome
  - Version: 79.0.3945.130
  - Channel: stable
  - Path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/chrome

2. Canary
  - Name: chrome
  - Version: 82.0.4054.0
  - Channel: canary
  - Path: /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/chrome

3. Edge
  - Name: edge
  - Version: 80.0.361.48
  - Channel: stable
  - Path: /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge

4. Edge Dev
  - Name: edge
  - Version: 81.0.410.1
  - Channel: dev
  - Path: /Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge

5. Edge Canary
  - Name: edge
  - Version: 82.0.418.0
  - Channel: canary
  - Path: /Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge

6. Firefox
  - Name: firefox
  - Version: 72.0.2
  - Channel: stable
  - Path: /Applications/Firefox.app/Contents/MacOS/firefox-bin
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox

7. Firefox Developer Edition
  - Name: firefox
  - Version: 73.0
  - Channel: dev
  - Path: /Applications/Firefox Developer Edition.app/Contents/MacOS/firefox-bin
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox

8. Firefox Nightly
  - Name: firefox
  - Version: 74.0a1
  - Channel: nightly
  - Path: /Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox

Note: To use these browsers, pass their name to the '--browser' field

Examples: 
- cypress run --browser firefox:dev
- cypress run --browser chrome:canary

Cypress Version: 0.0.0
System Platform: darwin (19.2.0)
System Memory: 17179869184 free 155295744

Application Data: /Users/gleb/Library/Application Support/Cypress/cy/development
Browser Profiles: /XXX/YYYY/etc/etc
Binary Caches: /Users/gleb/Library/Caches/Cypress
```

Do a diff with my text against yours to see all the changes.

It's worth using `chalk` extensively here to group / aggregate the important fields, key/values, etc.

Stretch goal: for providing examples of running browsers, I think we should display the *actual* browsers found by taking a random sample of 2-3 browsers detected. That way the example text matches exactly what the user would write.

**Review by brian-mann — CHANGES_REQUESTED** [review]
```
Displaying Cypress info...

Detected 8 Browsers installed:

1. Chrome
  - Name: chrome
  - Version: 79.0.3945.130
  - Channel: stable
  - Path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/chrome

2. Canary
  - Name: chrome
  - Version: 82.0.4054.0
  - Channel: canary
  - Path: /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/chrome

3. Edge
  - Name: edge
  - Version: 80.0.361.48
  - Channel: stable
  - Path: /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge

4. Edge Dev
  - Name: edge
  - Version: 81.0.410.1
  - Channel: dev
  - Path: /Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge

5. Edge Canary
  - Name: edge
  - Version: 82.0.418.0
  - Channel: canary
  - Path: /Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge

6. Firefox
  - Name: firefox
  - Version: 72.0.2
  - Channel: stable
  - Path: /Applications/Firefox.app/Contents/MacOS/firefox-bin
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox

7. Firefox Developer Edition
  - Name: firefox
  - Version: 73.0
  - Channel: dev
  - Path: /Applications/Firefox Developer Edition.app/Contents/MacOS/firefox-bin
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox

8. Firefox Nightly
  - Name: firefox
  - Version: 74.0a1
  - Channel: nightly
  - Path: /Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin
  - Profile path: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox

Note: To use these browsers, pass their name to the '--browser' field

Examples: 
- cypress run --browser firefox:dev
- cypress run --browser chrome:canary

Cypress Version: 0.0.0
System Platform: darwin (19.2.0)
System Memory: 17179869184 free 155295744

Application Data: /Users/gleb/Library/Application Support/Cypress/cy/development
Browser Profiles: /XXX/YYYY/etc/etc
Binary Caches: /Users/gleb/Library/Caches/Cypress
```

Do a diff with my text against yours to see all the changes.

It's worth using `chalk` extensively here to group / aggregate the important fields, key/values, etc.

Stretch goal: for providing examples of running browsers, I think we should display the *actual* browsers found by taking a random sample of 2-3 browsers detected. That way the example text matches exactly what the user would write.

Ideas: 
- add whether or not this is a detected CI environment
- add whether proxy settings are enabled / disabled
- add whether or not special environment variables are set which override cypress's behavior

**Comment by bahmutov** [comment]
## Question

Printing profile path for each detected browser seems like too much

Screen Shot 2020-02-10 at 2 36 43 PM

Especially since they all are subfolders under browser profiles folder

Screen Shot 2020-02-10 at 2 36 51 PM

**Comment by bahmutov** [comment]
I have picked the same colors
```
// color for numbers and short values
const n = chalk.green
// color for paths
const p = chalk.cyan
// color for accents and examples
const a = chalk.yellow
```

Looks good on white and black backgrounds

Screen Shot 2020-02-10 at 2 55 38 PM

Screen Shot 2020-02-10 at 2 56 14 PM

I also added printing versions cached of the binary - because sometimes you want to see it, especially on CI

**Comment by bahmutov** [comment]
## Question

Having a name, and channel, and version on separate lines seems to duplicate the header line. 

Screen Shot 2020-02-10 at 3 22 49 PM

I think we can combine them into 2 lines

Screen Shot 2020-02-10 at 3 23 39 PM

**Comment by brian-mann** [comment]
1. My first instinct was to agree with putting channel in `Name`, but then I thought about how the `Cypress.browser` object works, and it separates them out. The `--browser` argument is really a composite of `name:channel` with `channel` being `stable` by default if omitted.

2. You could shorten `Profile Path` to be `Profile` only. And I think I agree, but maybe we could conditionally show `Profile` **only if** the browser's profile has already been created. Otherwise, omit it. That would add an extra bit of clarity to `cypress info`.

**Comment by bahmutov** [comment]
- only showing `Profile:` for a browser if the folder exists

Screen Shot 2020-02-10 at 4 27 28 PM

- removed listing cached binaries instead will expand that list into `cypress cache list` with sizes in a separate PR

Screen Shot 2020-02-10 at 4 27 41 PM

**Review by brian-mann — CHANGES_REQUESTED** [review]
- Detected `N` browsers installed:
- Can we format the memory so its human readable? `17.5gb`, etc?
- Fix browser note:

```
Note: to run these browsers, pass <name>:<channel> to the `--browser` flag

Examples:
- example 1
- example 2

Learn More: <link>
```

**Comment by brian-mann** [comment]
- What about displaying special things in env vars that change Cypress behavior?
- What about displaying proxy settings? 
- What about displaying CI provider (maybe adding which env vars we're using from CI?)

**Comment by brian-mann** [comment]
Not worth doing now, but worth mentioning - as this is orthogonal to another PR we're working on... we should think about displaying the primary display's resolution on here as well.

**Comment by bahmutov** [comment]
Updated some text, and added human-friendly memory formatting

Screen Shot 2020-02-10 at 4 50 30 PM

**Comment by bahmutov** [comment]
added a little section that prints any detected proxy-related environment variables

Screen Shot 2020-02-10 at 5 00 23 PM

**Comment by bahmutov** [comment]
Added printing `CYPRESS_` environment variables is record key masked if present

```
$ NO_PROXY=foo HTTP_PROXY='another one' \
CYPRESS_NO_INSTALL=1 CYPRESS_RECORD_KEY=fff \
node cli/bin/cypress info --dev
```

Screen Shot 2020-02-10 at 5 15 56 PM

**Review by brian-mann — CHANGES_REQUESTED** [review]
- `Detected 9 browsers installed:` colon missing
- move the env vars + the proxy config immediately beneath the browsers text
- don't use long text form when there are not env vars or proxy settings detected

```
Displaying Cypress info...

Detected 9 browsers installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 79.0.3945.130
  - Executable: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  - Profile: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/chrome-stable

2. Canary
  - Name: chrome
  - Channel: canary
  - Version: 82.0.4055.0
  - Executable: /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary

3. Edge
  - Name: edge
  - Channel: stable
  - Version: 80.0.361.48
  - Executable: /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

4. Edge Beta
  - Name: edge
  - Channel: beta
  - Version: 80.0.361.50
  - Executable: /Applications/Microsoft Edge Beta.app/Contents/MacOS/Microsoft Edge Beta

5. Edge Dev
  - Name: edge
  - Channel: dev
  - Version: 81.0.410.1
  - Executable: /Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev
  - Profile: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge-dev

6. Edge Canary
  - Name: edge
  - Channel: canary
  - Version: 82.0.418.0
  - Executable: /Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary

7. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 72.0.2
  - Executable: /Applications/Firefox.app/Contents/MacOS/firefox-bin
  - Profile: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox-stable

8. Firefox Developer Edition
  - Name: firefox
  - Channel: dev
  - Version: 73.0
  - Executable: /Applications/Firefox Developer Edition.app/Contents/MacOS/firefox-bin

9. Firefox Nightly
  - Name: firefox
  - Channel: nightly
  - Version: 74.0a1
  - Executable: /Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser firefox
- cypress run --browser firefox:nightly

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected

Application Data: /Users/gleb/Library/Application Support/cypress/cy/development
Browser Profiles: /Users/gleb/Library/Application Support/cypress/cy/development/browsers
Binary Caches: /Users/gleb/Library/Caches/Cypress

Cypress Version: 0.0.0
System Platform: darwin (19.2.0)
System Memory: 17.2 GB free 779 MB
```

**Comment by bahmutov** [comment]
Updated: here is output when there are no env vars
```
Displaying Cypress info...

Detected 9 browsers installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 79.0.3945.130
  - Executable: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  - Profile: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/chrome-stable

2. Canary
  - Name: chrome
  - Channel: canary
  - Version: 82.0.4055.0
  - Executable: /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary

3. Edge
  - Name: edge
  - Channel: stable
  - Version: 80.0.361.48
  - Executable: /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

4. Edge Beta
  - Name: edge
  - Channel: beta
  - Version: 80.0.361.50
  - Executable: /Applications/Microsoft Edge Beta.app/Contents/MacOS/Microsoft Edge Beta

5. Edge Dev
  - Name: edge
  - Channel: dev
  - Version: 81.0.410.1
  - Executable: /Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev
  - Profile: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge-dev

6. Edge Canary
  - Name: edge
  - Channel: canary
  - Version: 82.0.418.0
  - Executable: /Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary

7. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 72.0.2
  - Executable: /Applications/Firefox.app/Contents/MacOS/firefox-bin
  - Profile: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox-stable

8. Firefox Developer Edition
  - Name: firefox
  - Channel: dev
  - Version: 73.0
  - Executable: /Applications/Firefox Developer Edition.app/Contents/MacOS/firefox-bin

9. Firefox Nightly
  - Name: firefox
  - Channel: nightly
  - Version: 74.0a1
  - Executable: /Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser firefox:dev
- cypress run --browser firefox:nightly

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings: none detected
Environment Variables: none detected

Application Data: /Users/gleb/Library/Application Support/cypress/cy/development
Browser Profiles: /Users/gleb/Library/Application Support/cypress/cy/development/browsers
Binary Caches: /Users/gleb/Library/Caches/Cypress

Cypress Version: 0.0.0
System Platform: darwin (19.2.0)
System Memory: 17.2 GB free 2.04 GB
```

with vars
```
NO_PROXY=foo HTTP_PROXY='another one' CYPRESS_NO_INSTALL=1 CYPRESS_RECORD_KEY=fff node cli/bin/cypress info --dev
Displaying Cypress info...

Detected 9 browsers installed:

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 79.0.3945.130
  - Executable: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  - Profile: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/chrome-stable

2. Canary
  - Name: chrome
  - Channel: canary
  - Version: 82.0.4055.0
  - Executable: /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary

3. Edge
  - Name: edge
  - Channel: stable
  - Version: 80.0.361.48
  - Executable: /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

4. Edge Beta
  - Name: edge
  - Channel: beta
  - Version: 80.0.361.50
  - Executable: /Applications/Microsoft Edge Beta.app/Contents/MacOS/Microsoft Edge Beta

5. Edge Dev
  - Name: edge
  - Channel: dev
  - Version: 81.0.410.1
  - Executable: /Applications/Microsoft Edge Dev.app/Contents/MacOS/Microsoft Edge Dev
  - Profile: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/edge-dev

6. Edge Canary
  - Name: edge
  - Channel: canary
  - Version: 82.0.418.0
  - Executable: /Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary

7. Firefox
  - Name: firefox
  - Channel: stable
  - Version: 72.0.2
  - Executable: /Applications/Firefox.app/Contents/MacOS/firefox-bin
  - Profile: /Users/gleb/Library/Application Support/Cypress/cy/development/browsers/firefox-stable

8. Firefox Developer Edition
  - Name: firefox
  - Channel: dev
  - Version: 73.0
  - Executable: /Applications/Firefox Developer Edition.app/Contents/MacOS/firefox-bin

9. Firefox Nightly
  - Name: firefox
  - Channel: nightly
  - Version: 74.0a1
  - Executable: /Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin

Note: to run these browsers, pass <name>:<channel> to the '--browser' field

Examples:
- cypress run --browser firefox:nightly
- cypress run --browser edge:beta

Learn More: https://on.cypress.io/launching-browsers

Proxy Settings:
HTTP_PROXY: another one
NO_PROXY: foo

Learn More: https://on.cypress.io/proxy-configuration

Environment Variables:
CYPRESS_NO_INSTALL: 1
CYPRESS_RECORD_KEY: <redacted>

Application Data: /Users/gleb/Library/Application Support/cypress/cy/development
Browser Profiles: /Users/gleb/Library/Application Support/cypress/cy/development/browsers
Binary Caches: /Users/gleb/Library/Caches/Cypress

Cypress Version: 0.0.0
System Platform: darwin (19.2.0)
System Memory: 17.2 GB free 923 MB
```

**Comment by bahmutov** [comment]
for up-to-date view of the output, check out the test artifact in `ci/circleci: cli-visual-tests` job - this is a terminal output as HTML page with colors

**Comment by bahmutov** [comment]
I have added `cypress info` CLI visual test with sanitized HTML output. See updated run on CI here https://percy.io/cypress-io/cypress-cli/builds/4138877

Note: if CI changes (like Debian version) start breaking our visual diffs, we can either approve new screenshot and be done with it, or add more sanitize rules

image

**Comment by Bkucera** [comment]
a note for later:
lets add a `--json` option to output the data in a machine parseable way. this will be useful for users trying to use data from info-like commands in scripts and tools

**Comment by bahmutov** [comment]
YES. Recently I used netlify cli deploy with —json option and it was such a joy

**Comment by brian-mann** [comment]
@bahmutov unit tests are failing... can you address so we can merge? I believe we are releasing later today

**Comment by bahmutov** [comment]
@brian-mann are you happy with output - I have not updated the unit tests yet, cause I was not sure all features are there for you

**Review by brian-mann — CHANGES_REQUESTED** [review]
Can we change the cli output to be nested in `cli/visual-snapshots` or something similar?

Other than that, this is good to go.

**Comment by brian-mann** [comment]
I think all the tests are passing but this still has WIP in the title

**Comment by bahmutov** [comment]
yeah, I am finishing test writing

**Comment by bahmutov** [comment]
I think this is good for review

**Comment by bahmutov** [comment]
`cypress info` command during build on AppVeyor 

Screen Shot 2020-02-15 at 10 11 50 PM

**Review by brian-mann — APPROVED** [review]

**Comment by maddhruv** [comment]
Also, resolve https://github.com/cypress-io/cypress/issues/6409

**Pull request merged**
