### PR TITLE
fix: #3847 only options.log !== false use options._log.error

### PR DESCRIPTION
**Pull request by ZWkang**
#3847 

i saw the querying.coffee file.
here have some codes :

```js
_.defaults(options, {
  retry: true
  withinSubject: cy.state("withinSubject")
  log: true
  command: null
  verify: true
})
```

it allows you can pass a `options.log` to control `options._log` initialization

```js
return if options.log is false

options._log ?= Cypress.log
  message: selector
  referencesAlias: if aliasObj?.alias then {name: aliasObj.alias}
  aliasType: aliasType
  consoleProps: -> consoleProps
```
the code looks like allow `log: false` to happen.

maybe just use `options._log.error` when `options.log` is `true`

when `options.log` is `false` just return error object

change like this
```js
e.onFail = -> if options.log is false then e else options._log.error(e)
```

### CODE REVIEW

**Comment by ZWkang** [comment]
@jennifer-shehane 

i write some test codes with this new behavior.

**Comment by ZWkang** [comment]
can you review it ? @jennifer-shehane

**Comment by jennifer-shehane** [comment]
@ZWkang Yes, I'll take a look as soon as I can

**Comment by ZWkang** [comment]
Thanks for your help ! @jennifer-shehane

**Pull request merged**
