### PR TITLE
feat: add regex support to GUI spec filter

### LINKED ISSUE #8220: Take into account the search pattern when running all specs in the interactive mode (RegEx)
### Current behavior:

Currently the search pattern does not allow the use of Regular Expressions.

### Desired behavior:

Since I have spec files created for individual brand tests in separate files within separate folders it would be very useful to be able to filter using a regular expression (using the folder separator and maybe include a dropdown to specify .spec.ts, .spec.js, etc.) so I can include the folder(s) and/or sub folder(s) that the spec files exist in.

### Test code to reproduce

Simply include a regular expression in the search pattern (include a back slack or forward slash or asterisks).

### Versions

4.12.1

### PR DESCRIPTION
**Pull request by samueloakley**
* Closes #8220

### User facing changelog

UI spec file search box supports RegEx input rather than just substring matching.

### How has the user experience changed?
Before users could only search by substring matching on file names.

Now users can input RegEx to filter the list of spec files.

### PR Tasks

* [ ] Have tests been added/updated?
* [ ] Has the original issue been tagged with a release in ZenHub? 
* [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
* [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
* [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@samueloakley I see this is in Draft so wasn't sure if you were ready for review. Do you have time to finish writing tests for this?

**Comment by samueloakley** [comment]
@jennifer-shehane Sure, I'll take a look at adding tests later today. I was having some issues with the project on Windows.

**Comment by lukeapage** [comment]
Personally I’d prefer to see magic matching than regex support - similar to when you search for a file name in webstorm or vscode. Eg “port gu” matches “xyz/port/xyz/GUI.spec”

I mention because I am not sure both are compatible.

**Comment by jennifer-shehane** [comment]
@samueloakley As you mentioned in the issue, it is not obvious that regex matching exists in the search with this current implementation. 

After re-looking at the original issue, our team is wondering if the real need here is some checkboxes in the GUI, to filter to "run all" matching specfiles as explained in this issue. https://github.com/cypress-io/cypress/issues/3607

So, right now our team is thinking the Regex search is not something we'd like to support as is.

**Comment by t00** [comment]
@jennifer-shehane this would be a real bummer if this PR was not accepted - currently search is good only if user knows upfront when naming tests which could be run and tested together. When certain test subset needs to be tested due to potential issues with the software being tested - checkboxes or substring won't solve the problem but regex will - login|logout|add (user|group) for example

**Comment by lukeapage** [comment]
We have a lot of specs but I’d prefer fuzzy search eg like what you get in the vscode and webstorm and search by file name - you can enter “cha user” and it would match “charts/integration/user.spec”. Not sure if normal fuzzy logic supports an aspect of regex or fits your requirements but I think it would be more expected. I’d never expect a GUI filter field to be a regex.

**Comment by speedwellsoftware** [comment]
How about adding an option to enable regular expressions? Besides, Cypress is for QA devs, regex is well known, and search can fall back to normal search if expression is invalid, making it an omnibox style search.

**Pull request closed without merging**
