### PR TITLE
[WIP] check that the element is an option el before attempting to access the props of the HTMLOptionElement

### LINKED ISSUE #4194: cy.clear() throws Type Error: Illegal Invocation
### Current behavior:

`cy.clear()` method intermittently throws the following error message shown below 
image

Additional error details below when running from the commandline

image

 
### Desired behavior:

`cy.clear()` should always clear the text area.

### Steps to reproduce: (app code and test code)

Run the below code on the following open-source website: 

```js
cy.visit("http://pie-website.surge.sh/examples/pie-multiple-choice.html");
cy.get('.Component-prompt-8 > .EditorAndToolbar-root-70 > .EditorAndToolbar-editorHolder-72 > .EditorAndToolbar-children-71 > .Editor-slateEditor-69 > div').as('question');
cy.get('@question').clear().type("Test Question");
```

### Versions

Cypress: 3.2.0
Operating System: macOS Mojave 10.4.3
Browser: Electron 59

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #4194 

See https://github.com/cypress-io/cypress/issues/4194#issuecomment-492630542 for more context on the fix.

### CODE REVIEW

**Comment by Bkucera** [comment]
@jennifer-shehane  how did you test this? If you can get a minimal reproducible that would help implementing with simulated events

**Review by kuceb — CHANGES_REQUESTED** [review]
could we add a test? I would recommend a test in type_spec.coffee

**Comment by jennifer-shehane** [comment]
Yeah, I tried to write a test but was unable to get one to exhibit the behavior. It's a bit tricky because I didn't pin down exactly what it is about their DOM/css that causes it to go down this route. I'll try to write a test for this again.

**Comment by jennifer-shehane** [comment]
I suspect the issue comes from something editor.js is doing https://github.com/codex-team/editor.js

**Comment by Bkucera** [comment]
@jennifer-shehane hmm, I thought it was using the slate editor. 

I think we just need to throw an error before we get to calling the native method, so we will get a better error than "illegal invocation"

**Comment by jennifer-shehane** [comment]
@Bkucera Yeah, I agree - just haven't been able to isolate. Figured at the least this check before calling to this native method on a non-option el should be there.

**Comment by jennifer-shehane** [comment]
Closing due to inactivity.

**Pull request closed without merging**
