### PR TITLE
feat: Implement custom resizable box for specs list

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
Implement resizing for specs list drawer:

https://user-images.githubusercontent.com/16926049/106774285-a2361b00-664a-11eb-8d38-a40c2ff8fd2c.mov

### CODE REVIEW

**Comment by JessicaSachs** [comment]
Oh the text highlight is a bummer. How do you think we should solve it?

**Review by JessicaSachs — COMMENTED** [review]
I like the custom ResizeableBox component. Happy to have finer-grained control over the resizing behavior than what split pane's api was giving us. I want to hear your ideas about fixing the text highlight situation. What do you think we should do?

**Comment by elevatebart** [comment]
We could play with [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) when dragging.

**Comment by elevatebart** [comment]
We should also absolutely avoid the wrapping of the file names... that's ugly, but out of scope for this request.

**Comment by JessicaSachs** [comment]
> We could play with [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) when dragging.

Yeah that was my initial thought... I want to be able to select the text when the user clicks on it though.... right?

**Comment by elevatebart** [comment]
Yes, but we can add a class on the body and remove it when release.

**Comment by dmtrKovalenko** [comment]
Closed in favor of #14940

**Pull request closed without merging**
