### PR TITLE
fix: copy other moment properties when wrapping with deprecated warning

### PR DESCRIPTION
**Pull request by bahmutov**
- for https://github.com/cypress-io/cypress/issues/8714
- builds on top of https://github.com/cypress-io/cypress/pull/9398 to copy the other moment properties

Screen Shot 2020-12-03 at 9 28 03 AM

Otherwise our build is broken, and any user using these properties would be broken

Screen Shot 2020-12-03 at 9 36 23 AM

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
It doesn't look like the deprecation warning will be shown when you call `Cypress.moment.duration`, etc.

**Comment by bahmutov** [comment]
yeah, I did not plan to show a warning when accessing every property, but I don't think it should be blocking this fix. After all, the `develop` is fixed, the warning for `Cypress.moment()` is shown and that's the most often use case, right

**Comment by bahmutov** [comment]
Ok, looked at this again - and now it is showing deprecated warning on _any_ function property recursively in `Cypress.moment`

**Review by jennifer-shehane — DISMISSED** [review]
Awesome! Thanks for fixing this. 🙇‍♀️

**Review by jennifer-shehane — APPROVED** [review]
Updated error message to say `Cypress.moment` instead of `Cypress.moment()`. I think showing individual methods as deprecated in TypeScript is unnecessary for this, so good to go.

**Pull request merged**
