### PR TITLE
Add keyboard shortcuts

### PR DESCRIPTION
**Pull request by timidak**
address #248 

### Changes
- add `shortcuts.js` in `reporter/src/lib` with an event handler for keydown events
- adding the event listener in `main.jsx` lifecycle methods by calling `start()` and `stop()`
- pressing the `R` key restarts the tests 
- pressing the `S` key stops the tests
- pressing `F` focuses the spec files window

### CODE REVIEW

**Comment by timidak** [comment]
Could someone help me with my problems? **friendly ping** 🙂

**Comment by thorlacius** [comment]
Is there any reason not to merge if only the two shortcuts that have been implemented?

**Comment by timidak** [comment]
Idk, but I thought it would be nice if everything works correctly. I actually don't want to merge code that only addresses half of the issue. 🤷‍♂ 
It would be nice if someone could look over the PR, also I don't know how to test the shortcuts lib. 😕

**Comment by thorlacius** [comment]
> I actually don't want to merge code that only addresses half of the issue. 🤷‍♂

But it provides most of the value! You've implemented the shortcuts I would learn by heart. The others, and a `?` shortcut for popping up a list of shortcuts, would be nice to add later.

> It would be nice if someone could look over the PR, also I don't know how to test the shortcuts lib. 😕

Yes. How about first branching from `timidak:issue-248`, removing the shortcuts that don't work, and reviewing and merging that into `cypress-io:develop`? Hopefully, someone points out a way to test shortcuts. That would help both in automating the shortcuts that you've already implemented and facilitate (test-driven) development of more shortcuts.

**Comment by jennifer-shehane** [comment]
I'm going to go ahead and review this as is and get some of the keyboard shortcuts in and close this PR - the rest can be a PR for later.

**Comment by brian-mann** [comment]
I'm glad we added the implementation for this - but this feature is completely hidden and I worry that it will be confusing for users if their application **also** binds to these events. When they hit those keystrokes, Cypress (because it is in top) will receive those events, and do it's own thing.

Since the shortcuts map exactly to the UI elements we already have - I believe this PR should have included updates to the UI to help indicate to users which key to press. As it stands, there's no way for users to have any idea these exist at all (or what they do).

I don't believe this should go into our documentation - it's completely unfindable - the best place to put it is at the exact place the user interacts with in the UI, which are the buttons themselves.

**Comment by jennifer-shehane** [comment]
@brian-mann I've added your notes to the original issue (which was not completely closed by this PR anyways) https://github.com/cypress-io/cypress/issues/248

It'd be great if anyone following this PR wants to pick that up.

**Pull request merged**
