### PR TITLE
Improve focus styles for suites and tests in reporter

### LINKED ISSUE #7855: Improve focus UI and keyboard navigation in reporter
### Current behavior:
Currently, the `focus` state when navigating and toggling the sidebar is fairly ugly and could be improved to be more similar to the `hover` state.

This is what it looks like now:
ezgif-6-03b3bf64ebbb

Keyboard controls:
| Key | Action |
| --- | --- |
| tab | move down |
| shift + tab | move up |
| enter | open / close |
| space | open / close |

### Similar behavior in other software:
**Webstorm**

ezgif-6-dcce8aaf609d

A click on the arrow will toggle open/closed, and a double click on the name or to the right of the name will open/close and shift focus.

Keyboard controls:
| Key | Action |
| --- | --- |
| down | move down |
| up | move up |
| left | close |
| right | open (move down if already open) |
| enter | open / close |

**VS Code**

ezgif-6-ea7d8b4fb9e8

A single click on the name (or anywhere on the line item) will open/close.

Keyboard controls:
| Key | Action |
| --- | --- |
| down | move down |
| up | move up |
| left | close |
| right | open (move down if already open) |
| space | open / close |
| enter | rename file |

**Atom**

ezgif-6-4097b9c85f20

A single click on the name (or anywhere on the line item) will open/close.

Keyboard controls:
| Key | Action |
| --- | --- |
| down | move down |
| up | move up |
| left | close |
| right | open (move down if already open) |
| enter | open / close |

**_My Two Cents_**

We should remove the `focus` state when clicking and only leave it for keyboard navigation like we do with the [print to console button](https://github.com/cypress-io/cypress/blob/715d07c1a9308ad215fe35da2775100a31dbf982/packages/reporter/src/errors/test-error.tsx#L81-L88). In addition, the focus state for keyboard navigation should be the same as the hover state, and not include an outline around the name. The keyboard controls are fairly standard for the browser and don't require a change, but I figured I would include them to provide a broader picture (perhaps we could also add additional keyboard shortcuts).

┆Issue is synchronized with this [Jira Story](https://cypress-io.atlassian.net/browse/TR-107) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #7855 

### User facing changelog

Updates the focus states to make both clicking and keyboard navigation in the reporter more attractive

### How has the user experience changed?

Before:

ezgif-6-af01351b8bfe

After:

ezgif-6-95e8bbccb696

### PR Tasks

- [ ] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?

### CODE REVIEW

**Review by JessicaSachs — CHANGES_REQUESTED** [review]
The dot border is removed, which is great... but there is no focus state indicator at all. I thought we had landed on the hover state being the same as the focus state.

e.g. when you click on any row, the gray state remains on the focused row

**Comment by panzarino** [comment]
@JessicaSachs I added the hover state as the focus state, but only when using a keyboard to navigate. I feel like it doesn't look great to have the background lingering around after clicking, especially when hovering over other items, but it is necessary for keyboard navigation. I've reverted those changes so that the focus state now behaves as typically expected from the `:focus` selector.

This is what it looks like now:

ezgif-6-75da93d51e7a

My originally proposed changes for comparison:

ezgif-6-95e8bbccb696

**Comment by JessicaSachs** [comment]
We probably should've gone with something like [this, from Material UI spec](https://material-ui.com/components/tree-view/#basic-tree-view)

**Comment by jennifer-shehane** [comment]
@panzarino I agree with the proposed changes for focus, only having focus affect when using keyboard. It is very weird maintaining the focus style, especially when the test is collapsed. This is currently implemented in the code correct?

I don't think the Material UI design is necessary - I don't think getting lost in the UI is a big concern for users here, the original intent was to clean up the background styles so they don't overwhelm the rest of the styles which I think this accomplishes.

**Comment by panzarino** [comment]
@jennifer-shehane That's how I implemented it originally. I then changed to the way that Jess had mentioned where the background persists. I also agree that it looks better when it does not persist and is only there when using keyboard navigation. I have now reverted to the original version and recommend that be the design that gets merged in.

For disambiguation, this is what it looks like:

ezgif-6-95e8bbccb696

**Review by jennifer-shehane — APPROVED** [review]

**Pull request merged**
