### PR TITLE
feat: adding solid component testing support

### LINKED ISSUE #24586: Solid Mount Support For Component Test
### What would you like?

New library for supporting Solid component testing in npm/solid

### Why is this needed?

To support Cypress Svelte Component Testing

### Other

_No response_

### PR DESCRIPTION
**Pull request by cuixiaorui**
- Closes #24586 

### Additional details

I refer to the [PR](https://github.com/cypress-io/cypress/pull/23553)

Implemented cypress component test support for solid

### TODO
1. No documentation written (similar to this document https://docs.cypress.io/guides/component-testing/quickstart-svelte#Configuring-Component-Testing)
2. did not generate changelog (I do not know how to complete this operation, I hope someone can help me)

### Steps to test

You can scaffold a new solid project with npm init vite and choose Solid. Then you can point yarn cypress:open at the solid project and get to testing!

There are also some system tests in system-tests/test/component_testing_spec.ts that test both webpack and vite.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by marktnoonan** [comment]
Hi @cuixiaorui, first, thank you for this PR. I'm going to close it without review, in light of this comment here: https://github.com/cypress-io/cypress/pull/24250#issuecomment-1307425853 and @lmiller1990's comment here: https://github.com/cypress-io/cypress/issues/24494#issuecomment-1312715440

To summarize: we don't intend to add support for new frameworks to the core Cypress app in the short term. But we do intend to make it easier to write community-owned mount adapters that are as easy for users to adopt as the "officially" supported framework.

**Comment by lmiller1990** [comment]
I am looking into a public API to let you support Solid (and other frameworks) directly in Cypress. Follow progress: https://github.com/cypress-io/cypress/issues/24991

**Comment by JessicaSachs** [comment]
@lmiller1990 or @baus is Solid still out of scope? I was literally about to make an issue/offer a PR when I saw there already was one! First class support for something that's topping the State of JS survey seems like a good move. 😄

---

I just asked a similar question of the Vite team about including it in their starter. They're probably going to have a "minimum number of npm downloads" stat as a metric on if they'll take on the maintenance burden. Seems like a reasonable approach to deciding if something will be 3rd party.

**Comment by baus** [comment]
@JessicaSachs It is on our roadmap to provide support for thirdparty framework implementations including documentation. We would like to use that to encourage support for Solid and other emerging frameworks.

**Comment by lmiller1990** [comment]
I am working on letting third parties slot into launchpad/onboarding right now, I was thinking Solid a good first candidate for "how to plug into launchpad".

There are a few Solid mount adapters around, so you can definitely use CT with it already. There is also SolidStart - the meta framework for Solid, and that should also be pretty easy to support since it's just Vite under the hood.

**Comment by JessicaSachs** [comment]
Yeah, the ecosystem also is struggling with Storybook integration, so there's a clear need for a sandbox that enables component-driven development in the meantime.

LMK when I should take a look and I'll play around.

**Pull request closed without merging**
