### PR TITLE
fix(webpack-dev-server): handle polyfills array for upcoming angular 15 change

### PR DESCRIPTION
**Pull request by Coly010**
- Closes  #24062 

### User facing changelog

n/a

### Additional details

Polyfills for Angular can now be an array of strings, and some of those can be node_modules. 
Therefore, this PR does two things to accommodate this change.

It checks if it is an array, then checks if the path starts with the source root of the project. If it does, it performs the additional path logic, if not, it leaves it as is.

It then adds the include paths of all elements of the polyfills array.

Added additional project fixture for angular 15 as it requires an ES target of 2022 for Angular 15

### Steps to test

Standard happy path for component testing but using Angular@next 

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by ZachJW34** [comment]
@Coly010 I pushed up a change reusing the `angular` project-fixture to reduce the number of files added, and added the new version to some other places where system-tests are run. System-tests seem happy with Angular v15!

**Review by jordanpowell88 — APPROVED** [review]
This looks good to me! Thanks for being proactive on this @Coly010

**Comment by Coly010** [comment]
Awesome! Looks better without the duplicated fixture!

**Review by ZachJW34 — APPROVED** [review]
LGTM!

**Pull request merged**
