### PR TITLE
fix: do not override existingSession setup

### LINKED ISSUE #17805: Cypress session validation failure results in a 'existingSession.setup is not a function' error
### Current behavior

While using the new experimental feature _sessions_ in cypress 8.2.0, adding a session validation routine does not seem to work correctly. Specifically, when a session exists, but the validation routine returns false, an error is thrown saying that the setup function does not exist.

Here is a sample block of code that can reproduce this issue:
Screenshot from 2021-08-19 09-53-14

When running this for the first time:
Screenshot from 2021-08-19 09-52-29

When re-running this test:
Screenshot from 2021-08-19 09-52-45

### Desired behavior

Cypress should fail the validation, and re-run the setup function as specified in the docs. For some reason, the current code somehow loses the setup function when validation fails.

### Test code to reproduce

```js
  it('fails the session setup on the second run', () => {
    var validateFlag = false
    cy.session('test', () => {
      validateFlag = true
      cy.log('setup')
    },
    {
      validate() {
        cy.log('validate')
        if (validateFlag) {
          return true
        }
        else {
          return false
        }
      },
    })
  });
```

### Cypress Version

8.2.0

### Other

_No response_

### PR DESCRIPTION
**Pull request by samtsai**
Use `existingSession.setup` instead of overriding with server stored
session because of string serialization.

This applies the fix mentioned by @bahmutov https://github.com/cypress-io/cypress/issues/17805#issuecomment-929595166

- Closes #17805

### User facing changelog

Fixed an issue with `cy.session` where hard refresh of a test in open mode would fail to recreate the session due to a `TypeError: existingSession.setup is not a function`.

### How has the user experience changed?

**Before**
Screen Shot 2022-04-27 at 11 23 12 AM

**After**
Screen Shot 2022-04-27 at 11 23 28 AM

### PR Tasks

- [X] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
@samtsai This issue has been on my radar for getting Sessions ready for GA support (hopefully soon) and am grateful for your contribution!

**Comment by samtsai** [comment]
> @samtsai This issue has been on my radar for getting Sessions ready for GA support (hopefully soon) and am grateful for your contribution!

Glad to help! I love using Cypress every day and am looking forward to this feature.

**Review by emilyrohrbough — APPROVED** [review]

**Comment by samtsai** [comment]
I don't have access to re-run those failing tests but from what I can see I don't think it's caused by my test. The failing one is labeled flaky.

**Comment by emilyrohrbough** [comment]
@samtsai ahh thanks for calling this out! I've been trying to keep an eye on this and got distracted. Just kicked if off again.

**Pull request merged**
