### PR TITLE
fix: Remove esModuleInterop from ts-node

### LINKED ISSUE #7575: Opinionated TS transpilation without overrides is problematic
### Current behavior:
Cypress recently added better native support for TypeScript, a great step forward, thanks!

However, part of this process added the following defaults for `ts-node`:

https://github.com/cypress-io/cypress/blob/bdcfe42f790a6f0e73e8f4ae2133c62df2de349d/packages/server/lib/util/ts-node-options.js#L13

Specifically, `esModuleInterop` is problematic. This is an opinionated transpilation, and cannot be overridden. Typically when working working with a JS / TS mix, you can either use imports such as

```ts
import * as Foo from 'foo';
```

or you can enable `esModuleInterop` and do

```ts
import Foo from 'foo';
```

In my case, I chose the former, to reduce the "magic" that is done by the TypeScript compiler; however, because Cypress enforces the latter, I get lots of errors along the lines of 

```
TypeError: Foo is not a function
```

### Desired behavior:
A test frameworks authors should not enforce an opinion about how I build my application; this `esModuleInterop` value should be possible to override. I tried manually changing it by editing the downloaded Cypress JS code in `~/.cache`, and the tests ran as expected.

### Test code to reproduce
Working on a minimal reproduction, please give me a bit of time :smile: 

### Versions
Cypress: 4.7.0

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-132) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by sainthkh**
- Closes #7575

### User facing changelog

This option prevents users from not using it. 

#### Why was this change necessary?

This option is too opinionated.

#### What is affected by this change?

A project will break if it meets these 3 conditions:

1. no `tsconfig.json` file
2. plugin/support files in typescript
3. use `import Foo from 'foo'` style

#### Any implementation details to explain?

N/A

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by sainthkh** [comment]
It seems that there is no alternative. 

1\. About using spec files. 

As we know, spec files and plugin/support files use different TypeScript transpiler settings. As for spec files, using opinionated typescript setting is necessary because tsify doesn't have `transpileOnly` option and that's the only way not to lose the traspile speed. 

Because of that, using spec files cannot test if `esModuleInterop` can be overridden for support/plugin files in Cypress.

I explained this in the `plugin` file and removed unnecessary tests in spec files. 

2\. Creating affirmative test.

I found out that it's impossible to create an affirmative test with `math.add`. Because:

| import | esModuleInterop | Result |
| --- | --- | --- |
| `import * as math from './math'` | false | pass |
| `import * as math from './math'` | true | pass |
| `import math from './math'` | false | fail |
| `import math from './math'` | true | pass |

I changed it to simply export `add` function.

**Comment by robcresswell** [comment]
Hello! Is this likely to land in 5.0? See to have stalled for a few weeks. Is there anything I can do to help?

**Comment by jennifer-shehane** [comment]
@robcresswell We're still reviewing the final 5.0 features. Hopefully this gets in. https://github.com/cypress-io/cypress/pull/7753

**Comment by robcresswell** [comment]
Ah sorry, thats poor research on my part. Thanks for the link @jennifer-shehane!

**Comment by jennifer-shehane** [comment]
@sainthkh Will this require any notes on our Migration Guide? Any updates people will need to be aware of for changes they need to make? I just noticed this is the only 5.0 PR that doesn't have specific docs updates.

**Comment by sainthkh** [comment]
When a user doesn't have a tsconfig.json file or define `esModuleInterop: true`, Cypress didn't fail in 4.x, but it might fail after 5.0. Because Cypress now uses the default `esModuleInterop` setting of TypeScript. 

I used 'might', because it wouldn't fail when a user didn't use `import` syntax.

**Comment by chrisbreiding** [comment]
Merging this into #8143 and continuing any work there.

**Pull request merged**
