### PR TITLE
fix: Have @cypress/schematic install as devDependency by default

### LINKED ISSUE #16954: schematic : should be installed as a devDependency
### Current behavior

When using the command `ng add @cypress/schematic` the library is installed as a `dependency`.

### Desired behavior

The schematic library should be installed as a `devDependency`.

### Fix
https://angular.io/guide/schematics-for-libraries#define-dependency-type

Add the following to the schematic `package.json`:
```json
"ng-add": {
  "save": "devDependencies"
}
```

### Versions
1.3.0

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #16954 

### User Facing Changelog

N/A

### Additional Details

>Use the `save` option of `ng-add` to configure if the library should be added to the `dependencies`, the `devDepedencies`, or not saved at all in the project's `package.json` configuration file. https://angular.io/guide/schematics-for-libraries#define-dependency-type
- Not sure if there’s a way y’all have set up already to test this.

### CODE REVIEW

**Comment by Badisi** [comment]
This should be added in the `package.json` of the schematic not in the `collection.json`.

**Comment by admah** [comment]
@jennifer-shehane I went ahead and updated the code. Since this is an external package it might be best to have the base branch as `master` to get these changes in faster. What do you think about that?

**Comment by jennifer-shehane** [comment]
Yep, updated the base branch to master. Yah I was a little unsure how the package.json was later generated for consuming and saw this `ng-add` in there so though it might've been the right place. Thanks for fixing.

**Comment by admah** [comment]
@jennifer-shehane I'm going to close this PR in favor of #16965

**Pull request closed without merging**
