### PR TITLE
fix: writeFile returns string instead JSON

### PR DESCRIPTION
**Pull request by rezaxdi**
According to [docs](https://docs.cypress.io/api/commands/writefile.html#JSON), if input of writeFile is an object, it should return an object after successful write instead of a string. 

This issue was mentioned here : [While writing to a file and then asserting a Cypress.io test, the system throws 'expected undefined to equal..'](https://stackoverflow.com/questions/51930347/while-writing-to-a-file-and-then-asserting-a-cypress-io-test-the-system-throws/51931483)

### CODE REVIEW

**Comment by chrisbreiding** [comment]
Thanks for submitting this. Could you please add a test? https://github.com/cypress-io/cypress/blob/develop/packages/driver/test/cypress/integration/commands/files_spec.coffee#L246

**Comment by rezaxdi** [comment]
I just forgot that, added.

**Comment by chrisbreiding** [comment]
Thanks for the test. There's an [issue with Circle CI related to PRs from forks and the cache](https://discuss.circleci.com/t/saving-cache-stopped-working-warning-skipping-this-step-disabled-in-configuration/24423) that's causing all the tests to fail. Once we resolve that and see all the tests pass, we'll get this merged.

**Comment by bahmutov** [comment]
the failure is due to group run bug, will be fixed soon by pushing the API

**Comment by brian-mann** [comment]
@lilaconlee per our discussion today... forgot this was an open PR, hah

**Pull request merged**
