### PR TITLE
fix(studio): restore intro modal styles

### LINKED ISSUE #17102: The Studio intro modal styling is showing incorrectly
### Current behavior

The styling of the Studio modal when first shown if not showing correctly. This was introduced in 7.6.0. 

Screen Shot 2021-06-24 at 8 49 45 AM

### Desired behavior

Screen Shot 2021-06-24 at 9 09 37 AM

### Test code to reproduce

- Install Cypress 7.6.0
- Within Cypress App Data, remove `showedStudioModal` value.
- Set `experimentalStudio` to `true` in `cypress.json`
- Run `cypress open` and click to 'Create command' via the Cypress Studio

### Versions

7.6.0

### PR DESCRIPTION
**Pull request by panzarino**
- Closes #17102

### User facing changelog
- Fix issue where Studio introduction would not display with correct styling

### Additional details
Most likely something got lost in the runner unification work - I've added a more explicit Cypress test with Percy so that this doesn't happen again (looks like we had only been doing enzyme previously)

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@panzarino Looks like the percy snapshot doesn't reflect the image. Anything we can do about that?
Screen Shot 2021-06-25 at 8 43 23 AM

**Review by jennifer-shehane — DISMISSED** [review]
It's working! 😄

**Review by lmiller1990 — DISMISSED** [review]
Thanks - dropped an approval, I'll leave dealing with Percy with you.

**Comment by panzarino** [comment]
Wasn't able to figure out a solution that would capture the gif properly - after searching a bit more we would probably have to modify the percy plugin setup to fix this which is out of scope here. For this PR it might actually be better that we consistently don't get it rendering so there's no flakiness from snapshotting different gif frames

**Review by lmiller1990 — APPROVED** [review]
Looks good - happy to revisit the Percy improvements at a later date.

**Pull request merged**
