### PR TITLE
feat: make cy.intercept url matching more closely match cy.route

### PR DESCRIPTION
**Pull request by flotwig**
- Closes 

### User facing changelog

- Removed `matchUrlAgainstPath` `RouteMatcher` property.
- Removed the "substring match" from `cy.intercept` URL matching. Previously, a URL would match if it contained the supplied string anywhere. Now, the URL (incl. querystring) only matches if it is an equality match or a minimatch.

### How has the user experience changed?

- Removed `matchUrlAgainstPath` since it's redundant, removing it doesn't break any use case.
- Substring match was removed because it ends up capturing more than the user intends.
 	- The most likely place this will trip users up: querystrings. Previously, `cy.intercept('/widgets')` would match `/widgets?limit=50`. Now it does not. This matches `cy.route`'s behavior, but now requires the user to do something like `cy.intercept('/widgets?limit=*')` or `cy.intercept({ pathname: '/widgets' })`

#### Table of changes:

<table>
<tr>
	<td>
	<td>
	<th colspan="2">Does the request match?
<tr>
	<th>Code
	<th>Request path
	<th>Before this PR
	<th>After this PR
<tr>
	<td><code>cy.intercept('/widgets')</code>
	<td><code>/widgets?limit=50</code>
	<th>:heavy_check_mark: 
	<th>:x:
<tr>
	<td><code>cy.intercept('/filename')</code>
	<td><code>/directory/filename</code>
	<th>:heavy_check_mark: 
	<th>:x:
</table>

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/3715
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by Bkucera** [comment]
is there a way to match a route + any query string?
because `/items*` will match `/items/foo/bar`
and `/items?*` wont match `/items`

would this work?
`/items(?*)`

**Comment by flotwig** [comment]
> is there a way to match a route + any query string?
> because `/items*` will match `/items/foo/bar`
> and `/items?*` wont match `/items`
> 
> something like this regex?
> `/items(\?*)?`

@Bkucera that regex would work, but you could also specify that you only wish to match on `pathname`, not on the full `path` (`path = pathname + querystring`). So something like `{ pathname: '/items' }`.

**Comment by Bkucera** [comment]
great, pathname looks like the solution

**Review by Bkucera — APPROVED** [review]

**Comment by flotwig** [comment]
Remaining test failures also exist in `7.0-release` branch. merging...

**Pull request merged**
