### PR TITLE
feat: updated record run instructions

### PR DESCRIPTION
**Pull request by panzarino**
- Closes GROW-218, GROW-219, GROW-220

**Requires https://github.com/cypress-io/cypress-services/pull/3909 to be deployed with `on` link changes before this can be merged**

### User facing changelog
- Updated record run instructions for some users

### Additional details
We've added a new record run instructions screen for some users - using the same method of A/B testing as on the dashboard (by `orgId`) we hope to trial A/B tests in the TR. We'll be able to track whether or not this leads to an increased percentage of new orgs that end up recording runs to the dashboard. The new screen is similar to our current dashboard 0 state which showed a much better rate of recording runs along with helpful links in the cards at the bottom.

### How has the user experience changed?

**New (test group)**

Screen Shot 2021-07-26 at 16 19 55

**Old (control group)**

Screen Shot 2021-07-26 at 16 20 13

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

**Review by jennifer-shehane — COMMENTED** [review]
@panzarino Can you resolve the conflicts and merge in develop. Will make this easier to test with the new project being fixed.

**Review by chrisbreiding — DISMISSED** [review]

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
@panzarino When I set up a run to record, the record key doesn't populate on this screen. If I change tabs and come back to the Runs tab - it does populate the record key. I tried to fix some conflicts from develop around getting the record key so it's possible I may have introduced this myself. 

Screen Shot 2021-07-30 at 11 08 12 AM

**Comment by panzarino** [comment]
@jennifer-shehane I'm struggling to reproduce - do you have more specifics on when this occurs? From looking at the code I don't see any problems and I've tried a couple different workflows to try to get it to happen

**Comment by jennifer-shehane** [comment]
@panzarino Sorry for the delay in replying. This is what I did:

- Run `yarn start` in the staging environment
- Login to Dashboard
- Add completely new project to Cypress
- Click on runs tab and connect to Dashboard
- Create a 'new' project (not existing)
- Click Setup Project

I've attached a gif below of the behavior.

**Comment by panzarino** [comment]
@jennifer-shehane So I still wasn't able to reproduce by following those exact steps but I did realize that I had accidentally slightly changed some of the logic around when to load the record key. I've reverted back to the original working version that we had (before this PR) which should fix the issue you were experiencing (and also fixes a memory leak error).

**Review by jennifer-shehane — APPROVED** [review]
Yes, the record key populates now like it used it.

**Pull request merged**
