### PR TITLE
chore: add a script to run all react tests in a single step

### PR DESCRIPTION
**Pull request by lmiller1990**
- Closes 

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by soulfulAdam — APPROVED** [review]

**Comment by dmtrKovalenko** [comment]
I can make a reporter myself, cause I think this will be a pain to understand which job is failed :) 
Had this experience in the past it was awful

**Comment by lmiller1990** [comment]
Please show me how you do it, thanks @dmtrKovalenko - already learned a lot from working on this PR with you :)! 

I spent a little time but was not sure how to debug this.

**Comment by dmtrKovalenko** [comment]
Oh gosh, I accidentally pushed without git config :(

**Comment by dmtrKovalenko** [comment]
image

**Review by JessicaSachs — APPROVED** [review]

**Pull request merged**
