### PR TITLE
feat: append (failed) to video filenames when test fails

### PR DESCRIPTION
**Pull request by MatthewDiamant**
* Closes https://github.com/cypress-io/cypress/issues/6998

### User facing changelog

Videos from failing tests are now marked as "(failed)" in their filename.

### Additional details
**Why was this change necessary?**
Screenshots from failed tests are currently marked as "(failed)", yet videos are not. This change brings them to parity.

**Implementation details**
Create a "final video name" for videos as either "foo.mp4" or, if we detect any failed tests, as "foo (failed).mp4". Replace the video name with this final video name in the results.

Pass this to the video capture `process`, and use this name when renaming the final compressed video file. Then delete the original video, which was previously overwritten by the compressed video.

### PR Tasks

* [x] Have tests been added/updated?
* [ ] Has the original issue been tagged with a release in ZenHub? 

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-223) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Possibly breaking change?

**Comment by jennifer-shehane** [comment]
The base needs to be changed to non-develop.

**Comment by chrisbreiding** [comment]
I'm not sure I agree with this. Screenshots are very different from videos. There can be multiple screenshots per test. Failure screenshots are automatically taken, so we label them to make it clear it's not one a user has taken with `cy.screenshot()`. There's only ever one video for a run. I'm not sure I see the utility of labeling them when the run fails.

**Comment by jennifer-shehane** [comment]
@chrisbreiding Users want to be able to target the videos after they are saved, so they can decide to trash the non-failed videos, like in their CI or do whatever they want with them. There's currently no way to distinguish between ones that were associated with a failed run or not.

**Comment by jennifer-shehane** [comment]
We've had some discussion about the implementation of this and feel that this may be better served under the larger feature set requested in https://github.com/cypress-io/cypress/issues/2522

Our thinking being that people essentially want to not save the non-passing test videos, which could be achieved in #2522 as opposed to just adding a string to the video and still leaving it up to people to implement the deletion. 

Appending the `(failed)` string may still be part of that larger work - we haven't decided, so opinions are welcome.

**Pull request closed without merging**
