### PR TITLE
Improve accessibility for screen readers

### LINKED ISSUE #3850: Screen reader accessibility
### Current behavior:

1. Various controls in the reporter with icons and labels on mouse hover don't expose alternative labels for screen readers:
	* Test controls: resume/restart, selector playground. These just get read as "button"
	* Statistics list: statistics like the actual no. of tests passed can be read, but the label is purely iconic.
2. Runnables list doesn't expose whether the node is expanded or collapsed programatically.

### Desired behavior:

Exposing this information for screen readers

### Steps to reproduce: (app code and test code)

1. Launch a screen reader, such as NVDA.
2. Start the driver, and run any test suite to launch the reporter.

### Versions

Latest master

### PR DESCRIPTION
**Pull request by Neurrone**
Fixes #3850 

* Use `aria-label` to label iconic buttons in the reporter
* Use CSS to provide text for screen readers in the statistics list

Investigated fixing the runnables and collapsable components so they would announce whether they are collapsed/expanded and to make them keyboard navigable, but because the collapsable content is a child of the node that can be clicked to toggle them would cause even worse side effects. For instance, the DOM looks something like this

```html
<div onClick="toggle collapsable open">
  <div>
    children
  </div>
</div>
```

Adding expanded indicators to the parent div would cause expanded to be announced not just for the title, but also all children, which is even worse than the current situation. 

The DOM would need to be changed to something like

```html
<div>
  <div onClick="toggle collapsable open"></div>
  <div>
    children
  </div>
</div>
```

### CODE REVIEW

**Comment by Neurrone** [comment]
@jennifer-shehane done. Would appreciate if you can verify that no unintended changes were introduced to how it looks visually. You should be able to test the keyboard operability by using the tab keys, and using space/enter to expand/collapse.

I figured out a way to make it work with only a change in the DOM structure for `Collapsable` by introducing an extra `<div>`, but was able to attach the keyboard listeners and set the attributes needed in the title's `<span>` in `Test`. 

The more ideal solution would be to use the more semantic `<button>` element and CSS to style it if starting from scratch.

I happen to be investigating the use of [react-axe](https://github.com/dequelabs/react-axe) and [eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y) for work. 

The thing that really helps most is end-user testing, since automated checks could find the lack of programatic labels, but wouldn't be able to tell you that there are no corresponding indicators for info that is only presented visually.

I'll be happy to answer any questions :)

**Comment by Neurrone** [comment]
Thanks @jennifer-shehane

**Comment by Neurrone** [comment]
Not sure what the process is - would also be happy to help with the changelog entry.

**Comment by jennifer-shehane** [comment]
This is good and ready to go in 3.3.0. New docs + changelog can be found here: https://github.com/cypress-io/cypress-documentation/pull/1534

We are still fixing up some issues found in the release unrelated to this PR.

**Comment by desfero** [comment]
@Neurrone will this also fix this one reported by me #3711?

**Comment by Neurrone** [comment]
@desfero if you're referring to the expandable nodes in the reporter, then yes. You should be able to tab to it and hit either enter or space to toggle collapsing / expanding.

**Comment by jennifer-shehane** [comment]
@Neurrone This PR actually only targets accessibility in the Test Runner screen. This one:

Reporter

This does not address your issue, which is about accessibility within the `packages/desktop-gui`: https://github.com/cypress-io/cypress/issues/3741

**Comment by jennifer-shehane** [comment]
Also - another issue related to keyboard support in the `packages/reporter` is here: https://github.com/cypress-io/cypress/issues/248

**Review by Rada8732 — APPROVED** [review]

**Pull request merged**
