### PR TITLE
Remove an unused package

### PR DESCRIPTION
**Pull request by koooge**
Hi there, vagrant is not necessary, isn't it?

### CODE REVIEW

**Comment by Saibamen** [comment]
Yes it is not used. Please resolve your conflicts

Found only 4 `vagrant`:
- 2 package.json from this PR
- packages\electron\dist\Cypress\resources\app\test\support\helpers\coverage.coffee
- packages\server\test\support\helpers\coverage.coffee

**Comment by koooge** [comment]
I fixed it. 

* packages\electron\dist\Cypress\resources\app\test\support\helpers\coverage.coffee

It's not a file on git

**Comment by Saibamen** [comment]
And what about `packages\server\test\support\helpers\coverage.coffee`?

**Comment by koooge** [comment]
I already modified it

**Comment by Saibamen** [comment]
Oh sorry, you're right.
Ready to merge

**Pull request merged**
