### PR TITLE
update coffee-script to non-deprecated npm package coffeescript

### PR DESCRIPTION
**Pull request by jennifer-shehane**

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@bahmutov Ugh, I'm really confused. I've run Appveyor multiple times. It keeps coming back as failing on this PR specifically, but the logs look fine?? Is there an error in the logs that I'm not seeing?

**Comment by Bkucera** [comment]
I think appveyor fails if the branch is it of sync with the base and there are any merge conflicts. Not sure if that's what's happening here though

**Comment by jennifer-shehane** [comment]
I just pulled in `develop` - no merge conflicts and is still failing @bahmutov ?

**Comment by Bkucera** [comment]
Causing binary build smoke tests to hang forever (on develop), I'll open a PR to revert
https://circleci.com/gh/cypress-io/cypress/118063?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Pull request merged**
