### PR TITLE
chore: add alpha nuxt tag

### PR DESCRIPTION
**Pull request by ZachJW34**
### User facing changelog
Nuxt is labeled "alpha" in CT setup

### Additional details
From the tech-brief, we stated we would mark `next` and `nuxt` as having alpha support. We missed adding the tag to `nuxt` so this PR adds the label.

### How has the user experience changed?
Screen Shot 2022-04-29 at 10 29 44 AM

### PR Tasks

- [n/a] Have tests been added/updated?
- [n/a] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [n/a] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by marktnoonan — APPROVED** [review]

**Comment by lmiller1990** [comment]
@ZachJW34 just realized this is going to be very confusing if anyone tries Nuxt 3, which absolutely has no level of support at the current time. What's worse, is that Nuxt 3 is currently in **alpha**, so this might read like "Nuxt 3 alpha" support. :thinking: ideas?

**Review by lmiller1990 — COMMENTED** [review]
One comment, I think this might be even more confusing now.

**Comment by ZachJW34** [comment]
@lmiller1990 I'll slap a `(2)` on it, similar to how we have `Vue CLI (Vue 3)`.

**Comment by lmiller1990** [comment]
Maybe v2 is more clear?

Either way, I'll drop a ☑️ , merge when ready 👍

**Review by lmiller1990 — APPROVED** [review]

**Comment by ZachJW34** [comment]
@jennifer-shehane yes i changed the wording so have to update the test.

**Comment by ZachJW34** [comment]
@lmiller1990 adding the `v2` is more clear.

**Comment by lmiller1990** [comment]
I think we still have some legitimate test failures @ZachJW34 😅

**Comment by ZachJW34** [comment]
Ok fixed what is hopefully the last test. The one I fixed was really flaky locally, so I cleaned it up a bit.

**Pull request merged**
