### PR TITLE
chore: Remove electron/dist as part of preinstall

### PR DESCRIPTION
**Pull request by jennifer-shehane**
Whenever you change OS’s in the `cypress` repo (run on Mac then run in docker in Linux) you get a nondescript error about the electron/dist when trying to run cypress as shown below:

Screen Shot 2021-06-01 at 9 22 57 AM

This PR will clear the `packages/electron/dist` folder as part of `preinstall` to run before `yarn`. 

Screen Shot 2021-06-01 at 9 30 03 AM

Perhaps this is too aggressive. I’m open to suggestions if this should be run elsewhere or some better way.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Failing the test-kitchensink run 🤔 

Screen Shot 2021-06-01 at 10 23 36 AM

**Comment by jennifer-shehane** [comment]
Need to not run the `preinstall` steps when `yarn --production` is run which doesn't seem built in.

**Review by flotwig — APPROVED** [review]
I'm ok with this since the Electron install does not take a significant amount of time, it is cached locally by the downloader.

**Comment by jennifer-shehane** [comment]
Let me pull in develop since we've moved some deps around. This can't be merged because the kitchensink teests aren't passing.

**Comment by jennifer-shehane** [comment]
Closing this PR due to inactivity. Please open a new PR addressing the original issue.

**Pull request closed without merging**
