### PR TITLE
feat: ignore non-letters in specs list filter

### PR DESCRIPTION
**Pull request by papermana**
### User facing changelog

When filtering specs in the desktop client, characters that are not letters will be ignored and don't have to be typed.

### Additional details
The logic for filtering the specs list is very strict currently, and you have to type in the name of the desired spec(s) exactly. Ideally, filtering would use fuzzy logic, but I can see that at least [one PR](https://github.com/cypress-io/cypress/pull/1707) included that, and the fuzzy search feature was removed because of some issues.

A low hanging fruit type of solution is simply ignoring certain characters. Having to type every "_" has been the biggest problem in my experience, so this should already make things more convenient.

I used a nifty newish regexp feature to detect all letter characters, including non-Latin ones. (I don't think it would be OK to break the search function for people using different writing systems.) You can see an explanation [here](https://javascript.info/regexp-unicode).

~Note that this change will also ignore any digits. Of course, that can be changed.~ I decided numbers should also be kept.

Small warning: I can't get dependencies to install on my M1 Macbook (Electron doesn't want to build), so I haven't tested this code myself. I'm hoping the E2E tests will pass.

### How has the user experience changed?
Before: to find `user_profile.spec`, I have to type "user_prof".
After: I can type "userprof".

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

**Comment by papermana** [comment]
Seems like the tests are not passing after all. Will resolve it and open the PR again.

**Comment by papermana** [comment]
Some tests are still failing, but they seem to be different every time I make a change. Are they just naturally flaky, or does it mean that something's wrong? I don't think my changes are related to Electron etc.

Anyway, I'm opening the PR again. Not sure if I should re-request review. @jennifer-shehane?

**Comment by jennifer-shehane** [comment]
Hey @papermana, thanks for the work. We'll review as soon as we can. We're a little tied up today getting our release out. Thanks!

**Review by jennifer-shehane — DISMISSED** [review]
Nice. I personally like this feature because I can't ever remember if we use snakecase or camelcase either. This is great because it also considers our users with non-English characters in their specfile. 

Tried it out manually and it's also tested. 

Screen Shot 2021-07-21 at 8 53 21 AM

**Review by chrisbreiding — APPROVED** [review]

**Pull request merged**
