### PR TITLE
feat(unify): share header bar between launchpad and app

### PR DESCRIPTION
**Pull request by marktnoonan**
- Closes https://cypress-io.atlassian.net/browse/UNIFY-500

### Additional details

A lot of this is file moves and adjustments to get the Header Bar to work correctly in the frontend-shared package. Part of this is allowing graphql codegen to run for Vue components inside frontend-shared, but only if they are nested in the /frontend-shared/src/gql-components directory. This is to prevent mixing gql-dependent components with shared components that can be shared beyond gql-driven packages like App and Launchpad.

### How has the user experience changed?

https://user-images.githubusercontent.com/8340719/139134617-64945f47-c808-45d8-90a1-091cc4dff0fa.mov

## How to Test

Use both the launchpad and the new runner and see that the header bar is present. See that in the App, a page name is shown and in the Launchpad, the "Projects > project-name" text appears. Change the browser being used via the dropdown in the header and see that the browser closes and the correct browser opens. Note that some things are still unfinished, like the login flow in app, which is currently not nailed down in terms of requirements, and the Cypress version list, with is being updated by other tickets.

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

**Review by elevatebart — COMMENTED** [review]
Looking at the files everything seems great, will checkout and see if it fulfills the promises ;)

**Review by elevatebart — APPROVED** [review]
Great Job, Works well, LGTM

I would have loved one or two e2e tests but we talked about it.
Can you explain why the changes to the `pages/x.vue` in the routing were necessary? I thought this PR was about the header bar.

**Review by lmiller1990 — COMMENTED** [review]
Left some comments!

Not a fan of aliases at all really, I don't see the tiny amount of keystrokes saved as a worthy benefit to add complexity, but happy to hear what everyone else thinks.

**Review by marktnoonan — COMMENTED** [review]
Thanks for the reviews! I've resolved all @lmiller1990's comments except the aliases since I see we are going to talk about them more generally later today.

@elevatebart the changes the the files in /pages are included in this PR because for the header bar to be correct in the App, it should show the page titles the way it does in Figma, so we need user-facing page titles associated with each route.

**Pull request merged**
