### PR TITLE
feat: include warning when running with invalid config

### LINKED ISSUE #428: Warning when running with invalid config
```ssh
cypress run --config trashAssetsBeforeHeadlessRun=false -s cypress/integration/test_spec.js
```

**EXAMPLE**: 

`trashAssetsBeforeHeadlessRun` should be `trashAssetsBeforeHeadlessRuns`.

### PR DESCRIPTION
**Pull request by mrmodise**
* Closes  #428
* Previous PR #8099 

### User facing changelog

This PR closes an issue where by a warning should be shown to the user when running Cypress with invalid config

#### Before

Would run fine - not knowing you passed the wrong config key

Screen Shot 2020-11-14 at 2 18 24 PM

#### After

Users will now get a warning message to help them understand why their configuration is not working, as expected

Screen Shot 2020-11-14 at 2 05 01 PM

### PR Tasks

* [x] Have tests been added/updated?
* [ ] Has the original issue or this PR been tagged with a release in ZenHub?

### CODE REVIEW

**Comment by mrmodise** [comment]
@jennifer-shehane sorry to tag you but I noticed you tracked the original PR. I noticed an interesting thing when dealing with any code inside `cypress/packages/server/lib/util/args.js` that no matter what the code always executes twice. Is this the desired behaviour or perhaps am not running the app correctly. I used the following commands to run the app:

```sh
 npx -p node@12 yarn dev --config trashAssetsBeforeRunssss=false
```

and 

```sh
node scripts/cypress.js run --config trashAssetsBeforeRunssss=false 
```

which results in duplicate message being shown to the user, as per below:

```typescript
Warning:

`trashAssetsBeforeRunssss` is not a valid configuration option
see, https://on.cypress.io/configuration
Warning:

`trashAssetsBeforeRunssss` is not a valid configuration option
see, https://on.cypress.io/configuration
```

Apologies if am missing any protocol. I tried to familiarise myself with most of the documentation I could get my hands on but I suppose its possible to miss some information since am new to contributing to Cypress 😊

**Comment by mrmodise** [comment]
@jennifer-shehane ignore above cracked it 🕺

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
We're getting these errors on the tests you added when they're run about `TypeError: electron_1.BrowserWindow is not a constructor`.

Screen Shot 2020-11-05 at 1 41 23 PM

You can see this locally by running `yarn test test/integration/cypress_spec.js` from within `packages/server`.

**Comment by mrmodise** [comment]
> We're getting these errors on the tests you added when they're run about `TypeError: electron_1.BrowserWindow is not a constructor`.
> 
> Screen Shot 2020-11-05 at 1 41 23 PM
> 
> You can see this locally by running `yarn test test/integration/cypress_spec.js` from within `packages/server`.

Thanks looks like Electron gets offloaded. I will refer to other tests to correct. Thanks for the feedback

**Comment by mrmodise** [comment]
@jennifer-shehane all ready for you 🕺

**Comment by mrmodise** [comment]
@jennifer-shehane sorry to ask here. Why are the pipelines always hanging?

**Comment by mrmodise** [comment]
@jennifer-shehane please re-trigger the pipeline on your end for me. Looks like its still hanging

**Comment by jennifer-shehane** [comment]
@mrmodise The only thing I can think is it is hanging due to your originally force pushing. This isn't happening for any other contributors. It's something unique to your PRs

**Review by jennifer-shehane — APPROVED** [review]
This looks good. I added another test for multiple invalid config options and added a snapshot. Thanks for the PR!

**Comment by mrmodise** [comment]
> @mrmodise The only thing I can think is it is hanging due to your originally force pushing. This isn't happening for any other contributors. It's something unique to your PRs

Noted will keep this in mind in future PRs

**Pull request merged**
