### PR TITLE
fix: typo in `@types/react` peer dependency package name

### PR DESCRIPTION
**Pull request by Spy-Seth**
Fix typo in `@types/react` package name in @cypress/react package file

### User facing changelog
None

### Additional details
I could not install `@cypress/react` on a project that use Yarn v2

```
$ yarn add --dev cypress @cypress/react
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @cypress/react@npm:4.16.1: Invalid descriptor (types/react)
    at Module.x (/home/armand/workspace/guest-journey/internet-booking-engine/.yarn/releases/yarn-2.4.0.cjs:2:434115)
    at load (/home/armand/workspace/guest-journey/internet-booking-engine/.yarn/releases/yarn-2.4.0.cjs:2:323494)
    at Object.resolve (/home/armand/workspace/guest-journey/internet-booking-engine/.yarn/releases/yarn-2.4.0.cjs:2:231488)
    at async n.resolve (/home/armand/workspace/guest-journey/internet-booking-engine/.yarn/releases/yarn-2.4.0.cjs:2:336461)
    at async n.resolve (/home/armand/workspace/guest-journey/internet-booking-engine/.yarn/releases/yarn-2.4.0.cjs:2:336461)
    at async /home/armand/workspace/guest-journey/internet-booking-engine/.yarn/releases/yarn-2.4.0.cjs:2:356788
    at async Module.w (/home/armand/workspace/guest-journey/internet-booking-engine/.yarn/releases/yarn-2.4.0.cjs:2:417407)
    at async d (/home/armand/workspace/guest-journey/internet-booking-engine/.yarn/releases/yarn-2.4.0.cjs:2:356751)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 114ms
```

### How has the user experience changed?
Nop

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Review by dmtrKovalenko — CHANGES_REQUESTED** [review]
Thank you for this contribution. 
In order to merge this, we need 
- [ ] To pass CI
- [ ] To sign the CLA

One more question – did you try to link or publish your own version of this package with updated package.json so we know that yarn2 works?

**Review by lmiller1990 — DISMISSED** [review]
Fix seems fine - need to verify publishing this works as expected.

**Review by lmiller1990 — DISMISSED** [review]

**Comment by Spy-Seth** [comment]
> did you try to link or publish your own version of this package with updated package.json so we know that yarn2 works?

I did not test it with the fix. The typo is here for other package manager too so will not hurt to fix it. 

I Will check with Yarn 2 after the change being released

**Review by panzarino — DISMISSED** [review]
Ran into this when playing with Yarn 2 and trying to fix some of our build issues, can confirm this fixes the described problem

We probably want to merge this directly into master to get an immediate fixed release, but since this branch was made off of develop we can't just change the base of the PR - do we have a process for resolving this (aside from cherry-picking to a new branch) that still attributes contributor credit correctly?

**Comment by lmiller1990** [comment]
Hmm I don't know any other way other than cherry picking. 🤔  which probably would not be that difficult - not sure if it will clobber the original contributor or not.

**Comment by Spy-Seth** [comment]
I can cherry pick this commit on master after the merge of this PR

**Comment by panzarino** [comment]
We actually get super lucky here that we just did a release and `develop` and `master` are even so we can change the branch with no extra commits getting added.

Perhaps we should update the PR template to draw more attention to the base branch to avoid this issue in the future.

**Comment by panzarino** [comment]
@Spy-Seth I apologize for all the noise here - I had actually independently noticed this while working on a separate PR but since you discovered this and submitted the PR I wanted to make sure you get credit where credit is due 👍

**Pull request merged**
