### PR TITLE
Capture stderr in e2e tests

### LINKED ISSUE #5269: Snapshot stderr in e2e tests
Currently, the e2e tests only capture and snapshot stdout:

https://github.com/cypress-io/cypress/blob/4ec77e3d589983b19d448d9c8cc2aed9d9068d05/packages/server/test/support/helpers/e2e.coffee#L164-L173

It would be nice to also capture and snapshot stderr, since sometimes issues only affect stderr, not stdout.

Things this would've caught early:

- #5256
- Electron debug output not being filtered correctly - can't find issue # for this

---

- Need to fix #5765 first

### PR DESCRIPTION
**Pull request by flotwig**
- Closes #5269 

### User facing changelog

N/A - not user facing

### Additional details

- This PR makes it so that all tests run through the CLI, instead of using the binary directly.
- This PR interleaves `stderr` with the `stdout` that is snapshotted in e2e tests. `stderr` lines are prefixed with `[e2e stderr]: ` to aid with understanding what parts of a snapshot are stderr and what parts are stdout.
- Surprisingly, there is currently no stderr in Cypress's normal operation, so the snapshots are unchanged.
- [x] Should the e2e test filter stderr using the same rules as in the CLI?
 	- I think yes - so the stderr captured is representative of the actual stderr a user would see
	- accomplished by running all tests through cli
- [x] Wait for #4628 and #5206 to merge since it will remove Electron warning from stderr
- [x] Wait for `snap-shot-it` release with bahmutov/snap-shot-core#311 so empty stderr can be snapshotted

This captures stderr from e2e tests in addition to stdout. Most specs don't produce any stderr, but this will allow us to keep track of unwanted stderr output in the future.

### PR Tasks

- [x] Have tests been added/updated?

### CODE REVIEW

**Comment by brian-mann** [comment]
This PR isn't necessary - all that's necessary is that we go through the CLI itself for e2e tests, which means we automatically get the logic from the CLI that does the filtering. This has been needed for a long time now - and with the advent of the `--dev` flag, it's made this possible for months.

Previously the CLI would always expect the raw built binary, but the `--dev` flag tells it to use the development non built binary. Several of our other `npm` commands use this flag.

The `scripts/e2e` file just needs to be updated to go through the CLI.

I'm closing but you can reopen if I'm missing something.

**Comment by flotwig** [comment]
Even if the e2e test went through the CLI, it doesn't snapshot the stderr from the child process, only the stdout, which is the purpose of this PR. So I think this is still necessary.

I can try refactoring the e2e tests to go through the CLI so that I don't need to require that function directly. That would be a nice improvement for the robustness of the e2e tests as a whole as well.

**Comment by brian-mann** [comment]
That's true - I'll reopen and we can rearchitect it.

**Comment by flotwig** [comment]
Been thinking about this, it probably makes more sense to have `stderr` interleaved with `stdout` in the snapshots, since it will help snapshot the visible output a user would get, and guarantee that the ordering of stderr vs. stdout does not change. Maybe `stderr` lines could get prefixed with `stderr: ` or something to make the output clear.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Pull request closed without merging**
