### PR TITLE
fix: Optionally highlighted element's shadow root

### LINKED ISSUE #20989: Selector playground does not support Shadow DOM
### Current behavior

When attempting to locate selectors using the highlight feature of the selector playground it does not locate elements within ShadowRoots even when `includeShadowDom` is enabled.

**fixtures/shadow-dom.html**

Resulting selector playground:

Screenshot 2022-04-08 at 09 59 55

### Desired behavior

When `includeShadowDom` is enabled selector should search all available ShadowRoots. This will most likely require https://github.com/cypress-io/cypress/blob/develop/packages/runner-shared/src/iframe/aut-iframe.js#L294 to be modified as it only searches the current `contentDocument`.

### Test code to reproduce

I wasn't able to find a test that would let me reproduce this but any test visiting the following HTML fixture should make it apparent.

```html
<my-custom-element></my-custom-element>

<script type="module">
  window.customElements.define(
    'my-custom-element',
    class extends HTMLElement {
      constructor() {
        super();
        this.attachShadow({ mode: 'open' });
      }

      connectedCallback() {
        this.shadowRoot.innerHTML = `
        <button data-testid="first-button">First Button (data-testid="first-button")</button>
        <button data-testid="second-button">Second Button (data-testid="second-button")</button>
        <button class="third-button">Third Button (class="third-button")</button>
        <div data-testid="more-buttons">
          <button class="fourth-button">Fourth nested button (data-testid="fourth-button")</button>
        </div>
        `;
      }
    }
  );
</script>
```

### Cypress Version

8.7.0 and 9.5.1

### Other

_No response_

### PR DESCRIPTION
**Pull request by simenbrekken-visma**
- Closes https://github.com/cypress-io/cypress/issues/20989

### User facing changelog

- When using the selector playground to locate elements, optionally search within the found element's shadow root

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@simenbrekken Make sure to sign our CLA when you get a chance. You still have some more code to add for this PR?

**Comment by simenbrekken-visma** [comment]
@jennifer-shehane I haven't been able to get `unique-selector` working with this patch and I'm not familiar with how this actually works either, so any help finishing this up would be greatly appreciated.

I'll sign the CLA as soon as I get a thumbs up from my employer

**Comment by simenbrekken-visma** [comment]
@jennifer-shehane I'm getting a 401 on the CLA signing page, any ideas?

**Comment by nagash77** [comment]
Hi @simenbrekken-visma do you plan on picking this work back up or should this draft PR be closed?

**Comment by simenbrekken-visma** [comment]
I didn't get any further as https://github.com/ericclemmons/unique-selector needs to be updated AFAIK and it appears to have been abandoned. You can probably close it.

**Pull request closed without merging**
