### PR TITLE
feat: support vite-dev-server middlewareMode

### PR DESCRIPTION
**Pull request by mucsi96**
Allow using vite dev server in middlerware mode as original does. See: https://vitejs.dev/config/server-options.html#server-middlewaremode

Helps resolving issues with MSW by allowing serving mock service worker from root.
- https://github.com/mswjs/msw/issues/744
- https://github.com/cypress-io/cypress/issues/28347#issuecomment-1850598171
- https://github.com/cypress-io/cypress/issues/26131
- https://github.com/cypress-io/cypress/issues/16742

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@mucsi96 Thanks for the contribution! Are you able to add some tests around this behavior?

**Comment by jennifer-shehane** [comment]
@mucsi96 We'll be unable to merge this change without tests verifying the behavior.

**Comment by mucsi96** [comment]
Hi! Sorry I got busy with work items. Let me try add a test

**Comment by mucsi96** [comment]
@jennifer-shehane I have added an E2E test inspired by `devServer-e2e.spec.ts` in `webpack-dev-server`.
Sorry for such long delay.

**Comment by jennifer-shehane** [comment]
@mucsi96 There are some failures in CI as is. I also want to call attention to this PR for vite 5 support which is in review. https://github.com/cypress-io/cypress/pull/29518

**Comment by jennifer-shehane** [comment]
@mucsi96 Could you address the new conflicts with vite 5 support going in?

**Comment by jennifer-shehane** [comment]
@mucsi96 Any update here?

**Comment by jennifer-shehane** [comment]
@mucsi96 There seem to be relevant failures in the CI logs - failing around the vite dev server. Can you take a look?

**Comment by mucsi96** [comment]
Hi @jennifer-shehane! Sorry I was not able to find out the root cause of the failures. From my perspective it's not a priority as I started to migrate my tests to Playwright.

**Pull request closed without merging**
