### PR TITLE
Allow .localhost tld to be parsed correctly

### LINKED ISSUE #451: Cypress will fail wit urls with a domain in the form of "*.local*"
If you try to run Cypress having set up the baseUrl as something like `something.localhost` or `something.localsite` it will not run and instead it will bring up a browser screen with a grey background, no command log window

### PR DESCRIPTION
**Pull request by peterhry**
Closes #451

Currently `parseDomain` returns an invalid response when passed a domain ending in `.localhost`. For example, `www.ourapp.localhost` returns:
```
domain: "loc"
subdomain: "www.ourapp"
tld: "local"
```

This PR adds `.localhost` to the `customTlds` list so that the domain is parsed correctly:
```
domain: "ourapp"
subdomain: "www"
tld: "localhost"
```

This PR closes #451

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Thanks for the PR. @brian-mann will review as soon as he can, he is out of town at the moment.

**Comment by ndf** [comment]
Works for me.
Note: I had a grey screen when using .localhost
With the PR this is gone and .localhost is behaving as expected.

**Comment by peterhry** [comment]
@ndf When you get the grey screen, you should also see a JS error in the console related to parsing the domain.

**Comment by peterhry** [comment]
rebuild this pr

**Comment by ndf** [comment]
@peterhry 
The error I get is (without this PR)

```
Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'loc.local' is not a suffix of 'my-test-site.localhost'.
    at $Cypress.setConfig (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:60460:23)
    at new $Cypress (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:60451:10)
    at Function.$Cypress.create (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:60784:12)
    at Object.setup (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:137952:32)
    at Iframes._this._run (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:136948:30)
    at Iframes.componentDidMount (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:137061:12)
    at Iframes.f (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:124495:14)
    at http://my-test-site.localhost/__cypress/runner/cypress_runner.js:85939:25
    at measureLifeCyclePerf (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:85750:12)
    at http://my-test-site.localhost/__cypress/runner/cypress_runner.js:85938:11
    at CallbackQueue.notifyAll (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:82309:22)
    at ReactReconcileTransaction.close (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:91901:26)
    at ReactReconcileTransaction.closeAll (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:94702:25)
    at ReactReconcileTransaction.perform (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:94649:16)
    at ReactUpdatesFlushTransaction.perform (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:94636:20)
    at ReactUpdatesFlushTransaction.perform (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:92794:32)
    at Object.flushBatchedUpdates (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:92877:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:94702:25)
    at ReactDefaultBatchingStrategyTransaction.perform (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:94649:16)
    at Object.batchedUpdates (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:89861:26)
    at batchedUpdates (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:92802:27)
    at reactionScheduler (http://my-test-site.localhost/__cypress/runner/cypress_runner.js:128040:47)
```

Where I use ```my-test-site.localhost``` as local domain.
When changing to ```my-test-site.local``` everything works normal.
With this PR ```my-test-site.localhost``` also works normal.

**Pull request merged**
