### PR TITLE
fix: chrome crash when CRI client is disconnected

### LINKED ISSUE #24650: Missing browserCriClient in connectToNewSpec
### Current behavior

Unfortunately, this issue is intermittent and only happens in our CI pipeline. But i wanted to see if could raise the issue in case there's something obvious.

We run cypress with the following: `cypress-run cross-env NODE_OPTIONS=--max-http-header-size=1000000 cypress run --browser chrome`. And we run in a docker container, using the cypress/included images. 

This error happens mid-way running through our test suites. Our tests can take 30 minutes, and the following error seems to occur when ending a test suite (or conversely, when starting the next test suite). 

```
Timed out waiting for the browser to connect. Retrying...
Missing browserCriClient in connectToNewSpec
Error: Missing browserCriClient in connectToNewSpec
    at Object.connectToNewSpec (<embedded>:2744:242702)
    at Object.connectToNewSpec (<embedded>:2750:24813)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async v.relaunchBrowser (<embedded>:2802:346537)
```

When this happens, the test run completely exits and the remaining suites do not run.

### Desired behavior

For the test run not to crash

### Test code to reproduce

Really difficult to do, sorry. It's intermittent, and it's a fairly large, sensitive, code-base.

### Cypress Version

11.0.1

### Node version

16.16.0

### Operating System

Jenkins CI - CentOS (but runs the cypress docker image)

### Debug Logs

_No response_

### Other

We've seen this happening in v10 and v11.

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #24650 

### Additional details
When running the [browser_crash_handling_spec.js -> when the browser process crashes in chrome](https://github.com/cypress-io/cypress/blob/develop/system-tests/test/browser_crash_handling_spec.js#L31) spec with `video: false`, Cypress enters an infinite test loop where it keeps trying to run `chrome_process_crash.cy.js`. 

The reason this is happening is when the `chrome_process_crash.cy.js` fails and crashes the browser, the CRI client becomes disconnected. However, the `browser-cri-client` is unaware of the disconnect. When `resetBrowserTabsForNextTest` is called at the end of the test, and [Target.createTarget](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/browser-cri-client.ts#L172) is called, the promise never resolves and hangs, meaning that the server state is [never reset](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/modes/run.ts#L678). We want `resetBrowserTabsForNextTest` to behave as a no-op, whether is succeeds or fails. Additionally, if the CRI socket is closed and a reconnect is attempted, and there are no pending commands in the queue and the socket is STILL closed, we want to reject send commands to prevent hanging promises. This doesn't seem to happen with video on I believe since the the video processing takes time, and in that time the browser CRI client is reconnected, which allows the state to be reset.

Additionally, after fixing the hanging promise and the state resetting, the [`relaunchBrowser`](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/open_project.ts#L161) method was getting called twice, once in [open_project](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/open_project.ts#L193) and again in [browsers/index.ts](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/index.ts#L245) when the browser crashes. I think this due to the run spec now actually resolving, which now hits the correct [`relaunchBrowser`](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/open_project.ts#L161), meaning the one in [browsers/index.ts](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/index.ts#L245) can be removed.

Lastly, when the browser crashes, we want [`shouldLaunchNewTab`](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/open_project.ts#L177) to be treated as `false`, which is handled by [runSpec](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/modes/run.ts#L789C34-L789C34). After crash this was being set to true, which was trying to run [connectToNewSpec](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/open_project.ts#L185) when it shouldn't, resulting in the infamous error `Missing browserCriClient in connectToNewSpec` [here](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.ts#L590) as the CRI client doesn't get instantiated yet.

 If a chrome crash is detected, we need to reset `isFirstSpec` (renamed to `isFirstSpecInBrowser`) to `false`, which in turn sets [`shouldLaunchNewTab`](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/open_project.ts#L177)  to `false`, which creates the CRI client as expected

### Steps to test
run the  [browser_crash_handling_spec.js -> when the browser process crashes in chrome](https://github.com/cypress-io/cypress/blob/develop/system-tests/test/browser_crash_handling_spec.js#L31) with video on and off (added in this PR)

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

### CODE REVIEW

**Review by mjhenkes — APPROVED** [review]

**Comment by jazpearson** [comment]
@AtofStryker i've tested out the changes and so far, i've not had the issue reproduce!!
although quite a few failures due to issues seen in 12.15.0 with `cy.task`

**Review by ryanthemanuel — APPROVED** [review]

**Comment by AtofStryker** [comment]
> @AtofStryker i've tested out the changes and so far, i've not had the issue reproduce!!
 That's great to here. If you do run into it, let us know, but hopefully this is the fix you need

> although quite a few failures due to issues seen in 12.15.0 with `cy.task`
That is currently expected. There was a regression in 12.15.0 which should be released in 12.16.0 today. Once that release goes out I can try updating the binaries to help reduce noise

**Comment by jazpearson** [comment]
> > That is currently expected. There was a regression in 12.15.0 which should be released in 12.16.0 today. Once that release goes out I can try updating the binaries to help reduce noise

Great. I will test once the binaries are updated and then it'll be MUCH easier to test this, Thanks again.

**Comment by AtofStryker** [comment]
@jazpearson updated binaries incoming [here](https://github.com/cypress-io/cypress/commit/dc56fabf0623952266168b954f71e386d7219e7f)

**Pull request merged**
